In [25]:
import pandas as pd
import re
import json

In [26]:
def extract_first_json(text):
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    match = re.search(r'\{.*?\}', text)
    if match:
        try:
            json_data = json.loads(match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}

def extract_last_json(text):
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    # Find all JSON objects in the text
    matches = list(re.finditer(r'\{.*?\}', text))
    if matches:
        # Get the last match
        last_match = matches[-1]
        try:
            json_data = json.loads(last_match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(last_match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}

In [27]:
pred_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_pfub_erlass_and_invoice_preds.csv")

In [28]:
pred_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,pfub_slug,pfub_debtor_name,clean_text,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm
0,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,'171607237715','Adomah',amtsgericht essen-borbeck\n-geschäftsstelle-\n...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
1,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,'161155294895','Aldag',"amtsgericht essen\n-30- amtsgericht essen, 451...",amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
2,50219909,ocr_source_files/2026-01-20/egvp_id_294128/502...,pair-data-engineering-new,50219909_BriefkopfGericht_20260120_0c3ba229939...,6588a5026d36290c01d535b3a1c0b82ecfc39cd9ff5e7d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Medebach\n-12- Amtsgericht Medebac...,False,0.00,...,'174452615191','Bernau',amtsgericht medebach\n-12- amtsgericht medebac...,amtsgericht medebach\n<NUMBER>- amtsgericht me...,0.00,0.300000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
3,50219939,ocr_source_files/2026-01-20/egvp_id_294136/502...,pair-data-engineering-new,50219939_4M61_26_GESV-GL_PairFinanceGmbH_70EC2...,3364f178c5530b3a472da9aabe546a60d0055d39d96716...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nWalsrode\nAmtsgericht Walsrode, L...",False,0.01,...,'106972047927','Justin Johnson',"amtsgericht\nwalsrode\namtsgericht walsrode, l...","amtsgericht\nwalsrode\namtsgericht walsrode, l...",0.00,0.216333,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
4,50220181,ocr_source_files/2026-01-20/egvp_id_294143/502...,pair-data-engineering-new,50220181_Allgemeines_Schreiben_R__20260120_03c...,5a7282c74de38b4592f081d20417fbfa3a21588c79b214...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-286a- Amtsgericht Köln, 509...",False,0.00,...,'167989001885','Holtmann',"amtsgericht köln\n-286a- amtsgericht köln, 509...","amtsgericht köln\n-286a- amtsgericht köln, <NU...",0.00,0.348000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2259,46502572,ocr_source_files/2025-12-11/egvp_id_276782/465...,pair-data-engineering-new,46502572_Dokument_139825_11122025_143428.pdf,1e92a05c47a9080efb2984a38b4bc21a6d6aa5a0e29aa9...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Dieter Drong\nHanauer Str. 25, Tel. 06185/8590...",True,NaN,...,NaN,NaN,"dieter drong\nhanauer str. 25, tel. 06185/8590...","dieter drong\nhanauer str. <NUMBER>, tel. <PHO...",0.13,0.080000,6,0,2025-12-11 14:44:00,"Okay, let's tackle this classification task. T..."
2260,48687571,ocr_source_files/2026-01-05/egvp_id_285295/486...,pair-data-engineering-new,48687571_WiderspruchsN_2513814550008E_e43611e7...,0cf6ffca843f52ed4d0557b8a066130347e3476f1f2a54...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Wedding\nMahnsache Liquandum Capit...,False,NaN,...,NaN,NaN,amtsgericht wedding\nmahnsache liquandum capit...,amtsgericht wedding\nmahnsache liquandum capit...,0.00,0.070000,2,3,2026-01-05 13:44:00,"Okay, let's tackle this document classificatio..."
2261,53306537,ocr_source_files/2026-02-18/egvp_id_311964/533...,pair-data-engineering-new,53306537_Dokument_161625_18022026_105814.pdf,c820f0ede2d9fe72349430b730b09fa5f22937516dfe3e...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,K. Hierl\nHeisenbergstraße 4/III\nGerichtsvoll...,False,0.02,...,NaN,NaN,k. hierl\nheisenbergstraße 4/iii\ngerichtsvoll...,k. hierl\nheisenbergstraße <NUMBER>/iii\ngeric...,0.00,0.117500,6,0,2026-02-18 11:44:00,"Okay, let's tackle this document classificatio..."
2262,46423738,ocr_source_files/2025-12-10/egvp_id_275532/464...,pair-data-engineering-new,46423738_Dokument_128825_10122025_093904.pdf,2846e09fa7a9097adf79b609a10fcd8ac58a8db7800ce8...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"U. Nathanael\nAmtsgericht Frb. i. Br., Kaiser-...",True,NaN,...,NaN,NaN,"u. nathanael\namtsgericht frb. i. br., kaiser-...","u. nathanael\namtsgericht frb. i. br., kaiser-...",0.05,0.140000,6,0,2025-12-10 10:01:22,"Okay, let's tackle this classification. First,..."
2263,46891785,ocr_source_files/2025-12-16/egvp_id_279774/468...,pair-data-engineering-new,46891785_Protokoll_GKB-EV21_16_12_2025.pdf,fc5f76f0ca93bcbe22c424c2f1f10bf7ede41c80a89210...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,STEFFEN SCHNEIDER\nDie nachstehend gewählten F...,True,NaN,...,NaN,NaN,steffen schneider\ndie nachstehend gewählten f...,steffen schneider\ndie nachstehend gewählten f...,0.00,0.120000,4,0,2025-12-16 22:44:00,"Okay, let's tackle this classification task st..."

In [29]:
pred_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,pfub_slug,pfub_debtor_name,clean_text,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm
0,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,'171607237715','Adomah',amtsgericht essen-borbeck\n-geschäftsstelle-\n...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
1,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,'161155294895','Aldag',"amtsgericht essen\n-30- amtsgericht essen, 451...",amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
2,50219909,ocr_source_files/2026-01-20/egvp_id_294128/502...,pair-data-engineering-new,50219909_BriefkopfGericht_20260120_0c3ba229939...,6588a5026d36290c01d535b3a1c0b82ecfc39cd9ff5e7d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Medebach\n-12- Amtsgericht Medebac...,False,0.00,...,'174452615191','Bernau',amtsgericht medebach\n-12- amtsgericht medebac...,amtsgericht medebach\n<NUMBER>- amtsgericht me...,0.00,0.300000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
3,50219939,ocr_source_files/2026-01-20/egvp_id_294136/502...,pair-data-engineering-new,50219939_4M61_26_GESV-GL_PairFinanceGmbH_70EC2...,3364f178c5530b3a472da9aabe546a60d0055d39d96716...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nWalsrode\nAmtsgericht Walsrode, L...",False,0.01,...,'106972047927','Justin Johnson',"amtsgericht\nwalsrode\namtsgericht walsrode, l...","amtsgericht\nwalsrode\namtsgericht walsrode, l...",0.00,0.216333,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
4,50220181,ocr_source_files/2026-01-20/egvp_id_294143/502...,pair-data-engineering-new,50220181_Allgemeines_Schreiben_R__20260120_03c...,5a7282c74de38b4592f081d20417fbfa3a21588c79b214...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-286a- Amtsgericht Köln, 509...",False,0.00,...,'167989001885','Holtmann',"amtsgericht köln\n-286a- amtsgericht köln, 509...","amtsgericht köln\n-286a- amtsgericht köln, <NU...",0.00,0.348000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2259,46502572,ocr_source_files/2025-12-11/egvp_id_276782/465...,pair-data-engineering-new,46502572_Dokument_139825_11122025_143428.pdf,1e92a05c47a9080efb2984a38b4bc21a6d6aa5a0e29aa9...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Dieter Drong\nHanauer Str. 25, Tel. 06185/8590...",True,NaN,...,NaN,NaN,"dieter drong\nhanauer str. 25, tel. 06185/8590...","dieter drong\nhanauer str. <NUMBER>, tel. <PHO...",0.13,0.080000,6,0,2025-12-11 14:44:00,"Okay, let's tackle this classification task. T..."
2260,48687571,ocr_source_files/2026-01-05/egvp_id_285295/486...,pair-data-engineering-new,48687571_WiderspruchsN_2513814550008E_e43611e7...,0cf6ffca843f52ed4d0557b8a066130347e3476f1f2a54...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Wedding\nMahnsache Liquandum Capit...,False,NaN,...,NaN,NaN,amtsgericht wedding\nmahnsache liquandum capit...,amtsgericht wedding\nmahnsache liquandum capit...,0.00,0.070000,2,3,2026-01-05 13:44:00,"Okay, let's tackle this document classificatio..."
2261,53306537,ocr_source_files/2026-02-18/egvp_id_311964/533...,pair-data-engineering-new,53306537_Dokument_161625_18022026_105814.pdf,c820f0ede2d9fe72349430b730b09fa5f22937516dfe3e...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,K. Hierl\nHeisenbergstraße 4/III\nGerichtsvoll...,False,0.02,...,NaN,NaN,k. hierl\nheisenbergstraße 4/iii\ngerichtsvoll...,k. hierl\nheisenbergstraße <NUMBER>/iii\ngeric...,0.00,0.117500,6,0,2026-02-18 11:44:00,"Okay, let's tackle this document classificatio..."
2262,46423738,ocr_source_files/2025-12-10/egvp_id_275532/464...,pair-data-engineering-new,46423738_Dokument_128825_10122025_093904.pdf,2846e09fa7a9097adf79b609a10fcd8ac58a8db7800ce8...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"U. Nathanael\nAmtsgericht Frb. i. Br., Kaiser-...",True,NaN,...,NaN,NaN,"u. nathanael\namtsgericht frb. i. br., kaiser-...","u. nathanael\namtsgericht frb. i. br., kaiser-...",0.05,0.140000,6,0,2025-12-10 10:01:22,"Okay, let's tackle this classification. First,..."
2263,46891785,ocr_source_files/2025-12-16/egvp_id_279774/468...,pair-data-engineering-new,46891785_Protokoll_GKB-EV21_16_12_2025.pdf,fc5f76f0ca93bcbe22c424c2f1f10bf7ede41c80a89210...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,STEFFEN SCHNEIDER\nDie nachstehend gewählten F...,True,NaN,...,NaN,NaN,steffen schneider\ndie nachstehend gewählten f...,steffen schneider\ndie nachstehend gewählten f...,0.00,0.120000,4,0,2025-12-16 22:44:00,"Okay, let's tackle this classification task st..."

In [30]:
pred_data["pred_json"] = pred_data["pred_llm"].apply(extract_first_json)

In [31]:
pred_data["pred_json"][0]

{'is_pfub': True, 'is_invoice_inside': False}

In [32]:
# extract is_erlass and is_invoice from pred_json
pred_data["llm_is_pfub"] = pred_data["pred_json"].apply(lambda x: x.get("is_pfub", None))
pred_data["llm_is_invoice"] = pred_data["pred_json"].apply(lambda x: x.get("is_invoice_inside", None))

In [33]:
pred_data["llm_is_pfub"].value_counts(dropna=False)

llm_is_pfub
True     1237
False    1027
Name: count, dtype: int64

In [34]:
pred_data["is_pfub"].value_counts(dropna=False)

is_pfub
True     1264
False    1000
Name: count, dtype: int64

In [35]:
# compare llm_is_pfub with is_pfub
# get llm predict positive cases where is_pfub is also positive
llm_pos_model_pos = pred_data[(pred_data["is_pfub"] == True) & (pred_data["llm_is_pfub"] == True)]
llm_pos_model_pos.shape

(1138, 28)

In [36]:
llm_pos_model_pos

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
0,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2,50219909,ocr_source_files/2026-01-20/egvp_id_294128/502...,pair-data-engineering-new,50219909_BriefkopfGericht_20260120_0c3ba229939...,6588a5026d36290c01d535b3a1c0b82ecfc39cd9ff5e7d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Medebach\n-12- Amtsgericht Medebac...,False,0.00,...,amtsgericht medebach\n<NUMBER>- amtsgericht me...,0.00,0.300000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
3,50219939,ocr_source_files/2026-01-20/egvp_id_294136/502...,pair-data-engineering-new,50219939_4M61_26_GESV-GL_PairFinanceGmbH_70EC2...,3364f178c5530b3a472da9aabe546a60d0055d39d96716...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nWalsrode\nAmtsgericht Walsrode, L...",False,0.01,...,"amtsgericht\nwalsrode\namtsgericht walsrode, l...",0.00,0.216333,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
4,50220181,ocr_source_files/2026-01-20/egvp_id_294143/502...,pair-data-engineering-new,50220181_Allgemeines_Schreiben_R__20260120_03c...,5a7282c74de38b4592f081d20417fbfa3a21588c79b214...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-286a- Amtsgericht Köln, 509...",False,0.00,...,"amtsgericht köln\n-286a- amtsgericht köln, <NU...",0.00,0.348000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,54150632,ocr_source_files/2026-02-26/egvp_id_316895/541...,pair-data-engineering-new,54150632_81M62_26_GESV-GL_PairFinanceGmbH_865A...,53c287842bcdc60f78285faf2e20d0ba8c30b0478eb70d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht\nOtterndorf\nAmtsgericht Otterndor...,False,0.02,...,amtsgericht\notterndorf\namtsgericht otterndor...,0.00,0.168333,3,0,2026-02-26 15:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1260,54150704,ocr_source_files/2026-02-26/egvp_id_316912/541...,pair-data-engineering-new,54150704_ANSCHR_PAIR_Finance_GmbH_Pair_Finance...,1de826493ff2fc7a005ecdad3ff31e54203affdd9fb9b2...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Staufen im Breisgau\nVOLLSTRECKUNG...,False,0.03,...,amtsgericht staufen im breisgau\nvollstreckung...,0.05,0.175000,3,0,2026-02-26 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1261,54150707,ocr_source_files/2026-02-26/egvp_id_316913/541...,pair-data-engineering-new,54150707_10M104_26_VB-GL_PairFinanceGmbH_2BF9F...,1106edef36cf004e7ab5ea9e7d9af974515c8c6ce52dae...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSpringe\nAmtsgericht Springe, Zum...",False,0.01,...,"amtsgericht\nspringe\namtsgericht springe, zum...",0.01,0.158333,3,0,2026-02-26 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1262,54203577,ocr_source_files/2026-02-27/egvp_id_317021/542...,pair-data-engineering-new,54203577_20aM474_26_VB-GL_PairFinanceGmbH_E20E...,674932dadc7a811fdd05b7cbc7299bfa572c483651aa2b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSyke\nAmtsgericht Syke, Amtshof 2...",False,0.02,...,"amtsgericht\nsyke\namtsgericht syke, amtshof <...",0.00,0.243333,3,0,2026-02-27 06:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1263,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...,False,0.05,...,amtsgericht dresden\namtsgericht dresden\nabte...,0.03,0.200000,3,0,2026-02-27 06:44:00,"Okay, let's tackle this classification task. F...","{'is_pfub': True, 'is_invoice_inside': False}",True,False

In [37]:
# llm pos, model neg
llm_pos_model_neg = pred_data[(pred_data["is_pfub"] == False) & (pred_data["llm_is_pfub"] == True)]
llm_pos_model_neg

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
1283,49274963,ocr_source_files/2026-01-10/egvp_id_288104/492...,pair-data-engineering-new,49274963_BriefkopfGericht_20260109_698d683cb94...,0ca05f8f1c6519a30733ae191bf9a6cb4c6a0f17abae8d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Duisburg\n-631- Amtsgericht Duisbu...,False,NaN,...,amtsgericht duisburg\n<NUMBER>- amtsgericht du...,0.00,0.190,3,0,2026-01-10 00:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1293,50908253,ocr_source_files/2026-01-27/egvp_id_297865/509...,pair-data-engineering-new,50908253_ANSCHR_PAIR_Finance_GmbH_Pair_Finance...,21b4180357140550543ddaeac51324f500ce7c8359f3f0...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Maulbronn\nVOLLSTRECKUNGSGERICHT\n...,False,0.03,...,amtsgericht maulbronn\nvollstreckungsgericht\n...,0.06,0.135,3,0,2026-01-27 14:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1295,46490739,ocr_source_files/2025-12-11/egvp_id_276448/464...,pair-data-engineering-new,46490739_89d38219f1f14929.pdf,0c93806ad6687f8f2c92b2194b712a10c65dc46f635dbe...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Lübbecke\n-7- Amtsgericht Lübbecke...,False,NaN,...,amtsgericht lübbecke\n<NUMBER>- amtsgericht lü...,0.01,0.120,3,0,2025-12-11 09:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1301,45115200,ocr_source_files/2025-11-27/egvp_id_267040/451...,pair-data-engineering-new,45115200_25_11_27_52M3826-25-PairFinanceGmbH-A...,0194c5958bf3641ee3edfcf3d521998a293d1371e36d6a...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Fulda\nVollstreckungsgericht\nAmts...,False,NaN,...,amtsgericht fulda\nvollstreckungsgericht\namts...,0.00,0.400,3,0,2025-11-27 12:01:19,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1304,49407379,ocr_source_files/2026-01-12/egvp_id_288710/494...,pair-data-engineering-new,49407379_Schreiben_Schreiben_vom_12_01_2026_fo...,c01e86cfd7639f891f757d57dbe72d817286e6aaf3be24...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Lübeck\nAmtsgericht Lübeck, Am Bur...",False,NaN,...,"amtsgericht lübeck\namtsgericht lübeck, am bur...",0.02,0.090,3,0,2026-01-12 11:44:00,"Okay, let me tackle this classification step b...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2207,50898003,ocr_source_files/2026-01-27/egvp_id_297440/508...,pair-data-engineering-new,50898003_26_01_26_041M525-26-PairFinanceGmbHal...,ef7b36c3fecb1024e839d4a6b050e527c588f332e30d58...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Gießen\nVollstreckungsgericht\nAmt...,False,0.28,...,amtsgericht gießen\nvollstreckungsgericht\namt...,0.08,0.315,3,0,2026-01-27 07:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2219,46417240,ocr_source_files/2025-12-10/egvp_id_275421/464...,pair-data-engineering-new,46417240_BriefkopfGericht_20251210_0d1cbc60161...,07752d5505dea90b9933bb5ea697bebc4fbbb297b4aae5...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Aachen\n-903- Amtsgericht Aachen, ...",False,NaN,...,amtsgericht aachen\n<NUMBER>- amtsgericht aach...,0.00,0.310,3,0,2025-12-10 09:01:19,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2222,49747967,ocr_source_files/2026-01-14/egvp_id_291181/497...,pair-data-engineering-new,49747967_069f37f164b74d48.pdf,a24762693936ca7598695a7f8103e5ca52c7a9a14bf944...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Abschrift -\nAmtsgericht Nettetal\n-15- Amtsge...,False,NaN,...,abschrift -\namtsgericht nettetal\n<NUMBER>- a...,0.00,0.260,3,0,2026-01-14 13:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2255,46114015,ocr_source_files/2025-12-08/egvp_id_274295/461...,pair-data-engineering-new,46114015_BriefkopfGericht_20251208_79954bf3867...,85bcd70d10f9cabb2232eef54df5e231b55767403cfdf8...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Düsseldorf\n-661- Amtsgericht Düss...,False,NaN,...,amtsgericht düsseldorf\n<NUMBER>- amtsgericht ...,0.01,0.350,3,0,2025-12-08 17:01:19,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2258,45876316,ocr_source_files/2025-12-05/egvp_id_272755/458...,pair-data-engineering-new,45876316_BriefkopfGericht_20251205_4b2544f6d26...,b6270215ff87f65a3030f682677854b9613ac343848dce...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Gelsenkirchen\n-34- Amtsgericht Ge...,False,NaN,...,amtsgericht gelsenkirchen\n<NUMBER>- amtsgeric...,0.00,0.130,3,0,2025-12-05 10:01:19,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False

In [38]:
# llm neg, model pos
llm_neg_model_pos = pred_data[(pred_data["is_pfub"] == True) & (pred_data["llm_is_pfub"] == False)]
llm_neg_model_pos

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
27,50225719,ocr_source_files/2026-01-20/egvp_id_294436/502...,pair-data-engineering-new,50225719_ANSCHR_PAIR_Finance_GmbH_Pair_Finance...,7ac1eb58e3db5dedee55eb24bebb28fed247270f9257aa...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Karlsruhe\nVOLLSTRECKUNGSGERICHT\n...,False,0.03,...,amtsgericht karlsruhe\nvollstreckungsgericht\n...,0.06,0.355000,3,0,2026-01-20 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
31,50225964,ocr_source_files/2026-01-20/egvp_id_294454/502...,pair-data-engineering-new,50225964_Allgemeines_Schreiben_R__20260120_0d0...,e508188c0786680fbb2106e5b1e27279f964eba4cf2c60...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",False,0.05,...,amtsgericht lemgo\n<NUMBER>- amtsgericht lemgo...,0.05,0.320381,3,0,2026-01-20 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
35,50386224,ocr_source_files/2026-01-21/egvp_id_294585/503...,pair-data-engineering-new,50386224_9M1639_25_VB-GL_PairFinanceGmbH_EFBCF...,b861f265acea7fc918e2f89b26c45633e75aeebb8ff029...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nGoslar\nAmtsgericht Goslar, ZenVG...",False,0.00,...,"amtsgericht\ngoslar\namtsgericht goslar, zenvg...",0.00,0.193333,3,0,2026-01-21 07:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
36,50386231,ocr_source_files/2026-01-21/egvp_id_294587/503...,pair-data-engineering-new,50386231_6a6ca122c11e40c0.pdf,bb577f18abd92069c1ff3006e02bc94067d277e4478c53...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dinslaken\n-08- Amtsgericht Dinsla...,False,0.04,...,amtsgericht dinslaken\n<NUMBER>- amtsgericht d...,0.00,0.220000,3,0,2026-01-21 07:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
51,50392983,ocr_source_files/2026-01-21/egvp_id_294659/503...,pair-data-engineering-new,50392983_23aM117_26_VB-GL_PairFinanceGmbH_EC8A...,7b98ed035d64139cdcd40b04e71e65e4a593a0476fa7a9...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht\nHildesheim\nAmtsgericht Hildeshei...,False,0.01,...,amtsgericht\nhildesheim\namtsgericht hildeshei...,0.02,0.183333,3,0,2026-01-21 09:44:00,"Okay, let me tackle this document classificati...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,54139675,ocr_source_files/2026-02-26/egvp_id_316211/541...,pair-data-engineering-new,54139675_ANSCHR_PAIR_Finance_GmbH_Pair_26_02_2...,7516be2ae5e4e59c30364fa726f32a4810910345fb1e6a...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Lörrach\nVOLLSTRECKUNGSGERICHT\nAm...,False,0.03,...,amtsgericht lörrach\nvollstreckungsgericht\nam...,0.07,0.170000,3,0,2026-02-26 08:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
1226,54139704,ocr_source_files/2026-02-26/egvp_id_316219/541...,pair-data-engineering-new,54139704_Sv2402202610M2341_25_B8F8A7E4-6C5E-4B...,2134586c8b825673872e20983fa8911918f700aa12cc0b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nUelzen\nAmtsgericht Uelzen, Postf...",False,0.04,...,"amtsgericht\nuelzen\namtsgericht uelzen, postf...",0.02,0.203333,3,0,2026-02-26 08:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
1232,54143180,ocr_source_files/2026-02-26/egvp_id_316399/541...,pair-data-engineering-new,54143180_Schreiben_Schreiben_vom_26_02_2026_fo...,73c25f4f40dd89a626e66d5e98b9b3a77d064f0407ce46...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RheinlandPfalz\nAMTSGERICHT\nBAD NEUENAHR-AHRW...,False,0.04,...,rheinlandpfalz\namtsgericht\nbad neuenahr-ahrw...,0.03,0.235000,3,0,2026-02-26 09:44:00,"Okay, let me tackle this document classificati...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
1257,54149751,ocr_source_files/2026-02-26/egvp_id_316882/541...,pair-data-engineering-new,54149751_Schreiben_20260226_4b4b6adf1719448a.pdf,b6cca8fc3c3cf71821f635ebce6b93ff4d7eb40cc8458a...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Hamm\n-7- Amtsgericht Hamm Postfac...,False,0.01,...,amtsgericht hamm\n<NUMBER>- amtsgericht hamm p...,0.01,0.328000,3,0,2026-02-26 14:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
1258,54150623,ocr_source_files/2026-02-26/egvp_id_316892/541...,pair-data-engineering-new,54150623_ANSCHR_Pair_Finance_GmbH_Pair_Finance...,86df992aca021615cbd7c937ddc6897dc711d3d5135d48...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Heilbronn\nVOLLSTRECKUNGSGERICHT\n...,False,0.03,...,amtsgericht heilbronn\nvollstreckungsgericht\n...,0.04,0.240000,3,0,2026-02-26 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False

In [39]:
# both neg
both_neg = pred_data[(pred_data["is_pfub"] == False) & (pred_data["llm_is_pfub"] == False)]
both_neg.shape

(901, 28)

In [40]:
# lets say model preds are gt, calculate precision, recall, f1 for llm preds
from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(pred_data["is_pfub"], pred_data["llm_is_pfub"])
recall = recall_score(pred_data["is_pfub"], pred_data["llm_is_pfub"])
f1 = f1_score(pred_data["is_pfub"], pred_data["llm_is_pfub"])
print(f"Precision: {precision}, Recall: {recall}, F1 Score: {f1}")

Precision: 0.919967663702506, Recall: 0.9003164556962026, F1 Score: 0.9100359856057577

In [41]:
# get llm pred positive and also invoice inside positive cases
llm_pos_invoice_pos = pred_data[(pred_data["llm_is_pfub"] == True) & (pred_data["llm_is_invoice"] == True)]
llm_pos_invoice_pos

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_json,llm_is_pfub,llm_is_invoice
1138,53789376,ocr_source_files/2026-02-24/egvp_id_314455/537...,pair-data-engineering-new,53789376_718M186461_25_VB-GL_PairFinanceGmbH_B...,234b2a566ff2ca1b76819aebf5efbd4826ec3738a3eb44...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nHannover\nAmtsgericht Hannover, V...",False,0.03,...,"amtsgericht\nhannover\namtsgericht hannover, v...",0.01,0.193333,3,0,2026-02-24 08:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1378,53417764,ocr_source_files/2026-02-20/egvp_id_313477/534...,pair-data-engineering-new,53417764_Dokument_107026_20022026_165432.pdf,a7b6cb94d8e8b56a761c6bc0fd0f0495a437f12601bd0d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Carina Frei\nPostfach 11 03\nObergerichtsvollz...,False,0.02,...,carina frei\npostfach <NUMBER> <NUMBER>\noberg...,0.04,0.140000,6,0,2026-02-20 20:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1415,50426388,ocr_source_files/2026-01-21/egvp_id_295065/504...,pair-data-engineering-new,50426388_DR_83-26_ZU.pdf,1183d6219297c55cc62570d05c3d64dfb83a764c7f90ac...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,FRANK SCHROER\nDie Zustellung konnte aus folge...,False,0.17,...,frank schroer\ndie zustellung konnte aus folge...,0.05,0.100000,4,0,2026-01-21 15:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1480,46499574,ocr_source_files/2025-12-11/egvp_id_276711/464...,pair-data-engineering-new,46499574_Dokument_210325_11122025_124445.pdf,76c2e7de85a4e46c3542ac861acad5e74bcea74aafe20a...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieherin Julia Gerlach\nPostfa...,False,NaN,...,obergerichtsvollzieherin julia gerlach\npostfa...,0.00,0.140000,6,0,2025-12-11 13:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1499,49803011,ocr_source_files/2026-01-15/egvp_id_291727/498...,pair-data-engineering-new,49803011_Dokument_6426_15012026_114841.pdf,31ea6441d383f26ad38175eaf61fa4ee354e8bc6ecde69...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,A. Beier\nErnst-Reuter-Straße 20 B\nObergerich...,True,NaN,...,a. beier\nernst-reuter-straße <NUMBER> b\nober...,0.14,0.110000,6,0,2026-01-15 12:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1547,49775445,ocr_source_files/2026-01-14/egvp_id_291251/497...,pair-data-engineering-new,49775445_0_sammel3.pdf,9ee74cd9e7336469e2b73a0bc672f09c3238869fc2cfdc...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Bitte stets angeben:\nDR 1214/25\nDer Auftrag ...,True,NaN,...,bitte stets angeben:\ndr <NUMBER>/<NUMBER>\nde...,0.23,0.000000,1,0,2026-01-14 15:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1627,45358291,ocr_source_files/2025-11-29/egvp_id_267995/453...,pair-data-engineering-new,45358291_Dokument_152725_29112025_101139.pdf,a5b72b5d8992f76f5d07d0a5f3f53c6de7af3cf5c37dca...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,M. Ibsch\nBrunsbütteler Damm 446\nGerichtsvoll...,False,NaN,...,m. ibsch\nbrunsbütteler damm <NUMBER>\ngericht...,0.01,0.110000,6,0,2025-11-29 11:01:14,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1646,50762520,ocr_source_files/2026-01-26/egvp_id_297010/507...,pair-data-engineering-new,50762520_DR-I_002626_Nachr_Ruecksendung_Titel_...,1b9d64091c1cbe37f1cf0f72c7a42b7325f1f0ef64ee12...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Am Barrenbach 6\nINES LOHMANN\n38855 Wernigero...,False,0.54,...,am barrenbach <NUMBER>\nines lohmann\n<NUMBER>...,0.02,0.000000,4,0,2026-01-26 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1763,47983841,ocr_source_files/2025-12-28/egvp_id_283627/479...,pair-data-engineering-new,47983841_DR-II_169925_Nachr_Textbaustein_pzur_...,2034d99b2a38a3dc8e8c2e2608d68728bb16c49e83e30c...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Wilhelm-Geiler-Straße 12 a\nDorothee Isailovic...,True,NaN,...,wilhelm-geiler-straße <NUMBER> a\ndorothee isa...,0.05,0.010000,4,0,2025-12-28 11:44:00,"Okay, let me tackle this classification task s...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1831,48862727,ocr_source_files/2026-01-06/egvp_id_285581/488...,pair-data-engineering-new,48862727_Dokument_243725_06012026_101815.pdf,12e34dec46c7f574a13f567e29694c45670795a31db4e2...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Felicia Hoffmann\nBachstraße 15\nGerichtsvollz...,True,NaN,...,felicia hoffmann\nbachstraße <NUMBER>\ngericht...,0.00,0.160000,6,0,2026-01-06 11:44:00,"Okay, let me tackle this step by step. First, ...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1838,45821901,ocr_source_files/2025-12-04/egvp_id_271981/458...,pair-data-engineering-new,45821901_Dokument_177925_04122025_113727.pdf,3c276b9a9b0c47f963c9d48a458af69a5d5bd7871cb88a...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Kolja Maletzki\nGerichtsstraße 24\nObergericht...,False,NaN,...,kolja maletzki\ngerichtsstraße <NUMBER>\noberg...,0.05,0.120000,6,0,2025-12-04 15:01:24,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1858,49053529,ocr_source_files/2026-01-07/egvp_id_286328/490...,pair-data-engineering-new,49053529_Dokumente_213125_06012026_121931.pdf,806a5abee627ae2c5c640907cd035788ead26ba3897329...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieher\nBeckerle\nOGV Beckerle...,True,NaN,...,obergerichtsvollzieher\nbeckerle\nogv beckerle...,0.05,0.050000,5,0,2026-01-07 12:44:00,"Okay, let's tackle this classification task. T...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1885,48662811,ocr_source_files/2026-01-04/egvp_id_284999/486...,pair-data-engineering-new,48662811_Dokument_129325_04012026_131926.pdf,0f8768a4b3a0a610c56d9b3ef120546e2979515fc8909f...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,J. Thesing\nHochstraße 13\nGerichtsvollzieheri...,True,NaN,...,j. thesing\nhochstraße <NUMBER>\ngerichtsvollz...,0.00,0.160000,6,0,2026-01-04 13:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1946,50453832,ocr_source_files/2026-01-22/egvp_id_295501/504...,pair-data-engineering-new,50453832_4_dr_103_26_pf%C3%9Cb_an_gl_mitteilun...,47343273c7bcfa857ba7e49150e51e48a6dac1e6e83211...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Hauptgerichtsvollzieher\nAm Pfad 1\nAnsgar Eng...,False,0.43,...,hauptgerichtsvollzieher\nam pfad <NUMBER>\nans...,0.05,0.160000,6,0,2026-01-22 15:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
1987,52425995,ocr_source_files/2026-02-10/egvp_id_307126/524...,pair-data-engineering-new,52425995_Dokument_7426_10022026_152606.pdf,a56af463436931f66bf74401a9b999d224543346d02cc3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,D. Höftmann\nBrunsbütteler Damm 446\nObergeric...,False,0.14,...,d. höftmann\nbrunsbütteler damm <NUMBER>\nober...,0.11,0.065000,6,0,2026-02-10 15:44:00,"Okay, let me tackle this classification step b...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
2010,46536305,ocr_source_files/2025-12-12/egvp_id_276952/465...,pair-data-engineering-new,46536305_DR-I_179225_Nachr_Pfueb_erledigt_12_1...,c4c6e9e0bf0b044a59f833050b7a22e08976f576926d7b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Friedrichstraße 15\nSVEN BALTHASAR\n39387 Osch...,False,NaN,...,friedrichstraße <NUMBER>\nsven balthasar\n<NUM...,0.03,0.020000,4,0,2025-12-12 05:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
2114,53804618,ocr_source_files/2026-02-24/egvp_id_315080/538...,pair-data-engineering-new,53804618_Dokument_22126_24022026_164138.pdf,eb5c0dd51a0209ca5c38ce8366146e7ccc9537cb0ff583...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"V. Marquardt\nMarkgrafendamm 24, Haus 16\nOber...",False,0.07,...,"v. marquardt\nmarkgrafendamm <NUMBER>, haus <N...",0.11,0.030000,6,0,2026-02-24 16:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
2159,47447415,ocr_source_files/2025-12-21/egvp_id_282190/474...,pair-data-engineering-new,47447415_Dokument_187025_21122025_091921.pdf,5160efb0abfab53338c21680caaf85c0e1e57ebcd8ef40...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Claudia Weidel\nHellersdorfer Weg 35\nGerichts...,True,NaN,...,claudia weidel\nhellersdorfer weg <NUMBER>\nge...,0.05,0.100000,6,0,2025-12-21 09:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': True}",True,True
2190,45185768,ocr_source_files/2025-11-28/egvp_id_267694/451...,pair-data-engineering-new,45185768_Dokument_162825_28112025_100012.pdf,5b52d248b36c4fbcb1f96f9851d68887f06f8de07d474c...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Florian Gärtner\nBismarckplatz 5\nGerichtsvoll...,False,NaN,...,florian gärtner\nbismarckplatz <NUMBER>\ngeric...,0.01,0.127500,6,0,2025-11-28 11:01:17,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': True}",True,True

In [42]:
import sys
sys.path.append("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation")

from utils.prod_utils import download_pdf_by_document_s3_info
import boto3

s3 = boto3.client("s3")
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/pfub_with_invoice_llm_pred"

for _, row in llm_pos_invoice_pos.iterrows():
    download_pdf_by_document_s3_info(
        s3=s3,
        document_s3_bucket=row["document_s3_bucket"],
        document_s3_key=row["document_s3_key"],
        download_dir=download_dir,
        file_name=row.get("file_name", None)
    )

❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.

ClientError: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.