### Purpose: Check which data we can use for PFUB ERLASS Documents

In [1]:
import pandas as pd
from python_utilities.db_connection import DbConnection

In [2]:
# First check created data for ladung. It countains multiple document types. We might have PFUB Erlass data there.

In [3]:
data_path = "../data/LADUNG_TRAINING_data_with_random_attachments.csv"
data = pd.read_csv(data_path)

In [4]:
data.shape

(5007, 6)

In [5]:
data['document_type'].value_counts()

document_type
ladung_va                                 2100
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              541
approved_seizure                           393
court_inbox                                346
approved_attachment_and_transfer_order      50
enforcement_order                           23
contradiction                                3
Name: count, dtype: int64

In [6]:
approved_seizure = data[data['document_type'] == 'approved_seizure']
# NOTE: Checked enforcement_order samples, they are NOT PFUB Erlass documents
# NOTE: Checked attachment_and_transfer_order samples, they are NOT PFUB Erlass documents
# NOTE: approved_seizure samples seems to be PFUB Erlass documents

In [7]:
approved_seizure

,text,object_key,document_type,is_ladung,cleaned_text,text_w_tags
2891,Amtsgericht Heinsberg\n-10- Amtsgericht Heinsb...,26.05.2023/1685099162_DS_002_26052023_130110.pdf,approved_seizure,0,amtsgericht heinsberg\n-10- amtsgericht heinsb...,amtsgericht heinsberg\n<NUMBER>- amtsgericht h...
2892,Amtsgericht Heinsberg\n-10- Amtsgericht Heinsb...,26.05.2023/1685099166_DS_003_26052023_125812.pdf,approved_seizure,0,amtsgericht heinsberg\n-10- amtsgericht heinsb...,amtsgericht heinsberg\n<NUMBER>- amtsgericht h...
2893,Amtsgericht Heinsberg\n-10- Amtsgericht Heinsb...,26.05.2023/1685099174_DS_004_26052023_125814.pdf,approved_seizure,0,amtsgericht heinsberg\n-10- amtsgericht heinsb...,amtsgericht heinsberg\n<NUMBER>- amtsgericht h...
2894,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,26.05.2023/1685099175_DS_004_26052023_130110.pdf,approved_seizure,0,amtsgericht frankfurt am main\nmobiliarzwangsv...,amtsgericht frankfurt am main\nmobiliarzwangsv...
2895,PAIR Finance GmbH\nAmtsgericht Köln\n23. Sep. ...,24.09.2024/ocr-v2_RB_003_24092024_150317.pdf,approved_seizure,0,pair finance gmbh\namtsgericht köln\n23. sep. ...,pair finance gmbh\namtsgericht köln\n<NUMBER>....
...,...,...,...,...,...,...
3279,Der Direktor des Amtsgerichts\nViersen\nDer Di...,26.05.2025/ocr-v2_KL_008-26052025-081914.pdf,approved_seizure,0,der direktor des amtsgerichts\nviersen\nder di...,der direktor des amtsgerichts\nviersen\nder di...
3280,"Amtsgericht Köln\n-288a- Amtsgericht Köln, 509...",29.11.2024/ocr-v2_FA_001_29112024_104728.pdf,approved_seizure,0,"amtsgericht köln\n-288a- amtsgericht köln, 509...","amtsgericht köln\n-288a- amtsgericht köln, <NU..."
3281,Amtsgericht Köln\n28. Nov 2024\n-288a- Amtsger...,29.11.2024/ocr-v2_FA_002_29112024_104728.pdf,approved_seizure,0,amtsgericht köln\n28. nov 2024\n-288a- amtsger...,amtsgericht köln\n<NUMBER>. nov <NUMBER>\n-288...
3282,Amtsgericht Köln\nPAIR Finance GmbH\n-288a- Am...,09.05.2025/ocr-v2_RB_001_09052025_081100.pdf,approved_seizure,0,amtsgericht köln\npair finance gmbh\n-288a- am...,amtsgericht köln\npair finance gmbh\n-288a- am...
3283,Amtsgericht Münster\nPAIR Finance GmbH\nAZ 26....,27.06.2025/ocr-v2_RB_001_27062025_080955.pdf,approved_seizure,0,amtsgericht münster\npair finance gmbh\naz 26....,amtsgericht münster\npair finance gmbh\naz <NU...

In [8]:
approved_attachment_and_transfer_order = data[data['document_type'] == 'approved_attachment_and_transfer_order']
approved_attachment_and_transfer_order

,text,object_key,document_type,is_ladung,cleaned_text,text_w_tags
3925,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,24.07.2023/1690187635_KD_004_24072023_101422.pdf,approved_attachment_and_transfer_order,0,amtsgericht mönchengladbach\n-22- amtsgericht ...,amtsgericht mönchengladbach\n<NUMBER>- amtsger...
3926,PAIR Finance GmbH\nRh\n09. Mai 2023\nAMTSGERIC...,10.05.2023/1683714907_DS_006_10052023_123210.pdf,approved_attachment_and_transfer_order,0,pair finance gmbh\n09. mai 2023\namtsgericht\n...,pair finance gmbh\n<NUMBER>. mai <NUMBER>\namt...
3927,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,10.01.2025/ocr-v2_cae1ca2d-9b14-4824-9929-c8fa...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3928,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,19.11.2024/ocr-v2_54_M_3722_24_Schreiben_vom_1...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3929,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,06.09.2024/ocr-v2_53_M_2439_24_Schreiben_vom_0...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3930,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,01.04.2025/ocr-v2_54_M_1067_25_Schreiben_vom_3...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3931,Amtsgericht Viersen\n-Geschäftsstelle-\n-15- A...,30.06.2025/ocr-v2_RB_001_30062025_082941.pdf,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-geschäftsstelle-\n-15- a...,amtsgericht viersen\n-geschäftsstelle-\n<NUMBE...
3932,Amtsgericht Köln\nPAIR Finance GmbH\n24. Juli ...,25.07.2025/ocr-v2_RB_003_25072025_085035.pdf,approved_attachment_and_transfer_order,0,amtsgericht köln\npair finance gmbh\n24. juli ...,amtsgericht köln\npair finance gmbh\n<NUMBER>....
3933,Amtsgericht Ludwigslust\n- Zweigstelle Parchim...,28.07.2025/ocr-v2_RB_001_28072025_091413.pdf,approved_attachment_and_transfer_order,0,amtsgericht ludwigslust\n- zweigstelle parchim...,amtsgericht ludwigslust\n- zweigstelle parchim...
3934,Amtsgericht Köln\nPAIR Finance GmbH\nS C. Juni...,01.07.2025/ocr-v2_KL_005-01072025-083128.pdf,approved_attachment_and_transfer_order,0,amtsgericht köln\npair finance gmbh\ns c. juni...,amtsgericht köln\npair finance gmbh\ns c. juni...
3935,Amtsgericht Viersen\n-Geschäftsstelle-\n-15- A...,01.07.2025/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-geschäftsstelle-\n-15- a...,amtsgericht viersen\n-geschäftsstelle-\n<NUMBE...
3936,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,14.08.2025/ocr-v2_54_M_2784_25_Schreiben_vom_1...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3937,"Amtsgericht Kiel\nAmtsgericht Kiel, Deliusstra...",25.07.2023/1690275940_KD_005_25072023_103947.pdf,approved_attachment_and_transfer_order,0,"amtsgericht kiel\namtsgericht kiel, deliusstra...","amtsgericht kiel\namtsgericht kiel, deliusstra..."
3938,Amtsgericht Viersen\n-15- Amtsgericht Viersen ...,15.10.2024/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-15- amtsgericht viersen ...,amtsgericht viersen\n<NUMBER>- amtsgericht vie...
3939,Amtsgericht Viersen\n-15- Amtsgericht Viersen ...,23.10.2024/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-15- amtsgericht viersen ...,amtsgericht viersen\n<NUMBER>- amtsgericht vie...
3940,Amtsgericht Viersen\n-15- Amtsgericht Viersen ...,23.10.2024/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-15- amtsgericht viersen ...,amtsgericht viersen\n<NUMBER>- amtsgericht vie...
3941,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,13.01.2025/ocr-v2_9b286913-0ebd-44ef-ac69-002d...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3942,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,27.11.2024/ocr-v2_54_M_3808_24_Schreiben_vom_2...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3943,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,18.12.2024/ocr-v2_54_M_4109_24_Schreiben_vom_1...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3944,"Amtsgericht Köln\n-287a- Amtsgericht Köln, 509...",26.02.2025/ocr-v2_RB_006_26022025_101203.pdf,approved_attachment_and_transfer_order,0,"amtsgericht köln\n-287a- amtsgericht köln, 509...","amtsgericht köln\n-287a- amtsgericht köln, <NU..."
3945,Amtsgericht Münster\n-33- Amtsgericht Münster ...,04.02.2025/ocr-v2_FA_009_04022025_132655.pdf,approved_attachment_and_transfer_order,0,amtsgericht münster\n-33- amtsgericht münster ...,amtsgericht münster\n<NUMBER>- amtsgericht mün...
3946,Amtsgericht Grevenbroich\n-30- Amtsgericht Gre...,23.01.2025/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht grevenbroich\n-30- amtsgericht gre...,amtsgericht grevenbroich\n<NUMBER>- amtsgerich...
3947,Amtsgericht Grevenbroich\n-30- Amtsgericht Gre...,12.03.2025/ocr-v2_Allgemeines_Schreiben_R__202...,approved_attachment_and_transfer_order,0,amtsgericht grevenbroich\n-30- amtsgericht gre...,amtsgericht grevenbroich\n<NUMBER>- amtsgerich...
3948,Amtsgericht Bergisch Gladbach\n-38- Amtsgerich...,02.04.2025/ocr-v2_KL_006-02042025-145002.pdf,approved_attachment_and_transfer_order,0,amtsgericht bergisch gladbach\n-38- amtsgerich...,amtsgericht bergisch gladbach\n<NUMBER>- amtsg...
3949,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,08.08.2025/ocr-v2_53_M_2720_25_Schreiben_vom_0...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3950,Amtsgericht Köln\nFinance GmbH\n-288a- Amtsger...,04.06.2025/ocr-v2_KL_007-04062025-075751.pdf,approved_attachment_and_transfer_order,0,amtsgericht köln\nfinance gmbh\n-288a- amtsger...,amtsgericht köln\nfinance gmbh\n-288a- amtsger...
3951,Amtsgericht Münster\nA7/Bemerkung:\n-33- Amtsg...,19.06.2025/ocr-v2_RB_008_19062025_091941.pdf,approved_attachment_and_transfer_order,0,amtsgericht münster\na7/bemerkung:\n-33- amtsg...,amtsgericht münster\na7/bemerkung:\n<NUMBER>- ...
3952,Amtsgericht Münster\n-33- Amtsgericht Münster ...,25.06.2025/ocr-v2_48855bacff7f4a8c.pdf,approved_attachment_and_transfer_order,0,amtsgericht münster\n-33- amtsgericht münster ...,amtsgericht münster\n<NUMBER>- amtsgericht mün...
3953,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,14.08.2025/ocr-v2_54_M_2784_25_Schreiben_vom_1...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3954,Amtsgericht Viersen\n-15- Amtsgericht Viersen ...,28.08.2023/1693211648_CA_005_28082023_103302.pdf,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-15- amtsgericht viersen ...,amtsgericht viersen\n<NUMBER>- amtsgericht vie...
3955,Amtsgericht Münster\n-33- Amtsgericht Münster ...,02.10.2023/1696236517_KD_001_02102023_103939.pdf,approved_attachment_and_transfer_order,0,amtsgericht münster\n-33- amtsgericht münster ...,amtsgericht münster\n<NUMBER>- amtsgericht mün...
3956,Amtsgericht Euskirchen\n-401- Amtsgericht Eusk...,02.10.2023/1696236518_KD_001_02102023_103941.pdf,approved_attachment_and_transfer_order,0,amtsgericht euskirchen\n-401- amtsgericht eusk...,amtsgericht euskirchen\n<NUMBER>- amtsgericht ...
3957,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",19.09.2023/1695112479_KD_002_19092023_100807.pdf,approved_attachment_and_transfer_order,0,"amtsgericht lemgo\n-14- amtsgericht lemgo, am ...",amtsgericht lemgo\n<NUMBER>- amtsgericht lemgo...
3958,Amtsgericht Lemgo\n:-Geschäftsstelle-\n-14- Am...,19.09.2023/1695112480_KD_002_19092023_100808.pdf,approved_attachment_and_transfer_order,0,amtsgericht lemgo\n:-geschäftsstelle-\n-14- am...,amtsgericht lemgo\n:-geschäftsstelle-\n<NUMBER...
3959,Amtsgericht Viersen\n-15- Amtsgericht Viersen ...,12.01.2024/ocr-v2_JD_002_12012024_085742.pdf,approved_attachment_and_transfer_order,0,amtsgericht viersen\n-15- amtsgericht viersen ...,amtsgericht viersen\n<NUMBER>- amtsgericht vie...
3960,"Amtsgericht Kiel\nAmtsgericht Kiel, Deliusstra...",24.07.2023/1690187636_KD_004_24072023_101425.pdf,approved_attachment_and_transfer_order,0,"amtsgericht kiel\namtsgericht kiel, deliusstra...","amtsgericht kiel\namtsgericht kiel, deliusstra..."
3961,AMTSGERICHT RUDOLSTADT\nAmtsgericht Rudolstadt...,18.07.2023/1689665587_KD_004_18072023_091413.pdf,approved_attachment_and_transfer_order,0,amtsgericht rudolstadt\namtsgericht rudolstadt...,amtsgericht rudolstadt\namtsgericht rudolstadt...
3962,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,19.11.2024/ocr-v2_54_M_3722_24_Schreiben_vom_1...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3963,Amtsgericht Wedding\n-Zentrales Mahngericht Be...,04.12.2024/ocr-v2_RB_008_04122024_133334.pdf,approved_attachment_and_transfer_order,0,amtsgericht wedding\n-zentrales mahngericht be...,amtsgericht wedding\n-zentrales mahngericht be...
3964,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,27.11.2024/ocr-v2_53_M_3226_24_Schreiben_vom_2...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3965,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,29.11.2024/ocr-v2_53_M_3869_24_Schreiben_vom_2...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3966,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,07.04.2025/ocr-v2_54_M_1129_25_Schreiben_vom_0...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3967,"Amtsgericht\nAmtsgericht Osnabrück, Postfach 1...",24.07.2025/ocr-v2_DF-000B487F0194D410_B830DE54...,approved_attachment_and_transfer_order,0,"amtsgericht\namtsgericht osnabrück, postfach 1...","amtsgericht\namtsgericht osnabrück, postfach <..."
3968,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,05.05.2025/ocr-v2_54_M_1479_25_Schreiben_vom_0...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3969,Der Direktor des Amtsgerichts\nViersen\nDer Di...,05.05.2025/ocr-v2_RB_002_05052025_074856.pdf,approved_attachment_and_transfer_order,0,der direktor des amtsgerichts\nviersen\nder di...,der direktor des amtsgerichts\nviersen\nder di...
3970,Amtsgericht Memmingen\nAbteilung für Zwangsvol...,28.07.2025/ocr-v2_54_M_2538_25_Schreiben_vom_2...,approved_attachment_and_transfer_order,0,amtsgericht memmingen\nabteilung für zwangsvol...,amtsgericht memmingen\nabteilung für zwangsvol...
3971,"Amtsgericht Köln\n-288a- Amtsgericht Köln, 509...",30.05.2025/ocr-v2_FA_007_30052025_074018.pdf,approved_attachment_and_transfer_order,0,"amtsgericht köln\n-288a- amtsgericht köln, 509...","amtsgericht köln\n-288a- amtsgericht köln, <NU..."
3972,PAIR Finance GmbH\n31. Mai 2025\nAmtsgericht L...,02.06.2025/ocr-v2_FA_003_02062025_082505.pdf,approved_attachment_and_transfer_order,0,pair finance gmbh\n31. mai 2025\namtsgericht l...,pair finance gmbh\n<NUMBER>. mai <NUMBER>\namt...
3973,Der Direktor des Amtsgerichts\nViersen\nDer Di...,30.06.2025/ocr-v2_RB_001_30062025_082940.pdf,approved_attachment_and_transfer_order,0,der direktor des amtsgerichts\nviersen\nder di...,der direktor des amtsgerichts\nviersen\nder di...
3974,"Amtsgericht Köln\n-288a- Amtsgericht Köln, 509...",30.07.2025/ocr-v2_RB_003_30072025_085818.pdf,approved_attachment_and_transfer_order,0,"amtsgericht köln\n-288a- amtsgericht köln, 509...","amtsgericht köln\n-288a- amtsgericht köln, <NU..."

In [9]:
import random
keys = approved_seizure['object_key'].values
random_indices = random.sample(range(len(keys)), 3)
for index in random_indices:
    print(f"https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix={keys[index]}")

https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix=15.11.2022/1668506758_Scan_YA_00215112022_104157.pdf
https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix=27.06.2023/1687860442_KD_007_27062023_115318.pdf
https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix=29.04.2022/1651239035_Doc_29042022_000000001_151833_1.pdf

In [10]:
# NOTE: So we can consider approved_seizure and approved_attachment_and_transfer_order as PFUB Erlass documents.
# This dataset is old. So update the dataset with new PFUB Erlass documents from the database.
total_pfub_erlass_old_data = data.apply(lambda row: row['document_type'] in ['approved_seizure', 'approved_attachment_and_transfer_order'], axis=1).sum()
print(f"Total PFUB Erlass documents in the old dataset: {total_pfub_erlass_old_data}")

Total PFUB Erlass documents in the old dataset: 443

In [11]:
psql_db = DbConnection('PROD', f'PROD_DE')
distinct_doc_types = ['court_inbox', 'monierung_mb',
                      'attachment_and_transfer_order', 'list_assets_available',
                      'ladung_va', 'contradiction',
                      'enforcement_order']

query = """
select * 
from ocr_documents od 
where document_type = 'approved_seizure' or document_type = 'approved_attachment_and_transfer_order'
"""
data_new = psql_db.sql_to_df(query)

INFO [2025-11-28 13:20:25] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [12]:
data_new['document_type'].value_counts()

document_type
approved_seizure                          409
approved_attachment_and_transfer_order     59
Name: count, dtype: int64

In [13]:
number_of_pfub_erlass = data_new.shape[0]
print(f"Number of PFUB Erlass documents in the new dataset: \033[94m{number_of_pfub_erlass}\033[0m")
print(f"In old data we have \033[92m{total_pfub_erlass_old_data}\033[0m PFUB Erlass documents.")
diff = number_of_pfub_erlass - total_pfub_erlass_old_data
print(f"So we will have \033[91m{diff}\033[0m PFUB Erlass in addition to the old dataset.")

Number of PFUB Erlass documents in the new dataset: 468
In old data we have 443 PFUB Erlass documents.
So we will have 25 PFUB Erlass in addition to the old dataset.

In [14]:
max_date = data_new['created_at'].max().date()
min_date = data_new['created_at'].min()
print(f"PFUB Erlass documents date range: {min_date} to {max_date}")

PFUB Erlass documents date range: 2021-12-10 14:00:42.068378 to 2025-11-24

In [15]:
# order by created_at
data_new = data_new.sort_values(by='created_at', ascending=False)
data_new

,id,case_file_id,object_key,document_type,status,log,api_page,data,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at
437,337874,3395593.0,None,approved_seizure,processed,None,None,"{'case_slug': '133953267076', 'debtor_name': '...",2025-11-24 07:03:33.662133,2025-11-24 07:46:09.512033,44737502.0,ApprovedSeizure,None,ocr-v2_b3001e8b1bf6455d.pdf,application/pdf,36224,2025-11-24 07:03:33.406826,None
438,337540,6303646.0,None,approved_attachment_and_transfer_order,processed,None,None,"{'case_slug': '163033803426', 'debtor_name': '...",2025-11-21 07:14:45.687370,2025-11-21 08:51:22.265281,44523807.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_54_M_4008_25_Anschreiben_AG_Memmingen.pdf,application/pdf,361543,2025-11-21 07:14:45.638188,None
379,330617,5121632.0,None,approved_seizure,processed,None,None,"{'case_slug': '151213656300', 'debtor_name': '...",2025-11-05 07:24:07.066465,2025-11-05 07:30:14.965714,43042357.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20251104_fa365...,application/pdf,18602,2025-11-05 07:24:07.023015,None
466,328542,8106297.0,None,approved_attachment_and_transfer_order,processed,None,None,"{'case_slug': '181060314323', 'debtor_name': '...",2025-10-30 07:34:14.548009,2025-10-30 13:04:39.461131,42371114.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_c0872fd7aa1c431e.pdf,application/pdf,36077,2025-10-30 07:34:14.501955,None
445,327269,1717477.0,None,approved_seizure,processed,None,None,"{'case_slug': '117172090849', 'debtor_name': '...",2025-10-27 07:38:37.385680,2025-10-27 07:43:50.643896,42014715.0,ApprovedSeizure,None,ocr-v2_FA_005-27102025-083721.pdf,application/pdf,232861,2025-10-27 07:38:37.339367,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,27788,NaN,None,approved_seizure,processing,None,None,"{'case_slug': '107431129462', 'debtor_name': N...",2022-01-05 15:00:40.797951,2023-12-04 07:31:05.664746,NaN,ApprovedSeizure,None,1641394840_Doc_05012022_000000001_154522_1.pdf,application/pdf,406008,2022-01-05 15:00:40.736788,None
353,25330,NaN,None,approved_seizure,processing,None,None,"{'case_slug': '107380668148', 'debtor_name': N...",2021-12-21 14:30:37.764469,2023-12-11 08:45:38.120058,NaN,ApprovedSeizure,None,1640097037_Doc_21122021_000000002_150555_1.pdf,application/pdf,402281,2021-12-21 14:30:37.684004,None
394,24735,NaN,None,approved_seizure,processing,None,None,"{'case_slug': '107567488534', 'debtor_name': '...",2021-12-16 14:00:47.578722,2023-12-11 08:45:37.889068,NaN,ApprovedSeizure,None,1639663247_Doc_16122021_000000003_145356_1.pdf,application/pdf,515433,2021-12-16 14:00:47.541558,None
393,24651,NaN,None,approved_seizure,processing,None,None,"{'case_slug': '107010113754', 'debtor_name': N...",2021-12-13 15:00:43.849026,2023-12-11 08:45:37.684636,NaN,ApprovedSeizure,None,1639407643_Doc_13122021_000000001_154611_1.pdf,application/pdf,647895,2021-12-13 15:00:43.816408,None
392,24631,NaN,None,approved_seizure,processing,None,None,"{'case_slug': '106566894742', 'debtor_name': '...",2021-12-10 14:00:42.068378,2023-12-11 08:45:37.497647,NaN,ApprovedSeizure,None,1639144841_Doc_10122021_000000001_145845_1.pdf,application/pdf,503401,2021-12-10 14:00:42.032687,None

In [16]:
# create object key -> DAT.MONHT.YEAR/filename.pdf
data_new['object_key'] = data_new.apply(lambda row: row['created_at'].strftime('%d.%m.%Y') + '/' + row['document_file_name'], axis=1)

In [17]:
data_new

,id,case_file_id,object_key,document_type,status,log,api_page,data,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at
437,337874,3395593.0,24.11.2025/ocr-v2_b3001e8b1bf6455d.pdf,approved_seizure,processed,None,None,"{'case_slug': '133953267076', 'debtor_name': '...",2025-11-24 07:03:33.662133,2025-11-24 07:46:09.512033,44737502.0,ApprovedSeizure,None,ocr-v2_b3001e8b1bf6455d.pdf,application/pdf,36224,2025-11-24 07:03:33.406826,None
438,337540,6303646.0,21.11.2025/ocr-v2_54_M_4008_25_Anschreiben_AG_...,approved_attachment_and_transfer_order,processed,None,None,"{'case_slug': '163033803426', 'debtor_name': '...",2025-11-21 07:14:45.687370,2025-11-21 08:51:22.265281,44523807.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_54_M_4008_25_Anschreiben_AG_Memmingen.pdf,application/pdf,361543,2025-11-21 07:14:45.638188,None
379,330617,5121632.0,05.11.2025/ocr-v2_Allgemeines_Schreiben_R__202...,approved_seizure,processed,None,None,"{'case_slug': '151213656300', 'debtor_name': '...",2025-11-05 07:24:07.066465,2025-11-05 07:30:14.965714,43042357.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20251104_fa365...,application/pdf,18602,2025-11-05 07:24:07.023015,None
466,328542,8106297.0,30.10.2025/ocr-v2_c0872fd7aa1c431e.pdf,approved_attachment_and_transfer_order,processed,None,None,"{'case_slug': '181060314323', 'debtor_name': '...",2025-10-30 07:34:14.548009,2025-10-30 13:04:39.461131,42371114.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_c0872fd7aa1c431e.pdf,application/pdf,36077,2025-10-30 07:34:14.501955,None
445,327269,1717477.0,27.10.2025/ocr-v2_FA_005-27102025-083721.pdf,approved_seizure,processed,None,None,"{'case_slug': '117172090849', 'debtor_name': '...",2025-10-27 07:38:37.385680,2025-10-27 07:43:50.643896,42014715.0,ApprovedSeizure,None,ocr-v2_FA_005-27102025-083721.pdf,application/pdf,232861,2025-10-27 07:38:37.339367,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,27788,NaN,05.01.2022/1641394840_Doc_05012022_000000001_1...,approved_seizure,processing,None,None,"{'case_slug': '107431129462', 'debtor_name': N...",2022-01-05 15:00:40.797951,2023-12-04 07:31:05.664746,NaN,ApprovedSeizure,None,1641394840_Doc_05012022_000000001_154522_1.pdf,application/pdf,406008,2022-01-05 15:00:40.736788,None
353,25330,NaN,21.12.2021/1640097037_Doc_21122021_000000002_1...,approved_seizure,processing,None,None,"{'case_slug': '107380668148', 'debtor_name': N...",2021-12-21 14:30:37.764469,2023-12-11 08:45:38.120058,NaN,ApprovedSeizure,None,1640097037_Doc_21122021_000000002_150555_1.pdf,application/pdf,402281,2021-12-21 14:30:37.684004,None
394,24735,NaN,16.12.2021/1639663247_Doc_16122021_000000003_1...,approved_seizure,processing,None,None,"{'case_slug': '107567488534', 'debtor_name': '...",2021-12-16 14:00:47.578722,2023-12-11 08:45:37.889068,NaN,ApprovedSeizure,None,1639663247_Doc_16122021_000000003_145356_1.pdf,application/pdf,515433,2021-12-16 14:00:47.541558,None
393,24651,NaN,13.12.2021/1639407643_Doc_13122021_000000001_1...,approved_seizure,processing,None,None,"{'case_slug': '107010113754', 'debtor_name': N...",2021-12-13 15:00:43.849026,2023-12-11 08:45:37.684636,NaN,ApprovedSeizure,None,1639407643_Doc_13122021_000000001_154611_1.pdf,application/pdf,647895,2021-12-13 15:00:43.816408,None
392,24631,NaN,10.12.2021/1639144841_Doc_10122021_000000001_1...,approved_seizure,processing,None,None,"{'case_slug': '106566894742', 'debtor_name': '...",2021-12-10 14:00:42.068378,2023-12-11 08:45:37.497647,NaN,ApprovedSeizure,None,1639144841_Doc_10122021_000000001_145845_1.pdf,application/pdf,503401,2021-12-10 14:00:42.032687,None

In [18]:
# NOTE: ASK THIS IF TIS PFUB ERLASS: 24.11.2025/ocr-v2_b3001e8b1bf6455d.pdf. I SAVED IT UNDER DESKTOP/PFUB_ERLASS/SOR.PDF

In [19]:
# Now do left join on old data to see which documents are new

data_merged = data.merge(data_new, on='object_key', how='outer', suffixes=('_old', '_new'))

In [20]:
before_merge = data.shape[0]
after_merge = data_merged.shape[0]
print(f"Before merge: {before_merge}, After merge: {after_merge}")

Before merge: 5007, After merge: 5032

In [21]:
texts_needs_to_be_extracted = data_merged[data_merged['cleaned_text'].isnull()]
texts_needs_to_be_extracted
# NOTE: We need to call textract for these new 25 documetents

,text,object_key,document_type_old,is_ladung,cleaned_text,text_w_tags,id,case_file_id,document_type_new,status,...,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at
364,NaN,04.09.2025/ocr-v2_4ddb453253bb45c4.pdf,NaN,NaN,NaN,NaN,305145.0,5600064.0,approved_seizure,processed,...,2025-09-04 06:30:19.386140,2025-09-04 07:53:20.745115,37697604.0,ApprovedSeizure,None,ocr-v2_4ddb453253bb45c4.pdf,application/pdf,36548.0,2025-09-04 06:30:19.322545,None
365,NaN,04.09.2025/ocr-v2_FA_008-04092025-081100.pdf,NaN,NaN,NaN,NaN,305098.0,2933164.0,approved_seizure,processed,...,2025-09-04 06:12:12.419009,2025-09-04 07:58:03.679137,37697828.0,ApprovedSeizure,None,ocr-v2_FA_008-04092025-081100.pdf,application/pdf,224849.0,2025-09-04 06:12:12.365048,None
366,NaN,04.09.2025/ocr-v2_b655aab1cf7f435d.pdf,NaN,NaN,NaN,NaN,305162.0,6693319.0,approved_seizure,processed,...,2025-09-04 06:43:53.524558,2025-09-04 07:51:25.607969,37697436.0,ApprovedSeizure,None,ocr-v2_b655aab1cf7f435d.pdf,application/pdf,36175.0,2025-09-04 06:43:53.481108,None
367,NaN,04.09.2025/ocr-v2_df541b471b2e46a5.pdf,NaN,NaN,NaN,NaN,305174.0,6693319.0,approved_seizure,processed,...,2025-09-04 06:53:58.310300,2025-09-04 07:50:25.064688,37697381.0,ApprovedSeizure,None,ocr-v2_df541b471b2e46a5.pdf,application/pdf,36175.0,2025-09-04 06:53:58.265461,None
487,NaN,05.09.2025/ocr-v2_KL_003-05092025-082642.pdf,NaN,NaN,NaN,NaN,305989.0,6286416.0,approved_seizure,processed,...,2025-09-05 06:28:28.506066,2025-09-05 07:39:13.322513,37828894.0,ApprovedSeizure,None,ocr-v2_KL_003-05092025-082642.pdf,application/pdf,292946.0,2025-09-05 06:28:28.460718,None
499,NaN,05.11.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,330617.0,5121632.0,approved_seizure,processed,...,2025-11-05 07:24:07.066465,2025-11-05 07:30:14.965714,43042357.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20251104_fa365...,application/pdf,18602.0,2025-11-05 07:24:07.023015,None
1068,NaN,09.09.2025/ocr-v2_KL_006-09092025-090016.pdf,NaN,NaN,NaN,NaN,308161.0,3187275.0,approved_seizure,processed,...,2025-09-09 07:00:48.474719,2025-09-09 07:14:45.391438,38105775.0,ApprovedSeizure,None,ocr-v2_KL_006-09092025-090016.pdf,application/pdf,246431.0,2025-09-09 07:00:48.420699,None
2017,NaN,15.08.2025/ocr-v2_54_M_2805_25_Schreiben_vom_1...,NaN,NaN,NaN,NaN,295341.0,7040950.0,approved_seizure,processed,...,2025-08-15 06:28:54.216282,2025-08-15 11:45:15.069116,36333158.0,ApprovedSeizure,None,ocr-v2_54_M_2805_25_Schreiben_vom_14_08_2025_f...,application/pdf,361280.0,2025-08-15 06:28:54.168009,None
2018,NaN,15.08.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,294990.0,5413965.0,approved_seizure,processed,...,2025-08-15 05:48:40.077067,2025-08-15 11:39:21.133071,36333118.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20250814_10748...,application/pdf,19236.0,2025-08-15 05:48:40.034672,None
2169,NaN,16.10.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,324340.0,6643906.0,approved_seizure,processed,...,2025-10-16 05:39:11.373279,2025-10-16 06:12:52.017929,41197657.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20251015_9e8b5...,application/pdf,19020.0,2025-10-16 05:39:11.326513,None
2654,NaN,20.08.2025/ocr-v2_54_M_2863_25_Schreiben_vom_1...,NaN,NaN,NaN,NaN,296829.0,5458860.0,approved_attachment_and_transfer_order,processed,...,2025-08-20 06:49:23.851769,2025-08-20 13:17:42.233173,36628145.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_54_M_2863_25_Schreiben_vom_19_08_2025_f...,application/pdf,361730.0,2025-08-20 06:49:23.804666,None
2656,NaN,20.10.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,325082.0,6734221.0,approved_attachment_and_transfer_order,processed,...,2025-10-20 06:19:17.899778,2025-10-20 07:00:46.854194,41440371.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_Allgemeines_Schreiben_R__20251017_bde4a...,application/pdf,18837.0,2025-10-20 06:19:17.852345,None
2657,NaN,20.10.2025/ocr-v2_FA_004-20102025-083535.pdf,NaN,NaN,NaN,NaN,325170.0,3795204.0,approved_seizure,processed,...,2025-10-20 13:33:11.797170,2025-10-20 14:00:01.015942,41447742.0,ApprovedSeizure,None,ocr-v2_FA_004-20102025-083535.pdf,application/pdf,324882.0,2025-10-20 13:33:11.749430,None
2815,NaN,21.11.2025/ocr-v2_54_M_4008_25_Anschreiben_AG_...,NaN,NaN,NaN,NaN,337540.0,6303646.0,approved_attachment_and_transfer_order,processed,...,2025-11-21 07:14:45.687370,2025-11-21 08:51:22.265281,44523807.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_54_M_4008_25_Anschreiben_AG_Memmingen.pdf,application/pdf,361543.0,2025-11-21 07:14:45.638188,None
2933,NaN,22.10.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,325700.0,6721104.0,approved_seizure,processed,...,2025-10-22 06:16:56.788876,2025-10-22 07:08:12.060108,41697104.0,ApprovedSeizure,None,ocr-v2_Allgemeines_Schreiben_R__20251021_b6138...,application/pdf,18984.0,2025-10-22 06:16:56.743901,None
3145,NaN,24.09.2025/ocr-v2_5d0c3ff3fb7443d5.pdf,NaN,NaN,NaN,NaN,316872.0,7861163.0,approved_seizure,processed,...,2025-09-24 05:43:35.965093,2025-09-24 07:17:16.004306,39348081.0,ApprovedSeizure,None,ocr-v2_5d0c3ff3fb7443d5.pdf,application/pdf,36289.0,2025-09-24 05:43:35.919406,None
3152,NaN,24.10.2025/ocr-v2_53_M_3604_25_Anschreiben_AG_...,NaN,NaN,NaN,NaN,327060.0,7793935.0,approved_attachment_and_transfer_order,processed,...,2025-10-24 07:51:20.884242,2025-10-24 08:01:50.444788,41797168.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_53_M_3604_25_Anschreiben_AG_Memmingen.pdf,application/pdf,361552.0,2025-10-24 07:51:20.837292,None
3153,NaN,24.10.2025/ocr-v2_DR-II_127225_Nachr_Mitlg__an...,NaN,NaN,NaN,NaN,326873.0,7393845.0,approved_attachment_and_transfer_order,processed,...,2025-10-24 06:47:26.056656,2025-10-24 07:58:12.488081,41797118.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_DR-II_127225_Nachr_Mitlg__an_Glb_ueber_...,application/pdf,16105.0,2025-10-24 06:47:26.009367,None
3154,NaN,24.11.2025/ocr-v2_b3001e8b1bf6455d.pdf,NaN,NaN,NaN,NaN,337874.0,3395593.0,approved_seizure,processed,...,2025-11-24 07:03:33.662133,2025-11-24 07:46:09.512033,44737502.0,ApprovedSeizure,None,ocr-v2_b3001e8b1bf6455d.pdf,application/pdf,36224.0,2025-11-24 07:03:33.406826,None
3253,NaN,25.09.2025/ocr-v2_54_M_3289_25_Schreiben_vom_2...,NaN,NaN,NaN,NaN,318592.0,1607516.0,approved_attachment_and_transfer_order,processed,...,2025-09-25 07:19:05.068496,2025-09-25 07:28:02.701142,39385031.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_54_M_3289_25_Schreiben_vom_24_09_2025_f...,application/pdf,361596.0,2025-09-25 07:19:05.006257,None
3534,NaN,27.08.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,300712.0,7581540.0,approved_attachment_and_transfer_order,processed,...,2025-08-27 06:20:34.911592,2025-08-27 06:26:19.057141,37058658.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_Allgemeines_Schreiben_R__20250826_922a2...,application/pdf,20521.0,2025-08-27 06:20:34.867887,None
3535,NaN,27.08.2025/ocr-v2_Allgemeines_Schreiben_R__202...,NaN,NaN,NaN,NaN,301134.0,6517715.0,approved_attachment_and_transfer_order,processed,...,2025-08-27 07:19:18.775517,2025-08-27 13:57:27.670494,37080738.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_Allgemeines_Schreiben_R__20250826_fd0d7...,application/pdf,20406.0,2025-08-27 07:19:18.729315,None
3539,NaN,27.10.2025/ocr-v2_FA_005-27102025-083721.pdf,NaN,NaN,NaN,NaN,327269.0,1717477.0,approved_seizure,processed,...,2025-10-27 07:38:37.385680,2025-10-27 07:43:50.643896,42014715.0,ApprovedSeizure,None,ocr-v2_FA_005-27102025-083721.pdf,application/pdf,232861.0,2025-10-27 07:38:37.339367,None
3700,NaN,28.08.2025/ocr-v2_54_M_2957_25_Schreiben_vom_2...,NaN,NaN,NaN,NaN,301246.0,2274574.0,approved_seizure,processed,...,2025-08-28 07:11:18.239222,2025-08-28 07:13:25.131791,37204277.0,ApprovedSeizure,None,ocr-v2_54_M_2957_25_Schreiben_vom_28_08_2025_f...,application/pdf,360930.0,2025-08-28 07:11:18.191979,None
3944,NaN,30.10.2025/ocr-v2_c0872fd7aa1c431e.pdf,NaN,NaN,NaN,NaN,328542.0,8106297.0,approved_attachment_and_transfer_order,processed,...,2025-10-30 07:34:14.548009,2025-10-30 13:04:39.461131,42371114.0,ApprovedAttachmentAndTransferOrder,None,ocr-v2_c0872fd7aa1c431e.pdf,application/pdf,36077.0,2025-10-30 07:34:14.501955,None

In [22]:
col_from_old = data.columns.tolist()
col_from_new = data_merged.columns.tolist()

diff = set(col_from_new) - set(col_from_old)

print("Columns from old data:", col_from_old)
print("Columns from new data:", col_from_new)
print("New columns added after merge:", diff)

Columns from old data: ['text', 'object_key', 'document_type', 'is_ladung', 'cleaned_text', 'text_w_tags']
Columns from new data: ['text', 'object_key', 'document_type_old', 'is_ladung', 'cleaned_text', 'text_w_tags', 'id', 'case_file_id', 'document_type_new', 'status', 'log', 'api_page', 'data', 'created_at', 'updated_at', 'attachment_id', 'type', 'textract_job_id', 'document_file_name', 'document_content_type', 'document_file_size', 'document_updated_at', 'deleted_at']
New columns added after merge: {'type', 'api_page', 'created_at', 'updated_at', 'document_type_old', 'document_file_name', 'status', 'deleted_at', 'log', 'document_file_size', 'textract_job_id', 'id', 'attachment_id', 'data', 'document_updated_at', 'document_type_new', 'document_content_type', 'case_file_id'}

In [23]:
data_merged['document_type_old'] = data_merged.apply(lambda row: row['document_type_old'] if pd.notnull(row['document_type_old']) else row['document_type_new'], axis=1)

In [24]:
# rename document_type_old to document_type
data_merged = data_merged.rename(columns={'document_type_old': 'document_type'})

In [25]:
get_colums = col_from_old + ['data']

In [26]:
data_merged = data_merged[get_colums]

In [27]:
data_merged

,text,object_key,document_type,is_ladung,cleaned_text,text_w_tags,data
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,4070071 967072\nantrag auf erlass eines pfändu...,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfänd 070071 967072\nü...,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändungs\n4 070071 96...,antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN
...,...,...,...,...,...,...,...
5027,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,0.0,grover\nfriedhelm august steiner\nbestellnumme...,grover\nfriedhelm august steiner\nbestellnumme...,NaN
5028,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,0.0,liste des créances\ncréé le: 21.08.2025\nnumér...,liste des créances\ncréé le: <NUMBER>.2025\nnu...,NaN
5029,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,0.0,"11:06\nretour détails de la transaction\n-209,...",<NUMBER>:<NUMBER>\nretour détails de la transa...,NaN
5030,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,0.0,klinikum\nklinik für dermatologie\nnürnberg\nu...,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN
5031,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,0.0,delgmann + partner\nrechtsanwälte fachanwälte\...,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN

In [28]:
object_keys_text_required = data_merged[data_merged['cleaned_text'].isnull()]['object_key'].tolist()
object_keys_data_required = data_merged[(data_merged['data'].isnull()) & (data_merged['document_type'].isin(['approved_seizure', 'approved_attachment_and_transfer_order']))]['object_key'].tolist()

In [29]:
len(object_keys_text_required)

25

In [30]:
len(object_keys_data_required)

0

In [31]:
# Use textract to get texts for object_keys_text_required
import awswrangler.secretsmanager as sm
import boto3
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


class AppConfig:
    AWS_REGION = "eu-central-1"
    CACHE_TIMEOUT = 60
    DEBUG = False
    TESTING = False
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_ID = "text-request-production"

    @classmethod
    def init_secrets(cls):
        """Initialize secrets from AWS Secrets Manager"""
        cls.SQLALCHEMY_DATABASE_URI = get_secret(
            cls.SECRET_ID, "ANALYTICS_DATABASE_URI"
        )
        cls.ZENDESK_BEARER_TOKEN = get_secret(cls.SECRET_ID, "ZENDESK_BEARER_TOKEN")
        

class ModelConfig:
    lost_condition_interval_days = 7
    scheduler_interval_lost_llm_hours = 2
    scheduler_interval_textract_send_minutes = 10
    scheduler_interval_textract_get_minutes = 10
    ocr_s3_bucket = "pair-scanner"
    ocr_source_path = "ocr_source_files"
    ocr_results_path = "ocr_prepared_output"
    irrelevant_file_extentions = ["vcf", "gif", "p7s", "asc", "ics", "bin"]
    unsupported_file_extentions = ["html", "mp4"]
    

def get_secret(secret_id, value):
    return sm.get_secret_json(
        secret_id,
        boto3_session=boto3.Session(region_name=AppConfig.AWS_REGION),
    ).get(value)


import boto3
from typing import Dict, List


class TextractClient:
    def __init__(self, app_config, model_config):
        self.model_config = model_config
        self.app_config = app_config
        self.boto3_session = boto3.Session(region_name=self.app_config.AWS_REGION)
        self.client = self.boto3_session.client("textract")

    def submit_textract_job(self, bucket_name, document_key):
        try:
            response = self.client.start_document_text_detection(
                DocumentLocation={
                    "S3Object": {"Bucket": bucket_name, "Name": document_key}
                }
            )
            return response["JobId"]
        except Exception as e:
            print(
                f"Error submitting Textract job for document {document_key}: {str(e)}"
            )
            return None

    def check_job_status(self, job_id) -> Dict:
        try:
            response = self.client.get_document_text_detection(JobId=job_id)
            status = response["JobStatus"]

            if status == "SUCCEEDED":
                result = self.get_job_results(job_id)
                return {"status": status, "result": result}
            else:
                return {"status": status}

        except Exception as e:
            print(f"Error checking status for job {job_id}: {str(e)}")
            return {"status": "ERROR"}

    def get_job_results(self, job_id) -> List:
        results = []
        pagination_token = None
        while True:
            if pagination_token:
                response = self.client.get_document_text_detection(
                    JobId=job_id, NextToken=pagination_token
                )
            else:
                response = self.client.get_document_text_detection(JobId=job_id)
            # Note: we could also get document metedata to get info like # of pages etc.
            results.extend(response["Blocks"])

            if "NextToken" in response:
                pagination_token = response["NextToken"]
            else:
                break

        return results
    

def _get_textract_client() -> TextractClient:
    app_config = AppConfig()
    app_config.init_secrets()  # Initialize secrets before using them
    model_config = ModelConfig()
    return TextractClient(app_config, model_config)

In [32]:
from typing import List, Dict, Any
import time


def get_texts_from_textract_outputs(textract_outputs: List[Dict[str, Any]]) -> List[str]:
    raw_text_outputs = []
    for output in textract_outputs:
        if output is None:
            raw_text_outputs.append("")
        else:
            raw_text = []
            for cur_doc in output:
                if cur_doc["BlockType"] == "LINE":
                    raw_text.append(cur_doc["Text"])    
               
            raw_text_outputs.append("\n".join(raw_text))

    return raw_text_outputs

def submit_textract_job(textract_client: TextractClient, doc_key: str) -> Dict[str, Any]:
    """Submit a single Textract job and return job info."""
    try:
        job_id = textract_client.submit_textract_job(
            bucket_name=textract_client.model_config.ocr_s3_bucket, 
            document_key=doc_key
        )
        logger.info("Textract job submitted for document '%s' with job_id '%s'", doc_key, job_id)
        return {
            'job_id': job_id,
            'doc_key': doc_key,
            'status': 'SUBMITTED'
        }
    except Exception as e:
        logger.error("Failed to submit job for document '%s': %s", doc_key, str(e))
        return {
            'job_id': None,
            'doc_key': doc_key,
            'status': 'FAILED',
            'error': str(e)
        }


def wait_for_job_completion(textract_client: TextractClient, job_info: Dict[str, Any], max_wait_time: int = 100) -> Dict[str, Any]:
    """Wait for a Textract job to complete and return the result."""
    job_id = job_info['job_id']
    doc_key = job_info['doc_key']
    
    if job_info['status'] == 'FAILED':
        return {
            'doc_key': doc_key,
            'result': None,
            'status': 'FAILED',
            'error': job_info.get('error', 'Job submission failed')
        }
    
    max_count = 0
    while max_count < max_wait_time:
        try:
            time.sleep(1)
            res = textract_client.check_job_status(job_id=job_id)
            
            if res["status"] == "SUCCEEDED":
                logger.info("Job Completed for job_id '%s' (document: %s)", job_id, doc_key)
                return {
                    'doc_key': doc_key,
                    'result': res['result'],
                    'status': 'SUCCEEDED'
                }
            elif res["status"] == "FAILED":
                logger.error("Job Failed for job_id '%s' (document: %s)", job_id, doc_key)
                return {
                    'doc_key': doc_key,
                    'result': None,
                    'status': 'FAILED',
                    'error': 'Textract job failed'
                }
                
        except Exception as e:
            logger.error("Error checking job status for job_id '%s': %s", job_id, str(e))
            
        max_count += 1
    
    # Timeout reached
    logger.warning("Max retries exceeded for job_id '%s' (document: %s)", job_id, doc_key)
    
    return {
        'doc_key': doc_key,
        'result': None,
        'status': 'TIMEOUT',
        'error': 'Job timeout'
    }



def aws_textract_pipeline(object_keys: List[str], max_workers: int = 10) -> List:
    
    textract_outputs = [None] * len(object_keys)  # Placeholder for results
    
    logger.info("Starting AWS Textract Jobs with batch processing (max {} jobs at a time)", max_workers)
    batch_size = 25
    job_results = []
    total_jobs = len(object_keys)
    submitted = 0
    
    textract_client: TextractClient = _get_textract_client()

    while submitted < total_jobs:
        current_batch_keys = object_keys[submitted:submitted+batch_size]
        job_infos = []
        # Submit jobs for current batch
        for doc_key in current_batch_keys:
            job_info = submit_textract_job(textract_client, doc_key)
            job_infos.append(job_info)
            
        logger.info(f"Submitted batch {submitted//batch_size+1}: {len(current_batch_keys)} jobs")
        
        # Wait for jobs in current batch
        batch_results = []
        for job_info in job_infos:
            result = wait_for_job_completion(textract_client, job_info)
            batch_results.append(result)
    
        job_results.extend(batch_results)
        submitted += batch_size
        
        logger.info(f"Completed batch {submitted//batch_size}: {min(submitted, total_jobs)}/{total_jobs} jobs")
        
    # Sort results to maintain original order
    doc_key_to_result = {result['doc_key']: result for result in job_results}
    ordered_results = [doc_key_to_result[doc_key] for doc_key in object_keys]
    # Process results and update cache and output array
    successful_count = 0
    failed_count = 0
    
    for result in ordered_results:
        original_index = object_keys.index(result['doc_key'])
        if result['status'] == 'SUCCEEDED':
            textract_outputs[original_index] = result['result']
            successful_count += 1
        else:
            textract_outputs[original_index] = None
            failed_count += 1
            logger.warning("Failed to process document '%s': %s", result['doc_key'], result.get('error', 'Unknown error'))
            
    logger.info("AWS Textract pipeline completed: %d successful, %d failed", successful_count, failed_count)


    # Final validation - ensure no None values where we expect results
    total_successful = sum(1 for result in textract_outputs if result is not None)
    total_failed = len(textract_outputs) - total_successful

    logger.info("Final results: %d successful, %d failed (including cached)", total_successful, total_failed)

    return textract_outputs

In [ ]:

textract_outputs = aws_textract_pipeline(object_keys_text_required, max_workers=2)
texts = get_texts_from_textract_outputs(textract_outputs)

new_texts_dict = {obj_key: text for obj_key, text in zip(object_keys_text_required, texts)}
# add new texts to data_merged
for obj_key, text in new_texts_dict.items():
    data_merged.loc[data_merged['object_key'] == obj_key, 'text'] = text

--- Logging error ---
Traceback (most recent call last):
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/melih.gorgulu/miniconda3/envs/intent-recog/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_15385/1098140052.py", line 1, in <module>
    textract_outputs = aws_textract_pipeline(object_keys_text_required, max_workers=2)
  File "/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_15385/1823465143.py", line 99, in aws_textract_pipeline
    logger.info("Starting AWS Textract Jobs with batch processing (max {} jobs at a time)", max_workers)
Message: 'Starting AWS Textract Jobs with batch processing (max {} jobs at a time)'
Arguments: (2,)
INFO [2025-11-28 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2025-11-28 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2025-11-28 13:20:29] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2025-11-28 13:20:29] - Textract job submitted for document '04.09.2025/ocr-v2_4ddb453253bb45c4.pdf' with job_id '8543a1729c82d2549e6acca917d38ac28a170b23fbbfefd18432e5f7a6e2ab1b'
INFO [2025-11-28 13:20:30] - Textract job submitted for document '04.09.2025/ocr-v2_FA_008-04092025-081100.pdf' with job_id '5e4b94ba2d7a969a6db9b64942677868650fd7363e747a8f3879c7c819ae10be'
INFO [2025-11-28 13:20:30] - Textract job submitted for document '04.09.2025/ocr-v2_b655aab1cf7f435d.pdf' with job_id 'd740bee1159974289876b9d61b7923dd9b20413bb8cb5ceceea6bec18e2d740f'
INFO [2025-11-28 13:20:33] - Textract job submitted for document '04.09.2025/ocr-v2_df541b471b2e46a5.pdf' with job_id '0141da753b20051f14d1364e3a79f70fcd13284884a376437ca566283e24c36c'
INFO [2025-11-28 13:20:33] - Textract job submitted for document '05.09.2025/ocr-v2_KL_003-05092025-082642.pdf' with job_id 'aafd09202ab7430f70f146c4a31d32dd2102ee14115145c6306b8d4d8bc9db4b'
INFO [2025-11-28 13:20:34] - Textract job submitted for document '05.11.2025/ocr-v2_Allgemeines_Schreiben_R__20251104_fa3650c3028040e9.pdf' with job_id '9ee127de260073666971d583158b7dc03770e8092d87ca050f69edd8e939a00e'
INFO [2025-11-28 13:20:34] - Textract job submitted for document '09.09.2025/ocr-v2_KL_006-09092025-090016.pdf' with job_id 'e5038c57340c6904b546ffea0444f83b13de096ce757fbca765af4e059335bb3'
INFO [2025-11-28 13:20:35] - Textract job submitted for document '15.08.2025/ocr-v2_54_M_2805_25_Schreiben_vom_14_08_2025_formlos_AG_Memmingen.pdf' with job_id '0e4f51fe6490715742dc3cfd74d3fa9dedda728b07f1b0f0a3e9ddd53007fb57'
INFO [2025-11-28 13:20:36] - Textract job submitted for document '15.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250814_10748d395aed4041.pdf' with job_id 'f61295dbc4067f163383064848597bb89aba8a1b7ee5e41b46e8b4a84868fa1d'
INFO [2025-11-28 13:20:37] - Textract job submitted for document '16.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251015_9e8b545c776646a0.pdf' with job_id '3af5933ed6fe5998530515c640452810aa17d3c1fbfd83d6d023f8aff2d417a5'
INFO [2025-11-28 13:20:37] - Textract job submitted for document '20.08.2025/ocr-v2_54_M_2863_25_Schreiben_vom_19_08_2025_formlos_AG_Memmingen.pdf' with job_id '8d669d96468d5bbc7e1b72a49e1a71869d138a0ae9ee8ba8a5e1cbfda143586b'
INFO [2025-11-28 13:20:38] - Textract job submitted for document '20.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251017_bde4a5e26ffc43c3.pdf' with job_id 'ff064a0b4923e41291bae8f9b9433d719ae15ded913b84eae5afa3685142def1'
INFO [2025-11-28 13:20:38] - Textract job submitted for document '20.10.2025/ocr-v2_FA_004-20102025-083535.pdf' with job_id 'bf00c050f3d1f61f62c89c30b2dd63b3ac342c9c7b357ac691deb1e7c132bc1d'
INFO [2025-11-28 13:20:39] - Textract job submitted for document '21.11.2025/ocr-v2_54_M_4008_25_Anschreiben_AG_Memmingen.pdf' with job_id '671246493f144e08581456477a30a7f593bb428bab6d370a3642bda8e879551a'
INFO [2025-11-28 13:20:40] - Textract job submitted for document '22.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251021_b613824b826d440a.pdf' with job_id '090574500d1a156e389ab3bb7338521aeac88176f2b64a6d9d9fa87ef95396aa'
INFO [2025-11-28 13:20:41] - Textract job submitted for document '24.09.2025/ocr-v2_5d0c3ff3fb7443d5.pdf' with job_id '3b80dcb9ea880c6e312f61e92426f5e80f6ee01720940a42450a18fa4fa34207'
INFO [2025-11-28 13:20:41] - Textract job submitted for document '24.10.2025/ocr-v2_53_M_3604_25_Anschreiben_AG_Memmingen.pdf' with job_id 'b13a6af1f17167ffca05544b92d634049ba96d55a0edeacc6178203a497b3d62'
INFO [2025-11-28 13:20:42] - Textract job submitted for document '24.10.2025/ocr-v2_DR-II_127225_Nachr_Mitlg__an_Glb_ueber_Termin_VA_23_10_2025.pdf' with job_id '97004d2737827d7797fe4cf06bee7eed1d65f24fd708f14067e34a11e90ee205'
INFO [2025-11-28 13:20:42] - Textract job submitted for document '24.11.2025/ocr-v2_b3001e8b1bf6455d.pdf' with job_id 'cd94d26a574f1f57da1da6508fb3663a696b583c8a3a94cdf9790a32af86814f'
INFO [2025-11-28 13:20:42] - Textract job submitted for document '25.09.2025/ocr-v2_54_M_3289_25_Schreiben_vom_24_09_2025_formlos_AG_Memmingen.pdf' with job_id '9bcfbf3385bfeb21202bb1db443ae4cfd2762c73b35de69022e75b93c8dd3ad4'
INFO [2025-11-28 13:20:44] - Textract job submitted for document '27.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250826_922a2b1ee2094a77.pdf' with job_id '9c9a5a9005730795918f514228aef66e8aff305daf09fcc4dfe79b99b4aa5bdf'
INFO [2025-11-28 13:20:45] - Textract job submitted for document '27.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250826_fd0d7706783943fb.pdf' with job_id '59ee56f6b4a568fa5fe94bb398f04d51cdfb453c932b0d11e52670098952c518'
INFO [2025-11-28 13:20:45] - Textract job submitted for document '27.10.2025/ocr-v2_FA_005-27102025-083721.pdf' with job_id 'c7334d2fd7232f97a12cd6be042836048c17343848ddcd61007cecf74c3e0fce'
INFO [2025-11-28 13:20:45] - Textract job submitted for document '28.08.2025/ocr-v2_54_M_2957_25_Schreiben_vom_28_08_2025_formlos_AG_Memmingen.pdf' with job_id 'a551c26d850925cf820e0c5b8d921da7341341b0b10e22a4c6d35bac72d43c28'
INFO [2025-11-28 13:20:46] - Textract job submitted for document '30.10.2025/ocr-v2_c0872fd7aa1c431e.pdf' with job_id 'f62a657b9116918fa7c8fce76cb11e34957879b70faeb0289d7a73b0c3344eac'
INFO [2025-11-28 13:20:46] - Submitted batch 1: 25 jobs
INFO [2025-11-28 13:21:14] - Job Completed for job_id '8543a1729c82d2549e6acca917d38ac28a170b23fbbfefd18432e5f7a6e2ab1b' (document: 04.09.2025/ocr-v2_4ddb453253bb45c4.pdf)
INFO [2025-11-28 13:21:21] - Job Completed for job_id '5e4b94ba2d7a969a6db9b64942677868650fd7363e747a8f3879c7c819ae10be' (document: 04.09.2025/ocr-v2_FA_008-04092025-081100.pdf)
INFO [2025-11-28 13:21:26] - Job Completed for job_id 'd740bee1159974289876b9d61b7923dd9b20413bb8cb5ceceea6bec18e2d740f' (document: 04.09.2025/ocr-v2_b655aab1cf7f435d.pdf)
INFO [2025-11-28 13:21:28] - Job Completed for job_id '0141da753b20051f14d1364e3a79f70fcd13284884a376437ca566283e24c36c' (document: 04.09.2025/ocr-v2_df541b471b2e46a5.pdf)
INFO [2025-11-28 13:21:29] - Job Completed for job_id 'aafd09202ab7430f70f146c4a31d32dd2102ee14115145c6306b8d4d8bc9db4b' (document: 05.09.2025/ocr-v2_KL_003-05092025-082642.pdf)
INFO [2025-11-28 13:21:30] - Job Completed for job_id '9ee127de260073666971d583158b7dc03770e8092d87ca050f69edd8e939a00e' (document: 05.11.2025/ocr-v2_Allgemeines_Schreiben_R__20251104_fa3650c3028040e9.pdf)
INFO [2025-11-28 13:21:32] - Job Completed for job_id 'e5038c57340c6904b546ffea0444f83b13de096ce757fbca765af4e059335bb3' (document: 09.09.2025/ocr-v2_KL_006-09092025-090016.pdf)
INFO [2025-11-28 13:21:33] - Job Completed for job_id '0e4f51fe6490715742dc3cfd74d3fa9dedda728b07f1b0f0a3e9ddd53007fb57' (document: 15.08.2025/ocr-v2_54_M_2805_25_Schreiben_vom_14_08_2025_formlos_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:35] - Job Completed for job_id 'f61295dbc4067f163383064848597bb89aba8a1b7ee5e41b46e8b4a84868fa1d' (document: 15.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250814_10748d395aed4041.pdf)
INFO [2025-11-28 13:21:36] - Job Completed for job_id '3af5933ed6fe5998530515c640452810aa17d3c1fbfd83d6d023f8aff2d417a5' (document: 16.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251015_9e8b545c776646a0.pdf)
INFO [2025-11-28 13:21:37] - Job Completed for job_id '8d669d96468d5bbc7e1b72a49e1a71869d138a0ae9ee8ba8a5e1cbfda143586b' (document: 20.08.2025/ocr-v2_54_M_2863_25_Schreiben_vom_19_08_2025_formlos_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:39] - Job Completed for job_id 'ff064a0b4923e41291bae8f9b9433d719ae15ded913b84eae5afa3685142def1' (document: 20.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251017_bde4a5e26ffc43c3.pdf)
INFO [2025-11-28 13:21:40] - Job Completed for job_id 'bf00c050f3d1f61f62c89c30b2dd63b3ac342c9c7b357ac691deb1e7c132bc1d' (document: 20.10.2025/ocr-v2_FA_004-20102025-083535.pdf)
INFO [2025-11-28 13:21:41] - Job Completed for job_id '671246493f144e08581456477a30a7f593bb428bab6d370a3642bda8e879551a' (document: 21.11.2025/ocr-v2_54_M_4008_25_Anschreiben_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:43] - Job Completed for job_id '090574500d1a156e389ab3bb7338521aeac88176f2b64a6d9d9fa87ef95396aa' (document: 22.10.2025/ocr-v2_Allgemeines_Schreiben_R__20251021_b613824b826d440a.pdf)
INFO [2025-11-28 13:21:44] - Job Completed for job_id '3b80dcb9ea880c6e312f61e92426f5e80f6ee01720940a42450a18fa4fa34207' (document: 24.09.2025/ocr-v2_5d0c3ff3fb7443d5.pdf)
INFO [2025-11-28 13:21:46] - Job Completed for job_id 'b13a6af1f17167ffca05544b92d634049ba96d55a0edeacc6178203a497b3d62' (document: 24.10.2025/ocr-v2_53_M_3604_25_Anschreiben_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:47] - Job Completed for job_id '97004d2737827d7797fe4cf06bee7eed1d65f24fd708f14067e34a11e90ee205' (document: 24.10.2025/ocr-v2_DR-II_127225_Nachr_Mitlg__an_Glb_ueber_Termin_VA_23_10_2025.pdf)
INFO [2025-11-28 13:21:49] - Job Completed for job_id 'cd94d26a574f1f57da1da6508fb3663a696b583c8a3a94cdf9790a32af86814f' (document: 24.11.2025/ocr-v2_b3001e8b1bf6455d.pdf)
INFO [2025-11-28 13:21:50] - Job Completed for job_id '9bcfbf3385bfeb21202bb1db443ae4cfd2762c73b35de69022e75b93c8dd3ad4' (document: 25.09.2025/ocr-v2_54_M_3289_25_Schreiben_vom_24_09_2025_formlos_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:51] - Job Completed for job_id '9c9a5a9005730795918f514228aef66e8aff305daf09fcc4dfe79b99b4aa5bdf' (document: 27.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250826_922a2b1ee2094a77.pdf)
INFO [2025-11-28 13:21:53] - Job Completed for job_id '59ee56f6b4a568fa5fe94bb398f04d51cdfb453c932b0d11e52670098952c518' (document: 27.08.2025/ocr-v2_Allgemeines_Schreiben_R__20250826_fd0d7706783943fb.pdf)
INFO [2025-11-28 13:21:54] - Job Completed for job_id 'c7334d2fd7232f97a12cd6be042836048c17343848ddcd61007cecf74c3e0fce' (document: 27.10.2025/ocr-v2_FA_005-27102025-083721.pdf)
INFO [2025-11-28 13:21:56] - Job Completed for job_id 'a551c26d850925cf820e0c5b8d921da7341341b0b10e22a4c6d35bac72d43c28' (document: 28.08.2025/ocr-v2_54_M_2957_25_Schreiben_vom_28_08_2025_formlos_AG_Memmingen.pdf)
INFO [2025-11-28 13:21:57] - Job Completed for job_id 'f62a657b9116918fa7c8fce76cb11e34957879b70faeb0289d7a73b0c3344eac' (document: 30.10.2025/ocr-v2_c0872fd7aa1c431e.pdf)
INFO [2025-11-28 13:21:57] - Completed batch 1: 25/25 jobs
INFO [2025-11-28 13:21:57] - AWS Textract pipeline completed: 25 successful, 0 failed
INFO [2025-11-28 13:21:57] - Final results: 25 successful, 0 failed (including cached)

In [34]:
data_merged

,text,object_key,document_type,is_ladung,cleaned_text,text_w_tags,data
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,4070071 967072\nantrag auf erlass eines pfändu...,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfänd 070071 967072\nü...,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändungs\n4 070071 96...,antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,0.0,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN
...,...,...,...,...,...,...,...
5027,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,0.0,grover\nfriedhelm august steiner\nbestellnumme...,grover\nfriedhelm august steiner\nbestellnumme...,NaN
5028,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,0.0,liste des créances\ncréé le: 21.08.2025\nnumér...,liste des créances\ncréé le: <NUMBER>.2025\nnu...,NaN
5029,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,0.0,"11:06\nretour détails de la transaction\n-209,...",<NUMBER>:<NUMBER>\nretour détails de la transa...,NaN
5030,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,0.0,klinikum\nklinik für dermatologie\nnürnberg\nu...,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN
5031,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,0.0,delgmann + partner\nrechtsanwälte fachanwälte\...,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN

In [ ]:
data_merged['is_pfub'] = data_merged.apply(lambda row: row['document_type'] in ['approved_seizure', 'approved_attachment_and_transfer_order'], axis=1)

In [37]:
data_merged

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,False
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,False
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,False
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,False
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,False
...,...,...,...,...,...,...,...
5027,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,grover\nfriedhelm august steiner\nbestellnumme...,grover\nfriedhelm august steiner\nbestellnumme...,NaN,False
5028,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,liste des créances\ncréé le: 21.08.2025\nnumér...,liste des créances\ncréé le: <NUMBER>.2025\nnu...,NaN,False
5029,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,"11:06\nretour détails de la transaction\n-209,...",<NUMBER>:<NUMBER>\nretour détails de la transa...,NaN,False
5030,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,klinikum\nklinik für dermatologie\nnürnberg\nu...,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN,False
5031,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,delgmann + partner\nrechtsanwälte fachanwälte\...,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN,False

In [38]:
data_merged['document_type'].value_counts()

document_type
ladung_va                                 2100
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              541
approved_seizure                           409
court_inbox                                346
approved_attachment_and_transfer_order      59
enforcement_order                           23
contradiction                                3
Name: count, dtype: int64

In [39]:
data_merged['is_pfub'].value_counts()

is_pfub
False    4564
True      468
Name: count, dtype: int64

In [40]:
data_merged.to_csv("../data/PFUB_ERLASS_dataset.csv", index=False)