In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('../data/PFUB_ERLASS_dataset_processed.csv')

In [3]:
data

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs..."
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes..."
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb..."
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs..."
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe..."
...,...,...,...,...,...,...,...,...,...
5026,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,grover\nfriedhelm august steiner\nbestellnumme...,grover\nfriedhelm august steiner\nbestellnumme...,NaN,False,False,"['grover', 'friedhelm', 'august', 'steiner', '..."
5027,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,liste des créances\ncréé le: 21.08.2025\nnumér...,liste des créances\ncréé le: <NUMBER>.2025\nnu...,NaN,False,False,"['liste', 'créance', 'créé', 'le', 'numéro', '..."
5028,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,"11:06\nretour détails de la transaction\n-209,...",<NUMBER>:<NUMBER>\nretour détails de la transa...,NaN,False,False,"['retour', 'détails', '--', '--', 'transaction..."
5029,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,klinikum\nklinik für dermatologie\nnürnberg\nu...,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN,False,False,"['klinikum', 'klinik', 'dermatologie', 'nürnbe..."
5030,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,delgmann + partner\nrechtsanwälte fachanwälte\...,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN,False,False,"['delgmann', '+', 'partner', 'rechtsanwälte', ..."

#### New Tag: Geschäftsnummer

In [4]:
#### New Tag: Geschäftsnummer

# Updated regex to match patterns like: 5 am 3951/23, 5a m 905/24, 5 am 4087/22, 7m 797/23

regex_geschaeftsnummer = r"(?i)\b(?:\d+\s*a?\s*m\s*\d+(?:\/\d+)?|m\s+\d+\/\d+)\b"
import re

In [5]:
data['geschaeftsnummer'] = data['cleaned_text'].apply(lambda x: re.findall(regex_geschaeftsnummer, x))
data['has_geschaeftsnummer'] = data['geschaeftsnummer'].apply(lambda x: len(x) > 0)

In [6]:
data[['geschaeftsnummer','has_geschaeftsnummer','is_pfub']]

     geschaeftsnummer  has_geschaeftsnummer  is_pfub
0                  []                 False    False
1                  []                 False    False
2          [20 am 01]                  True    False
3                  []                 False    False
4                  []                 False    False
...               ...                   ...      ...
5026               []                 False    False
5027               []                 False    False
5028               []                 False    False
5029               []                 False    False
5030               []                 False    False

[5031 rows x 3 columns]

In [7]:
has_geschaeftsnummer_NO_PFUB = data[(data['has_geschaeftsnummer'] == True) & (data['is_pfub'] == False)]
NOT_has_geschaeftsnummer_PFUB = data[(data['has_geschaeftsnummer'] == False) & (data['is_pfub'] == True)]

In [8]:
has_geschaeftsnummer_NO_PFUB.shape, NOT_has_geschaeftsnummer_PFUB.shape

((34, 11), (1, 11))

In [9]:
has_geschaeftsnummer_NO_PFUB

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized,geschaeftsnummer,has_geschaeftsnummer
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",[20 am 01],True
61,Amtsgericht Heinsberg\nPAIR Finance GmbH\n28. ...,02.05.2023/1683018418_YA_002_02052023_104625.pdf,attachment_and_transfer_order,amtsgericht heinsberg\npair finance gmbh\n28. ...,amtsgericht heinsberg\npair finance gmbh\n<NUM...,NaN,False,False,"['amtsgericht', 'heinsberg', 'pair', 'finance'...",[10 m 795/23],True
371,"Amtsgericht\nAmtsgericht Burgwedel, Postfach 1...",04.11.2024/ocr-v2_111239589364.EU_Z_00581Übers...,court_inbox,"amtsgericht\namtsgericht burgwedel, postfach 1...","amtsgericht\namtsgericht burgwedel, postfach <...",NaN,False,False,"['amtsgericht', 'amtsgericht', 'burgwedel', 'p...","[5a m 905/24, 5a m 905/24]",True
1060,"Amtsgericht Flensburg\nAmtsgericht Flensburg, ...",09.08.2023/1691564795_KD_002_09082023_084442.pdf,attachment_and_transfer_order,"amtsgericht flensburg\namtsgericht flensburg, ...","amtsgericht flensburg\namtsgericht flensburg, ...",NaN,False,False,"['amtsgericht', 'flensburg', 'amtsgericht', 'f...",[53 m 1267/23],True
1165,Amtsgericht Leverkusen\nPAIR Finance GmbH\n09....,10.08.2023/1691652786_PF_005_10082023_091626.pdf,attachment_and_transfer_order,amtsgericht leverkusen\npair finance gmbh\n09....,amtsgericht leverkusen\npair finance gmbh\n<NU...,NaN,False,False,"['amtsgericht', 'leverkusen', 'pair', 'finance...",[45 m 3062/23],True
1318,Hauptgerichtsvollzieher\n80992 München\nPeer\n...,11.12.2024/ocr-v2_80_dr_792_24_05a_an_gl_vv_se...,ladung_va,hauptgerichtsvollzieher\n80992 münchen\npeer\n...,hauptgerichtsvollzieher\n<NUMBER> münchen\npee...,NaN,False,True,"['hauptgerichtsvollzieh', 'münchen', 'peer', '...",[290869 m 016],True
1320,Wormser Landstr. 6\nGUNTER SCHULZ\n67551 Worms...,11.12.2024/ocr-v2_DR-II_100224_Nachr_Mitlg_an_...,ladung_va,wormser landstr. 6\ngunter schulz\n67551 worms...,wormser landstr. <NUMBER>\ngunter schulz\n<NUM...,NaN,False,True,"['wormser', 'landstr', 'gunter', 'schulz', 'wo...","[15 m 2712/24, 15 m 2712/24, 15 m 2712/24, 15 ...",True
1322,Postanschrift:\nBianka Zinn\nJustus-Perthes-St...,11.12.2024/ocr-v2_DR-II_130824_Nachr_GKB-ERVQ_...,ladung_va,postanschrift:\nbianka zinn\njustus-perthes-st...,postanschrift:\nbianka zinn\njustus-perthes-st...,NaN,False,True,"['postanschrift', 'bianka', 'zinn', 'justus-pe...","[2023\nm 624/23, 2023\nm 624/23, 2023\nm 624/2...",True
1338,M. Jödicke\nHellersdorfer Weg 35\nObergerichts...,11.12.2024/ocr-v2_Dokumente_129024_10122024_16...,ladung_va,m. jödicke\nhellersdorfer weg 35\nobergerichts...,m. jödicke\nhellersdorfer weg <NUMBER>\noberge...,NaN,False,True,"['m.', 'jödicke', 'hellersdorfer', 'weg', 'obe...",[041095 m 018],True
1343,Nadine Berkemeier\nRumbecker Straße 8\nGericht...,11.12.2024/ocr-v2_Dokumente_211724_10122024_14...,ladung_va,nadine berkemeier\nrumbecker straße 8\ngericht...,nadine berkemeier\nrumbecker straße <NUMBER>\n...,NaN,False,True,"['nadine', 'berkemeier', 'rumbecker', 'straße'...",[11171101m074],True
1574,Amtsgericht Duisburg\n-634- Amtsgericht Duisbu...,13.07.2023/1689237319_KD_002_13072023_100721.pdf,attachment_and_transfer_order,amtsgericht duisburg\n-634- amtsgericht duisbu...,amtsgericht duisburg\n<NUMBER>- amtsgericht du...,NaN,False,False,"['amtsgericht', 'duisburg', 'amtsgerichen', 'd...",[634 m 807/23],True
1772,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,14.08.2023/1692005615_MA_008_14082023_113233.pdf,attachment_and_transfer_order,amtsgericht frankfurt am main\nmobiliarzwangsv...,amtsgericht frankfurt am main\nmobiliarzwangsv...,NaN,False,False,"['amtsgericht', 'frankfurt', 'main', 'mobiliar...",[82 m 10356/23],True
1795,Antrag auf Erlass eines Pfändungs- und\n1\nÜbe...,14.08.2023/1692023606_SK_001_14082023_163008.pdf,attachment_and_transfer_order,antrag auf erlass eines pfändungs- und\nüberwe...,antrag auf erlass eines pfändungs- und\nüberwe...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[00\nam 14],True
1925,Amtsgericht Coburg\nA123\nZentrales Mahngerich...,15.07.2025/ocr-v2_VSB_Scan_000000210201_04_07_...,enforcement_order,amtsgericht coburg\na123\nzentrales mahngerich...,amtsgericht coburg\na123\nzentrales mahngerich...,NaN,False,False,"['amtsgericht', 'coburg', 'a123', 'zentral', '...",[63\nam 10],True
2104,Antrag auf Erlass eines Pfändungs- und\n1\nÜbe...,16.08.2023/1692180306_SK_001_16082023_114452.pdf,attachment_and_transfer_order,antrag auf erlass eines pfändungs- und\nüberwe...,antrag auf erlass eines pfändungs- und\nüberwe...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[00\nam 16],True
2613,THOMAS METHNER\nBremer Str. 40\n27749 Delmenho...,20.03.2024/ocr-v2_AK_001_20032024_090051.pdf,ladung_va,thomas methner\nbremer str. 40\n27749 delmenho...,thomas methner\nbremer str. <NUMBER>\n<NUMBER>...,NaN,False,True,"['thomas', 'methner', 'bremer', 'str', 'delmen...","[10 m 1805/22, 10 m 1805/22, 10 m 1805/22, 10 ...",True
3112,PAIR Finance GmbH\n23. Juli 2024\nAmtsgericht ...,24.07.2024/ocr-v2_ZJ_005_24072024_144624.pdf,attachment_and_transfer_order,pair finance gmbh\n23. juli 2024\namtsgericht ...,pair finance gmbh\n<NUMBER>. juli <NUMBER>\nam...,NaN,False,False,"['pair', 'finance', 'gmbh', 'juli', 'amtsgeric...",[2 m 2836/24],True
3136,Obergerichtsvollzieherin Christiane Klos\nBüro...,24.09.2024/ocr-v2_GVZ_0_sammel1_(2).pdf,ladung_va,obergerichtsvollzieherin christiane klos\nbüro...,obergerichtsvollzieherin christiane klos\nbüro...,NaN,False,True,"['obergerichtsvollzieherin', 'christiane', 'kl...",[8\nam 14],True
3137,Obergerichtsvollzieher\nLammstr. 11\nK. Nöbaue...,24.09.2024/ocr-v2_GVZ_2_dr_1002_24_an_gl_nachr...,ladung_va,obergerichtsvollzieher\nlammstr. 11\nk. nöbaue...,obergerichtsvollzieher\nlammstr. <NUMBER>\nk. ...,NaN,False,True,"['obergerichtsvollzieher', 'lammstr', 'k.', 'n...",[340602951\nam 14],True
3141,Gerichtsstraße 2 -Amtsgericht-\n15907 Lübben\n...,24.09.2024/ocr-v2_GVZ_Sammelmappe11.pdf,ladung_va,gerichtsstraße 2 -amtsgericht-\n15907 lübben\n...,gerichtsstraße <NUMBER> -amtsgericht-\n<NUMBER...,NaN,False,True,"['gerichtsstraße', '-amtsgericht-', 'lübben', ...","[50 m 140/23, 50 m 140/23, 50 m 140/23, 50 m 1...",True
3175,Amtsgericht Langenfeld\n-95- Amtsgericht Lange...,25.04.2023/1682411691_YA_001_25042023_101934.pdf,attachment_and_transfer_order,amtsgericht langenfeld\n-95- amtsgericht lange...,amtsgericht langenfeld\n<NUMBER>- amtsgericht ...,NaN,False,False,"['amtsgericht', 'langenfeld', 'amtsgerichen', ...",[95 m 1093/23],True
3260,Amtsgericht Langen (Hessen)\nVollstreckungsger...,25.10.2024/ocr-v2_EU_Z_00021FreitextschreibenB...,court_inbox,amtsgericht langen (hessen)\nvollstreckungsger...,amtsgericht langen (hessen)\nvollstreckungsger...,NaN,False,False,"['amtsgericht', 'lang', 'hessen', 'vollstrecku...",[71 m 2303/24],True
3611,Amtsgericht Lemgo\nGeschäftsstelle\n-14- Amtsg...,28.04.2023/1682678109_DS_003_28042023_121512.pdf,attachment_and_transfer_order,amtsgericht lemgo\ngeschäftsstelle\n-14- amtsg...,amtsgericht lemgo\ngeschäftsstelle\n<NUMBER>- ...,NaN,False,False,"['amtsgericht', 'lemgo', 'geschäftsstelle', 'a...",[14 m 764/23],True
3705,Amtsgericht Rostock\nAmtsgericht Rostock PF 10...,28.10.2024/ocr-v2_RB_004_28102024_133353.pdf,court_inbox,amtsgericht rostock\namtsgericht rostock pf 10...,amtsgericht rostock\namtsgericht rostock pf <N...,NaN,False,False,"['amtsgericht', 'rostock', 'amtsgericht', 'ros...",[63 m 3656/24],True
3710,Peter Lüdtke\nBrahmsstr. 42\nObergerichtsvollz...,28.11.2024/ocr-v2_Dokument_191724_27112024_112...,ladung_va,peter lüdtke\nbrahmsstr. 42\nobergerichtsvollz...,peter lüdtke\nbrahmsstr. <NUMBER>\nobergericht...,NaN,False,True,"['peter', 'lüdtke', 'brahmsstr', 'obergerichts...","[22 m 3332/02, 24 m 6367/05, 18 m 34/14, 35 m\...",True
3985,Antrag auf Erlass eines Pfändu\n4070071 967072...,31.01.2022/1643639438_Doc_31012022_000000002_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",[20 am 31],True
4040,"8/21/25, 1:26 PM\nTransaction\nKlarna\nZahlung...",NaN,mail_attachments,"8/21/25, 1:26 pm\ntransaction\nklarna\nzahlung...","<NUMBER>/<NUMBER>/<NUMBER>, <NUMBER>:<NUMBER> ...",NaN,False,False,"['pm', 'transaction', 'klarna', 'zahlung', 'fe...","[m\n8/21, m\n8/21]",True
4420,09:10\nzalando\nPlus\nDamen\nHerren\nKinder\nB...,NaN,mail_attachments,09:10\nzalando\nplus\ndamen\nherren\nkinder\nb...,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,NaN,False,False,"['zalando', 'plus', 'damen', 'herren', 'kind',...",[10603065778166 am 28],True
4560,STEINHAUER GÜNTHER\nRECHTSANWÄLTE & NOTAR\nRAE...,NaN,mail_attachments,steinhauer günther\nrechtsanwälte & notar\nrae...,steinhauer günther\nrechtsanwälte & notar\nrae...,NaN,False,False,"['steinhauer', 'günther', 'rechtsanwälte', 'no...",[7428357\nam 02],True
4705,energienetze\nmittelrhein\nEnergienetze Mittel...,NaN,mail_attachments,energienetze\nmittelrhein\nenergienetze mittel...,energienetze\nmittelrhein\nenergienetze mittel...,NaN,False,False,"['energienetze', 'mittelrhein', 'energienetzen...",[3038m3],True
4865,THANKS FOR\nMILES\nYOUR RIDE!\nTarek Shtewe\nM...,NaN,mail_attachments,thanks for\nmiles\nyour ride!\ntarek shtewe\nm...,thanks for\nmiles\nyour ride!\ntarek shtewe\nm...,NaN,False,False,"['thanks', 'for', 'mil', 'your', 'ride', 'tare...",[50m\n99],True
4923,Kontonummer\nerstellt am\nAuszug\nBlatt\nFrank...,NaN,mail_attachments,kontonummer\nerstellt am\nauszug\nblatt\nfrank...,kontonummer\nerstellt am\nauszug\nblatt\nfrank...,NaN,False,False,"['kontonummer', 'erstellen', 'auszug', 'blatt'...",[00001747 am 03],True
4941,09:10\nzalando\nPlus\nDamen\nHerren\nKinder\nB...,NaN,mail_attachments,09:10\nzalando\nplus\ndamen\nherren\nkinder\nb...,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,NaN,False,False,"['zalando', 'plus', 'damen', 'herren', 'kind',...",[10603065778166 am 28],True
4985,€\nschuldenanalyse-kostenlos.de\nrightmart Ber...,NaN,mail_attachments,schuldenanalyse-kostenlos.de\nrightmart berlin...,schuldenanalyse-kostenlos.de\nrightmart berlin...,NaN,False,False,"['schuldenanalyse-kostenlos.de', 'rightmart', ...",[202 m 6266/24],True

In [10]:
NOT_has_geschaeftsnummer_PFUB # this data gescaftnummber is 24-Og54fea-08-N (Different pattern)
# so its okay

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized,geschaeftsnummer,has_geschaeftsnummer
418,Amtsgericht Wedding\n-Zentrales Mahngericht Be...,04.12.2024/ocr-v2_RB_008_04122024_133334.pdf,approved_attachment_and_transfer_order,amtsgericht wedding\n-zentrales mahngericht be...,amtsgericht wedding\n-zentrales mahngericht be...,"{'case_slug': '152944268209', 'debtor_name': '...",True,False,"['amtsgericht', 'wedding', '-zentrales', 'mahn...",[],False

In [11]:
show_index = 13
row = has_geschaeftsnummer_NO_PFUB.iloc[show_index]
row

text                    Amtsgericht Coburg\nA123\nZentrales Mahngerich...
object_key              15.07.2025/ocr-v2_VSB_Scan_000000210201_04_07_...
document_type                                           enforcement_order
cleaned_text            amtsgericht coburg\na123\nzentrales mahngerich...
text_w_tags             amtsgericht coburg\na123\nzentrales mahngerich...
data                                                                  NaN
is_pfub                                                             False
is_ladung                                                           False
tokenized               ['amtsgericht', 'coburg', 'a123', 'zentral', '...
geschaeftsnummer                                              [63\nam 10]
has_geschaeftsnummer                                                 True
Name: 1925, dtype: object

In [13]:
"""show_index = 28
row = has_geschaeftsnummer_NO_PFUB.iloc[show_index]
document_key = row['object_key']
base = "https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix="
 
document_url = base + document_key

# Color codes
RED = '\033[1;31m'
GREEN = '\033[1;32m'
YELLOW = '\033[1;33m'
BLUE = '\033[1;34m'
MAGENTA = '\033[1;35m'
CYAN = '\033[1;36m'
RESET = '\033[0m'

if row['has_geschaeftsnummer']:
    print(f"{RED}Document has Geschäftsnummer but is not PFUB{RESET}")
    print(f"{CYAN}DOCUMENT URL: {BLUE}{document_url}{RESET}")
    print(f"{YELLOW}DOCUMENT TYPE: {GREEN}{has_geschaeftsnummer_NO_PFUB.iloc[show_index]['document_type']}{RESET}")
    geschaeftsnummer = row['geschaeftsnummer']
    # print text with highlighted geschäftsnummer
    text = row['cleaned_text']
    for gn in geschaeftsnummer:
        text = text.replace(gn, f"{MAGENTA}{gn}{RESET}")
    print(f"\n{text}")
else:
    print(f"{RED}Document is PFUB but does not have Geschäftsnummer{RESET}")
    print(f"{CYAN}DOCUMENT URL: {BLUE}{document_url}{RESET}")
    print(f"\n{row['cleaned_text']}")
    """

'show_index = 28\nrow = has_geschaeftsnummer_NO_PFUB.iloc[show_index]\ndocument_key = row[\'object_key\']\nbase = "https://eu-central-1.console.aws.amazon.com/s3/object/pair-scanner?region=eu-central-1&prefix="\n \ndocument_url = base + document_key\n\n# Color codes\nRED = \'\x1b[1;31m\'\nGREEN = \'\x1b[1;32m\'\nYELLOW = \'\x1b[1;33m\'\nBLUE = \'\x1b[1;34m\'\nMAGENTA = \'\x1b[1;35m\'\nCYAN = \'\x1b[1;36m\'\nRESET = \'\x1b[0m\'\n\nif row[\'has_geschaeftsnummer\']:\n    print(f"{RED}Document has Geschäftsnummer but is not PFUB{RESET}")\n    print(f"{CYAN}DOCUMENT URL: {BLUE}{document_url}{RESET}")\n    print(f"{YELLOW}DOCUMENT TYPE: {GREEN}{has_geschaeftsnummer_NO_PFUB.iloc[show_index][\'document_type\']}{RESET}")\n    geschaeftsnummer = row[\'geschaeftsnummer\']\n    # print text with highlighted geschäftsnummer\n    text = row[\'cleaned_text\']\n    for gn in geschaeftsnummer:\n        text = text.replace(gn, f"{MAGENTA}{gn}{RESET}")\n    print(f"\n{text}")\nelse:\n    print(f"{RED}Document is PFUB but does not have Geschäftsnummer{RESET}")\n    print(f"{CYAN}DOCUMENT URL: {BLUE}{document_url}{RESET}")\n    print(f"\n{row[\'cleaned_text\']}")\n    '

In [ ]:
# some false alarms:
# orderungskonto 17757/20 am 01.02.2022
# 28.11.2023/n m 624/23
# 00\nam 14 (cause: date)
# '63\nam 10' (knesebeckstr. 62-63 am 10.04.25 *******224,96 eur)

In [ ]:
# NOTE: MAKE SURE TO REPLACE URLS BEFORE OTHER TOKENS
# NOTE MAKE SURE TO COVER WITH Am
# NOTE: MAKE PATTERN COMPATIBLE TO OCR ERRORS

# e.g: 5 am 3951/23, 5a m 905/24, 5 am 4087/22, 7m 797/23
# RESULT: TO SOLVE THE PROBLEM, REPLACE DATES WITH TAG <DATE> in replace tags function.

In [14]:
# Import preprocessing function from src code.
import os
current_dir = os.getcwd()
src_dir = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/"
os.chdir(src_dir)
# DO IMPORTS HERE

from src.services.attachment_processing.base_input_processor import AfterCourtAttachmentPreprocessor
from src.domain.base.blueprints import AfterCourtPreprocessingBlueprint
from src.services.models.aftercourt_classification_model import ClassificationSpacyLemmaTokenizer

os.chdir(current_dir)

In [15]:
processing_configuration = AfterCourtPreprocessingBlueprint.from_dict({
    "clean_text_type": ["preprocessed", 'original'],
    "normalize_whitespace": True,
    "remove_short_lines": True,
    "short_line_threshold": 3,
    "remove_html_tags": True,
    "lowercase": True
})
process = AfterCourtAttachmentPreprocessor("pfub_erlass_processor",processing_configuration)._process
replace_with_tags = AfterCourtAttachmentPreprocessor("pfub_erlass_processor",processing_configuration)._replace_with_tags

In [16]:

data['text_w_tags_new'] = data['cleaned_text'].apply(lambda x: replace_with_tags(x))

In [18]:
data['new_gesh_token_exists'] = data['text_w_tags_new'].apply(lambda x: '<GESCHAEFTSNUMMER>' in x)

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized,geschaeftsnummer,has_geschaeftsnummer,text_w_tags_new,new_gesh_token_exists
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[],False,<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,False
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes...",[],False,antrag auf erlass eines pfänd <NUMBER><PHONE>\...,False
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",[20 am 01],True,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,False
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[],False,antrag auf erlass eines pfändungs\n<NUMBER> <N...,False
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",[],False,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Grover\nFriedhelm August Steiner\nBestellnumme...,NaN,mail_attachments,grover\nfriedhelm august steiner\nbestellnumme...,grover\nfriedhelm august steiner\nbestellnumme...,NaN,False,False,"['grover', 'friedhelm', 'august', 'steiner', '...",[],False,grover\nfriedhelm august steiner\nbestellnumme...,False
5027,Liste des créances\nCréé le: 21.08.2025\nNumér...,NaN,mail_attachments,liste des créances\ncréé le: 21.08.2025\nnumér...,liste des créances\ncréé le: <NUMBER>.2025\nnu...,NaN,False,False,"['liste', 'créance', 'créé', 'le', 'numéro', '...",[],False,liste des créances\ncréé le: <DATE>\nnuméro de...,False
5028,11:06\nRetour Détails de la transaction\nPDF\n...,NaN,mail_attachments,"11:06\nretour détails de la transaction\n-209,...",<NUMBER>:<NUMBER>\nretour détails de la transa...,NaN,False,False,"['retour', 'détails', '--', '--', 'transaction...",[],False,<NUMBER>:<NUMBER>\nretour détails de la transa...,False
5029,e\nKLINIKUM\nKlinik für Dermatologie\nNÜRNBERG...,NaN,mail_attachments,klinikum\nklinik für dermatologie\nnürnberg\nu...,klinikum\nklinik für dermatologie\nnürnberg\nu...,NaN,False,False,"['klinikum', 'klinik', 'dermatologie', 'nürnbe...",[],False,klinikum\nklinik für dermatologie\nnürnberg\nu...,False
5030,CP\nDELGMANN + PARTNER\nRECHTSANWÄLTE FACHANWÄ...,NaN,mail_attachments,delgmann + partner\nrechtsanwälte fachanwälte\...,delgmann + partner\nrechtsanwälte fachanwälte\...,NaN,False,False,"['delgmann', '+', 'partner', 'rechtsanwälte', ...",[],False,delgmann + partner\nrechtsanwälte fachanwälte\...,False

In [20]:
check = data["has_geschaeftsnummer"] != data["new_gesh_token_exists"]
data[check]

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized,geschaeftsnummer,has_geschaeftsnummer,text_w_tags_new,new_gesh_token_exists
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",[20 am 01],True,antrag auf erlass eines pfändun\n<PHONE> <NUMB...,False
1795,Antrag auf Erlass eines Pfändungs- und\n1\nÜbe...,14.08.2023/1692023606_SK_001_14082023_163008.pdf,attachment_and_transfer_order,antrag auf erlass eines pfändungs- und\nüberwe...,antrag auf erlass eines pfändungs- und\nüberwe...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[00\nam 14],True,antrag auf erlass eines pfändungs- und\nüberwe...,False
1925,Amtsgericht Coburg\nA123\nZentrales Mahngerich...,15.07.2025/ocr-v2_VSB_Scan_000000210201_04_07_...,enforcement_order,amtsgericht coburg\na123\nzentrales mahngerich...,amtsgericht coburg\na123\nzentrales mahngerich...,NaN,False,False,"['amtsgericht', 'coburg', 'a123', 'zentral', '...",[63\nam 10],True,amtsgericht coburg\na123\nzentrales mahngerich...,False
2104,Antrag auf Erlass eines Pfändungs- und\n1\nÜbe...,16.08.2023/1692180306_SK_001_16082023_114452.pdf,attachment_and_transfer_order,antrag auf erlass eines pfändungs- und\nüberwe...,antrag auf erlass eines pfändungs- und\nüberwe...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",[00\nam 16],True,antrag auf erlass eines pfändungs- und\nüberwe...,False
3136,Obergerichtsvollzieherin Christiane Klos\nBüro...,24.09.2024/ocr-v2_GVZ_0_sammel1_(2).pdf,ladung_va,obergerichtsvollzieherin christiane klos\nbüro...,obergerichtsvollzieherin christiane klos\nbüro...,NaN,False,True,"['obergerichtsvollzieherin', 'christiane', 'kl...",[8\nam 14],True,obergerichtsvollzieherin christiane klos\nbüro...,False
3137,Obergerichtsvollzieher\nLammstr. 11\nK. Nöbaue...,24.09.2024/ocr-v2_GVZ_2_dr_1002_24_an_gl_nachr...,ladung_va,obergerichtsvollzieher\nlammstr. 11\nk. nöbaue...,obergerichtsvollzieher\nlammstr. <NUMBER>\nk. ...,NaN,False,True,"['obergerichtsvollzieher', 'lammstr', 'k.', 'n...",[340602951\nam 14],True,obergerichtsvollzieher\nlammstr. <NUMBER>\nk. ...,False
3985,Antrag auf Erlass eines Pfändu\n4070071 967072...,31.01.2022/1643639438_Doc_31012022_000000002_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",[20 am 31],True,antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,False
4420,09:10\nzalando\nPlus\nDamen\nHerren\nKinder\nB...,NaN,mail_attachments,09:10\nzalando\nplus\ndamen\nherren\nkinder\nb...,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,NaN,False,False,"['zalando', 'plus', 'damen', 'herren', 'kind',...",[10603065778166 am 28],True,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,False
4560,STEINHAUER GÜNTHER\nRECHTSANWÄLTE & NOTAR\nRAE...,NaN,mail_attachments,steinhauer günther\nrechtsanwälte & notar\nrae...,steinhauer günther\nrechtsanwälte & notar\nrae...,NaN,False,False,"['steinhauer', 'günther', 'rechtsanwälte', 'no...",[7428357\nam 02],True,steinhauer günther\nrechtsanwälte & notar\nrae...,False
4923,Kontonummer\nerstellt am\nAuszug\nBlatt\nFrank...,NaN,mail_attachments,kontonummer\nerstellt am\nauszug\nblatt\nfrank...,kontonummer\nerstellt am\nauszug\nblatt\nfrank...,NaN,False,False,"['kontonummer', 'erstellen', 'auszug', 'blatt'...",[00001747 am 03],True,kontonummer\nerstellt am\nauszug\nblatt\nfrank...,False
4941,09:10\nzalando\nPlus\nDamen\nHerren\nKinder\nB...,NaN,mail_attachments,09:10\nzalando\nplus\ndamen\nherren\nkinder\nb...,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,NaN,False,False,"['zalando', 'plus', 'damen', 'herren', 'kind',...",[10603065778166 am 28],True,<NUMBER>:<NUMBER>\nzalando\nplus\ndamen\nherre...,False

In [21]:
check = data["is_pfub"] != data["new_gesh_token_exists"]
data[check]

,text,object_key,document_type,cleaned_text,text_w_tags,data,is_pfub,is_ladung,tokenized,geschaeftsnummer,has_geschaeftsnummer,text_w_tags_new,new_gesh_token_exists
61,Amtsgericht Heinsberg\nPAIR Finance GmbH\n28. ...,02.05.2023/1683018418_YA_002_02052023_104625.pdf,attachment_and_transfer_order,amtsgericht heinsberg\npair finance gmbh\n28. ...,amtsgericht heinsberg\npair finance gmbh\n<NUM...,NaN,False,False,"['amtsgericht', 'heinsberg', 'pair', 'finance'...",[10 m 795/23],True,amtsgericht heinsberg\npair finance gmbh\n<DAT...,True
371,"Amtsgericht\nAmtsgericht Burgwedel, Postfach 1...",04.11.2024/ocr-v2_111239589364.EU_Z_00581Übers...,court_inbox,"amtsgericht\namtsgericht burgwedel, postfach 1...","amtsgericht\namtsgericht burgwedel, postfach <...",NaN,False,False,"['amtsgericht', 'amtsgericht', 'burgwedel', 'p...","[5a m 905/24, 5a m 905/24]",True,"amtsgericht\namtsgericht burgwedel, postfach <...",True
418,Amtsgericht Wedding\n-Zentrales Mahngericht Be...,04.12.2024/ocr-v2_RB_008_04122024_133334.pdf,approved_attachment_and_transfer_order,amtsgericht wedding\n-zentrales mahngericht be...,amtsgericht wedding\n-zentrales mahngericht be...,"{'case_slug': '152944268209', 'debtor_name': '...",True,False,"['amtsgericht', 'wedding', '-zentrales', 'mahn...",[],False,amtsgericht wedding\n-zentrales mahngericht be...,False
1060,"Amtsgericht Flensburg\nAmtsgericht Flensburg, ...",09.08.2023/1691564795_KD_002_09082023_084442.pdf,attachment_and_transfer_order,"amtsgericht flensburg\namtsgericht flensburg, ...","amtsgericht flensburg\namtsgericht flensburg, ...",NaN,False,False,"['amtsgericht', 'flensburg', 'amtsgericht', 'f...",[53 m 1267/23],True,"amtsgericht flensburg\namtsgericht flensburg, ...",True
1165,Amtsgericht Leverkusen\nPAIR Finance GmbH\n09....,10.08.2023/1691652786_PF_005_10082023_091626.pdf,attachment_and_transfer_order,amtsgericht leverkusen\npair finance gmbh\n09....,amtsgericht leverkusen\npair finance gmbh\n<NU...,NaN,False,False,"['amtsgericht', 'leverkusen', 'pair', 'finance...",[45 m 3062/23],True,amtsgericht leverkusen\npair finance gmbh\n<DA...,True
1318,Hauptgerichtsvollzieher\n80992 München\nPeer\n...,11.12.2024/ocr-v2_80_dr_792_24_05a_an_gl_vv_se...,ladung_va,hauptgerichtsvollzieher\n80992 münchen\npeer\n...,hauptgerichtsvollzieher\n<NUMBER> münchen\npee...,NaN,False,True,"['hauptgerichtsvollzieh', 'münchen', 'peer', '...",[290869 m 016],True,hauptgerichtsvollzieher\n<NUMBER> münchen\npee...,True
1320,Wormser Landstr. 6\nGUNTER SCHULZ\n67551 Worms...,11.12.2024/ocr-v2_DR-II_100224_Nachr_Mitlg_an_...,ladung_va,wormser landstr. 6\ngunter schulz\n67551 worms...,wormser landstr. <NUMBER>\ngunter schulz\n<NUM...,NaN,False,True,"['wormser', 'landstr', 'gunter', 'schulz', 'wo...","[15 m 2712/24, 15 m 2712/24, 15 m 2712/24, 15 ...",True,wormser landstr. <NUMBER>\ngunter schulz\n<NUM...,True
1322,Postanschrift:\nBianka Zinn\nJustus-Perthes-St...,11.12.2024/ocr-v2_DR-II_130824_Nachr_GKB-ERVQ_...,ladung_va,postanschrift:\nbianka zinn\njustus-perthes-st...,postanschrift:\nbianka zinn\njustus-perthes-st...,NaN,False,True,"['postanschrift', 'bianka', 'zinn', 'justus-pe...","[2023\nm 624/23, 2023\nm 624/23, 2023\nm 624/2...",True,postanschrift:\nbianka zinn\njustus-perthes-st...,True
1338,M. Jödicke\nHellersdorfer Weg 35\nObergerichts...,11.12.2024/ocr-v2_Dokumente_129024_10122024_16...,ladung_va,m. jödicke\nhellersdorfer weg 35\nobergerichts...,m. jödicke\nhellersdorfer weg <NUMBER>\noberge...,NaN,False,True,"['m.', 'jödicke', 'hellersdorfer', 'weg', 'obe...",[041095 m 018],True,m. jödicke\nhellersdorfer weg <NUMBER>\noberge...,True
1343,Nadine Berkemeier\nRumbecker Straße 8\nGericht...,11.12.2024/ocr-v2_Dokumente_211724_10122024_14...,ladung_va,nadine berkemeier\nrumbecker straße 8\ngericht...,nadine berkemeier\nrumbecker straße <NUMBER>\n...,NaN,False,True,"['nadine', 'berkemeier', 'rumbecker', 'straße'...",[11171101m074],True,nadine berkemeier\nrumbecker straße <NUMBER>\n...,True
1574,Amtsgericht Duisburg\n-634- Amtsgericht Duisbu...,13.07.2023/1689237319_KD_002_13072023_100721.pdf,attachment_and_transfer_order,amtsgericht duisburg\n-634- amtsgericht duisbu...,amtsgericht duisburg\n<NUMBER>- amtsgericht du...,NaN,False,False,"['amtsgericht', 'duisburg', 'amtsgerichen', 'd...",[634 m 807/23],True,amtsgericht duisburg\n<NUMBER>- amtsgericht du...,True
1772,Amtsgericht Frankfurt am Main\nMobiliarzwangsv...,14.08.2023/1692005615_MA_008_14082023_113233.pdf,attachment_and_transfer_order,amtsgericht frankfurt am main\nmobiliarzwangsv...,amtsgericht frankfurt am main\nmobiliarzwangsv...,NaN,False,False,"['amtsgericht', 'frankfurt', 'main', 'mobiliar...",[82 m 10356/23],True,amtsgericht frankfurt am main\nmobiliarzwangsv...,True
2613,THOMAS METHNER\nBremer Str. 40\n27749 Delmenho...,20.03.2024/ocr-v2_AK_001_20032024_090051.pdf,ladung_va,thomas methner\nbremer str. 40\n27749 delmenho...,thomas methner\nbremer str. <NUMBER>\n<NUMBER>...,NaN,False,True,"['thomas', 'methner', 'bremer', 'str', 'delmen...","[10 m 1805/22, 10 m 1805/22, 10 m 1805/22, 10 ...",True,thomas methner\nbremer str. <NUMBER>\n<NUMBER>...,True
3112,PAIR Finance GmbH\n23. Juli 2024\nAmtsgericht ...,24.07.2024/ocr-v2_ZJ_005_24072024_144624.pdf,attachment_and_transfer_order,pair finance gmbh\n23. juli 2024\namtsgericht ...,pair finance gmbh\n<NUMBER>. juli <NUMBER>\nam...,NaN,False,False,"['pair', 'finance', 'gmbh', 'juli', 'amtsgeric...",[2 m 2836/24],True,pair finance gmbh\n<DATE>\namtsgericht ingolst...,True
3141,Gerichtsstraße 2 -Amtsgericht-\n15907 Lübben\n...,24.09.2024/ocr-v2_GVZ_Sammelmappe11.pdf,ladung_va,gerichtsstraße 2 -amtsgericht-\n15907 lübben\n...,gerichtsstraße <NUMBER> -amtsgericht-\n<NUMBER...,NaN,False,True,"['gerichtsstraße', '-amtsgericht-', 'lübben', ...","[50 m 140/23, 50 m 140/23, 50 m 140/23, 50 m 1...",True,gerichtsstraße <NUMBER> -amtsgericht-\n<NUMBER...,True
3175,Amtsgericht Langenfeld\n-95- Amtsgericht Lange...,25.04.2023/1682411691_YA_001_25042023_101934.pdf,attachment_and_transfer_order,amtsgericht langenfeld\n-95- amtsgericht lange...,amtsgericht langenfeld\n<NUMBER>- amtsgericht ...,NaN,False,False,"['amtsgericht', 'langenfeld', 'amtsgerichen', ...",[95 m 1093/23],True,amtsgericht langenfeld\n<NUMBER>- amtsgericht ...,True
3260,Amtsgericht Langen (Hessen)\nVollstreckungsger...,25.10.2024/ocr-v2_EU_Z_00021FreitextschreibenB...,court_inbox,amtsgericht langen (hessen)\nvollstreckungsger...,amtsgericht langen (hessen)\nvollstreckungsger...,NaN,False,False,"['amtsgericht', 'lang', 'hessen', 'vollstrecku...",[71 m 2303/24],True,amtsgericht langen (hessen)\nvollstreckungsger...,True
3611,Amtsgericht Lemgo\nGeschäftsstelle\n-14- Amtsg...,28.04.2023/1682678109_DS_003_28042023_121512.pdf,attachment_and_transfer_order,amtsgericht lemgo\ngeschäftsstelle\n-14- amtsg...,amtsgericht lemgo\ngeschäftsstelle\n<NUMBER>- ...,NaN,False,False,"['amtsgericht', 'lemgo', 'geschäftsstelle', 'a...",[14 m 764/23],True,amtsgericht lemgo\ngeschäftsstelle\n<NUMBER>- ...,True
3705,Amtsgericht Rostock\nAmtsgericht Rostock PF 10...,28.10.2024/ocr-v2_RB_004_28102024_133353.pdf,court_inbox,amtsgericht rostock\namtsgericht rostock pf 10...,amtsgericht rostock\namtsgericht rostock pf <N...,NaN,False,False,"['amtsgericht', 'rostock', 'amtsgericht', 'ros...",[63 m 3656/24],True,amtsgericht rostock\namtsgericht rostock pf <N...,True
3710,Peter Lüdtke\nBrahmsstr. 42\nObergerichtsvollz...,28.11.2024/ocr-v2_Dokument_191724_27112024_112...,ladung_va,peter lüdtke\nbrahmsstr. 42\nobergerichtsvollz...,peter lüdtke\nbrahmsstr. <NUMBER>\nobergericht...,NaN,False,True,"['peter', 'lüdtke', 'brahmsstr', 'obergerichts...","[22 m 3332/02, 24 m 6367/05, 18 m 34/14, 35 m\...",True,peter lüdtke\nbrahmsstr. <NUMBER>\nobergericht...,True
4040,"8/21/25, 1:26 PM\nTransaction\nKlarna\nZahlung...",NaN,mail_attachments,"8/21/25, 1:26 pm\ntransaction\nklarna\nzahlung...","<NUMBER>/<NUMBER>/<NUMBER>, <NUMBER>:<NUMBER> ...",NaN,False,False,"['pm', 'transaction', 'klarna', 'zahlung', 'fe...","[m\n8/21, m\n8/21]",True,"<NUMBER>/<NUMBER>/<NUMBER>, <NUMBER>:<NUMBER> ...",True
4705,energienetze\nmittelrhein\nEnergienetze Mittel...,NaN,mail_attachments,energienetze\nmittelrhein\nenergienetze mittel...,energienetze\nmittelrhein\nenergienetze mittel...,NaN,False,False,"['energienetze', 'mittelrhein', 'energienetzen...",[3038m3],True,energienetze\nmittelrhein\nenergienetze mittel...,True
4865,THANKS FOR\nMILES\nYOUR RIDE!\nTarek Shtewe\nM...,NaN,mail_attachments,thanks for\nmiles\nyour ride!\ntarek shtewe\nm...,thanks for\nmiles\nyour ride!\ntarek shtewe\nm...,NaN,False,False,"['thanks', 'for', 'mil', 'your', 'ride', 'tare...",[50m\n99],True,thanks for\nmiles\nyour ride!\ntarek shtewe\nm...,True
4985,€\nschuldenanalyse-kostenlos.de\nrightmart Ber...,NaN,mail_attachments,schuldenanalyse-kostenlos.de\nrightmart berlin...,schuldenanalyse-kostenlos.de\nrightmart berlin...,NaN,False,False,"['schuldenanalyse-kostenlos.de', 'rightmart', ...",[202 m 6266/24],True,schuldenanalyse-kostenlos.de\nrightmart berlin...,True

In [23]:
data.drop(columns=['geschaeftsnummer','text_w_tags','has_geschaeftsnummer','new_gesh_token_exists'], inplace=True)

In [24]:
data.rename(columns={'text_w_tags_new':'text_w_tags'}, inplace=True)

In [25]:
# save the new text with tags
data.to_csv('../data/PFUB_ERLASS_dataset_processed_with_geschaeftsnummer.csv', index=False)

In [27]:
data = pd.read_csv('../data/PFUB_ERLASS_dataset_processed_with_geschaeftsnummer.csv')

In [29]:
data['is_pfub'].value_counts()

is_pfub
False    4565
True      466
Name: count, dtype: int64

In [30]:
data['is_ladung'].value_counts()

is_ladung
False    2930
True     2101
Name: count, dtype: int64