In [1]:
import pandas as pd

In [2]:
RAW_DATA_PATH = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv"
NEW_DATA_PATH = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/final_preds_LLM_pfub_and_invoice_25-03-2026_prompt_v2.csv"

In [3]:
raw_data = pd.read_csv(RAW_DATA_PATH)

In [4]:
raw_data.shape

(5415, 13)

In [5]:
raw_data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           406
court_inbox                                346
fp_protocol                                220
fp_invoice                                 128
vermögensverzeichnis                        89
approved_attachment_and_transfer_order      64
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
contradiction                                3
Name: count, dtype: int64

In [6]:
new_data = pd.read_csv(NEW_DATA_PATH)

In [7]:
new_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,pfub_slug,pfub_debtor_name,clean_text,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm
0,50219849,ocr_source_files/2026-01-20/egvp_id_294117/502...,pair-data-engineering-new,50219849_d1a90b502e914570.pdf,6ad8a8476f2b35e078bfc39d3c31ee190edd0fc16bc328...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Detmold\n-9- Amtsgericht Detmold P...,False,0.00,...,NaN,NaN,amtsgericht detmold\n-9- amtsgericht detmold p...,amtsgericht detmold\n<NUMBER>- amtsgericht det...,0.00,0.130000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification step by..."
1,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,'171607237715','Adomah',amtsgericht essen-borbeck\n-geschäftsstelle-\n...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
2,50219891,ocr_source_files/2026-01-20/egvp_id_294123/502...,pair-data-engineering-new,50219891_Schreiben_Schreiben_vom_20_01_2026_fo...,2890235808b3d3e5cae0c43ba493a7ceab93c0fc3193e3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RheinlandPfalz\nAMTSGERICHT\nWITTLICH\nAmtsger...,False,0.03,...,NaN,NaN,rheinlandpfalz\namtsgericht\nwittlich\namtsger...,rheinlandpfalz\namtsgericht\nwittlich\namtsger...,0.02,0.245000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
3,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,'161155294895','Aldag',"amtsgericht essen\n-30- amtsgericht essen, 451...",amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
4,50219903,ocr_source_files/2026-01-20/egvp_id_294126/502...,pair-data-engineering-new,50219903_4_M_1523_25_Schreiben_vom_20_01_2026_...,361a91f08e36bb92417a35bee79fb654d79c1f9437e609...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RheinlandPfalz\nAMTSGERICHT\nLANDSTUHL\nAmtsge...,False,0.05,...,NaN,NaN,rheinlandpfalz\namtsgericht\nlandstuhl\namtsge...,rheinlandpfalz\namtsgericht\nlandstuhl\namtsge...,0.03,0.305000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3402,54087604,ocr_source_files/2026-02-25/egvp_id_315972/540...,pair-data-engineering-new,54087604_Dokument_32026_25022026_144324.pdf,ce2e743972daa690a195eac5f8ea010f64b4061d229f17...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Lars Hahn\nPempelforter Str. 47\nGerichtsvollz...,False,0.03,...,NaN,NaN,lars hahn\npempelforter str. 47\ngerichtsvollz...,lars hahn\npempelforter str. <NUMBER>\ngericht...,0.00,0.288571,6,0,2026-02-25 14:44:00,"Okay, let's tackle this classification step by..."
3403,52618325,ocr_source_files/2026-02-12/egvp_id_308299/526...,pair-data-engineering-new,52618325_Dr_ii_150_26_an_gl_terminsmitteilung_...,308927111bf37d532708e11c0fcb0aebe20293bffefd67...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieherin\nAmtsgericht\nSimone Urba...,True,1.00,...,NaN,NaN,gerichtsvollzieherin\namtsgericht\nsimone urba...,gerichtsvollzieherin\namtsgericht\nsimone urba...,0.95,0.050000,7,0,2026-02-12 10:44:00,"Okay, let's tackle this classification task st..."
3404,51175090,ocr_source_files/2026-01-30/egvp_id_299881/511...,pair-data-engineering-new,51175090_Dr_ii_1326_25_an_gl_s_bietet_g%C3%BCt...,13f73f36ebba5714bf4f12c5c16d79ef151378208073b5...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieherin\nAmtsgericht\nFrankfu...,False,0.75,...,NaN,NaN,obergerichtsvollzieherin\namtsgericht\nfrankfu...,obergerichtsvollzieherin\namtsgericht\nfrankfu...,0.13,0.040000,1,0,2026-01-30 09:44:00,"Okay, let's tackle this document classificatio..."
3405,52600493,ocr_source_files/2026-02-11/egvp_id_308099/526...,pair-data-engineering-new,52600493_Dokument_62526_11022026_183538.pdf,860c387cee0605b09143dc976917bf760d5ff0021591ac...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,OGV Sachs\nHellersdorfer Weg 35\nObergerichtsv...,False,0.13,...,NaN,NaN,ogv sachs\nhellersdorfer weg 35\nobergerichtsv...,ogv sachs\nhellersdorfer weg <NUMBER>\noberger...,0.15,0.030000,6,0,2026-02-11 18:44:00,"Okay, let's tackle this classification step by..."
3406,53359947,ocr_source_files/2026-02-19/egvp_id_312646/533...,pair-data-engineering-new,53359947_Dokument_19126_19022026_121808.pdf,aeb8af4ad2b66fa751e3453a04f01e9e99b98dd3204769...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,M. Hommel\nBrunsbütteler Damm 446\nGerichtsvol...,False,0.14,...,NaN,NaN,m. hommel\nbrunsbütteler damm 446\ngerichtsvol...,m. hommel\nbrunsbütteler damm <NUMBER>\ngerich...,0.02,0.120000,6,0,2026-02-19 12:44:00,"Okay, let's tackle this document classificatio..."

In [8]:
new_data.document_s3_key.is_unique

True

parse llm predictions

In [9]:
import re
import json
import pandas as pd
import numpy as np

def extract_first_json(text):
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    match = re.search(r'\{.*?\}', text)
    if match:
        try:
            json_data = json.loads(match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}

def extract_last_json(text):
    text = (
        text
        .replace(" ","")
        .replace("\n","")
        .replace("True", "true")
        .replace("False", "false")
        .replace("None", "null")
        .replace("'",'"')
    )
    # Find all JSON objects in the text
    matches = list(re.finditer(r'\{.*?\}', text))
    if matches:
        # Get the last match
        last_match = matches[-1]
        try:
            json_data = json.loads(last_match.group())
            return json_data
        except json.JSONDecodeError as e:
            print(last_match.group())
            print("failed", e)
            return {}
    else:
        print("format failed")
        return {}
    
def parse_date_safe(date):
    try:
        return pd.to_datetime(date)
    except:
        return np.nan

In [10]:
new_data["pred_parsed"] = new_data["pred_llm"].apply(extract_last_json)
# take is_pfub and is_invoice_inside from pred_parsed and create new columns for them
new_data["pred_is_pfub"] = new_data["pred_parsed"].apply(lambda x: x.get("is_pfub", False))
new_data["pred_is_invoice_inside"] = new_data["pred_parsed"].apply(lambda x: x.get("is_invoice_inside", False))

In [11]:
new_data["pred_is_pfub"].isna().sum()

np.int64(0)

In [12]:
ocr_dataset_llm_pred = new_data[new_data["source"] == "ocr"]
prod_dataset_llm_pred  = new_data[new_data["source"] == "prod"]

KeyError: 'source'

Using LLM's predictions for PFUB, make fixes in OCR dataset, if its required.

In [13]:
ocr_dataset_llm_pred.shape

NameError: name 'ocr_dataset_llm_pred' is not defined

In [14]:
ocr_dataset_llm_pred

NameError: name 'ocr_dataset_llm_pred' is not defined

In [15]:
ocr_dataset_llm_pred.ticket_uuid.isna().sum()

NameError: name 'ocr_dataset_llm_pred' is not defined

In [16]:
raw_data.ticket_uuid.isna().sum()

np.int64(0)

In [17]:
inner_join = pd.merge(raw_data, ocr_dataset_llm_pred, on="ticket_uuid", how="inner", suffixes=("_raw", "_llm_pred_ocr"))
inner_join.shape

NameError: name 'ocr_dataset_llm_pred' is not defined

5381 shared data

In [18]:
inner_join

NameError: name 'inner_join' is not defined

compare is_pfub_raw (current raw data gt labels) vs pred_is_pfub (predictions using llm)

In [19]:
different = inner_join[inner_join["pred_is_pfub"] != inner_join["is_pfub_raw"]]
different

NameError: name 'inner_join' is not defined

In [20]:
different.document_type_raw.value_counts()

NameError: name 'different' is not defined

In [21]:
different.pred_is_invoice_inside.value_counts()

NameError: name 'different' is not defined

In [22]:
different.object_key_raw.isna().sum()

NameError: name 'different' is not defined

download different documents

In [23]:
# lets see thed documents

import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "../../")))
from python_utilities.db_connection import DbConnection
import boto3

analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-04-22 17:08:27] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-04-22 17:08:27] - Found credentials in shared credentials file: ~/.aws/credentials

In [24]:
# from utils.prod_utils import download_pdf_from_s3
# download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/sil"
# for i, row in different.iterrows():
#     bucket_name = "pair-scanner"
#     key = row.object_key_raw
#     download_pdf_from_s3(s3, bucket_name=bucket_name, object_key=key, download_dir=download_dir, file_name=None)

In [25]:
check = different[(different["pred_is_pfub"] == True) & (different["is_pfub_raw"] == False)]
check

NameError: name 'different' is not defined

In [26]:
check = different[(different["pred_is_pfub"] == False) & (different["is_pfub_raw"] == True)]
check

NameError: name 'different' is not defined

Result: The difference happened because of low recall of the LLM model. there is no fix required for ocr data. 

TODO: it seems like we could improve the RECALL of the pfub erlass model, with some small changes in prompt.
create prompt v5. while testing for qwen4b, try out prompt v4 on data with qwen32b and qwen4b, also run prompt v5. see the results.

## Now add some new pfub erlass data coming from production.

In [56]:
prod_dataset_llm_pred = new_data.copy()

In [57]:
# prod data is the data where object key is none

In [58]:
prod_dataset_llm_pred

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_parsed,pred_is_pfub,pred_is_invoice_inside
0,50219849,ocr_source_files/2026-01-20/egvp_id_294117/502...,pair-data-engineering-new,50219849_d1a90b502e914570.pdf,6ad8a8476f2b35e078bfc39d3c31ee190edd0fc16bc328...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Detmold\n-9- Amtsgericht Detmold P...,False,0.00,...,amtsgericht detmold\n<NUMBER>- amtsgericht det...,0.00,0.130000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
1,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2,50219891,ocr_source_files/2026-01-20/egvp_id_294123/502...,pair-data-engineering-new,50219891_Schreiben_Schreiben_vom_20_01_2026_fo...,2890235808b3d3e5cae0c43ba493a7ceab93c0fc3193e3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RheinlandPfalz\nAMTSGERICHT\nWITTLICH\nAmtsger...,False,0.03,...,rheinlandpfalz\namtsgericht\nwittlich\namtsger...,0.02,0.245000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
4,50219903,ocr_source_files/2026-01-20/egvp_id_294126/502...,pair-data-engineering-new,50219903_4_M_1523_25_Schreiben_vom_20_01_2026_...,361a91f08e36bb92417a35bee79fb654d79c1f9437e609...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RheinlandPfalz\nAMTSGERICHT\nLANDSTUHL\nAmtsge...,False,0.05,...,rheinlandpfalz\namtsgericht\nlandstuhl\namtsge...,0.03,0.305000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3402,54087604,ocr_source_files/2026-02-25/egvp_id_315972/540...,pair-data-engineering-new,54087604_Dokument_32026_25022026_144324.pdf,ce2e743972daa690a195eac5f8ea010f64b4061d229f17...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Lars Hahn\nPempelforter Str. 47\nGerichtsvollz...,False,0.03,...,lars hahn\npempelforter str. <NUMBER>\ngericht...,0.00,0.288571,6,0,2026-02-25 14:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': True}",False,True
3403,52618325,ocr_source_files/2026-02-12/egvp_id_308299/526...,pair-data-engineering-new,52618325_Dr_ii_150_26_an_gl_terminsmitteilung_...,308927111bf37d532708e11c0fcb0aebe20293bffefd67...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieherin\nAmtsgericht\nSimone Urba...,True,1.00,...,gerichtsvollzieherin\namtsgericht\nsimone urba...,0.95,0.050000,7,0,2026-02-12 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3404,51175090,ocr_source_files/2026-01-30/egvp_id_299881/511...,pair-data-engineering-new,51175090_Dr_ii_1326_25_an_gl_s_bietet_g%C3%BCt...,13f73f36ebba5714bf4f12c5c16d79ef151378208073b5...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieherin\nAmtsgericht\nFrankfu...,False,0.75,...,obergerichtsvollzieherin\namtsgericht\nfrankfu...,0.13,0.040000,1,0,2026-01-30 09:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': False}",False,False
3405,52600493,ocr_source_files/2026-02-11/egvp_id_308099/526...,pair-data-engineering-new,52600493_Dokument_62526_11022026_183538.pdf,860c387cee0605b09143dc976917bf760d5ff0021591ac...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,OGV Sachs\nHellersdorfer Weg 35\nObergerichtsv...,False,0.13,...,ogv sachs\nhellersdorfer weg <NUMBER>\noberger...,0.15,0.030000,6,0,2026-02-11 18:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': False, 'is_invoice_inside': True}",False,True
3406,53359947,ocr_source_files/2026-02-19/egvp_id_312646/533...,pair-data-engineering-new,53359947_Dokument_19126_19022026_121808.pdf,aeb8af4ad2b66fa751e3453a04f01e9e99b98dd3204769...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,M. Hommel\nBrunsbütteler Damm 446\nGerichtsvol...,False,0.14,...,m. hommel\nbrunsbütteler damm <NUMBER>\ngerich...,0.02,0.120000,6,0,2026-02-19 12:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': False, 'is_invoice_inside': True}",False,True

In [59]:
prod_dataset_llm_pred_PFUB = prod_dataset_llm_pred[prod_dataset_llm_pred["pred_is_pfub"] == True]

In [60]:
prod_dataset_llm_pred_PFUB = prod_dataset_llm_pred_PFUB[prod_dataset_llm_pred_PFUB["pred_is_invoice_inside"] == False]

In [61]:
prod_dataset_llm_pred_PFUB

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_parsed,pred_is_pfub,pred_is_invoice_inside
1,50219877,ocr_source_files/2026-01-20/egvp_id_294119/502...,pair-data-engineering-new,50219877_Allgemeines_Schreiben_R__20260120_1f2...,0f7e93fc3bd3b02f7168d8b0b3a829da212839da854b52...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Essen-Borbeck\n-Geschäftsstelle-\n...,False,0.00,...,amtsgericht essen-borbeck\n-geschäftsstelle-\n...,0.00,0.320000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
3,50219898,ocr_source_files/2026-01-20/egvp_id_294125/502...,pair-data-engineering-new,50219898_Allgemeines_Schreiben_R__20260120_2a2...,26f5d9844c88ad1c35704dc4757acfb52202204049aab6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Essen\n-30- Amtsgericht Essen, 451...",False,0.00,...,amtsgericht essen\n<NUMBER>- amtsgericht essen...,0.00,0.348750,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
5,50219909,ocr_source_files/2026-01-20/egvp_id_294128/502...,pair-data-engineering-new,50219909_BriefkopfGericht_20260120_0c3ba229939...,6588a5026d36290c01d535b3a1c0b82ecfc39cd9ff5e7d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Medebach\n-12- Amtsgericht Medebac...,False,0.00,...,amtsgericht medebach\n<NUMBER>- amtsgericht me...,0.00,0.300000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
6,50219939,ocr_source_files/2026-01-20/egvp_id_294136/502...,pair-data-engineering-new,50219939_4M61_26_GESV-GL_PairFinanceGmbH_70EC2...,3364f178c5530b3a472da9aabe546a60d0055d39d96716...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nWalsrode\nAmtsgericht Walsrode, L...",False,0.01,...,"amtsgericht\nwalsrode\namtsgericht walsrode, l...",0.00,0.216333,3,0,2026-01-20 10:44:00,"Okay, let me tackle this classification step b...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
7,50220181,ocr_source_files/2026-01-20/egvp_id_294143/502...,pair-data-engineering-new,50220181_Allgemeines_Schreiben_R__20260120_03c...,5a7282c74de38b4592f081d20417fbfa3a21588c79b214...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-286a- Amtsgericht Köln, 509...",False,0.00,...,"amtsgericht köln\n-286a- amtsgericht köln, <NU...",0.00,0.348000,3,0,2026-01-20 10:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,54150707,ocr_source_files/2026-02-26/egvp_id_316913/541...,pair-data-engineering-new,54150707_10M104_26_VB-GL_PairFinanceGmbH_2BF9F...,1106edef36cf004e7ab5ea9e7d9af974515c8c6ce52dae...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSpringe\nAmtsgericht Springe, Zum...",False,0.01,...,"amtsgericht\nspringe\namtsgericht springe, zum...",0.01,0.158333,3,0,2026-02-26 15:44:00,"Okay, let me tackle this classification step b...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1904,54203493,ocr_source_files/2026-02-27/egvp_id_317018/542...,pair-data-engineering-new,54203493_ANSCHR_Pair_Finance_GmbH_Pair_Finance...,6cc92a56c5f872588c2bc1fd2d5504d130d04decd895cf...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Reutlingen\nVOLLSTRECKUNGSGERICHT\...,False,0.02,...,amtsgericht reutlingen\nvollstreckungsgericht\...,0.04,0.170000,3,0,2026-02-27 06:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1905,54203577,ocr_source_files/2026-02-27/egvp_id_317021/542...,pair-data-engineering-new,54203577_20aM474_26_VB-GL_PairFinanceGmbH_E20E...,674932dadc7a811fdd05b7cbc7299bfa572c483651aa2b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSyke\nAmtsgericht Syke, Amtshof 2...",False,0.02,...,"amtsgericht\nsyke\namtsgericht syke, amtshof <...",0.00,0.243333,3,0,2026-02-27 06:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1906,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...,False,0.05,...,amtsgericht dresden\namtsgericht dresden\nabte...,0.03,0.200000,3,0,2026-02-27 06:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
3388,53752407,ocr_source_files/2026-02-23/egvp_id_313870/537...,pair-data-engineering-new,53752407_pruefvermerk_f6eb9b8a-4fb7-4bd1-8007-...,2a30d48777c3d54c04f7f93b1d695a7b33f6af9bd19658...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Prüfvermerk\nDie unten aufgeführten Dokumente ...,False,0.00,...,prüfvermerk\ndie unten aufgeführten dokumente ...,0.00,0.110000,6,0,2026-02-23 11:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False

In [62]:
prod_dataset_llm_pred_PFUB.dropna(subset=["pfub_slug", "pfub_debtor_name"], inplace=True)

In [63]:
add_data = prod_dataset_llm_pred_PFUB.sample(n=200, random_state=1)

In [64]:
add_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_parsed,pred_is_pfub,pred_is_invoice_inside
435,50908179,ocr_source_files/2026-01-27/egvp_id_297844/509...,pair-data-engineering-new,50908179_BriefkopfGericht_20260127_1da1747c414...,b5aad3c87151a4dece3d704aca641f5eaa9a29c01e4a79...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Arnsberg\n-43- Amtsgericht Arnsber...,False,0.02,...,amtsgericht arnsberg\n<NUMBER>- amtsgericht ar...,0.00,0.375714,3,0,2026-01-27 14:44:00,"Okay, let's tackle this classification task. F...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1674,53757090,ocr_source_files/2026-02-23/egvp_id_314175/537...,pair-data-engineering-new,53757090_18M86_26_VB-GL_PairFinanceGmbH_8AE650...,8a2896206942c5723d31202db61ebe793713ece756b709...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nBurgdorf\nAmtsgericht Burgdorf, S...",False,0.01,...,"amtsgericht\nburgdorf\namtsgericht burgdorf, s...",0.01,0.148333,3,0,2026-02-23 14:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
776,51650146,ocr_source_files/2026-02-03/egvp_id_301946/516...,pair-data-engineering-new,51650146_Schreiben_b_00_49e42e1d21dc19b9e06361...,ae30b09956b4e0d55997fedf3988154d01c9555bb17f1d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Auerbach\nAmtsgericht Auerbach\nVo...,False,0.01,...,amtsgericht auerbach\namtsgericht auerbach\nvo...,0.02,0.180000,3,0,2026-02-03 12:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1468,53312990,ocr_source_files/2026-02-18/egvp_id_312310/533...,pair-data-engineering-new,53312990_BriefkopfGericht_20260218_1cc2f086dcd...,5626bd8d946d4de905bd02de1f18b4e13332e78321d5f5...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",False,0.00,...,amtsgericht lemgo\n<NUMBER>- amtsgericht lemgo...,0.00,0.280000,3,0,2026-02-18 20:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1071,52543820,ocr_source_files/2026-02-11/egvp_id_307453/525...,pair-data-engineering-new,52543820_14M189_26_VB-GL_PairFinanceGmbH_2C5F3...,4cac5b43d5399f93c9ec695a928a5018901248e711497d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Völklingen\nAmtsgericht Völklingen...,False,0.03,...,amtsgericht völklingen\namtsgericht völklingen...,0.05,0.288333,3,0,2026-02-11 09:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,51872432,ocr_source_files/2026-02-05/egvp_id_303723/518...,pair-data-engineering-new,51872432_66M910_25_VB-GL_PairFinanceGmbH_E65C3...,32ac48039ffa0427b6da10045ee0436ced37897597a74d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nAmtsgericht Oldenburg (Oldb), Eli...",False,0.01,...,"amtsgericht\namtsgericht oldenburg (oldb), eli...",0.00,0.193333,3,0,2026-02-05 10:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1881,54147640,ocr_source_files/2026-02-26/egvp_id_316710/541...,pair-data-engineering-new,54147640_BriefkopfGericht_20260226_812b589e2ab...,a5c004c018b5f63790a8b8d235bc536d6ffc03a2389821...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,False,0.00,...,amtsgericht mönchengladbach\n<NUMBER>- amtsger...,0.00,0.240000,3,0,2026-02-26 12:44:00,"Okay, let's tackle this classification task. I...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1513,53358951,ocr_source_files/2026-02-19/egvp_id_312560/533...,pair-data-engineering-new,53358951_Schreiben_b_00_4b285dbe816e17eee06362...,f116fe3ef6fe6d7cb6b23c94f76e5e49b72cf5e27dd813...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Pirna\nAmtsgericht Pirna\nVollstre...,False,0.05,...,amtsgericht pirna\namtsgericht pirna\nvollstre...,0.05,0.150000,3,0,2026-02-19 11:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
968,52405039,ocr_source_files/2026-02-10/egvp_id_306580/524...,pair-data-engineering-new,52405039_Allgemeines_Schreiben_R__20260210_51a...,5c369bf8dffc360762a9c9c66a49fa06a26d887c61a1db...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",False,0.00,...,"amtsgericht köln\n-290a- amtsgericht köln, <NU...",0.00,0.388000,3,0,2026-02-10 07:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
377,50899912,ocr_source_files/2026-01-27/egvp_id_297453/508...,pair-data-engineering-new,50899912_BriefkopfGericht_20260127_6c448120165...,37907ebf4333497827f27713f3ae58fb6fbdae6ccdb0c8...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Mönchengladbach-Rheydt\n-32- Amtsg...,False,0.00,...,amtsgericht mönchengladbach-rheydt\n<NUMBER>- ...,0.00,0.235000,3,0,2026-01-27 08:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False

In [103]:
from utils.prod_utils import get_data_by_attachment_id

# # download pdfs for add_data
# download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/add_data_sil"
# for i, row in add_data.iterrows():
#     attachment_id = row.attachment_id
#     data = get_data_by_attachment_id(attachment_id, analytics_db, s3, pdf_download=True, pdf_download_dir=download_dir, verbose=False)

In [104]:
# add_data.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/add_data_sample_sil.csv", index=False)

In [105]:
add_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/add_data_sample_sil.csv")

In [106]:
add_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,is_ladung,ladung_prob,...,text_with_tags,ladung_prob_cur,pfub_prob_cur,kmeans_cluster,dbscan_cluster,created_at,pred_llm,pred_parsed,pred_is_pfub,pred_is_invoice_inside
0,50908179,ocr_source_files/2026-01-27/egvp_id_297844/509...,pair-data-engineering-new,50908179_BriefkopfGericht_20260127_1da1747c414...,b5aad3c87151a4dece3d704aca641f5eaa9a29c01e4a79...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Arnsberg\n-43- Amtsgericht Arnsber...,False,0.02,...,amtsgericht arnsberg\n<NUMBER>- amtsgericht ar...,0.00,0.375714,3,0,2026-01-27 14:44:00,"Okay, let's tackle this classification task. F...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
1,53757090,ocr_source_files/2026-02-23/egvp_id_314175/537...,pair-data-engineering-new,53757090_18M86_26_VB-GL_PairFinanceGmbH_8AE650...,8a2896206942c5723d31202db61ebe793713ece756b709...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nBurgdorf\nAmtsgericht Burgdorf, S...",False,0.01,...,"amtsgericht\nburgdorf\namtsgericht burgdorf, s...",0.01,0.148333,3,0,2026-02-23 14:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
2,51650146,ocr_source_files/2026-02-03/egvp_id_301946/516...,pair-data-engineering-new,51650146_Schreiben_b_00_49e42e1d21dc19b9e06361...,ae30b09956b4e0d55997fedf3988154d01c9555bb17f1d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Auerbach\nAmtsgericht Auerbach\nVo...,False,0.01,...,amtsgericht auerbach\namtsgericht auerbach\nvo...,0.02,0.180000,3,0,2026-02-03 12:44:00,"Okay, let's tackle this classification task st...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
3,53312990,ocr_source_files/2026-02-18/egvp_id_312310/533...,pair-data-engineering-new,53312990_BriefkopfGericht_20260218_1cc2f086dcd...,5626bd8d946d4de905bd02de1f18b4e13332e78321d5f5...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",False,0.00,...,amtsgericht lemgo\n<NUMBER>- amtsgericht lemgo...,0.00,0.280000,3,0,2026-02-18 20:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
4,52543820,ocr_source_files/2026-02-11/egvp_id_307453/525...,pair-data-engineering-new,52543820_14M189_26_VB-GL_PairFinanceGmbH_2C5F3...,4cac5b43d5399f93c9ec695a928a5018901248e711497d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Völklingen\nAmtsgericht Völklingen...,False,0.03,...,amtsgericht völklingen\namtsgericht völklingen...,0.05,0.288333,3,0,2026-02-11 09:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,51872432,ocr_source_files/2026-02-05/egvp_id_303723/518...,pair-data-engineering-new,51872432_66M910_25_VB-GL_PairFinanceGmbH_E65C3...,32ac48039ffa0427b6da10045ee0436ced37897597a74d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nAmtsgericht Oldenburg (Oldb), Eli...",False,0.01,...,"amtsgericht\namtsgericht oldenburg (oldb), eli...",0.00,0.193333,3,0,2026-02-05 10:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
196,54147640,ocr_source_files/2026-02-26/egvp_id_316710/541...,pair-data-engineering-new,54147640_BriefkopfGericht_20260226_812b589e2ab...,a5c004c018b5f63790a8b8d235bc536d6ffc03a2389821...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,False,0.00,...,amtsgericht mönchengladbach\n<NUMBER>- amtsger...,0.00,0.240000,3,0,2026-02-26 12:44:00,"Okay, let's tackle this classification task. I...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
197,53358951,ocr_source_files/2026-02-19/egvp_id_312560/533...,pair-data-engineering-new,53358951_Schreiben_b_00_4b285dbe816e17eee06362...,f116fe3ef6fe6d7cb6b23c94f76e5e49b72cf5e27dd813...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Pirna\nAmtsgericht Pirna\nVollstre...,False,0.05,...,amtsgericht pirna\namtsgericht pirna\nvollstre...,0.05,0.150000,3,0,2026-02-19 11:44:00,"Okay, let's tackle this document classificatio...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
198,52405039,ocr_source_files/2026-02-10/egvp_id_306580/524...,pair-data-engineering-new,52405039_Allgemeines_Schreiben_R__20260210_51a...,5c369bf8dffc360762a9c9c66a49fa06a26d887c61a1db...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",False,0.00,...,"amtsgericht köln\n-290a- amtsgericht köln, <NU...",0.00,0.388000,3,0,2026-02-10 07:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False
199,50899912,ocr_source_files/2026-01-27/egvp_id_297453/508...,pair-data-engineering-new,50899912_BriefkopfGericht_20260127_6c448120165...,37907ebf4333497827f27713f3ae58fb6fbdae6ccdb0c8...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Mönchengladbach-Rheydt\n-32- Amtsg...,False,0.00,...,amtsgericht mönchengladbach-rheydt\n<NUMBER>- ...,0.00,0.235000,3,0,2026-01-27 08:44:00,"Okay, let's tackle this classification step by...","{'is_pfub': True, 'is_invoice_inside': False}",True,False

In [107]:
raw_data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410,c32daff3-49d9-5c6a-baef-ff36585d7fdc,20cd18e4-97d2-579b-8238-0465dd3c6253,Anlage zur Niederschrift d.:\nGV J. Hertel\nvo...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,anlage zur niederschrift d.:\ngv j. hertel\nvo...,NaN,False,False,NaN,5d38e9b4b6c5c862faf7cf5255a9a00550dfb4b0deedc9...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5411,4aa68493-cf56-5f8d-b10d-e38a44ec2d2d,4fdca78f-66dc-570d-b40c-0b520b892af5,Obergerichtsvollzieherin Kerstin Gernert\n1551...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,obergerichtsvollzieherin kerstin gernert\n1551...,NaN,False,False,NaN,63d4af42eca48e863ff72433c51f65ed627c4167d6a6ba...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5412,2e39888c-cc06-574f-90ae-348009e802af,9ee5bc1d-b55f-5250-98b7-2ab4bcf8bff0,Gerichtsvollzieherin Sülzle\nBüroanschrift:\nA...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,gerichtsvollzieherin sülzle\nbüroanschrift:\na...,NaN,False,False,NaN,0d9f9857bac053a6bdf1278afcef872f84a19d01385fd0...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5413,d8b85e90-59ba-5985-9699-1fab6c6a974e,071beb4b-a61e-5492-b016-ab7e4887509f,Obergerichtsvollzieher T. Eberl\nAmtsgericht S...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,obergerichtsvollzieher t. eberl\namtsgericht s...,NaN,False,False,NaN,a0b9a8854c8fc28fec0e95cb6f9433ee0adc2dbd3bdaea...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5414,d95b8c60-7670-57b3-a824-ae999125ee77,7142425f-6487-533c-bdc2-83010c516ee0,Amtsgericht Hamburg-St.Georg\nGerichtsvollzieh...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,amtsgericht hamburg-st.georg\ngerichtsvollzieh...,NaN,False,False,NaN,f4096ea2d73add08017d42ca48661a617ed13f1953db5a...,s3://pair-data-engineering-new/ocr_prepared_ou...,False

In [108]:
labels_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/llm_predictions/pfub_labels.txt"

In [109]:
with open(labels_path, "r") as f:
    labels = f.read().splitlines()

In [110]:
labels

['50908179',
 '53757090',
 '51650146',
 '53312990',
 '52543820',
 '51121192',
 '53791021',
 '53411105',
 '50390353',
 '50426119',
 '52678748',
 '51355964',
 '50772941',
 '50453739',
 '53305689',
 '53151370',
 '50451906',
 '53408137',
 '53753717',
 '50450168',
 '50903845',
 '51630144',
 '52543830',
 '50448711',
 '51875613',
 '53149109',
 '50908290',
 '53789418',
 '50390302',
 '53141953',
 '51467424',
 '50907293',
 '50393037',
 '53353706',
 '50222530',
 '52626830',
 '51118447',
 '50906360',
 '54143165',
 '50899965',
 '50772896',
 '53309241',
 '51120564',
 '50456033',
 '51928720',
 '53152580',
 '51122312',
 '52416174',
 '51875261',
 '50220240',
 '53309281',
 '53797919',
 '51789527',
 '50780674',
 '51179373',
 '51937109',
 '53310407',
 '53758338',
 '53752557',
 '53141945',
 '50756050',
 '50219939',
 '52617476',
 '53147741',
 '52679598',
 '51652158',
 '53006240',
 '53757057',
 '51458000',
 '53150391',
 '53757103',
 '53009638',
 '54083694',
 '50508761',
 '51170508',
 '50221860',
 '50425924',
 '51457973',
 '54081994',
 '53353661',
 '50763824',
 '51936158',
 '51057928',
 '53012424',
 '50220778',
 '50399442',
 '53353651',
 '50446596',
 '50766394',
 '51057700',
 '51936223',
 '53357561',
 '50426410',
 '53310325',
 '53306552',
 '51057826',
 '50780678',
 '52414918',
 '52619118',
 '53411120',
 '50897942',
 '52593780',
 '54079505',
 '50764673',
 '54088857',
 '50396530',
 '52679642',
 '53804720',
 '50908213',
 '53408117',
 '54088824',
 '53804709',
 '51063624',
 '53794854',
 '50903768',
 '54147640',
 '52405039']

In [111]:
labels_int = list(map(int, labels))

In [112]:
add_final = add_data[add_data.attachment_id.isin(labels_int)][["attachment_id", "text", "document_s3_key"]].copy()

In [113]:
add_final

,attachment_id,text,document_s3_key
0,50908179,Amtsgericht Arnsberg\n-43- Amtsgericht Arnsber...,ocr_source_files/2026-01-27/egvp_id_297844/509...
1,53757090,"Amtsgericht\nBurgdorf\nAmtsgericht Burgdorf, S...",ocr_source_files/2026-02-23/egvp_id_314175/537...
2,51650146,Amtsgericht Auerbach\nAmtsgericht Auerbach\nVo...,ocr_source_files/2026-02-03/egvp_id_301946/516...
3,53312990,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",ocr_source_files/2026-02-18/egvp_id_312310/533...
4,52543820,Amtsgericht Völklingen\nAmtsgericht Völklingen...,ocr_source_files/2026-02-11/egvp_id_307453/525...
...,...,...,...
190,51063624,"Amtsgericht\nStade\nAmtsgericht Stade, Wilhadi...",ocr_source_files/2026-01-28/egvp_id_298225/510...
192,53794854,Amtsgericht Recklinghausen\n-21- Amtsgericht R...,ocr_source_files/2026-02-24/egvp_id_314722/537...
194,50903768,Amtsgericht Balingen\nVOLLSTRECKUNGSGERICHT\nA...,ocr_source_files/2026-01-27/egvp_id_297553/509...
196,54147640,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,ocr_source_files/2026-02-26/egvp_id_316710/541...
198,52405039,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",ocr_source_files/2026-02-10/egvp_id_306580/524...

# add this new data

In [114]:
from utils.intent_recog_utils import apply_text_cleaning
from src.data_handling.update_raw_data import update_raw_data

final_raw_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [115]:
final_raw_data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           406
court_inbox                                346
fp_protocol                                220
fp_invoice                                 128
vermögensverzeichnis                        89
approved_attachment_and_transfer_order      64
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
contradiction                                3
Name: count, dtype: int64

In [116]:
add_final

,attachment_id,text,document_s3_key
0,50908179,Amtsgericht Arnsberg\n-43- Amtsgericht Arnsber...,ocr_source_files/2026-01-27/egvp_id_297844/509...
1,53757090,"Amtsgericht\nBurgdorf\nAmtsgericht Burgdorf, S...",ocr_source_files/2026-02-23/egvp_id_314175/537...
2,51650146,Amtsgericht Auerbach\nAmtsgericht Auerbach\nVo...,ocr_source_files/2026-02-03/egvp_id_301946/516...
3,53312990,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",ocr_source_files/2026-02-18/egvp_id_312310/533...
4,52543820,Amtsgericht Völklingen\nAmtsgericht Völklingen...,ocr_source_files/2026-02-11/egvp_id_307453/525...
...,...,...,...
190,51063624,"Amtsgericht\nStade\nAmtsgericht Stade, Wilhadi...",ocr_source_files/2026-01-28/egvp_id_298225/510...
192,53794854,Amtsgericht Recklinghausen\n-21- Amtsgericht R...,ocr_source_files/2026-02-24/egvp_id_314722/537...
194,50903768,Amtsgericht Balingen\nVOLLSTRECKUNGSGERICHT\nA...,ocr_source_files/2026-01-27/egvp_id_297553/509...
196,54147640,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,ocr_source_files/2026-02-26/egvp_id_316710/541...
198,52405039,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",ocr_source_files/2026-02-10/egvp_id_306580/524...

In [117]:

add_final["attachment_id"] = add_final["attachment_id"].astype(str)
add_final.rename(columns={"document_s3_key": "object_key"}, inplace=True)

In [118]:
# add required columns
add_final['document_type'] = 'approved_seizure'
add_final['is_pfub'] = True
add_final['is_ladung'] = False
add_final['cleaned_text'] = add_final['text'].fillna("").apply(apply_text_cleaning)

df_to_save = update_raw_data(final_raw_data, add_final)

Starting raw data update. Raw data: 5415 rows, New data: 117 rows.
Validating required columns: ['text', 'document_type', 'is_pfub', 'is_ladung']
All required columns validated successfully.
Filling generated columns for 117 rows.
Validating dtypes between raw data and new data.
No duplicates found.
Raw data update complete. Total rows: 5532 (added 117).

In [119]:
df_to_save

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,877fec37-14cc-54a4-981b-03068f06cfb0,51063624,"Amtsgericht\nStade\nAmtsgericht Stade, Wilhadi...",ocr_source_files/2026-01-28/egvp_id_298225/510...,approved_seizure,"amtsgericht\nstade\namtsgericht stade, wilhadi...",NaN,True,False,NaN,f1821528241834bf652de73072877d05e37e1bed41eb30...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5528,c23aa6cb-a450-55c0-959f-98b97c46aaae,53794854,Amtsgericht Recklinghausen\n-21- Amtsgericht R...,ocr_source_files/2026-02-24/egvp_id_314722/537...,approved_seizure,amtsgericht recklinghausen\n-21- amtsgericht r...,NaN,True,False,NaN,59f2ce713fb91a57615e31a1bc050ad0bac1a5fbc8831c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5529,a135f935-fcd8-5e57-9766-2d83bacddb71,50903768,Amtsgericht Balingen\nVOLLSTRECKUNGSGERICHT\nA...,ocr_source_files/2026-01-27/egvp_id_297553/509...,approved_seizure,amtsgericht balingen\nvollstreckungsgericht\na...,NaN,True,False,NaN,9a5f4109fbcc8d9f77539d9e6e44dc27f8046b13e6653a...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5530,6a1cd15e-01aa-579a-8dd9-87feacdc150c,54147640,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,ocr_source_files/2026-02-26/egvp_id_316710/541...,approved_seizure,amtsgericht mönchengladbach\n-22- amtsgericht ...,NaN,True,False,NaN,891fdead6ffabe702a76b2fc56bc60976eac132b0431b0...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5531,c48ba503-afd4-513c-9599-5aa282af27e1,52405039,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",ocr_source_files/2026-02-10/egvp_id_306580/524...,approved_seizure,"amtsgericht köln\n-290a- amtsgericht köln, 509...",NaN,True,False,NaN,8d95af8052e8b1e038bbb8f095a6eac411d5aa69a00377...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN

In [120]:
newly_added = df_to_save[df_to_save["attachment_id"].isin(add_final["attachment_id"])]

In [121]:
newly_added

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice
5415,b56645de-2f26-59e5-8168-2ab6fe583b36,50908179,Amtsgericht Arnsberg\n-43- Amtsgericht Arnsber...,ocr_source_files/2026-01-27/egvp_id_297844/509...,approved_seizure,amtsgericht arnsberg\n-43- amtsgericht arnsber...,NaN,True,False,NaN,9cb97d8bd64bd60821a70b808f6231e3a670b846da67a4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5416,c4a67368-0daa-504f-b372-8d607a7c2347,53757090,"Amtsgericht\nBurgdorf\nAmtsgericht Burgdorf, S...",ocr_source_files/2026-02-23/egvp_id_314175/537...,approved_seizure,"amtsgericht\nburgdorf\namtsgericht burgdorf, s...",NaN,True,False,NaN,349b38cf7703efdbe2614c80fbee1f116b5dbe514db727...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5417,fc7cbd7c-fa60-5517-8d14-61d2ca268652,51650146,Amtsgericht Auerbach\nAmtsgericht Auerbach\nVo...,ocr_source_files/2026-02-03/egvp_id_301946/516...,approved_seizure,amtsgericht auerbach\namtsgericht auerbach\nvo...,NaN,True,False,NaN,df67fd31d5b17b4adfb748ec52f8a1a9718eeb16b45cf3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5418,06b3f22a-5b2a-5d88-8c11-31f9d141b950,53312990,"Amtsgericht Lemgo\n-14- Amtsgericht Lemgo, Am ...",ocr_source_files/2026-02-18/egvp_id_312310/533...,approved_seizure,"amtsgericht lemgo\n-14- amtsgericht lemgo, am ...",NaN,True,False,NaN,bded7bf2d37a2afb8b1638a38052c5c322694ce086b669...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5419,d3eb7e3f-83c1-5838-83b8-e052d09c530d,52543820,Amtsgericht Völklingen\nAmtsgericht Völklingen...,ocr_source_files/2026-02-11/egvp_id_307453/525...,approved_seizure,amtsgericht völklingen\namtsgericht völklingen...,NaN,True,False,NaN,0ffc161a12c6fb1fd5eb76fa930b46583dd5dba71cb0f5...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527,877fec37-14cc-54a4-981b-03068f06cfb0,51063624,"Amtsgericht\nStade\nAmtsgericht Stade, Wilhadi...",ocr_source_files/2026-01-28/egvp_id_298225/510...,approved_seizure,"amtsgericht\nstade\namtsgericht stade, wilhadi...",NaN,True,False,NaN,f1821528241834bf652de73072877d05e37e1bed41eb30...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5528,c23aa6cb-a450-55c0-959f-98b97c46aaae,53794854,Amtsgericht Recklinghausen\n-21- Amtsgericht R...,ocr_source_files/2026-02-24/egvp_id_314722/537...,approved_seizure,amtsgericht recklinghausen\n-21- amtsgericht r...,NaN,True,False,NaN,59f2ce713fb91a57615e31a1bc050ad0bac1a5fbc8831c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5529,a135f935-fcd8-5e57-9766-2d83bacddb71,50903768,Amtsgericht Balingen\nVOLLSTRECKUNGSGERICHT\nA...,ocr_source_files/2026-01-27/egvp_id_297553/509...,approved_seizure,amtsgericht balingen\nvollstreckungsgericht\na...,NaN,True,False,NaN,9a5f4109fbcc8d9f77539d9e6e44dc27f8046b13e6653a...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5530,6a1cd15e-01aa-579a-8dd9-87feacdc150c,54147640,Amtsgericht Mönchengladbach\n-22- Amtsgericht ...,ocr_source_files/2026-02-26/egvp_id_316710/541...,approved_seizure,amtsgericht mönchengladbach\n-22- amtsgericht ...,NaN,True,False,NaN,891fdead6ffabe702a76b2fc56bc60976eac132b0431b0...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
5531,c48ba503-afd4-513c-9599-5aa282af27e1,52405039,"Amtsgericht Köln\n-290a- Amtsgericht Köln, 509...",ocr_source_files/2026-02-10/egvp_id_306580/524...,approved_seizure,"amtsgericht köln\n-290a- amtsgericht köln, 509...",NaN,True,False,NaN,8d95af8052e8b1e038bbb8f095a6eac411d5aa69a00377...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN

In [123]:
df_to_save.ticket_uuid.isna().sum()

np.int64(0)

In [124]:
df_to_save.ticket_uuid.is_unique

True

In [ ]:
# df_to_save.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)