In [ ]:
import pandas as pd

# 1) Adding ticket uuid and attachment id to the current dataframe

In [11]:
raw_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [12]:
raw_data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [13]:
attachment_ids = raw_data[~raw_data['attachment_id'].isna()]
attachment_ids

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

This 219 fp protocol data is already in our textract_jobs table, only add them to the llm_ticket_labels. Get theirs ticket uuids from the llm_tickets table

In [14]:
attachment_ids_to_fetch_ticket_uuid = attachment_ids['attachment_id'].tolist()
len(attachment_ids_to_fetch_ticket_uuid)

5383

In [15]:
attachment_ids['attachment_id'].nunique()

5383

In [16]:
attachment_ids['attachment_id'].isna().sum()

np.int64(0)

In [17]:
from python_utilities.db_connection import DbConnection
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
a_id_to_t_id = analytics_db.sql_to_df(f"""
    SELECT la.attachment_id, lt.ticket_uuid
    FROM llm_attachments la LEFT JOIN llm_tickets lt ON la.ticket_uuid = lt.ticket_uuid
    WHERE la.attachment_id IN ({','.join([str(id) for id in attachment_ids_to_fetch_ticket_uuid])})
""")

INFO [2026-03-09 12:36:55] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

KeyboardInterrupt

In [ ]:
a_id_to_t_id

    attachment_id                           ticket_uuid
0        44529743  4fe9b711-1c87-5072-8cee-30ef653866b7
1        44531561  0d29c484-086e-52c5-8e2d-1225798e8921
2        44689202  606b4c67-602f-5eb1-b278-32e464a5ebbe
3        44707482  92cfa0c5-cc22-5830-af7a-526d17fab297
4        44708172  22f3f9bd-48dd-50fb-aab7-9396d9cc4db2
..            ...                                   ...
207      49736954  15dae806-8d02-518a-bf32-2c51fe3e4792
208      49747921                                  None
209      49775489  5bebc9d4-4923-557a-a3e0-ae948c1396b2
210      49778889  ffa1e6d2-908a-54d7-ab14-d6d6c674bc33
211      49779491  075acea6-2657-55d2-bebd-baaf60f5a26b

[212 rows x 2 columns]

In [ ]:
# set ticket uuids in raw data for corresponding attachment ids
raw_data_with_ticket_uuids = raw_data.merge(a_id_to_t_id, on='attachment_id', how='left')

In [ ]:
raw_data_with_ticket_uuids.isna().sum()

text                0
object_key       1314
document_type       0
cleaned_text        0
data             4888
is_pfub           308
is_ladung           0
attachment_id    5136
s3_link          5136
ticket_uuid      5164
dtype: int64

In [ ]:
len(raw_data_with_ticket_uuids) - raw_data_with_ticket_uuids.isna().sum() # number of NOT NA

text             5355
object_key       4041
document_type    5355
cleaned_text     5355
data              467
is_pfub          5047
is_ladung        5355
attachment_id     219
s3_link           219
ticket_uuid       191
dtype: int64

In [ ]:
raw_data_with_ticket_uuids

NameError: name 'raw_data_with_ticket_uuids' is not defined

In [ ]:
import uuid
import hashlib


def generate_uuid(text: str, purpose: str) -> str:
    """
    Generate a UUID based on the input text.

    Args:
        text (str): The input text to generate the UUID from.
        purpose (str): The purpose for which the UUID is being generated.


    Returns:
        str: A UUID string generated from the input text and purpose.
    """
    # n = min(len(text), len(text), 5000)  # Limit to first 100 characters
    # text = text[:n]  # Limit the text to the first 100 characters
    signature = f"{purpose}:{text}"
    # Use nil UUID as namespace (compatible with all Python versions)
    nil_namespace = uuid.UUID('00000000-0000-0000-0000-000000000000')
    return str(uuid.uuid5(nil_namespace, signature))



def generate_hash_from_text(text: str) -> str:
    # n = min(len(text), 5000)  # Limit to first 1000 characters
    # text = text[:n]  # Limit the text to the first 1000 characters
    """Generate SHA-256 hash from text string"""
    return hashlib.sha256(text.encode('utf-8')).hexdigest()

def extract_filename_from_object_key(object_key: str) -> str:
    if pd.isna(object_key):
        return None
    return object_key.split('/')[-1]

def extract_s3_key(row):
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    base = "ocr_source_files"
    date_folder = created_at.split(' ')[0]  # Extract date part: YYYY-MM-DD
    egvp_id = row["egvp_id"]
    egvp_folder = f"egvp_id_{egvp_id}"
    full_path = f"{base}/{date_folder}/{egvp_folder}/{row['file_name']}"
    return full_path

add ticket_uuid

In [ ]:
raw_data['ticket_uuid'] = raw_data.apply(lambda row: generate_uuid(row['text'], purpose="ticket_uuid"), axis=1)

In [ ]:
raw_data.shape

(5462, 12)

In [ ]:
# only apply generate uuid if attachment_id lenght is 36

raw_data['attachment_id'] = raw_data.apply(lambda row: generate_uuid(row['text'], purpose="attachment_id") if pd.isna(row['attachment_id']) == True or len(row['attachment_id']) == 36 else row['attachment_id'], axis=1)

In [ ]:
# drop ticket uuid duplicates, keep the first occurrence
raw_data = raw_data.drop_duplicates(subset=['ticket_uuid'], keep='first')

In [ ]:
raw_data.attachment_id.is_unique

True

In [ ]:
# raw_data.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

In [ ]:
raw_data_with_ticket_uuids['ticket_uuid'] = raw_data_with_ticket_uuids.apply(lambda row: generate_uuid(row['text'], purpose="ticket_uuid") if pd.isna(row['ticket_uuid']) == True else row['ticket_uuid'], axis=1)

add attachment_id

In [ ]:
raw_data_with_ticket_uuids['attachment_id'] = raw_data_with_ticket_uuids.apply(lambda row: generate_uuid(row['text'], purpose="attachment_id") if pd.isna(row['attachment_id']) == True else row['attachment_id'], axis=1)

In [ ]:
raw_data_with_ticket_uuids['attachment_id'].isna().sum()

np.int64(0)

add textract related fields

In [ ]:
raw_data_with_ticket_uuids['textract_job_id'] = raw_data_with_ticket_uuids['text'].apply(lambda x: generate_hash_from_text(x))
raw_data_with_ticket_uuids['textract_s3_link'] = raw_data_with_ticket_uuids['textract_job_id'].apply(lambda x: f"s3://pair-data-engineering-new/ocr_prepared_output/{x}.json")

In [ ]:
raw_data_with_ticket_uuids['textract_job_id'].isna().sum(), raw_data_with_ticket_uuids['textract_s3_link'].isna().sum()

(np.int64(0), np.int64(0))

In [ ]:
new_column_order = ['ticket_uuid', 'attachment_id'] + [col for col in raw_data_with_ticket_uuids.columns if col not in ['ticket_uuid', 'attachment_id']]
raw_data_with_ticket_uuids = raw_data_with_ticket_uuids[new_column_order]

In [ ]:
raw_data_with_ticket_uuids

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,937b5e2e-f3b3-56bd-9225-f67840039ee1,8e6a76c1-34ed-5fe0-9144-bbd00e1cddd8,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,7e7ac68d-b2df-50d2-963d-200aa44b036b,417ecde8-b807-5de4-b066-f70f811c8f6a,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,2d315b63-cb84-56ef-bb02-af6c13dff49b,acc1f4fa-6891-58d3-a3d1-d3f3e54d93ba,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,dc9e9a0c-12a6-5b22-b6c0-52f1647505a2,cfc4d684-af88-506e-8fdb-39984cf93640,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,6abb8d66-912f-55bb-9b05-50dbd5c6a6f7,ccf92577-4ae3-505d-97eb-25c49e6fbc12,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5350,2bd93acd-08cd-5d66-9d0e-c72b3e1da733,0bd71681-f525-5f65-83eb-952e605409f3,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,False,False,NaN,ea578e5a3589fc0c5b640d644d57e917f384c0458f08ef...,s3://pair-data-engineering-new/ocr_prepared_ou...
5351,079a8404-edb0-5660-8722-8d46098ae215,8e8ef642-2c7a-5bdb-810b-48344c2a235a,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"paul-rohland-str.2\n06712 zeitz, elster\ntel. ...",NaN,False,False,NaN,dd4d8ce69f0e90db975a425b96b6c6515f56e912df606c...,s3://pair-data-engineering-new/ocr_prepared_ou...
5352,3321bf02-b3dd-592e-b0c6-e129b3719312,d47fad4c-772a-5f89-80c0-5ac9638b9e7e,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,wolfgang lurz\nschragenhofstraße 27\n80992 mün...,NaN,False,False,NaN,ce565a09de5e250d5545b02d2a482a08806b1df497e3cd...,s3://pair-data-engineering-new/ocr_prepared_ou...
5353,f5bdf478-897e-5da6-8669-f835dfcb9a38,ec52a8de-3bf8-5660-8501-414aebade679,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\n33104 paderborn\nwagen...,NaN,False,False,NaN,3aa213ac35184d2007d9386ad4f8b0f5b502ab1cb36b7d...,s3://pair-data-engineering-new/ocr_prepared_ou...
5354,d801cd78-4ff3-57ad-beab-cf574fbf4c73,76ee1429-e30e-5faa-8875-d3ba850bb4fa,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,False,False,NaN,6a0e3e72c6c47a6197ebd35a748ed1df71fc813d1568c5...,s3://pair-data-engineering-new/ocr_prepared_ou...

save raw df with new columns, update the data with dvc

In [ ]:
# raw_data_with_ticket_uuids.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

# 2) Scripts to add raw data to tables

Inter into llm_label_defs

In [ ]:
labels = list(raw_data_with_ticket_uuids['document_type'].unique())
labels

['attachment_and_transfer_order',
 'ladung_va',
 'approved_attachment_and_transfer_order',
 'contradiction',
 'approved_seizure',
 'fp_invoice',
 'court_inbox',
 'enforcement_order',
 'monierung_mb',
 'vermögensverzeichnis',
 'mail_attachments',
 'fp_protocol',
 'bailiff_ip']

### 2.1) INSERT INTO llm_labels_defs

In [ ]:
# label id is auto increment, we can diretly add label to the labels table

In [ ]:
def insert_labels_to_db(labels: list, connection=None):
    subtype = 'none'
    nature = 'aftercourt'
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    for label in labels:
        # query = """INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
        #            VALUES (%s, %s, %s, %s, %s, NULL);"""
        query = f"""INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('{label}', '{subtype}', '{nature}', '{created_at}', '{updated_at}', NULL);"""
        print(f"{Colors.CYAN}label:{Colors.END} {Colors.CYAN}{Colors.BOLD}{label}{Colors.END}")
        print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
        print("-"*100)
        # Use parameterized query with your DB cursor
        #cursor.execute(query, (label, subtype, nature, created_at, updated_at))
insert_labels_to_db(labels)

label: attachment_and_transfer_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('attachment_and_transfer_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: ladung_va
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('ladung_va', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: approved_attachment_and_transfer_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('approved_attachment_and_transfer_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: contradiction
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('contradiction', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: approved_seizure
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('approved_seizure', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: fp_invoice
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('fp_invoice', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: court_inbox
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('court_inbox', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: enforcement_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('enforcement_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: monierung_mb
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('monierung_mb', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: vermögensverzeichnis
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('vermögensverzeichnis', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: mail_attachments
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('mail_attachments', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: fp_protocol
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('fp_protocol', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: bailiff_ip
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('bailiff_ip', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------

### 2.2) Insert into llm_ticket_labels

In [ ]:
# first creaete label name label id mapping by checking the llm label defs

In [ ]:
label_to_id_mapping = {}

for lbl in labels:
    # query = "SELECT id FROM llm_label_defs WHERE type = %s AND subtype = 'none' AND nature = 'aftercourt';"
    # cursor.execute(query, (lbl,))
    query = f"SELECT id FROM llm_label_defs WHERE type = '{lbl}' AND subtype = 'none' AND nature = 'aftercourt';"
    # result = cursor.fetchone()
    # if result:
    #     label_to_id_mapping[lbl] = result[0]
    # dummy mapping
    label_to_id_mapping[lbl] = hash(lbl) % 1000  # Replace with actual ID from DB
label_to_id_mapping

{'attachment_and_transfer_order': 17,
 'ladung_va': 223,
 'approved_attachment_and_transfer_order': 483,
 'contradiction': 70,
 'approved_seizure': 715,
 'fp_invoice': 492,
 'court_inbox': 612,
 'enforcement_order': 580,
 'monierung_mb': 49,
 'vermögensverzeichnis': 593,
 'mail_attachments': 675,
 'fp_protocol': 435,
 'bailiff_ip': 863}

In [ ]:
def insert_into_llm_ticket_labels(row):
    label = row['document_type']
    ticket_uuid = row['ticket_uuid']
    zendesk_id = None
    comment_id = None
    attachment_id = row['attachment_id']
    label_id = label_to_id_mapping.get(label)
    value = "True"
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    
    assert label_id is not None, f"label_id cannot be None for label: {label}"
    assert ticket_uuid is not None, f"ticket_uuid cannot be None for attachment_id: {attachment_id}"
    assert attachment_id is not None, f"attachment_id cannot be None for ticket_uuid: {ticket_uuid}"
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BLUE = '\033[94m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    # query = """INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
    #            VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"""
    query = f"""INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('{ticket_uuid}', NULL, NULL, '{attachment_id}', {label_id}, '{value}', '{created_at}', '{updated_at}');"""
    print(f"{Colors.CYAN}ticket_uuid:{Colors.END} {Colors.CYAN}{Colors.BOLD}{ticket_uuid}{Colors.END} | "
          f"{Colors.GREEN}label:{Colors.END} {Colors.GREEN}{Colors.BOLD}{label}{Colors.END} | "
          f"{Colors.BLUE}label_id:{Colors.END} {Colors.BLUE}{Colors.BOLD}{label_id}{Colors.END}")
    print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
    print("-"*100)
    return True
    
# Apply the function to each row in the DataFrame
test = raw_data_with_ticket_uuids.sample(3,random_state=42)
test.apply(insert_into_llm_ticket_labels, axis=1)

ticket_uuid: b454a46e-dd84-5ba5-8832-4ff24b7c14c8 | label: mail_attachments | label_id: 675
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('b454a46e-dd84-5ba5-8832-4ff24b7c14c8', NULL, NULL, 'af878f5f-0c17-514c-9225-315e9347cf28', 675, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------
ticket_uuid: 8775beb9-791b-54e7-b8ee-f7c58f78e2bf | label: ladung_va | label_id: 223
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('8775beb9-791b-54e7-b8ee-f7c58f78e2bf', NULL, NULL, '9ce88f72-6e35-5105-b8dc-aed0e4802e39', 223, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------
ticket_uuid: 0dc12f74-3a28-5114-ad48-4faf8876c1c2 | label: court_inbox | label_id: 612
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('0dc12f74-3a28-5114-ad48-4faf8876c1c2', NULL, NULL, 'b215f94d-b874-5dd5-be1c-c2869806546e', 612, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------

5010    True
1650    True
401     True
dtype: bool

### 2.3) Insert into textract_jobs

In [ ]:
test.columns

Index(['ticket_uuid', 'attachment_id', 'text', 'object_key', 'document_type',
       'cleaned_text', 'data', 'is_pfub', 'is_ladung', 's3_link',
       'textract_job_id', 'textract_s3_link'],
      dtype='object')

In [ ]:
def uplaod_text_as_json_to_s3(row):
    """
    Upload text as Textract-formatted JSON to S3.
    Reverse engineers the Textract output format from plain text.
    """
    import boto3
    import json
    
    text = row['text']
    textract_s3_link = row['textract_s3_link']
    s3_bucket = "pair-data-engineering-new"
    textract_job_id = row['textract_job_id']
    
    # Parse s3 link: s3://bucket/path/to/file.json
    # Extract key from textract_s3_link
    s3_key = f"ocr_prepared_output/{textract_job_id}.json"
    
    assert textract_s3_link == f"s3://{s3_bucket}/{s3_key}", "S3 link does not match expected format"
     
    # Split text into lines
    lines = text.split('\n')
    
    # Create Textract-like JSON structure
    blocks = []
    for idx, line in enumerate(lines):
        if line.strip():  # Only include non-empty lines
            block = {
                "BlockType": "LINE",
                "Text": line,
                "Id": f"line_{idx}",
                "Confidence": 99.0
            }
            blocks.append(block)
    
    # Upload to S3
    # session = boto3.Session(profile_name='739275445236_DataScienceUser')
    # s3_client = session.client('s3')
    
    try:
        # Convert to JSON string
        json_content = json.dumps(blocks, ensure_ascii=False, indent=2)
        
        # Upload to S3
        # s3_client.put_object(
        #     Bucket=s3_bucket,
        #     Key=s3_key,
        #     Body=json_content.encode('utf-8'),
        #     ContentType='application/json'
        # )
        print(f"Uploaded JSON to s3://{s3_bucket}/{s3_key}")
    except Exception as e:
        print(f"Error uploading JSON: {e}")
    
    return True

def insert_into_textract_jobs(row):
    job_id = row['textract_job_id']
    status = "SUCCEEDED"
    s3_link = row['textract_s3_link']
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    attachment_id = row['attachment_id']
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BLUE = '\033[94m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    # query = """INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
    #            VALUES (%s, %s, %s, %s, %s, %s);"""
    query = f"""INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('{job_id}', '{status}', '{s3_link}', '{created_at}', '{updated_at}', '{attachment_id}');"""
    print(f"{Colors.CYAN}job_id:{Colors.END} {Colors.CYAN}{Colors.BOLD}{job_id}{Colors.END} | "
          f"{Colors.GREEN}attachment_id:{Colors.END} {Colors.GREEN}{Colors.BOLD}{attachment_id}{Colors.END} | "
          f"{Colors.BLUE}status:{Colors.END} {Colors.BLUE}{Colors.BOLD}{status}{Colors.END}")
    print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
    print("-"*100)

    return True

test.apply(insert_into_textract_jobs, axis=1)

job_id: 8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316 | attachment_id: af878f5f-0c17-514c-9225-315e9347cf28 | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', 'af878f5f-0c17-514c-9225-315e9347cf28');
----------------------------------------------------------------------------------------------------
job_id: 330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a | attachment_id: 9ce88f72-6e35-5105-b8dc-aed0e4802e39 | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', '9ce88f72-6e35-5105-b8dc-aed0e4802e39');
----------------------------------------------------------------------------------------------------
job_id: fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3 | attachment_id: b215f94d-b874-5dd5-be1c-c2869806546e | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', 'b215f94d-b874-5dd5-be1c-c2869806546e');
----------------------------------------------------------------------------------------------------

5010    True
1650    True
401     True
dtype: bool

### 3) uploading texts as JSON FILE to the textract s3 link

In [ ]:

test.apply(uplaod_text_as_json_to_s3, axis=1)

Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316.json
Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a.json
Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3.json

5010    True
1650    True
401     True
dtype: bool

# Uploading textract texts in approptiate json structure to appropriate s3 location

In [18]:
import pandas as pd
from python_utilities.db_connection import DbConnection
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')

INFO [2026-03-09 12:36:57] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [20]:
data_textract_new = pd.read_csv("/Users/melih.gorgulu/Desktop/send/textract-jobs-fix/textract_jobs_row_to_insert.csv")
data_textract_new

,job_id,status,s3_link,created_at,updated_at,attachment_id
0,a0f4cb491b8adc8b18ee574d4c8e0e3f2ccf0803da72f3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,7a78745c-e4ff-5d1f-abd0-39b5f517109b
1,f0823bec7f0229e720daea46dd5e1839213674da8a3904...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,8eb7ea40-2bb6-5828-98af-5c8686c67a34
2,13267605a6a5f0fcd5e1f71bc57882ea12693c0148ac27...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,dcf3e789-6aa7-595d-94c7-9133ae2b2375
3,8fc631fdf6289203aff7c103433654f0f10b77222899cc...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,f04f445f-dcd7-5044-8a7f-5d6f37a8e608
4,1dfa3e460080954d1f476a7c4544ba03189dedca3318ad...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,ff5c534d-1dd9-5dac-be2e-b57f812f36ac
...,...,...,...,...,...,...
4379,80a07fe2fc900658bf099aadf0c71305a4030507fc9682...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,50763696
4380,0bd713f1dbf623c594eb31ab82258ef0b523b28b7efa3d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,51170436
4381,c2fecb396b25f23d1a7c0b168aee34b88c6c5cc85ed4f7...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,52618215
4382,872abbcf24fad2675300d3173f866a03159c5b912596b0...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,51118089
4383,8d5c8ffca680b821bf61d62041bd40a97ce647f32df6be...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,50427647

# get texts for the attachments

In [21]:
text_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")
text_data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [24]:
data_textract_new_with_text = data_textract_new.merge(text_data[['attachment_id', 'text']], on='attachment_id', how='inner')

In [25]:
data_textract_new_with_text

,job_id,status,s3_link,created_at,updated_at,attachment_id,text
0,a0f4cb491b8adc8b18ee574d4c8e0e3f2ccf0803da72f3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...
1,f0823bec7f0229e720daea46dd5e1839213674da8a3904...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...
2,13267605a6a5f0fcd5e1f71bc57882ea12693c0148ac27...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...
3,8fc631fdf6289203aff7c103433654f0f10b77222899cc...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...
4,1dfa3e460080954d1f476a7c4544ba03189dedca3318ad...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...
...,...,...,...,...,...,...,...
4379,80a07fe2fc900658bf099aadf0c71305a4030507fc9682...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,50763696,Gerichtsvollzieher Schaare\nAmtsgericht Bad Sa...
4380,0bd713f1dbf623c594eb31ab82258ef0b523b28b7efa3d...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...
4381,c2fecb396b25f23d1a7c0b168aee34b88c6c5cc85ed4f7...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...
4382,872abbcf24fad2675300d3173f866a03159c5b912596b0...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...
4383,8d5c8ffca680b821bf61d62041bd40a97ce647f32df6be...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,2026-03-06 13:16:51,2026-03-06 13:16:51,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...

In [29]:
def is_jobid_in_db(job_id, connection):
    query = f"SELECT COUNT(*) FROM textract_jobs WHERE job_id = '{job_id}';"
    result = connection.sql_to_df(query)
    return result.iloc[0, 0] > 0

In [37]:
def upload_text_as_json_to_s3(row, counter, total):
    """
    Upload text as Textract-formatted JSON to S3.
    Reverse engineers the Textract output format from plain text.
    """
    import boto3
    import json
    
    counter[0] += 1
    remaining = total - counter[0]
    
    text = row['text']
    textract_s3_link = row['s3_link']
    s3_bucket = "pair-data-engineering-new"
    textract_job_id = row['job_id']
    
    # Parse s3 link: s3://bucket/path/to/file.json
    # Extract key from textract_s3_link
    s3_key = f"ocr_prepared_output/{textract_job_id}.json"
    
    assert textract_s3_link == f"s3://{s3_bucket}/{s3_key}", "S3 link does not match expected format"
     
    # Split text into lines
    lines = text.split('\n')
    
    # Create Textract-like JSON structure
    blocks = []
    for idx_line, line in enumerate(lines):
        if line.strip():  # Only include non-empty lines
            block = {
                "BlockType": "LINE",
                "Text": line,
                "Id": f"line_{idx_line}",
                "Confidence": 99.0
            }
            blocks.append(block)
    
    # Upload to S3
    session = boto3.Session(profile_name='739275445236_DataScienceUser')
    s3_client = session.client('s3')
    
    try:
        # Convert to JSON string
        json_content = json.dumps(blocks, ensure_ascii=False, indent=2)
        
        # Upload to S3
        s3_client.put_object(
            Bucket=s3_bucket,
            Key=s3_key,
            Body=json_content.encode('utf-8'),
            ContentType='application/json'
        )
        print(f"[{counter[0]}/{total} | remaining: {remaining}] Uploaded JSON to s3://{s3_bucket}/{s3_key}", end="\r")
    except Exception as e:
        print(f"[{counter[0]}/{total} | remaining: {remaining}] Error uploading JSON: {e}", end="\r")
    
    return True

In [ ]:
_counter = [0]
_total = len(data_textract_new_with_text)
data_textract_new_with_text['upload_result'] = data_textract_new_with_text.apply(
    lambda row: upload_text_as_json_to_s3(row, _counter, _total), axis=1
)

INFO [2026-03-09 13:08:24] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-03-09 13:08:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:08:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:09:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:10:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:11:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:11:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:11:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:17:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:18:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:19:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:20:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:21:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:22:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:23:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:24:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:54] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-03-09 13:25:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:25:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:26:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:37] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-03-09 13:27:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:27:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:28:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:29:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:30:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:32] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-03-09 13:31:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:31:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:32:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:33:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:34:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:35:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:36:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:37:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:47] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:48] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:49] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:50] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:51] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:52] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:53] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:54] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:55] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:56] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:57] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:58] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:38:59] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:00] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:01] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:02] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:03] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:04] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:05] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:06] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:07] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:08] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:09] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:10] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:11] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:12] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:13] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:14] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:15] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:16] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:17] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:18] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:19] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:20] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:21] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:22] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:23] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:24] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:25] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:26] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:27] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:28] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:29] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:30] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:31] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:32] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:33] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:34] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:35] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:36] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:37] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:38] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:39] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:40] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:41] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:42] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:43] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:44] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:45] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:46] - Found credentials in shared credentials file: ~/.aws/credentials

INFO [2026-03-09 13:39:46] - Found credentials in shared credentials file: ~/.aws/credentials

In [40]:
data_textract_new_with_text['upload_result'].value_counts()

upload_result
True    4384
Name: count, dtype: int64