In [1]:
import pandas as pd

# 1) Adding ticket uuid and attachment id to the current dataframe

In [2]:
raw_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [3]:
raw_data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [4]:
attachment_ids = raw_data[~raw_data['attachment_id'].isna()]
attachment_ids

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

This 219 fp protocol data is already in our textract_jobs table, only add them to the llm_ticket_labels. Get theirs ticket uuids from the llm_tickets table

In [5]:
attachment_ids_to_fetch_ticket_uuid = attachment_ids['attachment_id'].tolist()
len(attachment_ids_to_fetch_ticket_uuid)

5383

In [6]:
attachment_ids['attachment_id'].nunique()

5383

In [7]:
attachment_ids['attachment_id'].isna().sum()

np.int64(0)

In [8]:
from python_utilities.db_connection import DbConnection
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
a_id_to_t_id = analytics_db.sql_to_df(f"""
    SELECT la.attachment_id, lt.ticket_uuid
    FROM llm_attachments la LEFT JOIN llm_tickets lt ON la.ticket_uuid = lt.ticket_uuid
    WHERE la.attachment_id IN ({','.join([str(id) for id in attachment_ids_to_fetch_ticket_uuid])})
""")

INFO [2026-03-06 12:59:12] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

AttributeError: Query execution failed:
    SELECT la.attachment_id, lt.ticket_uuid
    FROM llm_attachments la LEFT JOIN llm_tickets lt ON la.ticket_uuid = lt.ticket_uuid

In [9]:
a_id_to_t_id

    attachment_id                           ticket_uuid
0        44529743  4fe9b711-1c87-5072-8cee-30ef653866b7
1        44531561  0d29c484-086e-52c5-8e2d-1225798e8921
2        44689202  606b4c67-602f-5eb1-b278-32e464a5ebbe
3        44707482  92cfa0c5-cc22-5830-af7a-526d17fab297
4        44708172  22f3f9bd-48dd-50fb-aab7-9396d9cc4db2
..            ...                                   ...
207      49736954  15dae806-8d02-518a-bf32-2c51fe3e4792
208      49747921                                  None
209      49775489  5bebc9d4-4923-557a-a3e0-ae948c1396b2
210      49778889  ffa1e6d2-908a-54d7-ab14-d6d6c674bc33
211      49779491  075acea6-2657-55d2-bebd-baaf60f5a26b

[212 rows x 2 columns]

In [10]:
# set ticket uuids in raw data for corresponding attachment ids
raw_data_with_ticket_uuids = raw_data.merge(a_id_to_t_id, on='attachment_id', how='left')

In [11]:
raw_data_with_ticket_uuids.isna().sum()

text                0
object_key       1314
document_type       0
cleaned_text        0
data             4888
is_pfub           308
is_ladung           0
attachment_id    5136
s3_link          5136
ticket_uuid      5164
dtype: int64

In [12]:
len(raw_data_with_ticket_uuids) - raw_data_with_ticket_uuids.isna().sum() # number of NOT NA

text             5355
object_key       4041
document_type    5355
cleaned_text     5355
data              467
is_pfub          5047
is_ladung        5355
attachment_id     219
s3_link           219
ticket_uuid       191
dtype: int64

In [4]:
raw_data_with_ticket_uuids

NameError: name 'raw_data_with_ticket_uuids' is not defined

In [8]:
import uuid
import hashlib


def generate_uuid(text: str, purpose: str) -> str:
    """
    Generate a UUID based on the input text.

    Args:
        text (str): The input text to generate the UUID from.
        purpose (str): The purpose for which the UUID is being generated.


    Returns:
        str: A UUID string generated from the input text and purpose.
    """
    # n = min(len(text), len(text), 5000)  # Limit to first 100 characters
    # text = text[:n]  # Limit the text to the first 100 characters
    signature = f"{purpose}:{text}"
    # Use nil UUID as namespace (compatible with all Python versions)
    nil_namespace = uuid.UUID('00000000-0000-0000-0000-000000000000')
    return str(uuid.uuid5(nil_namespace, signature))



def generate_hash_from_text(text: str) -> str:
    # n = min(len(text), 5000)  # Limit to first 1000 characters
    # text = text[:n]  # Limit the text to the first 1000 characters
    """Generate SHA-256 hash from text string"""
    return hashlib.sha256(text.encode('utf-8')).hexdigest()

def extract_filename_from_object_key(object_key: str) -> str:
    if pd.isna(object_key):
        return None
    return object_key.split('/')[-1]

def extract_s3_key(row):
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    base = "ocr_source_files"
    date_folder = created_at.split(' ')[0]  # Extract date part: YYYY-MM-DD
    egvp_id = row["egvp_id"]
    egvp_folder = f"egvp_id_{egvp_id}"
    full_path = f"{base}/{date_folder}/{egvp_folder}/{row['file_name']}"
    return full_path

add ticket_uuid

In [9]:
raw_data['ticket_uuid'] = raw_data.apply(lambda row: generate_uuid(row['text'], purpose="ticket_uuid"), axis=1)

In [10]:
raw_data.shape

(5462, 12)

In [11]:
# only apply generate uuid if attachment_id lenght is 36

raw_data['attachment_id'] = raw_data.apply(lambda row: generate_uuid(row['text'], purpose="attachment_id") if pd.isna(row['attachment_id']) == True or len(row['attachment_id']) == 36 else row['attachment_id'], axis=1)

In [14]:
# drop ticket uuid duplicates, keep the first occurrence
raw_data = raw_data.drop_duplicates(subset=['ticket_uuid'], keep='first')

In [17]:
raw_data.attachment_id.is_unique

True

In [ ]:
# raw_data.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

In [ ]:
raw_data_with_ticket_uuids['ticket_uuid'] = raw_data_with_ticket_uuids.apply(lambda row: generate_uuid(row['text'], purpose="ticket_uuid") if pd.isna(row['ticket_uuid']) == True else row['ticket_uuid'], axis=1)

add attachment_id

In [22]:
raw_data_with_ticket_uuids['attachment_id'] = raw_data_with_ticket_uuids.apply(lambda row: generate_uuid(row['text'], purpose="attachment_id") if pd.isna(row['attachment_id']) == True else row['attachment_id'], axis=1)

In [23]:
raw_data_with_ticket_uuids['attachment_id'].isna().sum()

np.int64(0)

add textract related fields

In [24]:
raw_data_with_ticket_uuids['textract_job_id'] = raw_data_with_ticket_uuids['text'].apply(lambda x: generate_hash_from_text(x))
raw_data_with_ticket_uuids['textract_s3_link'] = raw_data_with_ticket_uuids['textract_job_id'].apply(lambda x: f"s3://pair-data-engineering-new/ocr_prepared_output/{x}.json")

In [26]:
raw_data_with_ticket_uuids['textract_job_id'].isna().sum(), raw_data_with_ticket_uuids['textract_s3_link'].isna().sum()

(np.int64(0), np.int64(0))

In [28]:
new_column_order = ['ticket_uuid', 'attachment_id'] + [col for col in raw_data_with_ticket_uuids.columns if col not in ['ticket_uuid', 'attachment_id']]
raw_data_with_ticket_uuids = raw_data_with_ticket_uuids[new_column_order]

In [29]:
raw_data_with_ticket_uuids

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,937b5e2e-f3b3-56bd-9225-f67840039ee1,8e6a76c1-34ed-5fe0-9144-bbd00e1cddd8,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,7e7ac68d-b2df-50d2-963d-200aa44b036b,417ecde8-b807-5de4-b066-f70f811c8f6a,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,2d315b63-cb84-56ef-bb02-af6c13dff49b,acc1f4fa-6891-58d3-a3d1-d3f3e54d93ba,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,dc9e9a0c-12a6-5b22-b6c0-52f1647505a2,cfc4d684-af88-506e-8fdb-39984cf93640,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,6abb8d66-912f-55bb-9b05-50dbd5c6a6f7,ccf92577-4ae3-505d-97eb-25c49e6fbc12,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5350,2bd93acd-08cd-5d66-9d0e-c72b3e1da733,0bd71681-f525-5f65-83eb-952e605409f3,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,False,False,NaN,ea578e5a3589fc0c5b640d644d57e917f384c0458f08ef...,s3://pair-data-engineering-new/ocr_prepared_ou...
5351,079a8404-edb0-5660-8722-8d46098ae215,8e8ef642-2c7a-5bdb-810b-48344c2a235a,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"paul-rohland-str.2\n06712 zeitz, elster\ntel. ...",NaN,False,False,NaN,dd4d8ce69f0e90db975a425b96b6c6515f56e912df606c...,s3://pair-data-engineering-new/ocr_prepared_ou...
5352,3321bf02-b3dd-592e-b0c6-e129b3719312,d47fad4c-772a-5f89-80c0-5ac9638b9e7e,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,wolfgang lurz\nschragenhofstraße 27\n80992 mün...,NaN,False,False,NaN,ce565a09de5e250d5545b02d2a482a08806b1df497e3cd...,s3://pair-data-engineering-new/ocr_prepared_ou...
5353,f5bdf478-897e-5da6-8669-f835dfcb9a38,ec52a8de-3bf8-5660-8501-414aebade679,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\n33104 paderborn\nwagen...,NaN,False,False,NaN,3aa213ac35184d2007d9386ad4f8b0f5b502ab1cb36b7d...,s3://pair-data-engineering-new/ocr_prepared_ou...
5354,d801cd78-4ff3-57ad-beab-cf574fbf4c73,76ee1429-e30e-5faa-8875-d3ba850bb4fa,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,False,False,NaN,6a0e3e72c6c47a6197ebd35a748ed1df71fc813d1568c5...,s3://pair-data-engineering-new/ocr_prepared_ou...

save raw df with new columns, update the data with dvc

In [30]:
# raw_data_with_ticket_uuids.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

# 2) Scripts to add raw data to tables

Inter into llm_label_defs

In [31]:
labels = list(raw_data_with_ticket_uuids['document_type'].unique())
labels

['attachment_and_transfer_order',
 'ladung_va',
 'approved_attachment_and_transfer_order',
 'contradiction',
 'approved_seizure',
 'fp_invoice',
 'court_inbox',
 'enforcement_order',
 'monierung_mb',
 'vermögensverzeichnis',
 'mail_attachments',
 'fp_protocol',
 'bailiff_ip']

### 2.1) INSERT INTO llm_labels_defs

In [ ]:
# label id is auto increment, we can diretly add label to the labels table

In [32]:
def insert_labels_to_db(labels: list, connection=None):
    subtype = 'none'
    nature = 'aftercourt'
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    for label in labels:
        # query = """INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
        #            VALUES (%s, %s, %s, %s, %s, NULL);"""
        query = f"""INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('{label}', '{subtype}', '{nature}', '{created_at}', '{updated_at}', NULL);"""
        print(f"{Colors.CYAN}label:{Colors.END} {Colors.CYAN}{Colors.BOLD}{label}{Colors.END}")
        print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
        print("-"*100)
        # Use parameterized query with your DB cursor
        #cursor.execute(query, (label, subtype, nature, created_at, updated_at))
insert_labels_to_db(labels)

label: attachment_and_transfer_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('attachment_and_transfer_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: ladung_va
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('ladung_va', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: approved_attachment_and_transfer_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('approved_attachment_and_transfer_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: contradiction
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('contradiction', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: approved_seizure
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('approved_seizure', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: fp_invoice
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('fp_invoice', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: court_inbox
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('court_inbox', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: enforcement_order
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('enforcement_order', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: monierung_mb
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('monierung_mb', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: vermögensverzeichnis
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('vermögensverzeichnis', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: mail_attachments
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('mail_attachments', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: fp_protocol
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('fp_protocol', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------
label: bailiff_ip
Query: INSERT INTO llm_label_defs (type, subtype, nature, created_at, updated_at, datatype)
                   VALUES ('bailiff_ip', 'none', 'aftercourt', '2026-03-02 11:50:10', '2026-03-02 11:50:10', NULL);
----------------------------------------------------------------------------------------------------

### 2.2) Insert into llm_ticket_labels

In [34]:
# first creaete label name label id mapping by checking the llm label defs

In [38]:
label_to_id_mapping = {}

for lbl in labels:
    # query = "SELECT id FROM llm_label_defs WHERE type = %s AND subtype = 'none' AND nature = 'aftercourt';"
    # cursor.execute(query, (lbl,))
    query = f"SELECT id FROM llm_label_defs WHERE type = '{lbl}' AND subtype = 'none' AND nature = 'aftercourt';"
    # result = cursor.fetchone()
    # if result:
    #     label_to_id_mapping[lbl] = result[0]
    # dummy mapping
    label_to_id_mapping[lbl] = hash(lbl) % 1000  # Replace with actual ID from DB
label_to_id_mapping

{'attachment_and_transfer_order': 17,
 'ladung_va': 223,
 'approved_attachment_and_transfer_order': 483,
 'contradiction': 70,
 'approved_seizure': 715,
 'fp_invoice': 492,
 'court_inbox': 612,
 'enforcement_order': 580,
 'monierung_mb': 49,
 'vermögensverzeichnis': 593,
 'mail_attachments': 675,
 'fp_protocol': 435,
 'bailiff_ip': 863}

In [41]:
def insert_into_llm_ticket_labels(row):
    label = row['document_type']
    ticket_uuid = row['ticket_uuid']
    zendesk_id = None
    comment_id = None
    attachment_id = row['attachment_id']
    label_id = label_to_id_mapping.get(label)
    value = "True"
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    
    assert label_id is not None, f"label_id cannot be None for label: {label}"
    assert ticket_uuid is not None, f"ticket_uuid cannot be None for attachment_id: {attachment_id}"
    assert attachment_id is not None, f"attachment_id cannot be None for ticket_uuid: {ticket_uuid}"
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BLUE = '\033[94m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    # query = """INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
    #            VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"""
    query = f"""INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('{ticket_uuid}', NULL, NULL, '{attachment_id}', {label_id}, '{value}', '{created_at}', '{updated_at}');"""
    print(f"{Colors.CYAN}ticket_uuid:{Colors.END} {Colors.CYAN}{Colors.BOLD}{ticket_uuid}{Colors.END} | "
          f"{Colors.GREEN}label:{Colors.END} {Colors.GREEN}{Colors.BOLD}{label}{Colors.END} | "
          f"{Colors.BLUE}label_id:{Colors.END} {Colors.BLUE}{Colors.BOLD}{label_id}{Colors.END}")
    print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
    print("-"*100)
    return True
    
# Apply the function to each row in the DataFrame
test = raw_data_with_ticket_uuids.sample(3,random_state=42)
test.apply(insert_into_llm_ticket_labels, axis=1)

ticket_uuid: b454a46e-dd84-5ba5-8832-4ff24b7c14c8 | label: mail_attachments | label_id: 675
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('b454a46e-dd84-5ba5-8832-4ff24b7c14c8', NULL, NULL, 'af878f5f-0c17-514c-9225-315e9347cf28', 675, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------
ticket_uuid: 8775beb9-791b-54e7-b8ee-f7c58f78e2bf | label: ladung_va | label_id: 223
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('8775beb9-791b-54e7-b8ee-f7c58f78e2bf', NULL, NULL, '9ce88f72-6e35-5105-b8dc-aed0e4802e39', 223, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------
ticket_uuid: 0dc12f74-3a28-5114-ad48-4faf8876c1c2 | label: court_inbox | label_id: 612
Query: INSERT INTO llm_ticket_labels (ticket_uuid, zendesk_id, comment_id, attachment_id, label_id, value, created_at, updated_at)
               VALUES ('0dc12f74-3a28-5114-ad48-4faf8876c1c2', NULL, NULL, 'b215f94d-b874-5dd5-be1c-c2869806546e', 612, 'True', '2026-03-02 12:09:26', '2026-03-02 12:09:26');
----------------------------------------------------------------------------------------------------

5010    True
1650    True
401     True
dtype: bool

### 2.3) Insert into textract_jobs

In [40]:
test.columns

Index(['ticket_uuid', 'attachment_id', 'text', 'object_key', 'document_type',
       'cleaned_text', 'data', 'is_pfub', 'is_ladung', 's3_link',
       'textract_job_id', 'textract_s3_link'],
      dtype='object')

In [42]:
def uplaod_text_as_json_to_s3(row):
    """
    Upload text as Textract-formatted JSON to S3.
    Reverse engineers the Textract output format from plain text.
    """
    import boto3
    import json
    
    text = row['text']
    textract_s3_link = row['textract_s3_link']
    s3_bucket = "pair-data-engineering-new"
    textract_job_id = row['textract_job_id']
    
    # Parse s3 link: s3://bucket/path/to/file.json
    # Extract key from textract_s3_link
    s3_key = f"ocr_prepared_output/{textract_job_id}.json"
    
    assert textract_s3_link == f"s3://{s3_bucket}/{s3_key}", "S3 link does not match expected format"
     
    # Split text into lines
    lines = text.split('\n')
    
    # Create Textract-like JSON structure
    blocks = []
    for idx, line in enumerate(lines):
        if line.strip():  # Only include non-empty lines
            block = {
                "BlockType": "LINE",
                "Text": line,
                "Id": f"line_{idx}",
                "Confidence": 99.0
            }
            blocks.append(block)
    
    # Upload to S3
    # session = boto3.Session(profile_name='739275445236_DataScienceUser')
    # s3_client = session.client('s3')
    
    try:
        # Convert to JSON string
        json_content = json.dumps(blocks, ensure_ascii=False, indent=2)
        
        # Upload to S3
        # s3_client.put_object(
        #     Bucket=s3_bucket,
        #     Key=s3_key,
        #     Body=json_content.encode('utf-8'),
        #     ContentType='application/json'
        # )
        print(f"Uploaded JSON to s3://{s3_bucket}/{s3_key}")
    except Exception as e:
        print(f"Error uploading JSON: {e}")
    
    return True

def insert_into_textract_jobs(row):
    job_id = row['textract_job_id']
    status = "SUCCEEDED"
    s3_link = row['textract_s3_link']
    created_at = pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')
    updated_at = created_at
    attachment_id = row['attachment_id']
    
    # ANSI color codes
    class Colors:
        CYAN = '\033[96m'
        GREEN = '\033[92m'
        YELLOW = '\033[93m'
        BLUE = '\033[94m'
        BOLD = '\033[1m'
        END = '\033[0m'
    
    # query = """INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
    #            VALUES (%s, %s, %s, %s, %s, %s);"""
    query = f"""INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('{job_id}', '{status}', '{s3_link}', '{created_at}', '{updated_at}', '{attachment_id}');"""
    print(f"{Colors.CYAN}job_id:{Colors.END} {Colors.CYAN}{Colors.BOLD}{job_id}{Colors.END} | "
          f"{Colors.GREEN}attachment_id:{Colors.END} {Colors.GREEN}{Colors.BOLD}{attachment_id}{Colors.END} | "
          f"{Colors.BLUE}status:{Colors.END} {Colors.BLUE}{Colors.BOLD}{status}{Colors.END}")
    print(f"{Colors.YELLOW}Query:{Colors.END} {query}")
    print("-"*100)

    return True

test.apply(insert_into_textract_jobs, axis=1)

job_id: 8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316 | attachment_id: af878f5f-0c17-514c-9225-315e9347cf28 | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', 'af878f5f-0c17-514c-9225-315e9347cf28');
----------------------------------------------------------------------------------------------------
job_id: 330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a | attachment_id: 9ce88f72-6e35-5105-b8dc-aed0e4802e39 | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', '9ce88f72-6e35-5105-b8dc-aed0e4802e39');
----------------------------------------------------------------------------------------------------
job_id: fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3 | attachment_id: b215f94d-b874-5dd5-be1c-c2869806546e | status: SUCCEEDED
Query: INSERT INTO textract_jobs (job_id, status, s3_link, created_at, updated_at, attachment_id)
               VALUES ('fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3', 'SUCCEEDED', 's3://pair-data-engineering-new/ocr_prepared_output/fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3.json', '2026-03-02 12:15:07', '2026-03-02 12:15:07', 'b215f94d-b874-5dd5-be1c-c2869806546e');
----------------------------------------------------------------------------------------------------

5010    True
1650    True
401     True
dtype: bool

### 3) uploading texts as JSON FILE to the textract s3 link

In [43]:

test.apply(uplaod_text_as_json_to_s3, axis=1)

Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/8c08ecb91d62f22ffa1c8bb0f6d3aa0bc54b5d6329151b2014ca10baf6010316.json
Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/330c1bde2c046864e8b96137599785c8377caf83ab11e34c121f67d092827a4a.json
Uploaded JSON to s3://pair-data-engineering-new/ocr_prepared_output/fddfdded13ae257c4f75920ecdd30ef4b7de106428f3613a4325110ba1aef0d3.json

5010    True
1650    True
401     True
dtype: bool