In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [3]:
data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice,is_va
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,NaN,NaN,False
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,NaN,NaN,False
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,NaN,NaN,False
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,NaN,NaN,False
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5581,50143302-3ac3-587b-ae25-047d34d94750,99d61bd2-665c-59b1-a24d-264f41c2f474,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,93e56ec1cfb7719bf463bf44585e833cdd56fb9689d4f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,False
5582,de97e37c-ebf7-5c0e-92be-209db058d9ae,60913326-3481-573b-a96e-72bb2ca9a9ef,Anne-Katrin Götz\nAmtsgericht Dortmund\nOberg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,anne-katrin götz\namtsgericht dortmund\noberge...,NaN,False,False,NaN,870b8fd6e0da13bafd14ed6e5cec7e79af8c7ae43cae66...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnne-Katrin Götz\nAmtsgericht Dortmu...,False,False
5583,c72625b3-d66a-5df5-a933-11f57215838a,2a6e990a-3458-5efe-a8d9-f8b988af1740,Obergerichtsvollzieherin G. Samuels\nHESSEN\n...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieherin g. samuels\nhessen\nb...,NaN,False,False,NaN,6eb9335329883f671aa167608aa4108d45a5e0fcbbbb86...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin G. Samuels\...,False,False
5584,9d233a96-2fd2-5f56-ab60-58043398223d,f8f00142-5ef8-5940-8ec0-f211617274d8,Gerichtsvollzieherin\nKreuzgasse 17\nL. Lutz\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\nkreuzgasse 17\nl. lutz\n...,NaN,False,False,NaN,0d1359e435b18356222e26c4fc1eeb79c53373771c782b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nKreuzgasse 17\...,False,False
5585,0b1316ce-ff2c-5eba-b454-9d711aa46703,55949b14-c976-5567-abf4-cc169de245ec,Obergerichtsvollzieherin Evelyn Häp\nbeim Amt...,data/aftercourt/drittauskunf_with_invoice/hard...,neg_drittauskunft_hard,obergerichtsvollzieherin evelyn häp\nbeim amts...,NaN,False,False,NaN,f802828a42581642cac6aff41d05e6723e1d258050d1a1...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,True,False

In [4]:
data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           523
court_inbox                                346
fp_protocol                                220
fp_invoice                                 106
vermögensverzeichnis                        75
drittauskunft                               71
approved_attachment_and_transfer_order      64
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
va_dritt_invoice_protokol_combination       18
contradiction                                3
neg_drittauskunft_hard                       1
Name: count, dtype: int64

In [5]:
dritt = data[data['document_type'] == 'drittauskunft']

In [6]:
dritt

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice,is_va
1344,c518854d-2f65-53af-a4b3-d8b62df46502,e4b3c249-4de5-5cee-8e8f-32bd8ad0b5d9,"Gabriele Kruse\nKönigstraße 11, Zi EG 005\nObe...",11.12.2024/ocr-v2_Dokumente_45924_10122024_112...,drittauskunft,"gabriele kruse\nkönigstraße 11, zi eg 005\nobe...",NaN,False,False,NaN,292d99228bc98d5911d52d718ad555c152b3833d968164...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
5223,ca025357-d3f5-5b97-a780-a4725e3d6239,6cd033bf-c19e-53d4-af67-c5157c19991e,Svea Rietschek\nVolksparkstraße 52\nObergerich...,NaN,drittauskunft,svea rietschek\nvolksparkstraße 52\nobergerich...,NaN,False,False,NaN,6c3cea7cd3eb08d8d6f92e35bb0e258a9f3f35d271df94...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
5225,829321fd-6887-5d66-ab91-eedbf535ca14,b891083a-0024-5b8e-8e74-3caa640f800b,Gerichtsvollzieher P. Harig\nAmtsgericht Salzg...,NaN,drittauskunft,gerichtsvollzieher p. harig\namtsgericht salzg...,NaN,False,False,NaN,14ad5838a1ecaae3b006a095d34f7d678311ab50cb4abb...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
5254,8758f08b-eb4f-5d02-b9c4-6d06e6208f7b,1ada309d-2f0a-5f7c-b184-b356624cc518,Obergerichtsvollzieherin G. Samuels\nHESSEN\nb...,NaN,drittauskunft,obergerichtsvollzieherin g. samuels\nhessen\nb...,NaN,False,False,NaN,30b2fe3d8d382e7e79fd5515b6245e68cbb9e86821bd7d...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
5288,f5dfd4ef-5165-5a8e-96b2-e91be357b220,51643880,Gerichtsvollzieherin beim Amtsgericht Waibling...,NaN,drittauskunft,gerichtsvollzieherin beim amtsgericht waibling...,NaN,False,False,NaN,40c743dda99e173c9fbe465f029efa037f3f22b3cf344d...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5580,4f6c9081-0928-527c-9356-943ba2237293,e3a0150a-cdb8-5a9c-be4a-0f5603361356,R. Müller\nObergerichtsvollzieher\nLerchenweg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,r. müller\nobergerichtsvollzieher\nlerchenweg ...,NaN,False,False,NaN,fe02c9970e549b20806d238d71c0adfe8a6f3dccdf820a...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nR. Müller\nObergerichtsvollzieher\nL...,False,False
5581,50143302-3ac3-587b-ae25-047d34d94750,99d61bd2-665c-59b1-a24d-264f41c2f474,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,93e56ec1cfb7719bf463bf44585e833cdd56fb9689d4f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,False
5582,de97e37c-ebf7-5c0e-92be-209db058d9ae,60913326-3481-573b-a96e-72bb2ca9a9ef,Anne-Katrin Götz\nAmtsgericht Dortmund\nOberg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,anne-katrin götz\namtsgericht dortmund\noberge...,NaN,False,False,NaN,870b8fd6e0da13bafd14ed6e5cec7e79af8c7ae43cae66...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnne-Katrin Götz\nAmtsgericht Dortmu...,False,False
5583,c72625b3-d66a-5df5-a933-11f57215838a,2a6e990a-3458-5efe-a8d9-f8b988af1740,Obergerichtsvollzieherin G. Samuels\nHESSEN\n...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieherin g. samuels\nhessen\nb...,NaN,False,False,NaN,6eb9335329883f671aa167608aa4108d45a5e0fcbbbb86...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin G. Samuels\...,False,False
5584,9d233a96-2fd2-5f56-ab60-58043398223d,f8f00142-5ef8-5940-8ec0-f211617274d8,Gerichtsvollzieherin\nKreuzgasse 17\nL. Lutz\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\nkreuzgasse 17\nl. lutz\n...,NaN,False,False,NaN,0d1359e435b18356222e26c4fc1eeb79c53373771c782b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nKreuzgasse 17\...,False,False

In [7]:
dritt = dritt[dritt['object_key'].isnull() == False]

In [8]:
dritt

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice,is_va
1344,c518854d-2f65-53af-a4b3-d8b62df46502,e4b3c249-4de5-5cee-8e8f-32bd8ad0b5d9,"Gabriele Kruse\nKönigstraße 11, Zi EG 005\nObe...",11.12.2024/ocr-v2_Dokumente_45924_10122024_112...,drittauskunft,"gabriele kruse\nkönigstraße 11, zi eg 005\nobe...",NaN,False,False,NaN,292d99228bc98d5911d52d718ad555c152b3833d968164...,s3://pair-data-engineering-new/ocr_prepared_ou...,False,NaN,NaN,False
5532,a338ba12-5c7b-5f29-a4a8-474e049cc3a9,3d667522-5dd5-504c-ba5e-705c680e06bc,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,20bd93c565add2380243bc51e5f7add4a64ba56de1c53b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False
5533,fe565737-faf8-56e4-89fd-c07e1c6945c8,0ec59f78-6ea5-5085-88ae-1367f3f02895,Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st ii 4 s 0229a kevizz 2948091/2...,NaN,False,False,NaN,02d84a0862273ee852cb5eaa1a42830cb8f5289e9ff7c4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St II 4 S 0229a KEVIZZ...,True,False
5534,d87c35ce-1ba8-50dc-8338-7c3617b82d94,c322aca7-829a-5739-a1fe-a6d62684096a,Thomas Vetter\nJohann-Ruland-Weg 9\nGerichtsv...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,thomas vetter\njohann-ruland-weg 9\ngerichtsvo...,NaN,False,False,NaN,0892385a2609eda3c819ff07752cf6e019f59f5e62ffcb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nThomas Vetter\nJohann-Ruland-Weg 9\n...,True,False
5535,f9e9c3ec-afa7-5b17-a7ea-c950316713e2,546a42f3-85f4-5645-8765-63a4674024c9,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,990b7b5bbe92cfad9a1cb3cc98e829a195d2c010184156...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
5536,74c3a533-a8f0-5810-9ef1-e9e8458e9acc,f4d60c17-b34e-591d-b40f-a6beb4af8f0e,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,42967236e1da6c2ab8adb01acae2b024bb2430321f98e9...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False
5537,9f1f97e4-6fda-59ce-ae11-d5cf8d33fc7d,1b809711-e91d-5c49-a833-617bc4c7157f,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,2cc33385616966742d97d6d4d902e726c43a51f68039c0...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
5538,ba9b1fcd-81a8-51d4-a593-7f9b043236a2,acd659dc-1c2e-59fb-b29e-56cd3e95f4eb,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,bd08800d05ff7cf06ea333a5853b3ee7fd193fa516eb1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
5539,d9769e49-a43e-596f-996e-c8e49e83eaa9,a0366e06-b52c-5688-abcf-73903007cff4,Daniel Arlt\nUlrich-Kaegerl-Straße 5\nOberger...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,daniel arlt\nulrich-kaegerl-straße 5\nobergeri...,NaN,False,False,NaN,b616e8dfca3e65160d12b4d1c3275a96cc08c88b28aa28...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nDaniel Arlt\nUlrich-Kaegerl-Straße 5...,True,False
5540,6bd2cc0f-a888-526b-aa60-b2d5a1d94fc3,d8a8266a-5c3c-5730-adbd-9c54c847114e,Obergerichtsvollzieherin\nAmtsgericht Wolfsbu...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,obergerichtsvollzieherin\namtsgericht wolfsbur...,NaN,False,False,NaN,76eca03570ad86e15010fed9b2b2c6bd6b85261dcb5cb4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,True,False
5541,7a03718a-ec4b-5b8a-82e7-b5552c2bd503,67af9e85-cb23-5c5f-83ca-5ef343cf7614,Obergerichtsvollzieherin Evelyn Häp\nbeim Amt...,data/aftercourt/drittauskunf_with_invoice/B_DR...,drittauskunft,obergerichtsvollzieherin evelyn häp\nbeim amts...,NaN,False,False,NaN,6fc5a49ff23022f380aedbc73c3195cc9a7badfe5367ff...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,True,False
5542,ee911740-6c51-555d-a15f-79f118cd2e6d,90c0e66d-dbd2-5280-bb2b-82bc78232cac,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,82b95f3d2aae8ee732c8317475b65e2750a87f7fcea6af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
5543,d088fb8f-1da9-5f39-b888-37e7e49546f2,fefbb6bc-f262-500b-bddb-c849f70b6617,Kriegsstr. 65\nCLAUDIUS BETZLER\n76133 Karlsr...,data/aftercourt/drittauskunf_with_invoice/RB_0...,drittauskunft,kriegsstr. 65\nclaudius betzler\n76133 karlsru...,NaN,False,False,NaN,8662e0774a9bf64508058ebb4e3b646c74cd1e7f55a798...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nKriegsstr. 65\nCLAUDIUS BETZLER\n761...,True,False
5544,88325ce5-a859-5af9-8230-c01d51a1e539,934c4ff6-bf58-57cf-950b-9450b8bd1057,Obergerichtsvollzieher Frank Pergande\nBüroan...,data/aftercourt/drittauskunf_with_invoice/3_dr...,drittauskunft,obergerichtsvollzieher frank pergande\nbüroans...,NaN,False,False,NaN,6a8e6692235472796470ce5e96cb6b9d1b4dd1e45d496b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Pergand...,True,False
5545,9c129614-774b-58c1-bafd-d3f8b7890f85,6259ffbb-7549-54f1-8dab-53d58eee852b,Gerichtsvollzieherin beim Amtsgericht Eisenac...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,gerichtsvollzieherin beim amtsgericht eisenach...,NaN,False,False,NaN,c36bf9e79340f11d66093a12314c0758e13a3d7a6386af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin beim Amtsgerich...,True,False
5546,421c6599-37a0-5822-8d21-11de81eadee9,1ccc264b-566c-535f-a5aa-d2ea89e8547f,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,481d84aab52bb306dd926fb8952770634cac437de5d388...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
5547,8bef37cf-75b1-502a-b58b-1f05b1486e59,6d1b3bcc-8292-55f9-b37d-24560889de92,Gerichtsvollzieherin Antje Netzband\nAmtsgeri...,data/aftercourt/drittauskunf_with_invoice/KL_0...,drittauskunft,gerichtsvollzieherin antje netzband\namtsgeric...,NaN,False,False,NaN,5227c8222ab9fef267d0c18b0baa43cfd78156d2a0858e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin Antje Netzband\...,True,False
5548,7d4731b1-c146-50f0-8546-10754fefb7b4,f3e9c4f8-514e-5e40-b087-a28fb26d7d69,Obergerichtsvollzieher\n66292 Riegelsberg\nSt...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieher\n66292 riegelsberg\nste...,NaN,False,False,NaN,f29cf02fa0b1aca7ea815c19721e59405a7b5709a51440...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\n66292 Riegel...,True,False
5549,fdddcd76-8ff6-5677-b86b-0a50548c40ee,cc89240e-f2d4-5f0b-b8ae-a8d52bb6833d,Obergerichtsvollzieherin\nAnschrift\nPäßler R...,data/aftercourt/drittauskunf_with_invoice/Dr_1...,drittauskunft,obergerichtsvollzieherin\nanschrift\npäßler ra...,NaN,False,False,NaN,0eb7536021829c1555b3b5b46fc1f68d38a4792fd630de...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAnschrift\...,True,False
5550,359c370c-9c55-5178-9759-f195873f5c1d,d125ddc2-1145-5c21-947e-09c2d7d29792,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,b05af004fe90d19d2d829adeaa742287e882e3a3850730...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False
5551,56255120-f80b-5f28-8aab-1ebfcb4eb1d2,b1619e05-0674-5cfd-8e65-0ced9af2a582,Nicole Sommer\nKönigstr. 11\nGerichtsvollzieh...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,nicole sommer\nkönigstr. 11\ngerichtsvollziehe...,NaN,False,False,NaN,890ef069a6eec24f13a3bee665a504f30fe08567ba02f4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNicole Sommer\nKönigstr. 11\nGericht...,True,False
5552,6c04d43f-e9b1-5060-a309-6e011d0966ee,238a5666-fa3d-5bdb-b21d-083701f6a179,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,385b3545abfb7b0113a51dde5a6f260e43767704356acf...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False
5553,5a5eb696-42dc-5c79-b7fe-d729949ab720,d02cf7d3-9e98-504e-8d40-8d3665b8709c,Anlage zu GZ: St Il 4 - S 0229a KEVIZZ 280992...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st il 4 - s 0229a kevizz 2809922...,NaN,False,False,NaN,d86a7149a0fd5c63d91f164e44069726b338098f6d9928...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,True,False
5554,688ff55a-847d-553d-9ccf-49d8a4952480,ddec9621-abfc-5930-9e29-5bcc4214c576,Gerichtsvollzieherin\nMozartstraße 57\nV. Rup...,data/aftercourt/drittauskunf_with_invoice/1_sa...,drittauskunft,gerichtsvollzieherin\nmozartstraße 57\nv. rupp...,NaN,False,False,NaN,b64212be8a46358e539acd3435ea5c5b52461256f03a10...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nMozartstraße 5...,True,False
5555,b2b75267-7a21-5120-b909-5c448c1382d9,947820aa-481c-5447-bcfc-646834c2a34a,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,93d7eb28bf63f36ae24557834751cf47d2cdb256391076...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
5556,9aeb7314-a214-556a-ace8-6657d6f4b0c6,d9ba7c3c-a5e6-59a3-823b-c672855e4a34,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,fd1cfd1579a91cf23869999c9ef106f1522f60c30e64d6...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
5557,d2b3ca58-b8b9-58bb-9527-8bba49ea1c50,516d518e-33dd-5a69-b1b6-1b7fa89d3819,Obergerichtsvollzieherin\nEuropaplatz 11\nBea...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieherin\neuropaplatz 11\nbeat...,NaN,False,False,NaN,09bc758a37185c8fc3dd37c6648b712cc1e6f06597def2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nEuropaplat...,True,False
5558,aa7e27d2-0962-5d93-99d6-9d278a2411e3,ef376efd-2805-5742-a6cf-d13118d7db83,Gerichtsvollzieherin\nAmtsgericht: Besigheim\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\namtsgericht: besigheim\n...,NaN,False,False,NaN,3c63835fd0cbf6a7d3bea27dd388b74395287544adfac7...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nAmtsgericht: B...,False,False
5559,472c6cb2-5c1e-51c2-8767-ba1785af8ec5,10e09d46-9c80-5667-b087-25f32d1d8ae7,Gerichtsvollzieherin\nPostfach 60 02 11\nS. C...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\npostfach 60 02 11\ns. cz...,NaN,False,False,NaN,fd409356ed3d32e300a993543d8c2321d086d16069042e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nPostfach 60 02...,False,False
5560,d9f6ba15-63cf-5743-aa24-12f26140ace4,8b976e45-a27a-5f35-8f19-9c04a4a315bb,Neue Büroanschrift ab 01.12.2024\nDortmunder ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,neue büroanschrift ab 01.12.2024\ndortmunder s...,NaN,False,False,NaN,1d6062807bfb02abacfe2291ee4b68bcd1568d401b1acd...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNeue Büroanschrift ab 01.12.2024\nDo...,False,False
5561,352168c8-d418-5023-bfa1-f6c53a62e738,8af270a0-0aac-5f09-be68-40ce4bf1b041,Obergerichtsvollzieher\nHellersdorfer Weg 35\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieher\nhellersdorfer weg 35\n...,NaN,False,False,NaN,db6f409de21c9073aba585d6eb9d1e037633723e7ec830...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\nHellersdorfe...,False,False
5562,689055a0-23e6-5af1-bbfa-2dc208380567,3c2aa637-6910-504e-adff-0d6814cb0e87,Sylvia Niemeyer\nSchloßstraße 4\nObergerichts...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sylvia niemeyer\nschloßstraße 4\nobergerichtsv...,NaN,False,False,NaN,455cdfc2250320db433f7f2324a8355fc6f83557dfc3cb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSylvia Niemeyer\nSchloßstraße 4\nObe...,False,False
5563,a41f131d-7986-595c-b943-01439213fd89,62ed43ec-7d21-50d6-8e04-f6fe6bf168f9,Hauptgerichtsvollzieherin\nBüroanschrift\nFis...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,hauptgerichtsvollzieherin\nbüroanschrift\nfisc...,NaN,False,False,NaN,f5cd426ec871f7ac33d131d363bf7d85992b0dde9f2552...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nHauptgerichtsvollzieherin\nBüroansch...,False,False
5564,6eb5c07e-a206-5919-955f-d428768b9809,91aafd57-92de-5836-8418-0be4ebc9184d,"J. RIEGER\n89522 Heidenheim, Helmut-Bornef.-S...",data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,"j. rieger\n89522 heidenheim, helmut-bornef.-st...",NaN,False,False,NaN,d20c39d45436fb61ac7b26682a23dd8d6e7e8a18561653...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,"<page_1>\nJ. RIEGER\n89522 Heidenheim, Helmut-...",False,False
5565,fb4da508-93a4-585d-92ad-3cdd1e18cebd,72cc879b-455c-5fce-ba10-ada75a9c5063,N. Stenzel\nBlücherstraße 4\nGerichtsvollzieh...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,n. stenzel\nblücherstraße 4\ngerichtsvollziehe...,NaN,False,False,NaN,a37267c34d030a60a52af7376b12821937769babe846f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nN. Stenzel\nBlücherstraße 4\nGericht...,False,False
5566,43d92153-88ce-58b5-96cc-67b1f4c902dc,55d76158-1190-5c2c-b58a-fa2252117f16,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,d2a52b5ed580d39427974c22e0db6e655a59b07917ff12...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,False
5567,75d73218-6ac8-5f94-a8f1-9f6a122380f2,c312e6ec-6dae-5678-a3b5-b1d44c83af27,Marion Kruska\nLilly-Reich-Str. 5\nObergerich...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,marion kruska\nlilly-reich-str. 5\nobergericht...,NaN,False,False,NaN,c6242bd1d2b93a40afd2545cd44978efa7725779657e5c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nMarion Kruska\nLilly-Reich-Str. 5\nO...,False,False
5568,7475a344-7ab3-57bc-bc8d-5f86383999c6,b0e18f73-edca-5274-ac00-49084feb812f,Amtsgericht Mülheim-Ruhr\nObergerichtsvollzie...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,amtsgericht mülheim-ruhr\nobergerichtsvollzieh...,NaN,False,False,NaN,36c6316fbad13336601c8cea7de3400441f58a1b663513...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAmtsgericht Mülheim-Ruhr\nObergerich...,False,False
5569,09429949-63cc-5c52-8af9-6b81c3062509,c0c5e5d3-6663-57b5-9179-e019e22f61b4,Sandra Zander\nObergerichtsvollzieherin beim ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sandra zander\nobergerichtsvollzieherin beim a...,NaN,False,False,NaN,d44bf47d96ddc744395178e205b3ac70a234a4a0c8dee2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSandra Zander\nObergerichtsvollziehe...,False,False
5570,9b56d9ca-46f4-5711-ba70-0577a0a3bbbc,1366f284-dd3b-5940-af20-b7a3b07d0b62,F. Häußler\nMarktplatz 6\nGerichtsvollzieheri...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,f. häußler\nmarktplatz 6\ngerichtsvollzieherin...,NaN,False,False,NaN,0cb6fa6492e0550c6ec900e44ad20c4e1fed2355fd88b3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nF. Häußler\nMarktplatz 6\nGerichtsvo...,False,False
5571,fcb8f914-7324-53aa-a093-77d9a2ff502b,ac6193ae-de04-5325-8947-03865c1e8f9d,Gerichtsvollzieherbüro Duhnke\nAmtsgericht Lö...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherbüro duhnke\namtsgericht lör...,NaN,False,False,NaN,674af69a38c0bd80914157fc0769fec7fbf7d1170b0923...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherbüro Duhnke\nAmtsg...,False,False
5572,13d78d06-647f-502f-82b7-cd42d5eb914b,58c1cb69-a6b7-5c87-96ea-7bcbd8d8d142,OLIVER LIEB\nStethaimerstraße 32-34\n84034 La...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,oliver lieb\nstethaimerstraße 32-34\n84034 lan...,NaN,False,False,NaN,599c26934284ee812572072a717077b982e92b1ac17188...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nOLIVER LIEB\nStethaimerstraße 32-34\...,False,False
5573,8a730471-52ef-5536-ab02-14f8cb5ed90b,c76e734b-5b4c-5765-80be-5f6ee87040d4,Janina Dahlhaus\nAdolf-Grimme-Straße 3\nOberg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,janina dahlhaus\nadolf-grimme-straße 3\noberge...,NaN,False,False,NaN,970d9c4c4e1bae6888f5bf7f244a29295952d59088c2ef...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nJanina Dahlhaus\nAdolf-Grimme-Straße...,False,False
5574,2ae4c098-0459-5863-8f46-830caa0083e0,c76e9fd2-6ea6-5611-b44d-54bca1ceab58,Obergerichtsvollzieher\n66953 Pirmasens\nStep...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieher\n66953 pirmasens\nsteph...,NaN,False,False,NaN,18a4f16daa732e41e116c833c24e645e1dfc62a9e5acfc...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\n66953 Pirmas...,False,False
5575,e1d01068-d3ed-51bb-bb0b-00e4a20ae184,5cc802d4-c9fb-5494-9adc-3145ce2a693b,Theo Schmitz\nKölner Strasse 73\nObergerichts...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,theo schmitz\nkölner strasse 73\nobergerichtsv...,NaN,False,False,NaN,4b35ec6592919c14ea8685cbdaa3cc8a2dbf590ccde85e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nTheo Schmitz\nKölner Strasse 73\nObe...,False,False
5576,6eb55951-e9dc-5c08-bffa-1ab235649740,6b1c7bf3-0e62-5592-81ad-a7ef76d59854,Nina Glöckler\nMarktplatz 3\nGerichtsvollzieh...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,nina glöckler\nmarktplatz 3\ngerichtsvollziehe...,NaN,False,False,NaN,f9ec76ad48865c6afd1a341bb07bfc859680a471c0452c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNina Glöckler\nMarktplatz 3\nGericht...,False,False

In [9]:
dritt = dritt[dritt['object_key'].str.contains('data/aftercourt') == True]
dritt.reset_index(drop=True, inplace=True)

In [10]:

import re
NO_RESULT_PATTERN_1 = re.compile(
    r"\bkein(?:em|en|er|es|e)?\b"  # kein / keinem / keinen / keiner / keines / keine
    r"(?:\s+\w+){0,4}?"  # up to 4 optional words in between (e.g. "verwertbares")
    r"\s+ergebniss?(?:e|en|es)?\b",  # ergebnis / ergebnisse / ergebnissen / ergebnisses
    flags=re.IGNORECASE,
)

NO_RESULT_PATTERN_2 = re.compile(
    r"der\s+abruf\s+hat\s+zu\s+keinem\s+ergebnis\s+gef(?:ü|ue)hrt",
    re.IGNORECASE,
)

DRITTAUSKUNFT_BAK_NUMBER_REGEX = re.compile(r"\bbak\s*-\s*(?:nr|nummer)\.?:?\s*\d{6}\b", re.IGNORECASE)


def extract_no_result(text: str) -> bool:
    """
    Check if the document contains phrases indicating no results.

    Args:
        text (str): Input text to check for "kein Ergebnis" phrases

    Returns:
        bool: True if "kein Ergebnis" is found, False otherwise
    """
    if not text:
        return False

    # Search for the "kein Ergebnis" pattern in the text
    match = NO_RESULT_PATTERN_1.search(text) or NO_RESULT_PATTERN_2.search(text)
    return match is not None


def extract_bank_accounts(text: str) -> list:
    """Extract unique 6 digit BAK Numbers from results

    Args:
        text (str): OCR parsed text, detected as drittauskunft

    Returns:
        List of extracted Unique BAK Numbers
    """
    if not text:
        return []
    # search for BAK-NR pattern.
    matches = DRITTAUSKUNFT_BAK_NUMBER_REGEX.findall(text)
    unique_bak_numbers = set(re.search(r"\d{6}", match).group() for match in matches if re.search(r"\d{6}", match))
    return list(unique_bak_numbers)

In [11]:
dritt

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice,is_va
0,a338ba12-5c7b-5f29-a4a8-474e049cc3a9,3d667522-5dd5-504c-ba5e-705c680e06bc,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,20bd93c565add2380243bc51e5f7add4a64ba56de1c53b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False
1,fe565737-faf8-56e4-89fd-c07e1c6945c8,0ec59f78-6ea5-5085-88ae-1367f3f02895,Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st ii 4 s 0229a kevizz 2948091/2...,NaN,False,False,NaN,02d84a0862273ee852cb5eaa1a42830cb8f5289e9ff7c4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St II 4 S 0229a KEVIZZ...,True,False
2,d87c35ce-1ba8-50dc-8338-7c3617b82d94,c322aca7-829a-5739-a1fe-a6d62684096a,Thomas Vetter\nJohann-Ruland-Weg 9\nGerichtsv...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,thomas vetter\njohann-ruland-weg 9\ngerichtsvo...,NaN,False,False,NaN,0892385a2609eda3c819ff07752cf6e019f59f5e62ffcb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nThomas Vetter\nJohann-Ruland-Weg 9\n...,True,False
3,f9e9c3ec-afa7-5b17-a7ea-c950316713e2,546a42f3-85f4-5645-8765-63a4674024c9,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,990b7b5bbe92cfad9a1cb3cc98e829a195d2c010184156...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
4,74c3a533-a8f0-5810-9ef1-e9e8458e9acc,f4d60c17-b34e-591d-b40f-a6beb4af8f0e,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,42967236e1da6c2ab8adb01acae2b024bb2430321f98e9...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False
5,9f1f97e4-6fda-59ce-ae11-d5cf8d33fc7d,1b809711-e91d-5c49-a833-617bc4c7157f,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,2cc33385616966742d97d6d4d902e726c43a51f68039c0...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
6,ba9b1fcd-81a8-51d4-a593-7f9b043236a2,acd659dc-1c2e-59fb-b29e-56cd3e95f4eb,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,bd08800d05ff7cf06ea333a5853b3ee7fd193fa516eb1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
7,d9769e49-a43e-596f-996e-c8e49e83eaa9,a0366e06-b52c-5688-abcf-73903007cff4,Daniel Arlt\nUlrich-Kaegerl-Straße 5\nOberger...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,daniel arlt\nulrich-kaegerl-straße 5\nobergeri...,NaN,False,False,NaN,b616e8dfca3e65160d12b4d1c3275a96cc08c88b28aa28...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nDaniel Arlt\nUlrich-Kaegerl-Straße 5...,True,False
8,6bd2cc0f-a888-526b-aa60-b2d5a1d94fc3,d8a8266a-5c3c-5730-adbd-9c54c847114e,Obergerichtsvollzieherin\nAmtsgericht Wolfsbu...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,obergerichtsvollzieherin\namtsgericht wolfsbur...,NaN,False,False,NaN,76eca03570ad86e15010fed9b2b2c6bd6b85261dcb5cb4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,True,False
9,7a03718a-ec4b-5b8a-82e7-b5552c2bd503,67af9e85-cb23-5c5f-83ca-5ef343cf7614,Obergerichtsvollzieherin Evelyn Häp\nbeim Amt...,data/aftercourt/drittauskunf_with_invoice/B_DR...,drittauskunft,obergerichtsvollzieherin evelyn häp\nbeim amts...,NaN,False,False,NaN,6fc5a49ff23022f380aedbc73c3195cc9a7badfe5367ff...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,True,False
10,ee911740-6c51-555d-a15f-79f118cd2e6d,90c0e66d-dbd2-5280-bb2b-82bc78232cac,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,82b95f3d2aae8ee732c8317475b65e2750a87f7fcea6af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
11,d088fb8f-1da9-5f39-b888-37e7e49546f2,fefbb6bc-f262-500b-bddb-c849f70b6617,Kriegsstr. 65\nCLAUDIUS BETZLER\n76133 Karlsr...,data/aftercourt/drittauskunf_with_invoice/RB_0...,drittauskunft,kriegsstr. 65\nclaudius betzler\n76133 karlsru...,NaN,False,False,NaN,8662e0774a9bf64508058ebb4e3b646c74cd1e7f55a798...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nKriegsstr. 65\nCLAUDIUS BETZLER\n761...,True,False
12,88325ce5-a859-5af9-8230-c01d51a1e539,934c4ff6-bf58-57cf-950b-9450b8bd1057,Obergerichtsvollzieher Frank Pergande\nBüroan...,data/aftercourt/drittauskunf_with_invoice/3_dr...,drittauskunft,obergerichtsvollzieher frank pergande\nbüroans...,NaN,False,False,NaN,6a8e6692235472796470ce5e96cb6b9d1b4dd1e45d496b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Pergand...,True,False
13,9c129614-774b-58c1-bafd-d3f8b7890f85,6259ffbb-7549-54f1-8dab-53d58eee852b,Gerichtsvollzieherin beim Amtsgericht Eisenac...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,gerichtsvollzieherin beim amtsgericht eisenach...,NaN,False,False,NaN,c36bf9e79340f11d66093a12314c0758e13a3d7a6386af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin beim Amtsgerich...,True,False
14,421c6599-37a0-5822-8d21-11de81eadee9,1ccc264b-566c-535f-a5aa-d2ea89e8547f,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,481d84aab52bb306dd926fb8952770634cac437de5d388...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
15,8bef37cf-75b1-502a-b58b-1f05b1486e59,6d1b3bcc-8292-55f9-b37d-24560889de92,Gerichtsvollzieherin Antje Netzband\nAmtsgeri...,data/aftercourt/drittauskunf_with_invoice/KL_0...,drittauskunft,gerichtsvollzieherin antje netzband\namtsgeric...,NaN,False,False,NaN,5227c8222ab9fef267d0c18b0baa43cfd78156d2a0858e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin Antje Netzband\...,True,False
16,7d4731b1-c146-50f0-8546-10754fefb7b4,f3e9c4f8-514e-5e40-b087-a28fb26d7d69,Obergerichtsvollzieher\n66292 Riegelsberg\nSt...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieher\n66292 riegelsberg\nste...,NaN,False,False,NaN,f29cf02fa0b1aca7ea815c19721e59405a7b5709a51440...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\n66292 Riegel...,True,False
17,fdddcd76-8ff6-5677-b86b-0a50548c40ee,cc89240e-f2d4-5f0b-b8ae-a8d52bb6833d,Obergerichtsvollzieherin\nAnschrift\nPäßler R...,data/aftercourt/drittauskunf_with_invoice/Dr_1...,drittauskunft,obergerichtsvollzieherin\nanschrift\npäßler ra...,NaN,False,False,NaN,0eb7536021829c1555b3b5b46fc1f68d38a4792fd630de...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAnschrift\...,True,False
18,359c370c-9c55-5178-9759-f195873f5c1d,d125ddc2-1145-5c21-947e-09c2d7d29792,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,b05af004fe90d19d2d829adeaa742287e882e3a3850730...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False
19,56255120-f80b-5f28-8aab-1ebfcb4eb1d2,b1619e05-0674-5cfd-8e65-0ced9af2a582,Nicole Sommer\nKönigstr. 11\nGerichtsvollzieh...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,nicole sommer\nkönigstr. 11\ngerichtsvollziehe...,NaN,False,False,NaN,890ef069a6eec24f13a3bee665a504f30fe08567ba02f4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNicole Sommer\nKönigstr. 11\nGericht...,True,False
20,6c04d43f-e9b1-5060-a309-6e011d0966ee,238a5666-fa3d-5bdb-b21d-083701f6a179,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,385b3545abfb7b0113a51dde5a6f260e43767704356acf...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False
21,5a5eb696-42dc-5c79-b7fe-d729949ab720,d02cf7d3-9e98-504e-8d40-8d3665b8709c,Anlage zu GZ: St Il 4 - S 0229a KEVIZZ 280992...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st il 4 - s 0229a kevizz 2809922...,NaN,False,False,NaN,d86a7149a0fd5c63d91f164e44069726b338098f6d9928...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,True,False
22,688ff55a-847d-553d-9ccf-49d8a4952480,ddec9621-abfc-5930-9e29-5bcc4214c576,Gerichtsvollzieherin\nMozartstraße 57\nV. Rup...,data/aftercourt/drittauskunf_with_invoice/1_sa...,drittauskunft,gerichtsvollzieherin\nmozartstraße 57\nv. rupp...,NaN,False,False,NaN,b64212be8a46358e539acd3435ea5c5b52461256f03a10...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nMozartstraße 5...,True,False
23,b2b75267-7a21-5120-b909-5c448c1382d9,947820aa-481c-5447-bcfc-646834c2a34a,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,93d7eb28bf63f36ae24557834751cf47d2cdb256391076...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False
24,9aeb7314-a214-556a-ace8-6657d6f4b0c6,d9ba7c3c-a5e6-59a3-823b-c672855e4a34,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,fd1cfd1579a91cf23869999c9ef106f1522f60c30e64d6...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False
25,d2b3ca58-b8b9-58bb-9527-8bba49ea1c50,516d518e-33dd-5a69-b1b6-1b7fa89d3819,Obergerichtsvollzieherin\nEuropaplatz 11\nBea...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieherin\neuropaplatz 11\nbeat...,NaN,False,False,NaN,09bc758a37185c8fc3dd37c6648b712cc1e6f06597def2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nEuropaplat...,True,False
26,aa7e27d2-0962-5d93-99d6-9d278a2411e3,ef376efd-2805-5742-a6cf-d13118d7db83,Gerichtsvollzieherin\nAmtsgericht: Besigheim\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\namtsgericht: besigheim\n...,NaN,False,False,NaN,3c63835fd0cbf6a7d3bea27dd388b74395287544adfac7...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nAmtsgericht: B...,False,False
27,472c6cb2-5c1e-51c2-8767-ba1785af8ec5,10e09d46-9c80-5667-b087-25f32d1d8ae7,Gerichtsvollzieherin\nPostfach 60 02 11\nS. C...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\npostfach 60 02 11\ns. cz...,NaN,False,False,NaN,fd409356ed3d32e300a993543d8c2321d086d16069042e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nPostfach 60 02...,False,False
28,d9f6ba15-63cf-5743-aa24-12f26140ace4,8b976e45-a27a-5f35-8f19-9c04a4a315bb,Neue Büroanschrift ab 01.12.2024\nDortmunder ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,neue büroanschrift ab 01.12.2024\ndortmunder s...,NaN,False,False,NaN,1d6062807bfb02abacfe2291ee4b68bcd1568d401b1acd...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNeue Büroanschrift ab 01.12.2024\nDo...,False,False
29,352168c8-d418-5023-bfa1-f6c53a62e738,8af270a0-0aac-5f09-be68-40ce4bf1b041,Obergerichtsvollzieher\nHellersdorfer Weg 35\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieher\nhellersdorfer weg 35\n...,NaN,False,False,NaN,db6f409de21c9073aba585d6eb9d1e037633723e7ec830...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\nHellersdorfe...,False,False
30,689055a0-23e6-5af1-bbfa-2dc208380567,3c2aa637-6910-504e-adff-0d6814cb0e87,Sylvia Niemeyer\nSchloßstraße 4\nObergerichts...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sylvia niemeyer\nschloßstraße 4\nobergerichtsv...,NaN,False,False,NaN,455cdfc2250320db433f7f2324a8355fc6f83557dfc3cb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSylvia Niemeyer\nSchloßstraße 4\nObe...,False,False
31,a41f131d-7986-595c-b943-01439213fd89,62ed43ec-7d21-50d6-8e04-f6fe6bf168f9,Hauptgerichtsvollzieherin\nBüroanschrift\nFis...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,hauptgerichtsvollzieherin\nbüroanschrift\nfisc...,NaN,False,False,NaN,f5cd426ec871f7ac33d131d363bf7d85992b0dde9f2552...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nHauptgerichtsvollzieherin\nBüroansch...,False,False
32,6eb5c07e-a206-5919-955f-d428768b9809,91aafd57-92de-5836-8418-0be4ebc9184d,"J. RIEGER\n89522 Heidenheim, Helmut-Bornef.-S...",data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,"j. rieger\n89522 heidenheim, helmut-bornef.-st...",NaN,False,False,NaN,d20c39d45436fb61ac7b26682a23dd8d6e7e8a18561653...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,"<page_1>\nJ. RIEGER\n89522 Heidenheim, Helmut-...",False,False
33,fb4da508-93a4-585d-92ad-3cdd1e18cebd,72cc879b-455c-5fce-ba10-ada75a9c5063,N. Stenzel\nBlücherstraße 4\nGerichtsvollzieh...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,n. stenzel\nblücherstraße 4\ngerichtsvollziehe...,NaN,False,False,NaN,a37267c34d030a60a52af7376b12821937769babe846f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nN. Stenzel\nBlücherstraße 4\nGericht...,False,False
34,43d92153-88ce-58b5-96cc-67b1f4c902dc,55d76158-1190-5c2c-b58a-fa2252117f16,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,d2a52b5ed580d39427974c22e0db6e655a59b07917ff12...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,False
35,75d73218-6ac8-5f94-a8f1-9f6a122380f2,c312e6ec-6dae-5678-a3b5-b1d44c83af27,Marion Kruska\nLilly-Reich-Str. 5\nObergerich...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,marion kruska\nlilly-reich-str. 5\nobergericht...,NaN,False,False,NaN,c6242bd1d2b93a40afd2545cd44978efa7725779657e5c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nMarion Kruska\nLilly-Reich-Str. 5\nO...,False,False
36,7475a344-7ab3-57bc-bc8d-5f86383999c6,b0e18f73-edca-5274-ac00-49084feb812f,Amtsgericht Mülheim-Ruhr\nObergerichtsvollzie...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,amtsgericht mülheim-ruhr\nobergerichtsvollzieh...,NaN,False,False,NaN,36c6316fbad13336601c8cea7de3400441f58a1b663513...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAmtsgericht Mülheim-Ruhr\nObergerich...,False,False
37,09429949-63cc-5c52-8af9-6b81c3062509,c0c5e5d3-6663-57b5-9179-e019e22f61b4,Sandra Zander\nObergerichtsvollzieherin beim ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sandra zander\nobergerichtsvollzieherin beim a...,NaN,False,False,NaN,d44bf47d96ddc744395178e205b3ac70a234a4a0c8dee2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSandra Zander\nObergerichtsvollziehe...,False,False
38,9b56d9ca-46f4-5711-ba70-0577a0a3bbbc,1366f284-dd3b-5940-af20-b7a3b07d0b62,F. Häußler\nMarktplatz 6\nGerichtsvollzieheri...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,f. häußler\nmarktplatz 6\ngerichtsvollzieherin...,NaN,False,False,NaN,0cb6fa6492e0550c6ec900e44ad20c4e1fed2355fd88b3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nF. Häußler\nMarktplatz 6\nGerichtsvo...,False,False
39,fcb8f914-7324-53aa-a093-77d9a2ff502b,ac6193ae-de04-5325-8947-03865c1e8f9d,Gerichtsvollzieherbüro Duhnke\nAmtsgericht Lö...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherbüro duhnke\namtsgericht lör...,NaN,False,False,NaN,674af69a38c0bd80914157fc0769fec7fbf7d1170b0923...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherbüro Duhnke\nAmtsg...,False,False
40,13d78d06-647f-502f-82b7-cd42d5eb914b,58c1cb69-a6b7-5c87-96ea-7bcbd8d8d142,OLIVER LIEB\nStethaimerstraße 32-34\n84034 La...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,oliver lieb\nstethaimerstraße 32-34\n84034 lan...,NaN,False,False,NaN,599c26934284ee812572072a717077b982e92b1ac17188...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nOLIVER LIEB\nStethaimerstraße 32-34\...,False,False
41,8a730471-52ef-5536-ab02-14f8cb5ed90b,c76e734b-5b4c-5765-80be-5f6ee87040d4,Janina Dahlhaus\nAdolf-Grimme-Straße 3\nOberg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,janina dahlhaus\nadolf-grimme-straße 3\noberge...,NaN,False,False,NaN,970d9c4c4e1bae6888f5bf7f244a29295952d59088c2ef...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nJanina Dahlhaus\nAdolf-Grimme-Straße...,False,False
42,2ae4c098-0459-5863-8f46-830caa0083e0,c76e9fd2-6ea6-5611-b44d-54bca1ceab58,Obergerichtsvollzieher\n66953 Pirmasens\nStep...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieher\n66953 pirmasens\nsteph...,NaN,False,False,NaN,18a4f16daa732e41e116c833c24e645e1dfc62a9e5acfc...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\n66953 Pirmas...,False,False
43,e1d01068-d3ed-51bb-bb0b-00e4a20ae184,5cc802d4-c9fb-5494-9adc-3145ce2a693b,Theo Schmitz\nKölner Strasse 73\nObergerichts...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,theo schmitz\nkölner strasse 73\nobergerichtsv...,NaN,False,False,NaN,4b35ec6592919c14ea8685cbdaa3cc8a2dbf590ccde85e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nTheo Schmitz\nKölner Strasse 73\nObe...,False,False
44,6eb55951-e9dc-5c08-bffa-1ab235649740,6b1c7bf3-0e62-5592-81ad-a7ef76d59854,Nina Glöckler\nMarktplatz 3\nGerichtsvollzieh...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,nina glöckler\nmarktplatz 3\ngerichtsvollziehe...,NaN,False,False,NaN,f9ec76ad48865c6afd1a341bb07bfc859680a471c0452c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNina Glöckler\nMarktplatz 3\nGericht...,False,False
45,6ded2e97-089e-5f35-a1e5-40528d04e1fc,b8447b3c-e84a-5573-9578-cd2bc1a95678,Amtsgericht\nKontakt und Information\nBürospr...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,amtsgericht\nkontakt und information\nbürospre...,NaN,False,False,NaN,a3fe76f5b1f3dc7b6292757346037264739d148d00520b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAmtsgericht\nKontakt und Information...,False,False

In [12]:
dritt['no_result'] = dritt['text'].apply(extract_no_result)
dritt['bank_numbers'] = dritt['text'].apply(extract_bank_accounts)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_68873/4034705744.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dritt['no_result'] = dritt['text'].apply(extract_no_result)
/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_68873/4034705744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dritt['bank_numbers'] = dritt['text'].apply(extract_bank_accounts)

In [13]:
dritt.no_result.value_counts()

no_result
False    41
True     12
Name: count, dtype: int64

In [14]:
dritt.bank_numbers.value_counts()

bank_numbers
[]                                                                                                                                  14
[100005]                                                                                                                             2
[145827, 150368, 157210, 161008]                                                                                                     1
[100487, 100460]                                                                                                                     1
[100027, 100512, 100178, 101976, 109664, 157210, 100005, 100215, 115319, 145827, 108556]                                             1
[100732, 100178, 100436, 101659, 118881, 104078, 118635, 105625, 100072, 100721]                                                     1
[159131, 157210, 105513, 100541]                                                                                                     1
[100003]                                                                                                                             1
[150368, 100732, 161008, 100436, 143626, 100003, 101144, 100181, 101711, 100215, 101710, 108133, 156946, 118635, 105625, 108556]     1
[100003, 101687, 143626]                                                                                                             1
[105627, 100500]                                                                                                                     1
[100180]                                                                                                                             1
[100088, 143626, 115209, 100595, 101492, 100430]                                                                                     1
[100827, 108556, 100005]                                                                                                             1
[104189, 101328]                                                                                                                     1
[100446, 101434]                                                                                                                     1
[150368, 143626, 145827, 100112, 100564, 100118]                                                                                     1
[161008, 101587, 100178, 143626, 159131, 100005, 156937, 156946, 161352]                                                             1
[100816, 159131, 120560, 156937, 108556]                                                                                             1
[100909]                                                                                                                             1
[100892]                                                                                                                             1
[101413, 101316, 100530, 115162]                                                                                                     1
[103260, 100866, 103284, 100426, 100853]                                                                                             1
[100871]                                                                                                                             1
[100432]                                                                                                                             1
[156411, 100516, 104101, 102105, 117588]                                                                                             1
[150368, 100516, 104114]                                                                                                             1
[100215, 102319]                                                                                                                     1
[100732]                                                                                                                             1
[100215, 103547, 120560, 100999]                                                                                                     1
[104099]                                                                                                                             1
[150368, 161008, 101130, 143626, 162193, 100005, 156937]                                                                             1
[100003, 101007]                                                                                                                     1
[100663, 105649, 100180]                                                                                                             1
[108556, 100607]                                                                                                                     1
[150368, 100088, 143626, 141823, 157210, 159131, 119766, 145827, 108556]                                                             1
[109664, 100516, 104127, 105625, 102105, 105627]                                                                                     1
[105513, 159414, 159131, 100005, 101214, 143445, 100445]                                                                             1
[161008, 159131, 156937, 102296, 100493, 105627]                                                                                     1
Name: count, dtype: int64

In [15]:
import sys
sys.path.append('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation')

from utils.prod_utils import download_pdf_from_s3

In [16]:
import boto3

session = boto3.Session(profile_name="739275445236_DataScienceUser")
s3 = session.client("s3")

BUCKET_NAME = "pair-email-classification"

In [17]:

import os
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/dritt_iban"

downloaded_to = []
for _, row in dritt.iterrows():
    try:
        download_pdf_from_s3(
            s3=s3,
            bucket_name=BUCKET_NAME,
            object_key=row["object_key"],
            download_dir=download_dir,
            file_name=None,   # defaults to the key's basename
        )
        file_path = os.path.join(download_dir, os.path.basename(row["object_key"]))
        downloaded_to.append(file_path)
    except Exception as e:
        print(f"Failed to download {row['object_key']}: {e}")
        downloaded_to.append(None)

❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/0_sammel120251218-309-jspu2c.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_bzst-signed_2025-12-19_dr-ii_188525_nachr_5_5_uebersendung_drittauskunft_an_glaeubiger20251222-311-10bhj0c.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dokumente_238025_17122025_14321320251218-312-97pbhe.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_DR_II_2159_25_Information_Kontenabrufersuchen_3_Dokument_215925_18122025_09132920251218-312-txlij7.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/63_dr_1102_25_aus_schreibmaschine20251211-308-gl9s2l.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/1_dr_ii_1369_25_z2_bermittlung_drittausknfte_mit_kr20260226-287-ik0wbh (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/1_dr_ii_1336_25_z2_bermittlung_drittausknfte_mit_kr20260226-294-78eol8 (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dokumente_165825_15122025_132759-signed20251217-311-19b49nh.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_Dr_ii_522_25_aus_schreibmaschine_25-522BZST_DRII522_25_09122025EIGENEVfgVAK-TerminNICHTerschienVAK20251217-311-kpk801.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/B_DR_II_174_26_An_Gl_Nachricht_HBAntrag20260324-304-kxyzzq.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_DRII-097125_BZSt_Ergebnis_1_17_12_2025_DR-II_097125_Nachr_Mitt_Gl_kein_Hb_17_12_2025_2_20251218-312-r04edh.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/RB_002-19122025-081133.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/3_dr_ii_1591_25_a_an_gl_nachricht_hb__802_l20251211-303-1xor7g4.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dr_ii_1317_25_an_gl_nachricht_antrag_hb20251218-309-1jse4ut.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_DR_II_1012_25_Information_Kontenabrufersuchen1_signed_Dokument_101225_10122025_15223820251211-308-1us0bz8.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/KL_001-12032026-085848.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dr_ii_136_26_an_gl_nachricht_hbantrag20260226-293-1yzcwgz (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dr_1209_25_an_gl_nachricht_hbantrag20250919-309-za910z.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/0_sammel120251217-315-112ag8x.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dokumente_136725_16122025_082522_signed20251217-310-1jxjq7b.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/63_dr_1082_25_aus_schreibmaschine20251211-309-mig2e1.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_DR_II_2104_25_Information_Kontenabrufersuchen-signed_Dokument_210425_10122025_14290520251211-311-swgzdk.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/1_sammel120251217-310-5wcirs.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/1_dr_ii_1239_25_z2_bermittlung_drittausknfte_mit_kr20260226-295-qj184b (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/combined_pdf_DRII-010626_BZSt_Ergebnis_1_DR-II_010626_Nachr_VA_verweigert___Drittauskuenfte_eingeholt_-20260226-293-1wq46wy (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunf_with_invoice/Dr_ii_1274_25_an_gl_vollstreckungsunterlagen_zurck_ogv_bast20250919-308-14zl09u.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dr_ii_635_25_an_gl_mitt_ergebnis_drittauskunft_ohne_hb20251219-311-1savlpi.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/0_sammel120251218-310-1m86won.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/combined_pdf_DR-II_149625_Nachr_GKB-ERVQ_01_01_2026_BZSt__v__29_12_202520260102-311-6s6h3v.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/0_sammel120251216-308-iu9c0o (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/dokumente_69025_12012026_10332320260113-315-c1crge.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/1_dr_1414_25_08a_an_gl_mitt_ergebnis_drittstellen_ohne_kr20251218-308-iaqd55 (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dr_ii_1037_25_an_gl_mitt_ergebnis_drittauskunft20260102-313-1ulr793.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dokumente_189625_16122025_075131_signed20251217-309-173zmha.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/combined_pdf_02BZST_0120260106-313-zmejip.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/dokumente_124425_16122025_101226-signed20251217-312-5sjekx.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/0_sammel120251218-312-15w5rjs.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dr_ii_1771_25_an_gl_mitt_ergebnis_drittauskunft20251218-310-159b180.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dokumente_226625_16122025_07334620251217-309-zqn218.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/7_DR_II_1447_25_An_Gl_Mitt_Ergebnis_Drittauskunft20251222-308-ilur2x.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/551a7d98-8878-4a09-8b27-51b79e1bfbaf.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/32b91e58-d3ad-4a34-aa72-2ec754086c31.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/DA im Text.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dokument_163925_18122025_09065920251218-310-br2n6l.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/dokumente_31426_26022026_082419_signed20260227-294-dlzn16.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/Dokumente_242125_16122025_09032120251217-309-xib8rr (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/DA im Text Beispiel.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/2_dr_83_26_an_gl_mitt_ergebnis_drittauskunft20260226-292-1xxm4hj.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/FA_003-18122025-075010.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/combined_pdf_02BZST_0120251218-309-tsmi5u.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/0_sammel120260226-289-1cbt0ik (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/dr_ii_929_25_an_gl_mitt_ergebnis_drittauskunft20260102-312-13kqs0u (1).pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
❌ Error downloading PDF: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.
Failed to download data/aftercourt/drittauskunft_without_invoice/dr_ii_159_26_an_gl_mitt_ergebnis_drittauskunft20260305-294-fvfdxx.pdf: An error occurred (ExpiredToken) when calling the GetObject operation: The provided token has expired.

In [18]:
dritt['local_file_path'] = downloaded_to

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_68873/2740409994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dritt['local_file_path'] = downloaded_to

In [19]:
dritt['local_file_path'].isnull().sum()

np.int64(53)

In [20]:
def generator():
    i = 0
    while True:
        yield i
        i += 1

gen = generator()

In [21]:
import fitz  # pip install pymupdf
from IPython.display import Image, display


def show_pdf_as_images(path, dpi=150):
    doc = fitz.open(path)
    for page in doc:
        pix = page.get_pixmap(dpi=dpi)
        display(Image(pix.tobytes("png")))

show_pdf_as_images(dritt.iloc[next(gen)]['local_file_path'])  # Display the first PDF in the generator

In [22]:
# NOTE: ticket uuid 6bd2cc0f-a888-526b-aa60-b2d5a1d94fc3 only have one bak, this can be useful later for
# the testing

In [23]:
i = next(gen)
print(i)

text = dritt.iloc[i]['text']

pdf = dritt.iloc[i]['local_file_path']

# display the PDF as images
show_pdf_as_images(pdf)

1

In [24]:
print(text)

 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Dieses Dokument ist signiert mit Sign Live! CC 7.1.14
von: König, Bianca
Zeitpunkt: 19.12.2025 09:59
Ergebnisse
zu der Anfrage von dem/der:
Obergerichtsvollzieherin
Bianca König
vom:
18.12.2025
Ihr AZ:
DR-II 1885_25_1
mit folgenden Anhaltsdaten:
Name:
Nachname:
Izzia
Vorname:
Salvatore
Geburtsdatum:
18.09.1979
Kontonummer:
DekaBank Deutsche Girozentrale
BAK-Nr.: 100426
Große Gallusstraße 14, 60315 Frankfurt
Trefferanzahl: 1
Kontonummer: 0237776901
Errichtungsdatum: 16.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum
Seit
Bis
Matilde Izzia
16.08.2010
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Verfügungsberechtigte
Geburtsdatum
Seit
Bis
Salvatore Izzia
18.09.1979
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Rosa Campanaro
10.04 16.09.2022
Lange Str. 25 58636 Iserlohn DE
Sparkasse Märkisches Sauerland, Hemer Menden
BAK-Nr.: 100853
Hauptstraße 206, 58675 Hemer
Trefferanzahl: 4
Kontonummer: DE66445512100001615731
Errichtungsdatum: 12.04.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
12.04.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Cambanaro.
10
Lange Str. 58636 Iseriohn
Anfrage von Obergerichtsvollzieherin
Seite
1 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Kontonummer: DE41445512100001532761
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
10.04.1984- in 06.09.2022
Lange Str. 25, 586364serlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE63445512100001532753
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Campanaro
10.04.1984 06.09.2022
Lange Str. 25, 58636 Iserlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE97445512100001633700
Errichtungsdatum: 29.07.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
29.07.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Campanaro
10.04.1984
24.01.2025
Lange Iserlohn
Anfrage von Obergerichtsvollzieherin
Seite
2 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a - KEVIZZ 2948091/25 (Bitte stets angeben)
Sparkasse der Stadt Iserlohn
BAK-Nr.: 100866
Schillerplatz 6, 58636 Iserlohn
Trefferanzahl: 1
Kontonummer: DE33445500450300737020
Errichtungsdatum: 17.08.2018
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
17.08.2018
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
04 05.09.2018
ange Sit 25 Iserlohn
Salvatore Izzia
18.09.1979
17.08.2018
Lange Str. 25, 58636 Iserlohn
Märkische Bank eG
BAK-Nr.: 103260
Bahnhofstraße 21, 58095 Hagen, Westf
Trefferanzahl: 1
Kontonummer: DE73450600090040706200
Errichtungsdatum: 06.03.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Fratelli Frate. Pedicillo Immobilien eGbR
04.03.2024
14.08.2025
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien GbR
06.03.2023 04.03.2024
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien eGbR
14.08.2025
Schwerter Str. 77 58099 Hagen
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Simoy
17.04.2001
09.09.2024
63 58091 Hagen
Huser Feld 64 583 Herdecke
Salvatore Izzia
18.09.1979
14.05.2024
Lange Str. 25 58636 Iserlohn
Orazio Pedicillo
13.07.1970
06.03.2023 03.06.2024
Huserfeld
rdecke
15.09.1972
06.03.2023
Wubbers
gen-
Catia Carialino Pe dicillo
20.05.1972
29.01.2024
Wupperstr. 58097 Hagen
Anfrage von Obergerichtsvollzieherin
Seite
3 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Wirtschaftlich Berechtigte
Seit
Bis
Pedicillo
14.08.2025
Herdecke
4.08.2025
Wupperst 58097 Hagen
Volksbank Hohenlimburg eG
BAK-Nr.: 103284
Grünrockstraße 5, 58119 Hagen, Westf
Trefferanzahl: 1
Kontonummer: DE97450615244003713100
Errichtungsdatum: 04.08.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Fratelli Pedicillo Service GmbH
04.08.2023
Schwerter Str. 77 58099 Hagen
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
08.08.2023
Lange Str. 25 58636 Iserlohn
Orazio Pedicillo
13.07.1970 04.08.2023
Hi Feld 64 583 Herdecke
Fernando Pedicill
15.09.1972
.08.2023
Wupperstri 2 58097 Hagen
Wirtschaftlich Berechtigte
Seit
Bis
Orazio Pedicillo
04.08.2023
Peld 84 5831 Herdecke
EXPT
Fernando Pedicillo
04.08.2023
Wupperst Hagen
Anfrage von Obergerichtsvollzieherin
Seite
4 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Friedrichstr. 108-110
58636 Iserlohn (Amtsgericht)
Tel. 02372/5680247 + 0157/73563106
Bianca König
Obergerichtsvollzieherin
Urlaub 24.12.25 - 04.01.26
SPRECHSTUNDEN
Dienstag 09.00 10.00 Uhr
OGV König, Friedrichstr. 108-110, 58636 Iserlohn
Donnerstag 12.30 13.30 Uhr
Konrad-Adenauer-Ring 8
PAIR Finance GmbH
58636 Iserlohn
vertr. d. d. GF
Knesebeckstr. 62-63
10719 Berlin
DR-II 1885/25
BITTE BEI ALLEN SCHREIBEN
UND ZAHLUNGEN ANGEBEN
Ihr Zeichen: 175607610185
Datum: 19.12.2025
Sehr geehrte Damen und Herren
In der Zwangsvollstreckungssache E.ON Energie Deutschland GmbH vertr. d. d. GF,
Arnulfstr. 203, 80634 München
gegen Izzia, Salvatore, Lange Str. 25a, 58636 Iserlohn
übersende ich Ihnen anliegend antragsgemäß das Ergebnis der eingeholten Drittauskunft/Drittauskünfte
Sie werden darauf hingewiesen, dass gem. § 802 I Abs. 1 und 2 ZPO die Daten nur insoweit verwendet werden
dürfen, als sie zur Zwangsvollstreckung aus vorliegendem Rechtsverhältnis erforderlich sind. Die Daten dürfen
nicht für Inkasso- oder Vollstreckungszwecke in anderen Angelegenheiten verwendet werden.
Hochachtungsvoll
Kostenrechnung nach § 13 GVKostG an Auftraggeber:
E.ON Energie Deutschland GmbH vertr. d. d. GF
KV 440 Einholung Auskunft beim BZSt
15,60 €
KV 716 Auslagenpauschale zu §8021 ZPO
3,12 €
kein HB-Antrag 18.12.2025 V. 18.12.2025
48,68€
König
Summe:
67,40 €
Obergerichtsvollzieherin
Bitte überweisen Sie sofort
beim AG Iserlohn
Gegen diese Kostenrechnung kann schriftlich oder zu Protokoll der
Geschäftsstelle Erinnerung bei dem Amtsgericht Iserlohn, Friedrichstraße 108
110, 58636 Iserlohn oder dem Gerichtsvollzieher eingelegt werden.
3.3.1612
-
Bankverbindung Dienstkonto: IBAN: DE80 4401 0046 0291 0364 65 BIC: PBNKDEFF POSTBANK DORTMUND

In [25]:
first_match = DRITTAUSKUNFT_BAK_NUMBER_REGEX.search(text)

In [26]:
first_match.group()

'BAK-Nr.: 100426'

In [27]:
first_match.start()

427

In [28]:
first_match.end()

442

In [29]:
text[first_match.start():first_match.end()]

'BAK-Nr.: 100426'

In [30]:

match_objects = [m for m in DRITTAUSKUNFT_BAK_NUMBER_REGEX.finditer(text)]

In [31]:
match_objects

[<re.Match object; span=(427, 442), match='BAK-Nr.: 100426'>,
 <re.Match object; span=(908, 923), match='BAK-Nr.: 100853'>,
 <re.Match object; span=(2639, 2654), match='BAK-Nr.: 100866'>,
 <re.Match object; span=(3063, 3078), match='BAK-Nr.: 103260'>,
 <re.Match object; span=(4161, 4176), match='BAK-Nr.: 103284'>]

In [32]:
def filter_bak_spans(match_objects):
    # get unique baks, if there is duplicate bak, get the first detected
    unique_baks = {}
    unique_bak_spans = []
    for match in match_objects:
        bak_number = re.search(r"\d{6}", match.group()).group()
        if bak_number not in unique_baks:
            unique_baks[bak_number] = match
            unique_bak_spans.append(match)
    return unique_bak_spans

In [33]:
filter_bak_spans(match_objects)

[<re.Match object; span=(427, 442), match='BAK-Nr.: 100426'>,
 <re.Match object; span=(908, 923), match='BAK-Nr.: 100853'>,
 <re.Match object; span=(2639, 2654), match='BAK-Nr.: 100866'>,
 <re.Match object; span=(3063, 3078), match='BAK-Nr.: 103260'>,
 <re.Match object; span=(4161, 4176), match='BAK-Nr.: 103284'>]

In [34]:
filtered_match_objects = filter_bak_spans(match_objects)

In [35]:
from collections import deque

KONTOINHABER_REGEX = re.compile(r"\bkontoinhaber\b", re.IGNORECASE)

def split_to_contexts(filtered_match_objects: list, text: str) -> list[str]:
    window_size = 300
    if not filtered_match_objects:
        return [], []
    
    extracted_contexts = []
    bak_numbers = []
    
    for i in range(len(filtered_match_objects)):
        match_i = filtered_match_objects[i]
        match_j = filtered_match_objects[i + 1] if i + 1 < len(filtered_match_objects) else None
        if match_j:
            context_start = max(0, match_i.start())
            context_end = min(len(text), match_j.start())
            context = text[context_start:context_end]
            extracted_contexts.append(context)
            bak_numbers.append(re.search(r"\d{6}", match_i.group()).group())
        else:
            # meaning its last span
            context_start = max(0, match_i.start())
            text_filtered = text[context_start:]
            last_kontinhaber_match = deque(KONTOINHABER_REGEX.finditer(text_filtered), maxlen=1)
            if last_kontinhaber_match:
                context_end = last_kontinhaber_match[0].start() + context_start
            else:
                context_end = context_start + window_size
            context = text[context_start:context_end]
            extracted_contexts.append(context)
            bak_numbers.append(re.search(r"\d{6}", match_i.group()).group())
    return extracted_contexts, bak_numbers

In [36]:
contexts, bak_numbers = split_to_contexts(filtered_match_objects, text)

In [37]:
print(text)

 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Dieses Dokument ist signiert mit Sign Live! CC 7.1.14
von: König, Bianca
Zeitpunkt: 19.12.2025 09:59
Ergebnisse
zu der Anfrage von dem/der:
Obergerichtsvollzieherin
Bianca König
vom:
18.12.2025
Ihr AZ:
DR-II 1885_25_1
mit folgenden Anhaltsdaten:
Name:
Nachname:
Izzia
Vorname:
Salvatore
Geburtsdatum:
18.09.1979
Kontonummer:
DekaBank Deutsche Girozentrale
BAK-Nr.: 100426
Große Gallusstraße 14, 60315 Frankfurt
Trefferanzahl: 1
Kontonummer: 0237776901
Errichtungsdatum: 16.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum
Seit
Bis
Matilde Izzia
16.08.2010
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Verfügungsberechtigte
Geburtsdatum
Seit
Bis
Salvatore Izzia
18.09.1979
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Rosa Campanaro
10.04 16.09.2022
Lange Str. 25 58636 Iserlohn DE
Sparkasse Märkisches Sauerland, Hemer Menden
BAK-Nr.: 100853
Hauptstraße 206, 58675 Hemer
Trefferanzahl: 4
Kontonummer: DE66445512100001615731
Errichtungsdatum: 12.04.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
12.04.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Cambanaro.
10
Lange Str. 58636 Iseriohn
Anfrage von Obergerichtsvollzieherin
Seite
1 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Kontonummer: DE41445512100001532761
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
10.04.1984- in 06.09.2022
Lange Str. 25, 586364serlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE63445512100001532753
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Campanaro
10.04.1984 06.09.2022
Lange Str. 25, 58636 Iserlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE97445512100001633700
Errichtungsdatum: 29.07.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
29.07.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Campanaro
10.04.1984
24.01.2025
Lange Iserlohn
Anfrage von Obergerichtsvollzieherin
Seite
2 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a - KEVIZZ 2948091/25 (Bitte stets angeben)
Sparkasse der Stadt Iserlohn
BAK-Nr.: 100866
Schillerplatz 6, 58636 Iserlohn
Trefferanzahl: 1
Kontonummer: DE33445500450300737020
Errichtungsdatum: 17.08.2018
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
17.08.2018
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
04 05.09.2018
ange Sit 25 Iserlohn
Salvatore Izzia
18.09.1979
17.08.2018
Lange Str. 25, 58636 Iserlohn
Märkische Bank eG
BAK-Nr.: 103260
Bahnhofstraße 21, 58095 Hagen, Westf
Trefferanzahl: 1
Kontonummer: DE73450600090040706200
Errichtungsdatum: 06.03.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Fratelli Frate. Pedicillo Immobilien eGbR
04.03.2024
14.08.2025
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien GbR
06.03.2023 04.03.2024
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien eGbR
14.08.2025
Schwerter Str. 77 58099 Hagen
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Simoy
17.04.2001
09.09.2024
63 58091 Hagen
Huser Feld 64 583 Herdecke
Salvatore Izzia
18.09.1979
14.05.2024
Lange Str. 25 58636 Iserlohn
Orazio Pedicillo
13.07.1970
06.03.2023 03.06.2024
Huserfeld
rdecke
15.09.1972
06.03.2023
Wubbers
gen-
Catia Carialino Pe dicillo
20.05.1972
29.01.2024
Wupperstr. 58097 Hagen
Anfrage von Obergerichtsvollzieherin
Seite
3 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Wirtschaftlich Berechtigte
Seit
Bis
Pedicillo
14.08.2025
Herdecke
4.08.2025
Wupperst 58097 Hagen
Volksbank Hohenlimburg eG
BAK-Nr.: 103284
Grünrockstraße 5, 58119 Hagen, Westf
Trefferanzahl: 1
Kontonummer: DE97450615244003713100
Errichtungsdatum: 04.08.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Fratelli Pedicillo Service GmbH
04.08.2023
Schwerter Str. 77 58099 Hagen
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
08.08.2023
Lange Str. 25 58636 Iserlohn
Orazio Pedicillo
13.07.1970 04.08.2023
Hi Feld 64 583 Herdecke
Fernando Pedicill
15.09.1972
.08.2023
Wupperstri 2 58097 Hagen
Wirtschaftlich Berechtigte
Seit
Bis
Orazio Pedicillo
04.08.2023
Peld 84 5831 Herdecke
EXPT
Fernando Pedicillo
04.08.2023
Wupperst Hagen
Anfrage von Obergerichtsvollzieherin
Seite
4 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Friedrichstr. 108-110
58636 Iserlohn (Amtsgericht)
Tel. 02372/5680247 + 0157/73563106
Bianca König
Obergerichtsvollzieherin
Urlaub 24.12.25 - 04.01.26
SPRECHSTUNDEN
Dienstag 09.00 10.00 Uhr
OGV König, Friedrichstr. 108-110, 58636 Iserlohn
Donnerstag 12.30 13.30 Uhr
Konrad-Adenauer-Ring 8
PAIR Finance GmbH
58636 Iserlohn
vertr. d. d. GF
Knesebeckstr. 62-63
10719 Berlin
DR-II 1885/25
BITTE BEI ALLEN SCHREIBEN
UND ZAHLUNGEN ANGEBEN
Ihr Zeichen: 175607610185
Datum: 19.12.2025
Sehr geehrte Damen und Herren
In der Zwangsvollstreckungssache E.ON Energie Deutschland GmbH vertr. d. d. GF,
Arnulfstr. 203, 80634 München
gegen Izzia, Salvatore, Lange Str. 25a, 58636 Iserlohn
übersende ich Ihnen anliegend antragsgemäß das Ergebnis der eingeholten Drittauskunft/Drittauskünfte
Sie werden darauf hingewiesen, dass gem. § 802 I Abs. 1 und 2 ZPO die Daten nur insoweit verwendet werden
dürfen, als sie zur Zwangsvollstreckung aus vorliegendem Rechtsverhältnis erforderlich sind. Die Daten dürfen
nicht für Inkasso- oder Vollstreckungszwecke in anderen Angelegenheiten verwendet werden.
Hochachtungsvoll
Kostenrechnung nach § 13 GVKostG an Auftraggeber:
E.ON Energie Deutschland GmbH vertr. d. d. GF
KV 440 Einholung Auskunft beim BZSt
15,60 €
KV 716 Auslagenpauschale zu §8021 ZPO
3,12 €
kein HB-Antrag 18.12.2025 V. 18.12.2025
48,68€
König
Summe:
67,40 €
Obergerichtsvollzieherin
Bitte überweisen Sie sofort
beim AG Iserlohn
Gegen diese Kostenrechnung kann schriftlich oder zu Protokoll der
Geschäftsstelle Erinnerung bei dem Amtsgericht Iserlohn, Friedrichstraße 108
110, 58636 Iserlohn oder dem Gerichtsvollzieher eingelegt werden.
3.3.1612
-
Bankverbindung Dienstkonto: IBAN: DE80 4401 0046 0291 0364 65 BIC: PBNKDEFF POSTBANK DORTMUND

In [38]:
print(contexts[0], "******************\n", contexts[1], "******************\n", contexts[2], "******************\n", contexts[3])

BAK-Nr.: 100426
Große Gallusstraße 14, 60315 Frankfurt
Trefferanzahl: 1
Kontonummer: 0237776901
Errichtungsdatum: 16.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum
Seit
Bis
Matilde Izzia
16.08.2010
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Verfügungsberechtigte
Geburtsdatum
Seit
Bis
Salvatore Izzia
18.09.1979
16.09.2022
Lange Str. 25, 58636 Iserlohn DE
Rosa Campanaro
10.04 16.09.2022
Lange Str. 25 58636 Iserlohn DE
Sparkasse Märkisches Sauerland, Hemer Menden
 ******************
 BAK-Nr.: 100853
Hauptstraße 206, 58675 Hemer
Trefferanzahl: 4
Kontonummer: DE66445512100001615731
Errichtungsdatum: 12.04.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
12.04.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Cambanaro.
10
Lange Str. 58636 Iseriohn
Anfrage von Obergerichtsvollzieherin
Seite
1 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Kontonummer: DE41445512100001532761
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
10.04.1984- in 06.09.2022
Lange Str. 25, 586364serlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE63445512100001532753
Errichtungsdatum: 06.09.2022
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
06.09.2022
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Campanaro
10.04.1984 06.09.2022
Lange Str. 25, 58636 Iserlohn
Salvatore Izzia
18.09.1979
06.09.2022
Lange Str. 25, 58636 Iserlohn
Kontonummer: DE97445512100001633700
Errichtungsdatum: 29.07.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Salvatore Izzia
18.09.1979
29.07.2024
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Rosa Campanaro
10.04.1984
24.01.2025
Lange Iserlohn
Anfrage von Obergerichtsvollzieherin
Seite
2 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a - KEVIZZ 2948091/25 (Bitte stets angeben)
Sparkasse der Stadt Iserlohn
 ******************
 BAK-Nr.: 100866
Schillerplatz 6, 58636 Iserlohn
Trefferanzahl: 1
Kontonummer: DE33445500450300737020
Errichtungsdatum: 17.08.2018
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Matilde Izzia
16.08.2010
17.08.2018
Lange Str. 25, 58636 Iserlohn
Verfügungsberechtigte
Geburtsdatum Seit
Bis
04 05.09.2018
ange Sit 25 Iserlohn
Salvatore Izzia
18.09.1979
17.08.2018
Lange Str. 25, 58636 Iserlohn
Märkische Bank eG
 ******************
 BAK-Nr.: 103260
Bahnhofstraße 21, 58095 Hagen, Westf
Trefferanzahl: 1
Kontonummer: DE73450600090040706200
Errichtungsdatum: 06.03.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Fratelli Frate. Pedicillo Immobilien eGbR
04.03.2024
14.08.2025
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien GbR
06.03.2023 04.03.2024
Schwerter Str. 77 58099 Hagen
Fratelli Pedicillo Immobilien eGbR
14.08.2025
Schwerter Str. 77 58099 Hagen
Verfügungsberechtigte
Geburtsdatum Seit
Bis
Simoy
17.04.2001
09.09.2024
63 58091 Hagen
Huser Feld 64 583 Herdecke
Salvatore Izzia
18.09.1979
14.05.2024
Lange Str. 25 58636 Iserlohn
Orazio Pedicillo
13.07.1970
06.03.2023 03.06.2024
Huserfeld
rdecke
15.09.1972
06.03.2023
Wubbers
gen-
Catia Carialino Pe dicillo
20.05.1972
29.01.2024
Wupperstr. 58097 Hagen
Anfrage von Obergerichtsvollzieherin
Seite
3 von
4
Bianca König (G21233) zu AZ DR-II 1885_25_1
 Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/25 (Bitte stets angeben)
Wirtschaftlich Berechtigte
Seit
Bis
Pedicillo
14.08.2025
Herdecke
4.08.2025
Wupperst 58097 Hagen
Volksbank Hohenlimburg eG

In [45]:

GENERAL_IBAN_REGEX = re.compile(r'\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){2,7}\s?[A-Z0-9]{1,3}\b')

def validate_iban(iban: str) -> bool:
    """
    Validate an IBAN using the standard IBAN validation algorithm.
    
    Referance: https://en.wikipedia.org/wiki/International_Bank_Account_Number

    Args:
        iban (str): The IBAN to validate.

    Returns:
        bool: True if the IBAN is valid, False otherwise.
    """
    # Remove spaces and convert to uppercase
    iban = iban.replace(' ', '').upper()
    
    # Check if the IBAN length is valid (between 15 and 34 characters)
    if not (15 <= len(iban) <= 34):
        return False
    
    # Move the first four characters to the end of the string
    rearranged_iban = iban[4:] + iban[:4]
    
    # Replace each letter in the string with two digits, where A=10, B=11, ..., Z=35
    numeric_iban = ''
    for char in rearranged_iban:
        if char.isdigit():
            numeric_iban += char
        else:
            numeric_iban += str(ord(char) - 55)  # Convert letter to number (A=10, B=11, ..., Z=35)
    
    # Convert the string to an integer and compute the remainder of that number on division by 97
    iban_int = int(numeric_iban)
    
    return iban_int % 97 == 1


def _normalize_iban(iban: str) -> str:
    """Canonical form used for uniqueness checks (no spaces, uppercase)."""
    return iban.replace(" ", "").upper()



DATE_REGEX = re.compile(
    r"""(?x)
(?<!\d)
(?:
    (?:(?:0?[1-9]|[12]\d)|3[01])\s?[./:-][\s.]?(?:0?[13578]|1[02]|J(?:an(?:uar)?|uli?)|M(?:ärz?|ai)|Aug(?:ust)?|Dez(?:ember)?|Okt(?:ober)?)\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)|
    (?:(?:0?[1-9]|[12]\d)|30)\s?[./:-][\s.]?(?:0?[13-9]|1[012]|J(?:an(?:uar)?|u[nl]i?)|M(?:ärz?|ai)|A(?:pr(?:il)?|ug(?:ust)?)|Sep(?:tember)?|(?:Nov|Dez)(?:ember)?|Okt(?:ober)?)\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)|
    (?:0?[1-9]|[12]\d)\s?[./:-][\s.]?(?:0?2|Fe(?:b(?:ruar)?)?|(?:0?2|Feb(?:r(?:uar)?)?))\s?(?:[./:-][\s.]?)?(?:[1-9]\d(?:[02468][048]|[13579][26])|\d\d)|
    (?:0?[1-9]|[12][0-9])\s?[./:-][\s.]?(?:0?2|Fe(?:b(?:ruar)?)?|(?:0?2|Feb(?:r(?:uar)?)?))\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)
)
(?!\d)""",
    re.IGNORECASE | re.VERBOSE,
)

import dateparser  # same parser used by the Ladung summon_date_extractor
from datetime import datetime


def extract_date_from_context(context: str) -> datetime | None:
    """Extract the Errichtungsdatum from an IBAN subcontext.

    Reuses the DATE_REGEX and dateparser from the Ladung summon_date_extractor.
    The subcontext spans from an IBAN to the next Kontoinhaber, so it typically
    contains a single relevant date. The first parseable date found is returned.

    Args:
        context (str): Text slice starting at an IBAN and ending before the next
            Kontoinhaber (or end of context).

    Returns:
        datetime | None: The parsed date, or None if no valid date is found.
    """
    if not context:
        return None

    for match in DATE_REGEX.finditer(context):
        parsed = dateparser.parse(match.group(), languages=["de"])
        if parsed is not None:
            return parsed

    return None

def get_latest_iban(ibans: list[str], ibans_date: list[datetime | None]) -> str | None:
    """Return the IBAN with the most recent Errichtungsdatum.

    Args:
        ibans (list[str]): Normalized IBANs found for a single BAK context.
        ibans_date (list[datetime | None]): The Errichtungsdatum for each IBAN,
            aligned by index with ``ibans``. May contain None when no date was
            found.

    Returns:
        str | None: The IBAN with the latest date. If none of the IBANs have a
            date, falls back to the last IBAN found. Returns None if there are
            no IBANs.
    """
    if not ibans:
        return None

    dated_ibans = [(iban, date) for iban, date in zip(ibans, ibans_date) if date is not None]
    if dated_ibans:
        return max(dated_ibans, key=lambda pair: pair[1])[0]

    # No dates available -> fall back to the last IBAN found.
    return ibans[-1]

def extract_iban_from_contexts(contexts: list[str], bak_numbers: list[str]) -> dict[str, str]:
    # TODO: New task: we also need to extract errictungsdatum of the iban
    bak_to_iban = {}
    seen_ibans = set()  # normalized IBANs already assigned to a BAK
    for ctx, bak in zip(contexts, bak_numbers):
        extracted_ibans = []
        ibans_date = []
        for iban in GENERAL_IBAN_REGEX.findall(ctx):
            if not validate_iban(iban):
                continue
            norm = _normalize_iban(iban)
            if norm in seen_ibans:
                continue
            # iban is found for the current bak number context. Now we need to extract its date.
            # for that search in subcontext to prevent fetching multiple dates
            # subcontext = starts with iban and ends with first next Kontoinhaber
            subcontext_start = ctx.find(iban) # start index of the iban in the context
            first_kontinhaber_match = next(KONTOINHABER_REGEX.finditer(ctx[subcontext_start:]), None)
            if first_kontinhaber_match:
                subcontext_end = subcontext_start + first_kontinhaber_match.start()
            else:
                # if no Kontoinhaber is found, the end is  nd of the context
                subcontext_end = len(ctx)
            
            extracted_date = extract_date_from_context(ctx[subcontext_start:subcontext_end])
            # add iban
            seen_ibans.add(norm)
            extracted_ibans.append(norm)
            ibans_date.append(extracted_date)
            
        latest_iban = get_latest_iban(extracted_ibans, ibans_date)
            
        bak_to_iban[bak] = latest_iban
    return bak_to_iban

In [47]:
extracted_ibans = extract_iban_from_contexts(contexts, bak_numbers)
extracted_ibans

{'100426': None,
 '100853': 'DE97445512100001633700',
 '100866': 'DE33445500450300737020',
 '103260': 'DE73450600090040706200',
 '103284': 'DE97450615244003713100'}

In [41]:
def extract_bak_to_ibans(text: str) -> dict[str, list[str]]:
    """Extract a mapping of BAK numbers to their validated IBANs from a Drittauskunft document.

    Pipeline:
        1. Find all BAK-Nr. matches in the text.
        2. Deduplicate BAK numbers (keep first occurrence).
        3. Split the text into a context window per BAK.
        4. Extract and validate IBANs within each context.

    Args:
        text (str): OCR parsed text of a document detected as drittauskunft.

    Returns:
        dict[str, list[str]]: Mapping of BAK number -> list of validated IBANs.
    """
    if not text:
        return {}

    match_objects = list(DRITTAUSKUNFT_BAK_NUMBER_REGEX.finditer(text))
    filtered_match_objects = filter_bak_spans(match_objects)
    contexts, bak_numbers = split_to_contexts(filtered_match_objects, text)
    return extract_iban_from_contexts(contexts, bak_numbers)

In [48]:
# apply it to all dataset

dritt['bak_to_ibans'] = dritt['text'].apply(extract_bak_to_ibans)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_68873/3275243164.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dritt['bak_to_ibans'] = dritt['text'].apply(extract_bak_to_ibans)

In [49]:
dritt

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice,is_va,no_result,bank_numbers,local_file_path,bak_to_ibans
0,a338ba12-5c7b-5f29-a4a8-474e049cc3a9,3d667522-5dd5-504c-ba5e-705c680e06bc,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,20bd93c565add2380243bc51e5f7add4a64ba56de1c53b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False,False,"[145827, 150368, 157210, 161008]",None,"{'145827': 'DE91100110012811132575', '150368':..."
1,fe565737-faf8-56e4-89fd-c07e1c6945c8,0ec59f78-6ea5-5085-88ae-1367f3f02895,Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st ii 4 s 0229a kevizz 2948091/2...,NaN,False,False,NaN,02d84a0862273ee852cb5eaa1a42830cb8f5289e9ff7c4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St II 4 S 0229a KEVIZZ...,True,False,False,"[103260, 100866, 103284, 100426, 100853]",None,"{'100426': None, '100853': 'DE9744551210000163..."
2,d87c35ce-1ba8-50dc-8338-7c3617b82d94,c322aca7-829a-5739-a1fe-a6d62684096a,Thomas Vetter\nJohann-Ruland-Weg 9\nGerichtsv...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,thomas vetter\njohann-ruland-weg 9\ngerichtsvo...,NaN,False,False,NaN,0892385a2609eda3c819ff07752cf6e019f59f5e62ffcb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nThomas Vetter\nJohann-Ruland-Weg 9\n...,True,False,False,[100871],None,{'100871': 'DE26370502991146111108'}
3,f9e9c3ec-afa7-5b17-a7ea-c950316713e2,546a42f3-85f4-5645-8765-63a4674024c9,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,990b7b5bbe92cfad9a1cb3cc98e829a195d2c010184156...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False,False,[100432],None,{'100432': 'DE85100500006011648990'}
4,74c3a533-a8f0-5810-9ef1-e9e8458e9acc,f4d60c17-b34e-591d-b40f-a6beb4af8f0e,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,42967236e1da6c2ab8adb01acae2b024bb2430321f98e9...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False,True,[],None,{}
5,9f1f97e4-6fda-59ce-ae11-d5cf8d33fc7d,1b809711-e91d-5c49-a833-617bc4c7157f,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,2cc33385616966742d97d6d4d902e726c43a51f68039c0...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False,False,"[156411, 100516, 104101, 102105, 117588]",None,"{'100516': 'DE20670505050040370072', '102105':..."
6,ba9b1fcd-81a8-51d4-a593-7f9b043236a2,acd659dc-1c2e-59fb-b29e-56cd3e95f4eb,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,bd08800d05ff7cf06ea333a5853b3ee7fd193fa516eb1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False,False,"[150368, 100516, 104114]",None,"{'100516': 'DE40670505051200652866', '104114':..."
7,d9769e49-a43e-596f-996e-c8e49e83eaa9,a0366e06-b52c-5688-abcf-73903007cff4,Daniel Arlt\nUlrich-Kaegerl-Straße 5\nOberger...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,daniel arlt\nulrich-kaegerl-straße 5\nobergeri...,NaN,False,False,NaN,b616e8dfca3e65160d12b4d1c3275a96cc08c88b28aa28...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nDaniel Arlt\nUlrich-Kaegerl-Straße 5...,True,False,True,"[100215, 102319]",None,"{'100215': 'DE42120300001039150386', '102319':..."
8,6bd2cc0f-a888-526b-aa60-b2d5a1d94fc3,d8a8266a-5c3c-5730-adbd-9c54c847114e,Obergerichtsvollzieherin\nAmtsgericht Wolfsbu...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,obergerichtsvollzieherin\namtsgericht wolfsbur...,NaN,False,False,NaN,76eca03570ad86e15010fed9b2b2c6bd6b85261dcb5cb4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,True,False,False,[100732],None,{'100732': 'DE46269513110163131337'}
9,7a03718a-ec4b-5b8a-82e7-b5552c2bd503,67af9e85-cb23-5c5f-83ca-5ef343cf7614,Obergerichtsvollzieherin Evelyn Häp\nbeim Amt...,data/aftercourt/drittauskunf_with_invoice/B_DR...,drittauskunft,obergerichtsvollzieherin evelyn häp\nbeim amts...,NaN,False,False,NaN,6fc5a49ff23022f380aedbc73c3195cc9a7badfe5367ff...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,True,False,False,"[100215, 103547, 120560, 100999]",None,"{'100215': 'DE23120300001306287564', '100999':..."
10,ee911740-6c51-555d-a15f-79f118cd2e6d,90c0e66d-dbd2-5280-bb2b-82bc78232cac,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,82b95f3d2aae8ee732c8317475b65e2750a87f7fcea6af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False,True,[],None,{}
11,d088fb8f-1da9-5f39-b888-37e7e49546f2,fefbb6bc-f262-500b-bddb-c849f70b6617,Kriegsstr. 65\nCLAUDIUS BETZLER\n76133 Karlsr...,data/aftercourt/drittauskunf_with_invoice/RB_0...,drittauskunft,kriegsstr. 65\nclaudius betzler\n76133 karlsru...,NaN,False,False,NaN,8662e0774a9bf64508058ebb4e3b646c74cd1e7f55a798...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nKriegsstr. 65\nCLAUDIUS BETZLER\n761...,True,False,True,[],None,{}
12,88325ce5-a859-5af9-8230-c01d51a1e539,934c4ff6-bf58-57cf-950b-9450b8bd1057,Obergerichtsvollzieher Frank Pergande\nBüroan...,data/aftercourt/drittauskunf_with_invoice/3_dr...,drittauskunft,obergerichtsvollzieher frank pergande\nbüroans...,NaN,False,False,NaN,6a8e6692235472796470ce5e96cb6b9d1b4dd1e45d496b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Pergand...,True,False,True,[],None,{}
13,9c129614-774b-58c1-bafd-d3f8b7890f85,6259ffbb-7549-54f1-8dab-53d58eee852b,Gerichtsvollzieherin beim Amtsgericht Eisenac...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,gerichtsvollzieherin beim amtsgericht eisenach...,NaN,False,False,NaN,c36bf9e79340f11d66093a12314c0758e13a3d7a6386af...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin beim Amtsgerich...,True,False,True,[],None,{}
14,421c6599-37a0-5822-8d21-11de81eadee9,1ccc264b-566c-535f-a5aa-d2ea89e8547f,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,481d84aab52bb306dd926fb8952770634cac437de5d388...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False,False,[104099],None,{'104099': 'DE79742901003454000382'}
15,8bef37cf-75b1-502a-b58b-1f05b1486e59,6d1b3bcc-8292-55f9-b37d-24560889de92,Gerichtsvollzieherin Antje Netzband\nAmtsgeri...,data/aftercourt/drittauskunf_with_invoice/KL_0...,drittauskunft,gerichtsvollzieherin antje netzband\namtsgeric...,NaN,False,False,NaN,5227c8222ab9fef267d0c18b0baa43cfd78156d2a0858e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin Antje Netzband\...,True,False,False,"[150368, 161008, 101130, 143626, 162193, 10000...",None,"{'156937': 'DE08202208000046030406', '161008':..."
16,7d4731b1-c146-50f0-8546-10754fefb7b4,f3e9c4f8-514e-5e40-b087-a28fb26d7d69,Obergerichtsvollzieher\n66292 Riegelsberg\nSt...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieher\n66292 riegelsberg\nste...,NaN,False,False,NaN,f29cf02fa0b1aca7ea815c19721e59405a7b5709a51440...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\n66292 Riegel...,True,False,False,"[100003, 101007]",None,"{'100003': 'DE72550703240067352500', '101007':..."
17,fdddcd76-8ff6-5677-b86b-0a50548c40ee,cc89240e-f2d4-5f0b-b8ae-a8d52bb6833d,Obergerichtsvollzieherin\nAnschrift\nPäßler R...,data/aftercourt/drittauskunf_with_invoice/Dr_1...,drittauskunft,obergerichtsvollzieherin\nanschrift\npäßler ra...,NaN,False,False,NaN,0eb7536021829c1555b3b5b46fc1f68d38a4792fd630de...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nAnschrift\...,True,False,True,[],None,{}
18,359c370c-9c55-5178-9759-f195873f5c1d,d125ddc2-1145-5c21-947e-09c2d7d29792,Obergerichtsvollzieher Frank Schäfer\nbei dem...,data/aftercourt/drittauskunf_with_invoice/0_sa...,drittauskunft,obergerichtsvollzieher frank schäfer\nbei dem ...,NaN,False,False,NaN,b05af004fe90d19d2d829adeaa742287e882e3a3850730...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,False,False,"[100663, 105649, 100180]",None,"{'100180': 'DE51300209007400026434', '100663':..."
19,56255120-f80b-5f28-8aab-1ebfcb4eb1d2,b1619e05-0674-5cfd-8e65-0ced9af2a582,Nicole Sommer\nKönigstr. 11\nGerichtsvollzieh...,data/aftercourt/drittauskunf_with_invoice/Doku...,drittauskunft,nicole sommer\nkönigstr. 11\ngerichtsvollziehe...,NaN,False,False,NaN,890ef069a6eec24f13a3bee665a504f30fe08567ba02f4...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNicole Sommer\nKönigstr. 11\nGericht...,True,False,False,[100005],None,{'100005': 'DE88200400000511006901'}
20,6c04d43f-e9b1-5060-a309-6e011d0966ee,238a5666-fa3d-5bdb-b21d-083701f6a179,Christian Linner\nSchragenhofstraße 27\nGeric...,data/aftercourt/drittauskunf_with_invoice/63_d...,drittauskunft,christian linner\nschragenhofstraße 27\ngerich...,NaN,False,False,NaN,385b3545abfb7b0113a51dde5a6f260e43767704356acf...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,False,False,"[108556, 100607]",None,"{'100607': 'DE44701500003002965923', '108556':..."
21,5a5eb696-42dc-5c79-b7fe-d729949ab720,d02cf7d3-9e98-504e-8d40-8d3665b8709c,Anlage zu GZ: St Il 4 - S 0229a KEVIZZ 280992...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,anlage zu gz: st il 4 - s 0229a kevizz 2809922...,NaN,False,False,NaN,d86a7149a0fd5c63d91f164e44069726b338098f6d9928...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,True,False,False,"[150368, 100088, 143626, 141823, 157210, 15913...",None,"{'100088': 'DE70500105175807889843', '108556':..."
22,688ff55a-847d-553d-9ccf-49d8a4952480,ddec9621-abfc-5930-9e29-5bcc4214c576,Gerichtsvollzieherin\nMozartstraße 57\nV. Rup...,data/aftercourt/drittauskunf_with_invoice/1_sa...,drittauskunft,gerichtsvollzieherin\nmozartstraße 57\nv. rupp...,NaN,False,False,NaN,b64212be8a46358e539acd3435ea5c5b52461256f03a10...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nMozartstraße 5...,True,False,False,[100005],None,{'100005': 'DE05763400610829527101'}
23,b2b75267-7a21-5120-b909-5c448c1382d9,947820aa-481c-5447-bcfc-646834c2a34a,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...,data/aftercourt/drittauskunf_with_invoice/1_dr...,drittauskunft,gerichtsvollzieherin\nwaldhofer straße 17\nkat...,NaN,False,False,NaN,93d7eb28bf63f36ae24557834751cf47d2cdb256391076...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,False,False,"[109664, 100516, 104127, 105625, 102105, 105627]",None,"{'100516': 'DE67670505050040276203', '102105':..."
24,9aeb7314-a214-556a-ace8-6657d6f4b0c6,d9ba7c3c-a5e6-59a3-823b-c672855e4a34,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunf_with_invoice/comb...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,fd1cfd1579a91cf23869999c9ef106f1522f60c30e64d6...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,False,False,"[105513, 159414, 159131, 100005, 101214, 14344...",None,"{'100005': 'DE42200411440651077000', '100445':..."
25,d2b3ca58-b8b9-58bb-9527-8bba49ea1c50,516d518e-33dd-5a69-b1b6-1b7fa89d3819,Obergerichtsvollzieherin\nEuropaplatz 11\nBea...,data/aftercourt/drittauskunf_with_invoice/Dr_i...,drittauskunft,obergerichtsvollzieherin\neuropaplatz 11\nbeat...,NaN,False,False,NaN,09bc758a37185c8fc3dd37c6648b712cc1e6f06597def2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin\nEuropaplat...,True,False,False,[100892],None,{'100892': 'DE18310500001004624324'}
26,aa7e27d2-0962-5d93-99d6-9d278a2411e3,ef376efd-2805-5742-a6cf-d13118d7db83,Gerichtsvollzieherin\nAmtsgericht: Besigheim\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\namtsgericht: besigheim\n...,NaN,False,False,NaN,3c63835fd0cbf6a7d3bea27dd388b74395287544adfac7...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nAmtsgericht: B...,False,False,False,"[101413, 101316, 100530, 115162]",None,"{'100530': 'DE09604500504001036873', '101316':..."
27,472c6cb2-5c1e-51c2-8767-ba1785af8ec5,10e09d46-9c80-5667-b087-25f32d1d8ae7,Gerichtsvollzieherin\nPostfach 60 02 11\nS. C...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,gerichtsvollzieherin\npostfach 60 02 11\ns. cz...,NaN,False,False,NaN,fd409356ed3d32e300a993543d8c2321d086d16069042e...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nPostfach 60 02...,False,False,False,[100180],None,{'100180': 'DE38300209005300010230'}
28,d9f6ba15-63cf-5743-aa24-12f26140ace4,8b976e45-a27a-5f35-8f19-9c04a4a315bb,Neue Büroanschrift ab 01.12.2024\nDortmunder ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,neue büroanschrift ab 01.12.2024\ndortmunder s...,NaN,False,False,NaN,1d6062807bfb02abacfe2291ee4b68bcd1568d401b1acd...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nNeue Büroanschrift ab 01.12.2024\nDo...,False,False,False,[100909],None,{'100909': 'DE94426501501001047867'}
29,352168c8-d418-5023-bfa1-f6c53a62e738,8af270a0-0aac-5f09-be68-40ce4bf1b041,Obergerichtsvollzieher\nHellersdorfer Weg 35\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,obergerichtsvollzieher\nhellersdorfer weg 35\n...,NaN,False,False,NaN,db6f409de21c9073aba585d6eb9d1e037633723e7ec830...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieher\nHellersdorfe...,False,False,False,"[100027, 100512, 100178, 101976, 109664, 15721...",None,"{'100005': 'DE75200411660135838100', '100027':..."
30,689055a0-23e6-5af1-bbfa-2dc208380567,3c2aa637-6910-504e-adff-0d6814cb0e87,Sylvia Niemeyer\nSchloßstraße 4\nObergerichts...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sylvia niemeyer\nschloßstraße 4\nobergerichtsv...,NaN,False,False,NaN,455cdfc2250320db433f7f2324a8355fc6f83557dfc3cb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSylvia Niemeyer\nSchloßstraße 4\nObe...,False,False,False,"[100732, 100178, 100436, 101659, 118881, 10407...",None,"{'100072': 'DE47305305000739501931', '100178':..."
31,a41f131d-7986-595c-b943-01439213fd89,62ed43ec-7d21-50d6-8e04-f6fe6bf168f9,Hauptgerichtsvollzieherin\nBüroanschrift\nFis...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,hauptgerichtsvollzieherin\nbüroanschrift\nfisc...,NaN,False,False,NaN,f5cd426ec871f7ac33d131d363bf7d85992b0dde9f2552...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nHauptgerichtsvollzieherin\nBüroansch...,False,False,False,"[159131, 157210, 105513, 100541]",None,"{'100541': 'DE17765500000008606121', '105513':..."
32,6eb5c07e-a206-5919-955f-d428768b9809,91aafd57-92de-5836-8418-0be4ebc9184d,"J. RIEGER\n89522 Heidenheim, Helmut-Bornef.-S...",data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,"j. rieger\n89522 heidenheim, helmut-bornef.-st...",NaN,False,False,NaN,d20c39d45436fb61ac7b26682a23dd8d6e7e8a18561653...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,"<page_1>\nJ. RIEGER\n89522 Heidenheim, Helmut-...",False,False,False,[100003],None,{'100003': None}
33,fb4da508-93a4-585d-92ad-3cdd1e18cebd,72cc879b-455c-5fce-ba10-ada75a9c5063,N. Stenzel\nBlücherstraße 4\nGerichtsvollzieh...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,n. stenzel\nblücherstraße 4\ngerichtsvollziehe...,NaN,False,False,NaN,a37267c34d030a60a52af7376b12821937769babe846f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nN. Stenzel\nBlücherstraße 4\nGericht...,False,False,False,[],None,{}
34,43d92153-88ce-58b5-96cc-67b1f4c902dc,55d76158-1190-5c2c-b58a-fa2252117f16,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,bundeszentralamt\nfür steuern\npostanschrift\n...,NaN,False,False,NaN,d2a52b5ed580d39427974c22e0db6e655a59b07917ff12...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,False,False,"[150368, 100732, 161008, 100436, 143626, 10000...",None,"{'100003': 'DE70250700240201495943', '100181':..."
35,75d73218-6ac8-5f94-a8f1-9f6a122380f2,c312e6ec-6dae-5678-a3b5-b1d44c83af27,Marion Kruska\nLilly-Reich-Str. 5\nObergerich...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,marion kruska\nlilly-reich-str. 5\nobergericht...,NaN,False,False,NaN,c6242bd1d2b93a40afd2545cd44978efa7725779657e5c...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nMarion Kruska\nLilly-Reich-Str. 5\nO...,False,False,False,"[100003, 101687, 143626]",None,"{'100003': 'DE42270703240776344460', '101687':..."
36,7475a344-7ab3-57bc-bc8d-5f86383999c6,b0e18f73-edca-5274-ac00-49084feb812f,Amtsgericht Mülheim-Ruhr\nObergerichtsvollzie...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,amtsgericht mülheim-ruhr\nobergerichtsvollzieh...,NaN,False,False,NaN,36c6316fbad13336601c8cea7de3400441f58a1b663513...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAmtsgericht Mülheim-Ruhr\nObergerich...,False,False,True,[],None,{}
37,09429949-63cc-5c52-8af9-6b81c3062509,c0c5e5d3-6663-57b5-9179-e019e22f61b4,Sandra Zander\nObergerichtsvollzieherin beim ...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,sandra zander\nobergerichtsvollzieherin beim a...,NaN,False,False,NaN,d44bf47d96ddc744395178e205b3ac70a234a4a0c8dee2...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nSandra Zander\nObergerichtsvollziehe...,False,False,True,[],None,{}
38,9b56d9ca-46f4-5711-ba70-0577a0a3bbbc,1366f284-dd3b-5940-af20-b7a3b07d0b62,F. Häußler\nMarktplatz 6\nGerichtsvollzieheri...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,f. häußler\nmarktplatz 6\ngerichtsvollzieherin...,NaN,False,False,NaN,0cb6fa6492e0550c6ec900e44ad20c4e1fed2355fd88b3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nF. Häußler\nMarktplatz 6\nGerichtsvo...,False,False,False,"[100487, 100460]",None,"{'100460': 'DE31642510600013909693', '100487':..."

In [50]:
dritt['bak_to_ibans']

0     {'145827': 'DE91100110012811132575', '150368':...
1     {'100426': None, '100853': 'DE9744551210000163...
2                  {'100871': 'DE26370502991146111108'}
3                  {'100432': 'DE85100500006011648990'}
4                                                    {}
5     {'100516': 'DE20670505050040370072', '102105':...
6     {'100516': 'DE40670505051200652866', '104114':...
7     {'100215': 'DE42120300001039150386', '102319':...
8                  {'100732': 'DE46269513110163131337'}
9     {'100215': 'DE23120300001306287564', '100999':...
10                                                   {}
11                                                   {}
12                                                   {}
13                                                   {}
14                 {'104099': 'DE79742901003454000382'}
15    {'156937': 'DE08202208000046030406', '161008':...
16    {'100003': 'DE72550703240067352500', '101007':...
17                                                   {}
18    {'100180': 'DE51300209007400026434', '100663':...
19                 {'100005': 'DE88200400000511006901'}
20    {'100607': 'DE44701500003002965923', '108556':...
21    {'100088': 'DE70500105175807889843', '108556':...
22                 {'100005': 'DE05763400610829527101'}
23    {'100516': 'DE67670505050040276203', '102105':...
24    {'100005': 'DE42200411440651077000', '100445':...
25                 {'100892': 'DE18310500001004624324'}
26    {'100530': 'DE09604500504001036873', '101316':...
27                 {'100180': 'DE38300209005300010230'}
28                 {'100909': 'DE94426501501001047867'}
29    {'100005': 'DE75200411660135838100', '100027':...
30    {'100072': 'DE47305305000739501931', '100178':...
31    {'100541': 'DE17765500000008606121', '105513':...
32                                     {'100003': None}
33                                                   {}
34    {'100003': 'DE70250700240201495943', '100181':...
35    {'100003': 'DE42270703240776344460', '101687':...
36                                                   {}
37                                                   {}
38    {'100460': 'DE31642510600013909693', '100487':...
39    {'100500': 'DE93683515576203206872', '105627':...
40    {'100088': 'DE77500105175582724878', '100430':...
41    {'100005': 'DE57360400390181274202', '100827':...
42                                                   {}
43                                                   {}
44    {'101328': 'DE80630910100605346003', '104189':...
45    {'100446': 'DE70654500700008226783', '101434':...
46                                                   {}
47    {'100112': 'DE93503302002275715002', '100118':...
48                                                   {}
49    {'100005': 'DE67532400480105574801', '100178':...
50    {'100816': 'DE05440501990272147116', '108556':...
51                                                   {}
52    {'100493': 'DE53640500001101758030', '102296':...
Name: bak_to_ibans, dtype: object

In [51]:
dritt.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/parameter_extraction/drittauskunft/dritt_streamlit_latestiban.csv", index=False)

In [ ]:
# NOTE: ILOC 49 ENTERESAN, BUNU YARIN GOSTER

## ALL CODE HERE

In [ ]:
from collections import deque

In [ ]:
# REGEXES
KONTOINHABER_REGEX = re.compile(r"\bkontoinhaber\b", re.IGNORECASE)
GENERAL_IBAN_REGEX = re.compile(r'\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){2,7}\s?[A-Z0-9]{1,3}\b')
DRITTAUSKUNFT_BAK_NUMBER_REGEX = re.compile(r"\bbak\s*-\s*(?:nr|nummer)\.?:?\s*\d{6}\b", re.IGNORECASE)
DATE_REGEX = re.compile(
    r"""(?x)
(?<!\d)
(?:
    (?:(?:0?[1-9]|[12]\d)|3[01])\s?[./:-][\s.]?(?:0?[13578]|1[02]|J(?:an(?:uar)?|uli?)|M(?:ärz?|ai)|Aug(?:ust)?|Dez(?:ember)?|Okt(?:ober)?)\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)|
    (?:(?:0?[1-9]|[12]\d)|30)\s?[./:-][\s.]?(?:0?[13-9]|1[012]|J(?:an(?:uar)?|u[nl]i?)|M(?:ärz?|ai)|A(?:pr(?:il)?|ug(?:ust)?)|Sep(?:tember)?|(?:Nov|Dez)(?:ember)?|Okt(?:ober)?)\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)|
    (?:0?[1-9]|[12]\d)\s?[./:-][\s.]?(?:0?2|Fe(?:b(?:ruar)?)?|(?:0?2|Feb(?:r(?:uar)?)?))\s?(?:[./:-][\s.]?)?(?:[1-9]\d(?:[02468][048]|[13579][26])|\d\d)|
    (?:0?[1-9]|[12][0-9])\s?[./:-][\s.]?(?:0?2|Fe(?:b(?:ruar)?)?|(?:0?2|Feb(?:r(?:uar)?)?))\s?(?:[./:-][\s.]?)?(?:[1-9]\d\d\d|\d\d)
)
(?!\d)""",
    re.IGNORECASE | re.VERBOSE,
)

In [ ]:
import dateparser  # same parser used by the Ladung summon_date_extractor
from datetime import datetime


def filter_bak_spans(match_objects):
    # get unique baks, if there is duplicate bak, get the first detected
    unique_baks = {}
    unique_bak_spans = []
    for match in match_objects:
        bak_number = re.search(r"\d{6}", match.group()).group()
        if bak_number not in unique_baks:
            unique_baks[bak_number] = match
            unique_bak_spans.append(match)
    return unique_bak_spans

def split_to_contexts(filtered_match_objects: list, text: str) -> list[str]:
    window_size = 300
    if not filtered_match_objects:
        return [], []
    
    extracted_contexts = []
    bak_numbers = []
    
    for i in range(len(filtered_match_objects)):
        match_i = filtered_match_objects[i]
        match_j = filtered_match_objects[i + 1] if i + 1 < len(filtered_match_objects) else None
        if match_j:
            context_start = max(0, match_i.start())
            context_end = min(len(text), match_j.start())
            context = text[context_start:context_end]
            extracted_contexts.append(context)
            bak_numbers.append(re.search(r"\d{6}", match_i.group()).group())
        else:
            # meaning its last span
            context_start = max(0, match_i.start())
            text_filtered = text[context_start:]
            last_kontinhaber_match = deque(KONTOINHABER_REGEX.finditer(text_filtered), maxlen=1)
            if last_kontinhaber_match:
                context_end = last_kontinhaber_match[0].start() + context_start
            else:
                context_end = context_start + window_size
            context = text[context_start:context_end]
            extracted_contexts.append(context)
            bak_numbers.append(re.search(r"\d{6}", match_i.group()).group())
    return extracted_contexts, bak_numbers
        


def validate_iban(iban: str) -> bool:
    """
    Validate an IBAN using the standard IBAN validation algorithm.
    
    Referance: https://en.wikipedia.org/wiki/International_Bank_Account_Number

    Args:
        iban (str): The IBAN to validate.

    Returns:
        bool: True if the IBAN is valid, False otherwise.
    """
    # Remove spaces and convert to uppercase
    iban = iban.replace(' ', '').upper()
    
    # Check if the IBAN length is valid (between 15 and 34 characters)
    if not (15 <= len(iban) <= 34):
        return False
    
    # Move the first four characters to the end of the string
    rearranged_iban = iban[4:] + iban[:4]
    
    # Replace each letter in the string with two digits, where A=10, B=11, ..., Z=35
    numeric_iban = ''
    for char in rearranged_iban:
        if char.isdigit():
            numeric_iban += char
        else:
            numeric_iban += str(ord(char) - 55)  # Convert letter to number (A=10, B=11, ..., Z=35)
    
    # Convert the string to an integer and compute the remainder of that number on division by 97
    iban_int = int(numeric_iban)
    
    return iban_int % 97 == 1


def _normalize_iban(iban: str) -> str:
    """Canonical form used for uniqueness checks (no spaces, uppercase)."""
    return iban.replace(" ", "").upper()


def extract_date_from_context(context: str) -> datetime | None:
    """Extract the Errichtungsdatum from an IBAN subcontext.

    Reuses the DATE_REGEX and dateparser from the Ladung summon_date_extractor.
    The subcontext spans from an IBAN to the next Kontoinhaber, so it typically
    contains a single relevant date. The first parseable date found is returned.

    Args:
        context (str): Text slice starting at an IBAN and ending before the next
            Kontoinhaber (or end of context).

    Returns:
        datetime | None: The parsed date, or None if no valid date is found.
    """
    if not context:
        return None

    for match in DATE_REGEX.finditer(context):
        parsed = dateparser.parse(match.group(), languages=["de"])
        if parsed is not None:
            return parsed

    return None


def get_latest_iban(ibans: list[str], ibans_date: list[datetime | None]) -> str | None:
    """Return the IBAN with the most recent Errichtungsdatum.

    Args:
        ibans (list[str]): Normalized IBANs found for a single BAK context.
        ibans_date (list[datetime | None]): The Errichtungsdatum for each IBAN,
            aligned by index with ``ibans``. May contain None when no date was
            found.

    Returns:
        str | None: The IBAN with the latest date. If none of the IBANs have a
            date, falls back to the last IBAN found. Returns None if there are
            no IBANs.
    """
    if not ibans:
        return None

    dated_ibans = [(iban, date) for iban, date in zip(ibans, ibans_date) if date is not None]
    if dated_ibans:
        return max(dated_ibans, key=lambda pair: pair[1])[0]

    # No dates available -> fall back to the last IBAN found.
    return ibans[-1]


def extract_iban_from_contexts(contexts: list[str], bak_numbers: list[str]) -> dict[str, str | None]:
    bak_to_iban = {}
    seen_ibans = set()  # normalized IBANs already assigned to a BAK
    for ctx, bak in zip(contexts, bak_numbers):
        extracted_ibans = []
        ibans_date = []
        for iban in GENERAL_IBAN_REGEX.findall(ctx):
            if not validate_iban(iban):
                continue
            norm = _normalize_iban(iban)
            if norm in seen_ibans:
                continue
            # iban is found for the current bak number context. Now we need to extract its date.
            # for that search in subcontext to prevent fetching multiple dates
            # subcontext = starts with iban and ends with first next Kontoinhaber
            subcontext_start = ctx.find(iban)  # start index of the iban in the context
            first_kontinhaber_match = next(KONTOINHABER_REGEX.finditer(ctx[subcontext_start:]), None)
            if first_kontinhaber_match:
                subcontext_end = subcontext_start + first_kontinhaber_match.start()
            else:
                # if no Kontoinhaber is found, the end is the end of the context
                subcontext_end = len(ctx)

            extracted_date = extract_date_from_context(ctx[subcontext_start:subcontext_end])
            # add iban
            seen_ibans.add(norm)
            extracted_ibans.append(norm)
            ibans_date.append(extracted_date)

        latest_iban = get_latest_iban(extracted_ibans, ibans_date)

        bak_to_iban[bak] = latest_iban
    return bak_to_iban


def extract_bak_to_ibans(text: str) -> dict[str, str | None]:
    """Extract a mapping of BAK numbers to their latest validated IBAN from a Drittauskunft document.

    Pipeline:
        1. Find all BAK-Nr. matches in the text.
        2. Deduplicate BAK numbers (keep first occurrence).
        3. Split the text into a context window per BAK.
        4. Extract and validate IBANs within each context, keeping the one with
           the most recent Errichtungsdatum.

    Args:
        text (str): OCR parsed text of a document detected as drittauskunft.

    Returns:
        dict[str, str | None]: Mapping of BAK number -> latest validated IBAN.
    """
    if not text:
        return {}

    match_objects = list(DRITTAUSKUNFT_BAK_NUMBER_REGEX.finditer(text))
    filtered_match_objects = filter_bak_spans(match_objects)
    contexts, bak_numbers = split_to_contexts(filtered_match_objects, text)
    return extract_iban_from_contexts(contexts, bak_numbers)

In [52]:
dritt.iloc[17]

ticket_uuid                        fdddcd76-8ff6-5677-b86b-0a50548c40ee
attachment_id                      cc89240e-f2d4-5f0b-b8ae-a8d52bb6833d
text                   Obergerichtsvollzieherin\nAnschrift\nPäßler R...
object_key            data/aftercourt/drittauskunf_with_invoice/Dr_1...
document_type                                             drittauskunft
cleaned_text          obergerichtsvollzieherin\nanschrift\npäßler ra...
data                                                                NaN
is_pfub                                                           False
is_ladung                                                         False
s3_link                                                             NaN
textract_job_id       0eb7536021829c1555b3b5b46fc1f68d38a4792fd630de...
textract_s3_link      s3://pair-data-engineering-new/ocr_prepared_ou...
is_ve_with_invoice                                                  NaN
text_w_pages          <page_1>\nObergerichtsvollzieherin\nAnschrift\...
is_da_with_invoice                                                 True
is_va                                                             False
no_result                                                          True
bank_numbers                                                         []
local_file_path                                                    None
bak_to_ibans                                                         {}
Name: 17, dtype: object