In [1]:
from python_utilities.db_connection import DbConnection
import pandas as pd

In [2]:
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')

INFO [2026-02-27 13:18:18] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [3]:
query = """
SELECT * 
FROM llm_attachments
WHERE attachment_id NOT LIKE '%%-%%'
"""


data = analytics_db.sql_to_df(query)
data

,id,ticket_uuid,attachment_id,zendesk_id,comment_id,status,file_name,file_extension,status_written_at,created_at,s3_key,s3_bucket
0,776888,,69306,None,None,processed,img-20210107-wa0002_jpg,jpeg,2021-01-07 08:52:21,2021-01-07 08:52:21,107748365130/img-20210107-wa0002_jpg,pair-app-zendesk-production
1,776889,,69307,None,None,processed,img_3306.pdf,pdf,2024-01-02 14:59:05,2024-01-02 14:59:05,127015181135/img_3306.pdf,pair-app-zendesk-production
2,776890,,69308,None,None,processed,20c97d12-fd1b-450b-961c-e8d6a73b58a9.pdf,pdf,2024-01-02 19:23:53,2024-01-02 19:23:53,142429575905/20c97d12-fd1b-450b-961c-e8d6a73b5...,pair-app-zendesk-production
3,776891,,69309,None,None,processed,screenshot_20240102_130218_chrome.pdf,pdf,2024-01-02 12:03:50,2024-01-02 12:03:50,144856447210/screenshot_20240102_130218_chrome...,pair-app-zendesk-production
4,776892,,69310,None,None,processed,nachweis_der_rueckerstattung.pdf,pdf,2024-01-02 16:30:58,2024-01-02 16:30:58,144578802197/nachweis_der_rueckerstattung.pdf,pair-app-zendesk-production
...,...,...,...,...,...,...,...,...,...,...,...,...
34368,3237558,2164faec-c8eb-5283-bf5d-2d1dcdd542f0,54212908,None,None,new,54212908_BriefkopfGericht_20260227_11c35ffa15a...,pdf,2026-02-27 11:44:00,2026-02-27 11:44:00,ocr_source_files/2026-02-27/egvp_id_317543/542...,pair-data-engineering-new
34369,3237559,cdbc14cf-b651-5bd0-b609-0c9a435a2206,54212917,None,None,new,54212917_DR-II_034726_Nachr_Mitlg__an_Glb_uebe...,pdf,2026-02-27 11:44:00,2026-02-27 11:44:00,ocr_source_files/2026-02-27/egvp_id_317545/542...,pair-data-engineering-new
34370,3237560,e4223aca-278d-5489-bf29-aee9b6d9c1fd,54212922,None,None,new,54212922_11aM10321_25_VB-GL_PairFinanceGmbH_4B...,pdf,2026-02-27 11:44:00,2026-02-27 11:44:00,ocr_source_files/2026-02-27/egvp_id_317546/542...,pair-data-engineering-new
34371,3237561,27b9d821-86c4-57b9-ba00-707472a911cc,54212931,None,None,new,54212931_3_dr_103_26_an_gl_sch_zur_vak_nicht_e...,pdf,2026-02-27 11:44:00,2026-02-27 11:44:00,ocr_source_files/2026-02-27/egvp_id_317548/542...,pair-data-engineering-new
34372,3237562,2a955be8-0272-57ad-8175-74fee6a281a1,54212952,None,None,new,54212952_ANSCHR_GP_27_02_2026_b_00_4bcc5fc1148...,pdf,2026-02-27 11:44:00,2026-02-27 11:44:00,ocr_source_files/2026-02-27/egvp_id_317553/542...,pair-data-engineering-new

In [4]:
print( "Data Range:", data.created_at.max().date(), "-", data.created_at.min().date())

Data Range: 2026-02-27 - 2021-01-07

In [5]:
data = data[data.created_at >= '2025-01-20']
data = data[data.status == 'processed']

data.reset_index(drop=True, inplace=True)
data

,id,ticket_uuid,attachment_id,zendesk_id,comment_id,status,file_name,file_extension,status_written_at,created_at,s3_key,s3_bucket
0,1823701,,44528753,None,None,processed,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,pdf,2025-11-22 09:17:20,2025-11-21 15:59:17,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new
1,1823703,,44528764,None,None,processed,44528764_Protokoll_GKB-EV21_19_11_2025__Gl_.pdf,pdf,2025-11-22 09:17:20,2025-11-21 15:59:17,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new
2,1823704,,44528763,None,None,processed,44528763_DR-II_135225_Nachr_GKB-VAKA_21_11_202...,pdf,2025-11-22 09:17:20,2025-11-21 15:59:17,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new
3,1823708,,44528778,None,None,processed,44528778_DR-II_050625_Nachr_Uebermittlung_elek...,pdf,2025-11-22 09:17:21,2025-11-21 15:59:17,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new
4,1823709,,44528777,None,None,processed,44528777_DR-II_050625_Nachr_GKB-HBGA_21_11_202...,pdf,2025-11-22 09:17:21,2025-11-21 15:59:17,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new
...,...,...,...,...,...,...,...,...,...,...,...,...
29340,3235135,e58a3bbe-abb8-5816-adb4-4c1707607e86,54203493,None,None,processed,54203493_ANSCHR_Pair_Finance_GmbH_Pair_Finance...,pdf,2026-02-27 09:08:58,2026-02-27 06:44:00,ocr_source_files/2026-02-27/egvp_id_317018/542...,pair-data-engineering-new
29341,3235136,9f23bd43-2c3b-5972-a353-8172915cd6e7,54203577,None,None,processed,54203577_20aM474_26_VB-GL_PairFinanceGmbH_E20E...,pdf,2026-02-27 09:08:59,2026-02-27 06:44:00,ocr_source_files/2026-02-27/egvp_id_317021/542...,pair-data-engineering-new
29342,3235137,35d58c50-ed11-5c88-aba4-18690f46da98,54203581,None,None,processed,54203581_Dokument_185525_27022026_063106.pdf,pdf,2026-02-27 09:08:59,2026-02-27 06:44:00,ocr_source_files/2026-02-27/egvp_id_317022/542...,pair-data-engineering-new
29343,3235138,c3852ea5-b6e7-5ec4-9aca-fd9341cee3ed,54203585,None,None,processed,54203585_0_sammel1.pdf,pdf,2026-02-27 09:08:59,2026-02-27 06:44:00,ocr_source_files/2026-02-27/egvp_id_317023/542...,pair-data-engineering-new
29344,3235139,fe37da4f-52fb-59d4-9665-7ed65b2c57df,54203590,None,None,processed,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,pdf,2026-02-27 09:08:59,2026-02-27 06:44:00,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new

In [6]:
data.status.value_counts()

status
processed    29345
Name: count, dtype: int64

# fetch text data for attachments

In [7]:
def flatten_attachment_pred_df(df: pd.DataFrame) -> pd.DataFrame:
    metadata_cols = ['attachment_id', 'document_s3_key', 'document_s3_bucket',
                     'file_name', 'textract_job_id', 'textract_status', 'textract_s3_link', 'text']
    try:
        metadata = df[metadata_cols].iloc[[0]].reset_index(drop=True)
    except Exception:
        print("attachment_id:", df['attachment_id'].iloc[0], "is missing some metadata columns.")
        metadata = pd.DataFrame(columns=metadata_cols)

    preds = df[['attachment_id', 'type', 'subtype', 'value']].copy()
    preds['col_name'] = preds['type'] + '__' + preds['subtype'].fillna('')
    pivoted = preds.pivot_table(
        index='attachment_id', columns='col_name', values='value', aggfunc='first'
    ).reset_index(drop=True)

    return pd.concat([metadata, pivoted], axis=1)

In [8]:
import sys
import os
import glob

import boto3
sys.path.append('../../')

from utils.prod_utils import get_data_by_attachment_id

session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')
unique_attchment_ids = data.attachment_id.unique()

CHECKPOINT_DIR = '/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/egvp_full_attachment_data_checkpoints'
CHECKPOINT_PREFIX = 'attachment_data_chunk'
CHECKPOINT_INTERVAL = 1000

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Load already processed attachment_ids from existing checkpoints
existing_files = sorted(glob.glob(f'{CHECKPOINT_DIR}/{CHECKPOINT_PREFIX}_*.csv'))
if existing_files:
    already_processed_df = pd.concat([pd.read_csv(f) for f in existing_files], ignore_index=True)
    already_processed_ids = set(already_processed_df['attachment_id'].astype(str).unique())
    print(f"Resuming: {len(already_processed_ids)} attachment_ids already processed across {len(existing_files)} checkpoint(s).")
else:
    already_processed_ids = set()
    print("Starting fresh.")

pending_ids = [aid for aid in unique_attchment_ids if str(aid) not in already_processed_ids]
print(f"Remaining: {len(pending_ids)} attachment_ids to process.")

chunk = []
chunk_start_index = len(already_processed_ids)
n = len(unique_attchment_ids)

for i, attachment_id in enumerate(pending_ids):
    cur_attch_data = get_data_by_attachment_id(attachment_id, analytics_db, s3, verbose=False)
    chunk.append(cur_attch_data)
    processed_count = chunk_start_index + i + 1
    print(f"Processed {processed_count}/{n} attachment_ids", end='\r')

    if len(chunk) >= CHECKPOINT_INTERVAL:
        chunk_df = pd.concat(chunk, ignore_index=True)
        chunk_index = processed_count // CHECKPOINT_INTERVAL
        chunk_path = f'{CHECKPOINT_DIR}/{CHECKPOINT_PREFIX}_{chunk_index:04d}.csv'
        chunk_df.to_csv(chunk_path, index=False)
        print(f"\nSaved checkpoint: {chunk_path}")
        chunk = []

# Save any remaining records
if chunk:
    chunk_df = pd.concat(chunk, ignore_index=True)
    chunk_index = (chunk_start_index + len(pending_ids)) // CHECKPOINT_INTERVAL + 1
    chunk_path = f'{CHECKPOINT_DIR}/{CHECKPOINT_PREFIX}_{chunk_index:04d}_final.csv'
    chunk_df.to_csv(chunk_path, index=False)
    print(f"\nSaved final checkpoint: {chunk_path}")

# Load all checkpoints into a single DataFrame
all_files = sorted(glob.glob(f'{CHECKPOINT_DIR}/{CHECKPOINT_PREFIX}_*.csv'))
attachment_data = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)
print(f"\nDone. Total records loaded: {len(attachment_data)}")

INFO [2026-02-27 13:18:22] - Found credentials in shared credentials file: ~/.aws/credentials

Resuming: 29345 attachment_ids already processed across 30 checkpoint(s).
Remaining: 0 attachment_ids to process.

Done. Total records loaded: 167901

In [9]:
attachment_data

,attachment_id,document_s3_key,document_s3_bucket,file_name,model_name,type,subtype,value,textract_job_id,textract_status,textract_s3_link,text
0,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,payment_proof,payment_proof,is_payment_proof,'False',67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...
1,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,payment_proof,payment_proof,payment_proof_type,'none',67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...
2,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,multi_attachment,multi_attachment,attachment_type,'invoice',67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...
3,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,aftercourt_classification,aftercourt_classification,is_aftercourt,'True',67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...
4,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,aftercourt_classification,aftercourt_classification,aftercourt_type,'ladung',67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...
...,...,...,...,...,...,...,...,...,...,...,...,...
167896,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,aftercourt_classification_pfub,aftercourt_classification_pfub,aftercourt_type,'pfub_erlass',377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...
167897,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_pred,'True',377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...
167898,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,aftercourt_classification_pfub,aftercourt_classification_pfub,class_prob,'0.55',377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...
167899,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,aftercourt_classification_pfub,aftercourt_classification_pfub,slug,'174132033708',377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...
167900,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,aftercourt_classification_pfub,aftercourt_classification_pfub,debtor_name,'Steve Mosch',377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...

In [10]:
flattened_dfs = []
for attachment_id, group_df in attachment_data.groupby('attachment_id'):
    try:
        flattened_dfs.append(flatten_attachment_pred_df(group_df))
    except Exception as e:
        print(f"Error processing attachment_id {attachment_id}: {e}")

flattened_df = pd.concat(flattened_dfs, ignore_index=True)
print(f"Flattened DataFrame shape: {flattened_df.shape}")
flattened_df

Flattened DataFrame shape: (29345, 46)

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,aftercourt_classification__aftercourt_type,aftercourt_classification__debtor_name,...,aftercourt_classification_ladung__class_pred,aftercourt_classification_ladung__class_prob,aftercourt_classification_pfub__aftercourt_type,aftercourt_classification_pfub__class_pred,aftercourt_classification_pfub__class_prob,aftercourt_classification_ladung__debtor_name,aftercourt_classification_ladung__judicial_summon_date,aftercourt_classification_ladung__slug,aftercourt_classification_pfub__debtor_name,aftercourt_classification_pfub__slug
0,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...,'ladung','Raik Rönnicke',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44528763,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new,44528763_DR-II_135225_Nachr_GKB-VAKA_21_11_202...,aa0f9ffd827347c6a5092cfc5eaa6f70616717aa9a42f4...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Neue Büroanschrift ab 01.12.2024\nDortmunder S...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44528764,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new,44528764_Protokoll_GKB-EV21_19_11_2025__Gl_.pdf,e9aa64c7f95b93fa63717116455de13d0f6984b4b5aaf6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RICHARD STIPP\nDie nachstehend gewählten Formu...,'ladung','Die',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44528777,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new,44528777_DR-II_050625_Nachr_GKB-HBGA_21_11_202...,769f2c7c81621742ac8cc6fbdc1c308187f7c2f6340cb9...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,CHRISTOPH JOST\nKohlstr. 55\n66450 Bexbach-Höc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44528778,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new,44528778_DR-II_050625_Nachr_Uebermittlung_elek...,051c81569a38c7d25956fd1a14e983f44830c9f85c87dd...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,CHRISTOPH JOST\nKohlstr. 55\n66450 Bexbach-Höc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29340,54203493,ocr_source_files/2026-02-27/egvp_id_317018/542...,pair-data-engineering-new,54203493_ANSCHR_Pair_Finance_GmbH_Pair_Finance...,6cc92a56c5f872588c2bc1fd2d5504d130d04decd895cf...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Reutlingen\nVOLLSTRECKUNGSGERICHT\...,NaN,NaN,...,'False','0.02','pfub_erlass','False','0.43',NaN,NaN,NaN,NaN,NaN
29341,54203577,ocr_source_files/2026-02-27/egvp_id_317021/542...,pair-data-engineering-new,54203577_20aM474_26_VB-GL_PairFinanceGmbH_E20E...,674932dadc7a811fdd05b7cbc7299bfa572c483651aa2b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSyke\nAmtsgericht Syke, Amtshof 2...",NaN,NaN,...,'False','0.02','pfub_erlass','True','0.8475',NaN,NaN,NaN,'Eve Stummer','184509923993'
29342,54203581,ocr_source_files/2026-02-27/egvp_id_317022/542...,pair-data-engineering-new,54203581_Dokument_185525_27022026_063106.pdf,4b136029ff45376978a64fa58a71dd94e79f2af7bbd483...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Kai Spitzner\nEuroparatstraße 4\nObergerichtsv...,NaN,NaN,...,'False','0.05','pfub_erlass','False','0.0',NaN,NaN,NaN,NaN,NaN
29343,54203585,ocr_source_files/2026-02-27/egvp_id_317023/542...,pair-data-engineering-new,54203585_0_sammel1.pdf,8ec3cfb4d1edebcbfaf9ed719228254fa07ced061634f2...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieherin\nAmtsgericht: Burg\nM...,NaN,NaN,...,'True','1.0','pfub_erlass','False','0.0','Kerstin Ina Carmen Reinschmidt','24-03-2026','192224133616',NaN,NaN
29344,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...,NaN,NaN,...,'False','0.05','pfub_erlass','True','0.55',NaN,NaN,NaN,'Steve Mosch','174132033708'

In [11]:
flattened_df.attachment_id.nunique()

29345

In [14]:
drop =  ['debt_counseling_attachment__attachment_type',
       'debt_counseling_attachment__counselling_slug',
       'debt_counseling_attachment__counsellor_address',
       'debt_counseling_attachment__counsellor_firstname',
       'debt_counseling_attachment__counsellor_lastname',
       'debt_counseling_attachment__debtor_firstname',
       'debt_counseling_attachment__debtor_lastname',
       'multi_attachment__attachment_type', 'payment_proof__is_payment_proof',
       'payment_proof__payment_proof_type',
       'debt_counseling_attachment__counsellor_email',
       'debt_counseling_attachment__counsellor_agency_name',
       'debt_counseling_attachment__casefile_number',
       'debt_counseling_attachment__installment_plan_start_date',
       'debt_counseling_attachment__monthly_installment_amount_offer_to_us',
       'debt_counseling_attachment__number_of_installments',
       'debt_counseling_attachment__settlement_amount_offer_to_us',
       'payment_proof__payment_amount', 'payment_proof__payment_date',
       'payment_proof__recipient', 'payment_proof__recipient_iban',
       'payment_proof__sender_iban']

flattened_df.drop(columns=drop, inplace=True)
flattened_df

,attachment_id,document_s3_key,document_s3_bucket,file_name,textract_job_id,textract_status,textract_s3_link,text,aftercourt_classification__aftercourt_type,aftercourt_classification__debtor_name,...,aftercourt_classification_ladung__class_pred,aftercourt_classification_ladung__class_prob,aftercourt_classification_pfub__aftercourt_type,aftercourt_classification_pfub__class_pred,aftercourt_classification_pfub__class_prob,aftercourt_classification_ladung__debtor_name,aftercourt_classification_ladung__judicial_summon_date,aftercourt_classification_ladung__slug,aftercourt_classification_pfub__debtor_name,aftercourt_classification_pfub__slug
0,44528753,ocr_source_files/2025-11-21/egvp_id_263308/445...,pair-data-engineering-new,44528753_Dr_ii_788_25_aus_schreibmaschine.pdf,67060082c28ff4555915be5927987865ee1585937169a3...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Gerichtsvollzieher\nAG Pasewalk\nThomas Rex\nZ...,'ladung','Raik Rönnicke',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44528763,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new,44528763_DR-II_135225_Nachr_GKB-VAKA_21_11_202...,aa0f9ffd827347c6a5092cfc5eaa6f70616717aa9a42f4...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Neue Büroanschrift ab 01.12.2024\nDortmunder S...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44528764,ocr_source_files/2025-11-21/egvp_id_263309/445...,pair-data-engineering-new,44528764_Protokoll_GKB-EV21_19_11_2025__Gl_.pdf,e9aa64c7f95b93fa63717116455de13d0f6984b4b5aaf6...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,RICHARD STIPP\nDie nachstehend gewählten Formu...,'ladung','Die',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44528777,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new,44528777_DR-II_050625_Nachr_GKB-HBGA_21_11_202...,769f2c7c81621742ac8cc6fbdc1c308187f7c2f6340cb9...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,CHRISTOPH JOST\nKohlstr. 55\n66450 Bexbach-Höc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44528778,ocr_source_files/2025-11-21/egvp_id_263312/445...,pair-data-engineering-new,44528778_DR-II_050625_Nachr_Uebermittlung_elek...,051c81569a38c7d25956fd1a14e983f44830c9f85c87dd...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,CHRISTOPH JOST\nKohlstr. 55\n66450 Bexbach-Höc...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29340,54203493,ocr_source_files/2026-02-27/egvp_id_317018/542...,pair-data-engineering-new,54203493_ANSCHR_Pair_Finance_GmbH_Pair_Finance...,6cc92a56c5f872588c2bc1fd2d5504d130d04decd895cf...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Reutlingen\nVOLLSTRECKUNGSGERICHT\...,NaN,NaN,...,'False','0.02','pfub_erlass','False','0.43',NaN,NaN,NaN,NaN,NaN
29341,54203577,ocr_source_files/2026-02-27/egvp_id_317021/542...,pair-data-engineering-new,54203577_20aM474_26_VB-GL_PairFinanceGmbH_E20E...,674932dadc7a811fdd05b7cbc7299bfa572c483651aa2b...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,"Amtsgericht\nSyke\nAmtsgericht Syke, Amtshof 2...",NaN,NaN,...,'False','0.02','pfub_erlass','True','0.8475',NaN,NaN,NaN,'Eve Stummer','184509923993'
29342,54203581,ocr_source_files/2026-02-27/egvp_id_317022/542...,pair-data-engineering-new,54203581_Dokument_185525_27022026_063106.pdf,4b136029ff45376978a64fa58a71dd94e79f2af7bbd483...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Kai Spitzner\nEuroparatstraße 4\nObergerichtsv...,NaN,NaN,...,'False','0.05','pfub_erlass','False','0.0',NaN,NaN,NaN,NaN,NaN
29343,54203585,ocr_source_files/2026-02-27/egvp_id_317023/542...,pair-data-engineering-new,54203585_0_sammel1.pdf,8ec3cfb4d1edebcbfaf9ed719228254fa07ced061634f2...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Obergerichtsvollzieherin\nAmtsgericht: Burg\nM...,NaN,NaN,...,'True','1.0','pfub_erlass','False','0.0','Kerstin Ina Carmen Reinschmidt','24-03-2026','192224133616',NaN,NaN
29344,54203590,ocr_source_files/2026-02-27/egvp_id_317024/542...,pair-data-engineering-new,54203590_Schreiben_b_00_4bc85da570ba6912e06362...,377fc4e6038fa8a8bd68b5eb245dce6633e3ac106cbe14...,SUCCEEDED,s3://pair-data-engineering-new/ocr_prepared_ou...,Amtsgericht Dresden\nAmtsgericht Dresden\nAbte...,NaN,NaN,...,'False','0.05','pfub_erlass','True','0.55',NaN,NaN,NaN,'Steve Mosch','174132033708'

In [17]:
flattened_df.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/analysis_data/full_egvp_attachment_data_2025-01-20_to_2025-02-27.csv", index=False)