We have protokol documents very similar to ladung, which model consufes. Get fp examples and re-train the model

In [2]:
import pandas as pd
import os
import sys
import dill

# Add notebooks/after-court to path
current_dir = os.path.dirname(os.path.abspath('__file__'))
after_court_dir = os.path.join(current_dir, '..')
sys.path.insert(0, after_court_dir)

from utils import parse_pdfs_with_textract, apply_tokenization, apply_replace_with_tags, apply_text_cleaning, plot_token_counts_by_document_type,get_token_frequency

In [ ]:
# fp_data_protokol = pd.read_csv('/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/data/improvments_data/ladung_fp_protokoll_docs.csv')
# fp_data_protokol['document_type'] = 'fp_protocol'
# fp_data_protokol['is_ladung'] = 0
# fp_data_invoice = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/data/improvments_data/final_fp_invoice_data_ladung.csv")
# fp_data_invoice.rename(columns={'text':'texts'}, inplace=True)
# fp_data_invoice['document_type'] = 'fp_invoice'
# fp_data_invoice['is_ladung'] = 0

# latest_full_data = pd.read_csv(r'../data/PFUB_ERLASS_dataset_processed_with_geschaeftsnummer.csv')

# current_model_path = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/models/classification/15-01-2026_binary_ladung_rf_classifier_v1.dill"
# current_model = dill.load(open(current_model_path, 'rb'))


# fp_data = pd.concat([fp_data_protokol, fp_data_invoice], ignore_index=True)

In [ ]:
# fp_data['document_type'].value_counts()

In [ ]:
# fp_data

In [4]:
VEC_PATH = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/models/vectorizers/05-12-2026_tf_idf_vectorizer_v1.dill"
DATA_PATH = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/model_training_data/ladung/18-02-2026-ladung_training_data_with_bailiff_ip.csv"
data = pd.read_csv(DATA_PATH)
data.document_type.value_counts()

document_type
ladung_va                                 2029
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
fp_invoice                                 157
approved_attachment_and_transfer_order      60
enforcement_order                           23
bailiff_ip                                  17
contradiction                                3
vermögensverzeichnis                         3
Name: count, dtype: int64

In [ ]:
data

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes...",antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5350,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,False,False,NaN,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,NaN
5351,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"paul-rohland-str.2\n06712 zeitz, elster\ntel. ...",NaN,False,False,NaN,"paul-rohland-str.2\n<NUMBER> zeitz, elster\nte...",NaN,NaN
5352,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,wolfgang lurz\nschragenhofstraße 27\n80992 mün...,NaN,False,False,NaN,wolfgang lurz\nschragenhofstraße <NUMBER>\n<NU...,NaN,NaN
5353,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\n33104 paderborn\nwagen...,NaN,False,False,NaN,obergerichtsvollzieher\n<NUMBER> paderborn\nwa...,NaN,NaN
5354,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,False,False,NaN,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,NaN

In [3]:
import os

notebook_dir = r'/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks'
project_dir = os.path.dirname(notebook_dir)
print("Notebook Directory:", notebook_dir)
print("Project Directory:", project_dir)
os.chdir(project_dir)

Notebook Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks
Project Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition

In [7]:
data.columns

Index(['text', 'object_key', 'document_type', 'cleaned_text', 'data',
       'is_pfub', 'is_ladung', 'tokenized', 'text_w_tags', 'attachment_id',
       's3_link'],
      dtype='object')

In [10]:
check = data[['text', 'object_key', 'document_type','attachment_id','s3_link']]
check

,text,object_key,document_type,attachment_id,s3_link
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,NaN,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,NaN,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,NaN,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,NaN,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,NaN,NaN
...,...,...,...,...,...
5350,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,NaN,NaN
5351,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,NaN,NaN
5352,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,NaN,NaN
5353,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,NaN,NaN
5354,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,NaN,NaN

In [5]:
data['is_ladung'].value_counts()

is_ladung
False    3326
True     2029
Name: count, dtype: int64

In [6]:
data

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes...",antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5350,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,False,False,NaN,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,NaN
5351,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"paul-rohland-str.2\n06712 zeitz, elster\ntel. ...",NaN,False,False,NaN,"paul-rohland-str.2\n<NUMBER> zeitz, elster\nte...",NaN,NaN
5352,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,wolfgang lurz\nschragenhofstraße 27\n80992 mün...,NaN,False,False,NaN,wolfgang lurz\nschragenhofstraße <NUMBER>\n<NU...,NaN,NaN
5353,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\n33104 paderborn\nwagen...,NaN,False,False,NaN,obergerichtsvollzieher\n<NUMBER> paderborn\nwa...,NaN,NaN
5354,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,False,False,NaN,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,NaN

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Make sure to import ClassificationSpacyLemmaTokenizer from the source code.
from src.services.models.aftercourt_tokenizer import ClassificationSpacyLemmaTokenizer

VEC_PATH = "path to vec"
tf_idf_vectorizer = dill.load(open(VEC_PATH, 'rb'))

X_text = data['text_w_tags']
y = data['is_ladung']

# train test split
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train set size: {len(X_train_text)}, Test set size: {len(X_test_text)}")
print(f"Train set is pfub dist: {y_train.value_counts(normalize=True)}")
print(f"Test set is pfub dist: {y_test.value_counts(normalize=True)}")


X_train_tfidf = tf_idf_vectorizer.transform(X_train_text)
X_test_tfidf = tf_idf_vectorizer.transform(X_test_text)

In [ ]:
# from src.services.attachment_processing.base_input_processor import AfterCourtAttachmentPreprocessor
# from src.domain.base.blueprints import AfterCourtPreprocessingBlueprint

In [ ]:
# # Initialize preprocessor
# config = AfterCourtPreprocessingBlueprint(
#     normalize_whitespace=True,
#     remove_short_lines=True,
#     short_line_threshold=3,
#     remove_html_tags=True,
#     lowercase=True,
#     clean_text_type='processed'
# )

# preprocessor = AfterCourtAttachmentPreprocessor(name='after_court', preprocessing_config=config)

# # Apply replace_with_tags directly to each text

# fp_data['text_w_tags'] = fp_data['texts'].apply(lambda x: preprocessor._replace_with_tags(preprocessor._process(x)))

Check current model predicted probs for fp_data

In [ ]:

# probs = current_model.predict_proba(tf_idf_vectorizer.transform(fp_data['text_w_tags']))[:, 1]
# prob_df = fp_data[['attachment_id','document_type']].copy()
# prob_df['ladung_probability'] = probs

In [ ]:
# prob_df

In [ ]:
# import matplotlib.pyplot as plt

# # Get unique document types and assign colors
# document_types = prob_df['document_type'].unique()
# colors = plt.cm.tab10(range(len(document_types)))
# color_map = dict(zip(document_types, colors))

# # Create histogram with colors by document type
# plt.figure(figsize=(10, 6))
# for doc_type in document_types:
#     data_subset = prob_df[prob_df['document_type'] == doc_type]['ladung_probability']
#     plt.hist(data_subset, bins=20, alpha=0.6, label=doc_type, color=color_map[doc_type])

# plt.title('Histogram of Ladung Probabilities by Document Type')
# plt.xlabel('Ladung Probability')
# plt.ylabel('Frequency')
# plt.legend()
# plt.show()

In [ ]:
# latest_full_data

In [ ]:
# data = pd.concat([latest_full_data, fp_data])
# data = data.reset_index(drop=True)

In [8]:
data['document_type'].value_counts()

document_type
ladung_va                                 2029
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
fp_invoice                                 157
approved_attachment_and_transfer_order      60
enforcement_order                           23
bailiff_ip                                  17
contradiction                                3
vermögensverzeichnis                         3
Name: count, dtype: int64

In [9]:
data['is_ladung'].value_counts()

is_ladung
False    3326
True     2029
Name: count, dtype: int64

get the vectorizer

train test split

In [10]:

X_text = data['text_w_tags']
y = data['is_ladung']

# train test split
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train set size: {len(X_train_text)}, Test set size: {len(X_test_text)}")
print(f"Train set is pfub dist: {y_train.value_counts(normalize=True)}")
print(f"Test set is pfub dist: {y_test.value_counts(normalize=True)}")

Train set size: 4284, Test set size: 1071
Train set is pfub dist: is_ladung
False    0.621148
True     0.378852
Name: proportion, dtype: float64
Test set is pfub dist: is_ladung
False    0.620915
True     0.379085
Name: proportion, dtype: float64

In [11]:
document_types_train = data.loc[X_train_text.index, 'document_type']
document_types_test = data.loc[X_test_text.index, 'document_type']

In [12]:
document_types_test.shape

(1071,)

In [13]:
document_types_train.value_counts()

document_type
ladung_va                                 1623
mail_attachments                           811
monierung_mb                               439
attachment_and_transfer_order              424
approved_seizure                           329
court_inbox                                289
fp_protocol                                172
fp_invoice                                 114
approved_attachment_and_transfer_order      44
enforcement_order                           19
bailiff_ip                                  15
contradiction                                3
vermögensverzeichnis                         2
Name: count, dtype: int64

In [14]:
document_types_test.value_counts()

document_type
ladung_va                                 406
mail_attachments                          195
attachment_and_transfer_order             115
monierung_mb                              106
approved_seizure                           79
court_inbox                                57
fp_protocol                                47
fp_invoice                                 43
approved_attachment_and_transfer_order     16
enforcement_order                           4
bailiff_ip                                  2
vermögensverzeichnis                        1
Name: count, dtype: int64

In [15]:
X_train_tfidf = tf_idf_vectorizer.transform(X_train_text)
X_test_tfidf = tf_idf_vectorizer.transform(X_test_text)

In [16]:
# basic RF

from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tfidf, y_train)

RandomForestClassifier(random_state=42)

compare probs of old and new on fp data

In [ ]:
# probs_new_model = rf_classifier.predict_proba(tf_idf_vectorizer.transform(fp_data['text_w_tags']))[:, 1]
# prob_df['ladung_probability_new_model'] = probs_new_model

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Get unique document types
# document_types = prob_df['document_type'].unique()
# n_types = len(document_types)

# # Create subplots for each document type
# fig, axes = plt.subplots(n_types, 1, figsize=(10, 6 * n_types))

# # Handle case where there's only one document type
# if n_types == 1:
#     axes = [axes]

# # Plot for each document type
# for idx, doc_type in enumerate(document_types):
#     # Filter data for this document type
#     df_subset = prob_df[prob_df['document_type'] == doc_type]
    
#     # Create the KDE plot
#     sns.kdeplot(df_subset['ladung_probability'], label='Current Model', fill=True, alpha=0.5, ax=axes[idx])
#     sns.kdeplot(df_subset['ladung_probability_new_model'], label='New Model', fill=True, alpha=0.5, ax=axes[idx])
    
#     axes[idx].set_title(f'Ladung Probability Distribution Comparison - {doc_type}')
#     axes[idx].set_xlabel('Ladung Probability')
#     axes[idx].set_ylabel('Density')
#     axes[idx].legend()

# plt.tight_layout()
# plt.show()

In [ ]:
# # Inspect probability values
# print("Current Model Probabilities:")
# print(f"Min: {prob_df['ladung_probability'].min()}")
# print(f"Max: {prob_df['ladung_probability'].max()}")
# print(f"Mean: {prob_df['ladung_probability'].mean()}")
# print("\nNew Model Probabilities:")
# print(f"Min: {prob_df['ladung_probability_new_model'].min()}")
# print(f"Max: {prob_df['ladung_probability_new_model'].max()}")
# print(f"Mean: {prob_df['ladung_probability_new_model'].mean()}")
# print("\nSample of prob_df:")
# print(prob_df.head(10))

In [ ]:
# prob_df

In [17]:
y_pred_probs = rf_classifier.predict_proba(X_test_tfidf)[:, 1]
y_pred = y_pred_probs >= 0.6

In [18]:
doc_type_to_pred = pd.DataFrame({
    'document_type': document_types_test,
    'predicted_probs': y_pred_probs
})

In [19]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create subplots with 1 row and 2 columns
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Distribution of Predicted Probabilities by Document Type (Box Plot)',
                    'Distribution of Predicted Probabilities by Document Type (Violin Plot)')
)

# Get unique document types
doc_types = doc_type_to_pred['document_type'].unique()

# Add box plots
for doc_type in doc_types:
    data_subset = doc_type_to_pred[doc_type_to_pred['document_type'] == doc_type]
    fig.add_trace(
        go.Box(
            y=data_subset['predicted_probs'],
            name=doc_type,
            boxmean='sd'
        ),
        row=1, col=1
    )

# Add violin plots
for doc_type in doc_types:
    data_subset = doc_type_to_pred[doc_type_to_pred['document_type'] == doc_type]
    fig.add_trace(
        go.Violin(
            y=data_subset['predicted_probs'],
            name=doc_type,
            box_visible=True,
            meanline_visible=True
        ),
        row=1, col=2
    )

# Add threshold line to violin plot
fig.add_hline(
    y=0.95, 
    line_dash="dash", 
    line_color="red",
    annotation_text="Threshold (0.95)",
    annotation_position="right",
    col=2
)

# Update layout
fig.update_layout(
    height=500,
    width=1400,
    showlegend=True,
    title_text="Predicted Probabilities Analysis by Document Type"
)

# Update y-axes labels
fig.update_yaxes(title_text="Predicted Probability", row=1, col=1)
fig.update_yaxes(title_text="Predicted Probability", row=1, col=2)

fig.show()

# Summary statistics by document type
print("\nSummary Statistics by Document Type:")
print(doc_type_to_pred.groupby('document_type')['predicted_probs'].describe())

Summary Statistics by Document Type:
                                        count      mean       std   min  \
document_type
approved_attachment_and_transfer_order   16.0  0.004375  0.010935  0.00
approved_seizure                         79.0  0.001519  0.004554  0.00
attachment_and_transfer_order           115.0  0.000174  0.001865  0.00
bailiff_ip                                2.0  0.170000  0.240416  0.00
court_inbox                              57.0  0.001930  0.009342  0.00
enforcement_order                         4.0  0.000000  0.000000  0.00
fp_invoice                               43.0  0.079535  0.133291  0.00
fp_protocol                              47.0  0.003617  0.012585  0.00
ladung_va                               406.0  0.988916  0.038488  0.58
mail_attachments                        195.0  0.005231  0.017060  0.00
monierung_mb                            106.0  0.000189  0.001367  0.00
vermögensverzeichnis                      1.0  0.000000       NaN  0.00

                                          25%   50%    75%   max
document_type
approved_attachment_and_transfer_order  0.000  0.00  0.000  0.04
approved_seizure                        0.000  0.00  0.000  0.03
attachment_and_transfer_order           0.000  0.00  0.000  0.02
bailiff_ip                              0.085  0.17  0.255  0.34
court_inbox                             0.000  0.00  0.000  0.05
enforcement_order                       0.000  0.00  0.000  0.00
fp_invoice                              0.000  0.01  0.115  0.55
fp_protocol                             0.000  0.00  0.000  0.08
ladung_va                               1.000  1.00  1.000  1.00
mail_attachments                        0.000  0.00  0.000  0.17
monierung_mb                            0.000  0.00  0.000  0.01
vermögensverzeichnis                    0.000  0.00  0.000  0.00

In [20]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)


print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""
    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, 
    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}
"""

Accuracy: 0.9991

Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       665
        True       1.00      1.00      1.00       406

    accuracy                           1.00      1071
   macro avg       1.00      1.00      1.00      1071
weighted avg       1.00      1.00      1.00      1071


Confusion Matrix:
[[665   0]
 [  1 405]]

'\n    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, \n    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}\n'

In [ ]:
import pandas as pd

# Create dataframe with predictions, actual values, and original indexes
results_df = pd.DataFrame({
    'index': y_test.index,
    'y_test': y_test.values,
    'y_pred': y_pred
})

results_df

      index  y_test  y_pred
0       762   False   False
1      2598    True    True
2      3414    True    True
3      3321    True    True
4      5166   False   False
...     ...     ...     ...
1066   1465   False   False
1067   2504    True    True
1068   5005   False   False
1069   4566   False   False
1070   3274    True    True

[1071 rows x 3 columns]

In [22]:
results_df['FP'] = (results_df['y_test'] == 0) & (results_df['y_pred'] == True)
results_df['FN'] = (results_df['y_test'] == 1) & (results_df['y_pred'] == False)

In [23]:
print("Total fp:", results_df['FP'].sum())
print("Total fn:", results_df['FN'].sum())

Total fp: 0
Total fn: 1

In [24]:
fp = results_df[results_df['FP']]
fn = results_df[results_df['FN']]

In [25]:
model_fp_preds = data.loc[fp['index']].copy()

In [26]:
model_fp_preds

Empty DataFrame
Columns: [text, object_key, document_type, cleaned_text, data, is_pfub, is_ladung, tokenized, text_w_tags, attachment_id, s3_link]
Index: []

In [27]:
model_fn_preds = data.loc[fn['index']].copy()

# Add predicted probabilities to model_fn_preds
# Create a mapping from test indices to predicted probabilities
prob_mapping = pd.Series(y_pred_probs, index=y_test.index)
model_fn_preds['predicted_prob'] = model_fn_preds.index.map(prob_mapping)

In [28]:
model_fn_preds

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link,predicted_prob
3103,Bitte tragen Sie ein Mund/Nasen-Schutz bei Bet...,24.07.2024/ocr-v2_DR-II_037724_Nachr_kenn_23_0...,ladung_va,bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,False,True,"['bitte', 'tragen', 'mund', 'nasen-schutz', 'b...",bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,NaN,0.58

save the new ladung binary model

In [ ]:
# # save the trained model
# save_path = os.path.join(notebook_dir, "after-court/models/classification/28-01-2026_binary_ladung_rf_classifier_v1.dill")
# with open(save_path, "wb") as f:
#     dill.dump(rf_classifier, f)

In [29]:
ths = [0.1,0.5,0.6,0.7,0.8,0.90, 0.91, 0.92, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99]

threshold_results = []

for th in ths:
    y_pred_label = y_pred_probs >= th
    
    # Calculate confusion matrix components
    tp = ((y_pred_label == 1) & (y_test == 1)).sum()
    fp = ((y_pred_label == 1) & (y_test == 0)).sum()
    tn = ((y_pred_label == 0) & (y_test == 0)).sum()
    fn = ((y_pred_label == 0) & (y_test == 1)).sum()
    
    # Calculate metrics
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    accuracy = (tp + tn) / (tp + tn + fp + fn)
    
    threshold_results.append({
        'threshold': th,
        'tp': tp,
        'fp': fp,
        'tn': tn,
        'fn': fn,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'accuracy': accuracy
    })

# Create DataFrame
threshold_df = pd.DataFrame(threshold_results)
threshold_df

    threshold   tp  fp   tn  fn  precision    recall  f1_score  accuracy
0        0.10  406  15  650   0   0.964371  1.000000  0.981862  0.985994
1        0.50  406   1  664   0   0.997543  1.000000  0.998770  0.999066
2        0.60  405   0  665   1   1.000000  0.997537  0.998767  0.999066
3        0.70  404   0  665   2   1.000000  0.995074  0.997531  0.998133
4        0.80  403   0  665   3   1.000000  0.992611  0.996292  0.997199
5        0.90  395   0  665  11   1.000000  0.972906  0.986267  0.989729
6        0.91  394   0  665  12   1.000000  0.970443  0.985000  0.988796
7        0.92  390   0  665  16   1.000000  0.960591  0.979899  0.985061
8        0.93  388   0  665  18   1.000000  0.955665  0.977330  0.983193
9        0.95  381   0  665  25   1.000000  0.938424  0.968234  0.976657
10       0.96  376   0  665  30   1.000000  0.926108  0.961637  0.971989
11       0.97  372   0  665  34   1.000000  0.916256  0.956298  0.968254
12       0.98  361   0  665  45   1.000000  0.889163  0.941330  0.957983
13       0.99  348   0  665  58   1.000000  0.857143  0.923077  0.945845

In [30]:
import plotly.graph_objects as go

# Create interactive plot with multiple metrics
fig = go.Figure()

# Add traces for each metric
fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['precision'],
    mode='lines+markers',
    name='Precision',
    line=dict(color='blue', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['recall'],
    mode='lines+markers',
    name='Recall',
    line=dict(color='green', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['f1_score'],
    mode='lines+markers',
    name='F1 Score',
    line=dict(color='red', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['accuracy'],
    mode='lines+markers',
    name='Accuracy',
    line=dict(color='purple', width=2),
    marker=dict(size=8)
))

# Add vertical line at current threshold (0.95)
fig.add_vline(
    x=0.95,
    line_dash="dash",
    line_color="gray",
    annotation_text="Current Threshold (0.95)",
    annotation_position="top"
)

# Update layout
fig.update_layout(
    title='Performance Metrics vs Threshold',
    xaxis_title='Threshold',
    yaxis_title='Score',
    hovermode='x unified',
    height=500,
    width=1000,
    legend=dict(
        yanchor="middle",
        y=0.5,
        xanchor="right",
        x=1.15,
        bgcolor="rgba(255, 255, 255, 0.8)",
        bordercolor="gray",
        borderwidth=1
    )
)

fig.show()

# Display metrics at current threshold (0.95)
print("\nMetrics at threshold = 0.95:")
print(threshold_df[threshold_df['threshold'] == 0.95].T)

Metrics at threshold = 0.95:
                    9
threshold    0.950000
tp         381.000000
fp           0.000000
tn         665.000000
fn          25.000000
precision    1.000000
recall       0.938424
f1_score     0.968234
accuracy     0.976657

# check false negatives

In [ ]:
model_fn_preds

In [ ]:
import boto3
import os

# Setup S3 client with specific profile
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3_client = session.client('s3')

# Create tmp_pdfs directory if it doesn't exist
tmp_dir = os.path.join(os.getcwd(), 'tmp_pdfs')
os.makedirs(tmp_dir, exist_ok=True)

print(f"{'='*80}")
print(f"Downloading False Negative PDFs to: {tmp_dir}")
print(f"Total False Negatives: {len(model_fn_preds)}")
print(f"{'='*80}\n")

# Download PDFs for false negative predictions
downloaded = 0
failed = 0

for idx, row in model_fn_preds.iterrows():
    predicted_prob = row['predicted_prob']
    doc_type = row['document_type']
    key = row['object_key']
    s3_bucket = "pair-scanner"
    
    # Extract filename from key
    filename = os.path.basename(key)
    local_path = os.path.join(tmp_dir, filename)
    
    print(f"\n{'-'*80}")
    print(f"\033[1m\033[96m📄 Document {downloaded + failed + 1}/{len(model_fn_preds)}\033[0m")
    print(f"   \033[93mDatabase Index\033[0m       : \033[1m{idx}\033[0m")
    print(f"   \033[93mGT Document Type\033[0m     : {doc_type}")
    print(f"   \033[93mPredicted Ladung Prob\033[0m: \033[1m{predicted_prob:.4f}\033[0m")
    print(f"   \033[93mFilename\033[0m             : {filename}")
    print(f"   \033[93mS3 Path\033[0m              : s3://{s3_bucket}/{key}")
    
    try:
        s3_client.download_file(s3_bucket, key, local_path)
        print(f"   \033[92m✅ Status\033[0m            : Downloaded successfully")
        print(f"   \033[93mLocal Path\033[0m           : {local_path}")
        downloaded += 1
    except Exception as e:
        print(f"   \033[91m❌ Status\033[0m            : Failed")
        print(f"   \033[91mError\033[0m                : {e}")
        failed += 1
    
print(f"\n\033[1m{'='*80}\033[0m")
print(f"\033[1m\033[92mDownload Summary: {downloaded} succeeded\033[0m, \033[91m{failed} failed\033[0m")
print(f"\033[1m{'='*80}\033[0m")

# index_needs_to_be_fixed
1) 2146 is invoice
2) 2950 is invoice
3) 1342 is invoice
4) 2613 is invoice
5) 2027 weird data, delete
6) 1071 is invoice
7) 40 is invoice
8) 3138 is invoice
9) 1070 is invoice
10) 1109 is invoice
11) 2154 is invoice
12) 1324 is invoice
13) 3139 is invoice

save the updated model, train on all dataset

In [31]:
# retrain the model with updated data
X_text_updated = data['text_w_tags']
y_updated = data['is_ladung']
X_tfidf_updated = tf_idf_vectorizer.transform(X_text_updated)
rf_classifier_updated = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier_updated.fit(X_tfidf_updated, y_updated)

RandomForestClassifier(random_state=42)

In [ ]:
# # save the2 trained model with dill
# save_path = os.path.join(notebook_dir, "after-court/models/classification/18-02-2026_binary_ladung_rf_classifier_v1.dill")
# with open(save_path, "wb") as f:
#     dill.dump(rf_classifier_updated, f)