We have protokol documents very similar to ladung, which model consufes. Get fp examples and re-train the model

In [49]:
import pandas as pd
import dill

In [50]:
# fp_data_protokol = pd.read_csv('/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/data/improvments_data/ladung_fp_protokoll_docs.csv')
# fp_data_protokol['document_type'] = 'fp_protocol'
# fp_data_protokol['is_ladung'] = 0
# fp_data_invoice = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/data/improvments_data/final_fp_invoice_data_ladung.csv")
# fp_data_invoice.rename(columns={'text':'texts'}, inplace=True)
# fp_data_invoice['document_type'] = 'fp_invoice'
# fp_data_invoice['is_ladung'] = 0

# latest_full_data = pd.read_csv(r'../data/PFUB_ERLASS_dataset_processed_with_geschaeftsnummer.csv')

# current_model_path = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/models/classification/15-01-2026_binary_ladung_rf_classifier_v1.dill"
# current_model = dill.load(open(current_model_path, 'rb'))


# fp_data = pd.concat([fp_data_protokol, fp_data_invoice], ignore_index=True)

In [51]:
# fp_data['document_type'].value_counts()

In [52]:
# fp_data

In [53]:
VEC_PATH = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/models/vectorizers/05-12-2026_tf_idf_vectorizer_v1.dill"
DATA_PATH = "/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court/model_training_data/ladung/05-02-2026-ladung_training_data.csv"
data = pd.read_csv(DATA_PATH)

In [54]:
import os

notebook_dir = r'/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks'
project_dir = os.path.dirname(notebook_dir)
print("Notebook Directory:", notebook_dir)
print("Project Directory:", project_dir)
os.chdir(project_dir)

Notebook Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks
Project Directory: /Users/melih.gorgulu/Desktop/Projects/intent_recognition

In [55]:
data

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link
0,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",<PHONE> <NUMBER>\nantrag auf erlass eines pfän...,NaN,NaN
1,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,"['antrag', 'erlass', 'pfänd', 'überweisungsbes...",antrag auf erlass eines pfänd <NUMBER><PHONE>\...,NaN,NaN
2,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,"['antrag', 'erlass', 'pfändun', 'überweisungsb...",antrag auf erlass eines pfändun\n<PHONE> <NUMB...,NaN,NaN
3,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,"['antrag', 'erlass', 'pfändung', 'überweisungs...",antrag auf erlass eines pfändungs\n<NUMBER> <N...,NaN,NaN
4,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,"['antrag', 'erlass', 'pfändu', 'überweisungsbe...",antrag auf erlass eines pfändu\n<PHONE> <NUMBE...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5333,Nicole Wernicke\nHanauer Straße 44\nGerichtsvo...,NaN,fp_invoice,NaN,NaN,NaN,False,NaN,nicole wernicke\nhanauer straße <NUMBER>\ngeri...,NaN,NaN
5334,Obergerichtsvollzieher Kiermeier\nAmtsgericht ...,NaN,fp_invoice,NaN,NaN,NaN,False,NaN,obergerichtsvollzieher kiermeier\namtsgericht ...,NaN,NaN
5335,Elvira Jugovic\nHindenburgstraße 45 Rgb.\nGeri...,NaN,fp_invoice,NaN,NaN,NaN,False,NaN,elvira jugovic\nhindenburgstraße <NUMBER> rgb....,NaN,NaN
5336,Vanessa Göldner\nAm alten Bahnhof 9 (vormals 1...,NaN,fp_invoice,NaN,NaN,NaN,False,NaN,vanessa göldner\nam alten bahnhof <NUMBER> (vo...,NaN,NaN
5337,Obergerichtsvollzieher Lars Kramer\nPostanschr...,NaN,fp_invoice,NaN,NaN,NaN,False,NaN,obergerichtsvollzieher lars kramer\npostanschr...,NaN,NaN

In [56]:
data['is_ladung'].value_counts()

is_ladung
False    3309
True     2029
Name: count, dtype: int64

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Make sure to import ClassificationSpacyLemmaTokenizer from the source code.
from src.services.models.aftercourt_tokenizer import ClassificationSpacyLemmaTokenizer
tf_idf_vectorizer = dill.load(open(VEC_PATH, 'rb'))

In [58]:
# from src.services.attachment_processing.base_input_processor import AfterCourtAttachmentPreprocessor
# from src.domain.base.blueprints import AfterCourtPreprocessingBlueprint

In [59]:
# # Initialize preprocessor
# config = AfterCourtPreprocessingBlueprint(
#     normalize_whitespace=True,
#     remove_short_lines=True,
#     short_line_threshold=3,
#     remove_html_tags=True,
#     lowercase=True,
#     clean_text_type='processed'
# )

# preprocessor = AfterCourtAttachmentPreprocessor(name='after_court', preprocessing_config=config)

# # Apply replace_with_tags directly to each text

# fp_data['text_w_tags'] = fp_data['texts'].apply(lambda x: preprocessor._replace_with_tags(preprocessor._process(x)))

Check current model predicted probs for fp_data

In [60]:

# probs = current_model.predict_proba(tf_idf_vectorizer.transform(fp_data['text_w_tags']))[:, 1]
# prob_df = fp_data[['attachment_id','document_type']].copy()
# prob_df['ladung_probability'] = probs

In [61]:
# prob_df

In [62]:
# import matplotlib.pyplot as plt

# # Get unique document types and assign colors
# document_types = prob_df['document_type'].unique()
# colors = plt.cm.tab10(range(len(document_types)))
# color_map = dict(zip(document_types, colors))

# # Create histogram with colors by document type
# plt.figure(figsize=(10, 6))
# for doc_type in document_types:
#     data_subset = prob_df[prob_df['document_type'] == doc_type]['ladung_probability']
#     plt.hist(data_subset, bins=20, alpha=0.6, label=doc_type, color=color_map[doc_type])

# plt.title('Histogram of Ladung Probabilities by Document Type')
# plt.xlabel('Ladung Probability')
# plt.ylabel('Frequency')
# plt.legend()
# plt.show()

In [63]:
# latest_full_data

In [64]:
# data = pd.concat([latest_full_data, fp_data])
# data = data.reset_index(drop=True)

In [65]:
data['document_type'].value_counts()

document_type
ladung_va                                 2029
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
fp_invoice                                 157
approved_attachment_and_transfer_order      60
enforcement_order                           23
contradiction                                3
vermögensverzeichnis                         3
Name: count, dtype: int64

In [66]:
data['is_ladung'].value_counts()

is_ladung
False    3309
True     2029
Name: count, dtype: int64

get the vectorizer

train test split

In [67]:

X_text = data['text_w_tags']
y = data['is_ladung']

# train test split
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train set size: {len(X_train_text)}, Test set size: {len(X_test_text)}")
print(f"Train set is pfub dist: {y_train.value_counts(normalize=True)}")
print(f"Test set is pfub dist: {y_test.value_counts(normalize=True)}")

Train set size: 4270, Test set size: 1068
Train set is pfub dist: is_ladung
False    0.619906
True     0.380094
Name: proportion, dtype: float64
Test set is pfub dist: is_ladung
False    0.61985
True     0.38015
Name: proportion, dtype: float64

In [68]:
document_types_train = data.loc[X_train_text.index, 'document_type']
document_types_test = data.loc[X_test_text.index, 'document_type']

In [69]:
document_types_test.shape

(1068,)

In [70]:
document_types_train.value_counts()

document_type
ladung_va                                 1623
mail_attachments                           815
monierung_mb                               438
attachment_and_transfer_order              422
approved_seizure                           329
court_inbox                                289
fp_protocol                                168
fp_invoice                                 118
approved_attachment_and_transfer_order      44
enforcement_order                           19
contradiction                                3
vermögensverzeichnis                         2
Name: count, dtype: int64

In [71]:
document_types_test.value_counts()

document_type
ladung_va                                 406
mail_attachments                          191
attachment_and_transfer_order             117
monierung_mb                              107
approved_seizure                           79
court_inbox                                57
fp_protocol                                51
fp_invoice                                 39
approved_attachment_and_transfer_order     16
enforcement_order                           4
vermögensverzeichnis                        1
Name: count, dtype: int64

In [72]:
X_train_tfidf = tf_idf_vectorizer.transform(X_train_text)
X_test_tfidf = tf_idf_vectorizer.transform(X_test_text)

In [73]:
# basic RF

from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tfidf, y_train)

RandomForestClassifier(random_state=42)

compare probs of old and new on fp data

In [74]:
# probs_new_model = rf_classifier.predict_proba(tf_idf_vectorizer.transform(fp_data['text_w_tags']))[:, 1]
# prob_df['ladung_probability_new_model'] = probs_new_model

# import matplotlib.pyplot as plt
# import seaborn as sns

# # Get unique document types
# document_types = prob_df['document_type'].unique()
# n_types = len(document_types)

# # Create subplots for each document type
# fig, axes = plt.subplots(n_types, 1, figsize=(10, 6 * n_types))

# # Handle case where there's only one document type
# if n_types == 1:
#     axes = [axes]

# # Plot for each document type
# for idx, doc_type in enumerate(document_types):
#     # Filter data for this document type
#     df_subset = prob_df[prob_df['document_type'] == doc_type]
    
#     # Create the KDE plot
#     sns.kdeplot(df_subset['ladung_probability'], label='Current Model', fill=True, alpha=0.5, ax=axes[idx])
#     sns.kdeplot(df_subset['ladung_probability_new_model'], label='New Model', fill=True, alpha=0.5, ax=axes[idx])
    
#     axes[idx].set_title(f'Ladung Probability Distribution Comparison - {doc_type}')
#     axes[idx].set_xlabel('Ladung Probability')
#     axes[idx].set_ylabel('Density')
#     axes[idx].legend()

# plt.tight_layout()
# plt.show()

In [75]:
# # Inspect probability values
# print("Current Model Probabilities:")
# print(f"Min: {prob_df['ladung_probability'].min()}")
# print(f"Max: {prob_df['ladung_probability'].max()}")
# print(f"Mean: {prob_df['ladung_probability'].mean()}")
# print("\nNew Model Probabilities:")
# print(f"Min: {prob_df['ladung_probability_new_model'].min()}")
# print(f"Max: {prob_df['ladung_probability_new_model'].max()}")
# print(f"Mean: {prob_df['ladung_probability_new_model'].mean()}")
# print("\nSample of prob_df:")
# print(prob_df.head(10))

In [76]:
# prob_df

In [97]:
y_pred_probs = rf_classifier.predict_proba(X_test_tfidf)[:, 1]
y_pred = y_pred_probs >= 0.6

In [98]:
doc_type_to_pred = pd.DataFrame({
    'document_type': document_types_test,
    'predicted_probs': y_pred_probs
})

In [99]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create subplots with 1 row and 2 columns
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('Distribution of Predicted Probabilities by Document Type (Box Plot)',
                    'Distribution of Predicted Probabilities by Document Type (Violin Plot)')
)

# Get unique document types
doc_types = doc_type_to_pred['document_type'].unique()

# Add box plots
for doc_type in doc_types:
    data_subset = doc_type_to_pred[doc_type_to_pred['document_type'] == doc_type]
    fig.add_trace(
        go.Box(
            y=data_subset['predicted_probs'],
            name=doc_type,
            boxmean='sd'
        ),
        row=1, col=1
    )

# Add violin plots
for doc_type in doc_types:
    data_subset = doc_type_to_pred[doc_type_to_pred['document_type'] == doc_type]
    fig.add_trace(
        go.Violin(
            y=data_subset['predicted_probs'],
            name=doc_type,
            box_visible=True,
            meanline_visible=True
        ),
        row=1, col=2
    )

# Add threshold line to violin plot
fig.add_hline(
    y=0.95, 
    line_dash="dash", 
    line_color="red",
    annotation_text="Threshold (0.95)",
    annotation_position="right",
    col=2
)

# Update layout
fig.update_layout(
    height=500,
    width=1400,
    showlegend=True,
    title_text="Predicted Probabilities Analysis by Document Type"
)

# Update y-axes labels
fig.update_yaxes(title_text="Predicted Probability", row=1, col=1)
fig.update_yaxes(title_text="Predicted Probability", row=1, col=2)

fig.show()

# Summary statistics by document type
print("\nSummary Statistics by Document Type:")
print(doc_type_to_pred.groupby('document_type')['predicted_probs'].describe())

Summary Statistics by Document Type:
                                        count      mean       std   min   25%  \
document_type
approved_attachment_and_transfer_order   16.0  0.004375  0.012093  0.00  0.00
approved_seizure                         79.0  0.001899  0.006617  0.00  0.00
attachment_and_transfer_order           117.0  0.001026  0.010203  0.00  0.00
court_inbox                              57.0  0.004035  0.018695  0.00  0.00
enforcement_order                         4.0  0.000000  0.000000  0.00  0.00
fp_invoice                               39.0  0.091282  0.137097  0.00  0.00
fp_protocol                              51.0  0.003137  0.013037  0.00  0.00
ladung_va                               406.0  0.990468  0.030316  0.69  1.00
mail_attachments                        191.0  0.007120  0.027921  0.00  0.00
monierung_mb                            107.0  0.000000  0.000000  0.00  0.00
vermögensverzeichnis                      1.0  0.010000       NaN  0.01  0.01

                                         50%   75%   max
document_type
approved_attachment_and_transfer_order  0.00  0.00  0.04
approved_seizure                        0.00  0.00  0.05
attachment_and_transfer_order           0.00  0.00  0.11
court_inbox                             0.00  0.00  0.11
enforcement_order                       0.00  0.00  0.00
fp_invoice                              0.02  0.18  0.54
fp_protocol                             0.00  0.00  0.08
ladung_va                               1.00  1.00  1.00
mail_attachments                        0.00  0.00  0.33
monierung_mb                            0.00  0.00  0.00
vermögensverzeichnis                    0.01  0.01  0.01

In [100]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)


print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""
    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, 
    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}
"""

Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00       662
        True       1.00      1.00      1.00       406

    accuracy                           1.00      1068
   macro avg       1.00      1.00      1.00      1068
weighted avg       1.00      1.00      1.00      1068


Confusion Matrix:
[[662   0]
 [  0 406]]

'\n    true negatives is :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, \n    true positives is :math:`C_{1,1}` and false positives is :math:`C_{0,1}\n'

In [81]:
import pandas as pd

# Create dataframe with predictions, actual values, and original indexes
results_df = pd.DataFrame({
    'index': y_test.index,
    'y_test': y_test.values,
    'y_pred': y_pred
})

results_df

      index  y_test  y_pred
0       228    True    True
1      2347    True    True
2      2028    True    True
3      1339   False   False
4       733   False   False
...     ...     ...     ...
1063   4253   False   False
1064   2283    True    True
1065   1686    True    True
1066   3503    True    True
1067   1889    True    True

[1068 rows x 3 columns]

In [82]:
results_df['FP'] = (results_df['y_test'] == 0) & (results_df['y_pred'] == True)
results_df['FN'] = (results_df['y_test'] == 1) & (results_df['y_pred'] == False)

In [83]:
print("Total fp:", results_df['FP'].sum())
print("Total fn:", results_df['FN'].sum())

Total fp: 0
Total fn: 24

In [84]:
fp = results_df[results_df['FP']]
fn = results_df[results_df['FN']]

In [85]:
model_fp_preds = data.loc[fp['index']].copy()

In [86]:
model_fp_preds

Empty DataFrame
Columns: [text, object_key, document_type, cleaned_text, data, is_pfub, is_ladung, tokenized, text_w_tags, attachment_id, s3_link]
Index: []

In [87]:
model_fn_preds = data.loc[fn['index']].copy()

# Add predicted probabilities to model_fn_preds
# Create a mapping from test indices to predicted probabilities
prob_mapping = pd.Series(y_pred_probs, index=y_test.index)
model_fn_preds['predicted_prob'] = model_fn_preds.index.map(prob_mapping)

In [88]:
model_fn_preds

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link,predicted_prob
1865,"Martina Riemer, Obergerichtsvollzieherin\nBüro...",14.10.2024/ocr-v2_Anlage101024172435.pdf,ladung_va,"martina riemer, obergerichtsvollzieherin\nbüro...",NaN,False,True,"['martina', 'riemer', 'obergerichtsvollzieheri...","martina riemer, obergerichtsvollzieherin\nbüro...",NaN,NaN,0.92
42,Georgenstr. 28\nT. PUHANE\n86152 Augsburg\nTel...,01.10.2024/ocr-v2_KL_002-01102024-134336.pdf,ladung_va,georgenstr. 28\nt. puhane\n86152 augsburg\ntel...,NaN,False,True,"['georgenstr', 't.', 'puhane', 'augsburg', 'ha...",georgenstr. <NUMBER>\nt. puhane\n<NUMBER> augs...,NaN,NaN,0.94
2971,HENRIK MANTEK\nReilstr. 74 / gegenüber Zoo\nOb...,23.05.2025/ocr-v2_DR-II_069225_Nachr_Mitlg__an...,ladung_va,henrik mantek\nreilstr. 74 / gegenüber zoo\nob...,NaN,False,True,"['henrik', 'mantek', 'reilstr', 'zoo', 'oberge...",henrik mantek\nreilstr. <NUMBER> / gegenüber z...,NaN,NaN,0.94
3223,Eschbacher Str. 40\nNICOLLE BOB\n61267 Neu-Ans...,25.07.2024/ocr-v2_DR-II_066324_Nachr_VAK-T_an_...,ladung_va,eschbacher str. 40\nnicolle bob\n61267 neu-ans...,NaN,False,True,"['eschbach', 'str', 'nicoll', 'bob', 'neu-ansp...",eschbacher str. <NUMBER>\nnicolle bob\n<NUMBER...,NaN,NaN,0.92
325,Obergerichtsvollzieherin\nJ. Ehnert\nFriedberg...,04.07.2024/ocr-v2_DR_II_461_24_An_Gl_Terminsmi...,ladung_va,obergerichtsvollzieherin\nj. ehnert\nfriedberg...,NaN,False,True,"['obergerichtsvollzieherin', 'j.', 'ehnern', '...",obergerichtsvollzieherin\nj. ehnert\nfriedberg...,NaN,NaN,0.94
3864,Isolde Pastschenko\nFleischgasse 30\nObergeric...,30.01.2025/ocr-v2_Dokument_12525_29012025_0851...,ladung_va,isolde pastschenko\nfleischgasse 30\nobergeric...,NaN,False,True,"['isolden', 'pastschenko', 'fleischgasse', 'ob...",isolde pastschenko\nfleischgasse <NUMBER>\nobe...,NaN,NaN,0.72
163,WENDELIN SCHULTE\nKirchweg 4\n46499 Hamminkeln...,02.12.2024/ocr-v2_DR-II_296124_Nachr_Gl.Nr._vo...,ladung_va,wendelin schulte\nkirchweg 4\n46499 hamminkeln...,NaN,False,True,"['wendelin', 'schulen', 'kirchweg', 'hamminkel...",wendelin schulte\nkirchweg <NUMBER>\n<NUMBER> ...,NaN,NaN,0.87
3409,Oberger ichtsvo 1 lzieher T.Boxhorn\n+49 511 6...,27.02.2025/ocr-v2_2025-01-16_17-27-36_05116009...,ladung_va,oberger ichtsvo 1 lzieher t.boxhorn\n+49 511 6...,NaN,False,True,"['oberger', 'ichtsvo', 'lzieh', 't.boxhorn', '...",oberger ichtsvo <NUMBER> lzieher t.boxhorn\n<N...,NaN,NaN,0.92
1762,10/07/2024 10:37\n095319448418\nGVTAEFFNER\nS....,14.07.2024/ocr-v2_2024-07-10_10-23-43_09531944...,ladung_va,10/07/2024 10:37\n095319448418\ngvtaeffner\n01...,NaN,False,True,"['gvtaeffner', 'obergerichtsvollzieher', 'eber...",<DATE> <NUMBER>:<NUMBER>\n<PHONE>\ngvtaeffner\...,NaN,NaN,0.94
3087,"Michael Braasch\nAdresse, Sprechstunden u. Ban...",24.06.2024/ocr-v2_DR-II_098024_Nachr_Gl__Lad__...,ladung_va,"michael braasch\nadresse, sprechstunden u. ban...",NaN,False,True,"['michael', 'braasch', 'adresse', 'sprechstund...","michael braasch\nadresse, sprechstunden u. ban...",NaN,NaN,0.85
3285,Obergerichtsvollzieherin\nAmtsgericht: Geestla...,26.02.2025/ocr-v2_Dr_ii_194_25_an_gl_terminsmi...,ladung_va,obergerichtsvollzieherin\namtsgericht: geestla...,NaN,False,True,"['obergerichtsvollzieherin', 'amtsgerichen', '...",obergerichtsvollzieherin\namtsgericht: geestla...,NaN,NaN,0.91
2233,Obergerichtsvollzieher\nAmtsgericht\nDuisburg\...,17.02.2025/ocr-v2_f1aacab4-682f-4e97-8c62-4dbe...,ladung_va,obergerichtsvollzieher\namtsgericht\nduisburg\...,NaN,False,True,"['obergerichtsvollzieher', 'amtsgericht', 'dui...",obergerichtsvollzieher\namtsgericht\nduisburg\...,NaN,NaN,0.94
3335,Ellen Seeber\nFreistaat\nObergerichtsvollziehe...,26.05.2025/ocr-v2_DRII202500487TerminVAanGLBV0...,ladung_va,ellen seeber\nfreistaat\nobergerichtsvollziehe...,NaN,False,True,"['ell', 'seeber', 'freistaat', 'obergerichtsvo...",ellen seeber\nfreistaat\nobergerichtsvollziehe...,NaN,NaN,0.81
3275,Helmut Everding\nObergerichtsvollzieher / AG P...,25.11.2024/ocr-v2_Dr_ii_2152_24_00118_gläubige...,ladung_va,helmut everding\nobergerichtsvollzieher / ag p...,NaN,False,True,"['helmut', 'everding', 'obergerichtsvollzieh',...",helmut everding\nobergerichtsvollzieher / ag p...,NaN,NaN,0.88
3103,Bitte tragen Sie ein Mund/Nasen-Schutz bei Bet...,24.07.2024/ocr-v2_DR-II_037724_Nachr_kenn_23_0...,ladung_va,bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,False,True,"['bitte', 'tragen', 'mund', 'nasen-schutz', 'b...",bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,NaN,0.69
3933,Schafhausener Str. 47\n52525 Heinsberg\nClaudi...,30.07.2024/ocr-v2_DR-II_154324_Nachr_va1_29_07...,ladung_va,schafhausener str. 47\n52525 heinsberg\nclaudi...,NaN,False,True,"['schafhausen', 'str', 'heinsberg', 'claudia',...",schafhausener str. <NUMBER>\n<NUMBER> heinsber...,NaN,NaN,0.92
2484,Tangermünder Str. 8\n06124 Halle (Saale)\nSTEF...,19.02.2025/ocr-v2_b09242cc-a62c-43f1-80f9-9425...,ladung_va,tangermünder str. 8\n06124 halle (saale)\nstef...,NaN,False,True,"['tangermünd', 'str', 'halle', 'saal', 'steffe...",tangermünder str. <NUMBER>\n<NUMBER> halle (sa...,NaN,NaN,0.94
3494,Schafhausener Str. 47\n52525 Heinsberg\nClaudi...,27.06.2024/ocr-v2_DR-II_135024_Nachr_va1_26_06...,ladung_va,schafhausener str. 47\n52525 heinsberg\nclaudi...,NaN,False,True,"['schafhausen', 'str', 'heinsberg', 'claudia',...",schafhausener str. <NUMBER>\n<NUMBER> heinsber...,NaN,NaN,0.92
827,Roschstraße 4\n98527 Suhl\nTel. 03681-300995\n...,07.07.2025/ocr-v2_DR-II_057525_Nachr_Mitlg__an...,ladung_va,roschstraße 4\n98527 suhl\ntel. 03681-300995\n...,NaN,False,True,"['roschstraße', 'suhl', 'katrin', 'menzel', 'f...",roschstraße <NUMBER>\n<NUMBER> suhl\ntel. <NUM...,NaN,NaN,0.93
321,Gerichtsvollzieherin (b)\nSprechstunden im Amt...,04.06.2025/ocr-v2_Dr_ii_722_25_an_gl_terminsmi...,ladung_va,gerichtsvollzieherin (b)\nsprechstunden im amt...,NaN,False,True,"['gerichtsvollzieherin', '--', 'sprechstunden'...",gerichtsvollzieherin (b)\nsprechstunden im amt...,NaN,NaN,0.93
3856,"Martina Riemer, Obergerichtsvollzieherin\nBüro...",30.01.2025/ocr-v2_Anlage200125160132.pdf,ladung_va,"martina riemer, obergerichtsvollzieherin\nbüro...",NaN,False,True,"['martina', 'riemer', 'obergerichtsvollzieheri...","martina riemer, obergerichtsvollzieherin\nbüro...",NaN,NaN,0.93
3006,Domkauler Weg 58\n50171 Kerpen\nTel. 02275/911...,23.08.2024/ocr-v2_DR-II_097624_Nachr_Mitlg__an...,ladung_va,domkauler weg 58\n50171 kerpen\ntel. 02275/911...,NaN,False,True,"['domkauler', 'weg', 'kerpen', 'helga', 'mucke...",domkauler weg <NUMBER>\n<NUMBER> kerpen\ntel. ...,NaN,NaN,0.93
2996,Obergerichtsvollzieher am Amtsgericht Leipzig\...,23.07.2025/ocr-v2_38_dr_819_25_an_gl_terminsmi...,ladung_va,obergerichtsvollzieher am amtsgericht leipzig\...,NaN,False,True,"['obergerichtsvollzieher', 'amtsgericht', 'lei...",obergerichtsvollzieher am amtsgericht leipzig\...,NaN,NaN,0.87
1228,Gerichtsvollzieherin\nBismarckstraße 23\nC. Re...,11.04.2025/ocr-v2_Dr_ii_347_25_an_gl_terminsmi...,ladung_va,gerichtsvollzieherin\nbismarckstraße 23\nc. re...,NaN,False,True,"['gerichtsvollzieherin', 'bismarckstraßen', 'c...",gerichtsvollzieherin\nbismarckstraße <NUMBER>\...,NaN,NaN,0.89

save the new ladung binary model

In [89]:
# # save the trained model
# save_path = os.path.join(notebook_dir, "after-court/models/classification/28-01-2026_binary_ladung_rf_classifier_v1.dill")
# with open(save_path, "wb") as f:
#     dill.dump(rf_classifier, f)

In [95]:
ths = [0.1,0.5,0.6,0.7,0.8,0.90, 0.91, 0.92, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99]

threshold_results = []

for th in ths:
    y_pred_label = y_pred_probs >= th
    
    # Calculate confusion matrix components
    tp = ((y_pred_label == 1) & (y_test == 1)).sum()
    fp = ((y_pred_label == 1) & (y_test == 0)).sum()
    tn = ((y_pred_label == 0) & (y_test == 0)).sum()
    fn = ((y_pred_label == 0) & (y_test == 1)).sum()
    
    # Calculate metrics
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    accuracy = (tp + tn) / (tp + tn + fp + fn)
    
    threshold_results.append({
        'threshold': th,
        'tp': tp,
        'fp': fp,
        'tn': tn,
        'fn': fn,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'accuracy': accuracy
    })

# Create DataFrame
threshold_df = pd.DataFrame(threshold_results)
threshold_df

    threshold   tp  fp   tn  fn  precision    recall  f1_score  accuracy
0        0.10  406  16  646   0   0.962085  1.000000  0.980676  0.985019
1        0.50  406   1  661   0   0.997543  1.000000  0.998770  0.999064
2        0.60  406   0  662   0   1.000000  1.000000  1.000000  1.000000
3        0.70  405   0  662   1   1.000000  0.997537  0.998767  0.999064
4        0.80  404   0  662   2   1.000000  0.995074  0.997531  0.998127
5        0.90  398   0  662   8   1.000000  0.980296  0.990050  0.992509
6        0.91  398   0  662   8   1.000000  0.980296  0.990050  0.992509
7        0.92  397   0  662   9   1.000000  0.977833  0.988792  0.991573
8        0.93  392   0  662  14   1.000000  0.965517  0.982456  0.986891
9        0.95  382   0  662  24   1.000000  0.940887  0.969543  0.977528
10       0.96  379   0  662  27   1.000000  0.933498  0.965605  0.974719
11       0.97  375   0  662  31   1.000000  0.923645  0.960307  0.970974
12       0.98  360   0  662  46   1.000000  0.886700  0.939948  0.956929
13       0.99  353   0  662  53   1.000000  0.869458  0.930171  0.950375

In [96]:
import plotly.graph_objects as go

# Create interactive plot with multiple metrics
fig = go.Figure()

# Add traces for each metric
fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['precision'],
    mode='lines+markers',
    name='Precision',
    line=dict(color='blue', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['recall'],
    mode='lines+markers',
    name='Recall',
    line=dict(color='green', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['f1_score'],
    mode='lines+markers',
    name='F1 Score',
    line=dict(color='red', width=2),
    marker=dict(size=8)
))

fig.add_trace(go.Scatter(
    x=threshold_df['threshold'],
    y=threshold_df['accuracy'],
    mode='lines+markers',
    name='Accuracy',
    line=dict(color='purple', width=2),
    marker=dict(size=8)
))

# Add vertical line at current threshold (0.95)
fig.add_vline(
    x=0.95,
    line_dash="dash",
    line_color="gray",
    annotation_text="Current Threshold (0.95)",
    annotation_position="top"
)

# Update layout
fig.update_layout(
    title='Performance Metrics vs Threshold',
    xaxis_title='Threshold',
    yaxis_title='Score',
    hovermode='x unified',
    height=500,
    width=1000,
    legend=dict(
        yanchor="middle",
        y=0.5,
        xanchor="right",
        x=1.15,
        bgcolor="rgba(255, 255, 255, 0.8)",
        bordercolor="gray",
        borderwidth=1
    )
)

fig.show()

# Display metrics at current threshold (0.95)
print("\nMetrics at threshold = 0.95:")
print(threshold_df[threshold_df['threshold'] == 0.95].T)

Metrics at threshold = 0.95:
                    9
threshold    0.950000
tp         382.000000
fp           0.000000
tn         662.000000
fn          24.000000
precision    1.000000
recall       0.940887
f1_score     0.969543
accuracy     0.977528

# check false negatives

In [101]:
model_fn_preds

,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,tokenized,text_w_tags,attachment_id,s3_link,predicted_prob
1865,"Martina Riemer, Obergerichtsvollzieherin\nBüro...",14.10.2024/ocr-v2_Anlage101024172435.pdf,ladung_va,"martina riemer, obergerichtsvollzieherin\nbüro...",NaN,False,True,"['martina', 'riemer', 'obergerichtsvollzieheri...","martina riemer, obergerichtsvollzieherin\nbüro...",NaN,NaN,0.92
42,Georgenstr. 28\nT. PUHANE\n86152 Augsburg\nTel...,01.10.2024/ocr-v2_KL_002-01102024-134336.pdf,ladung_va,georgenstr. 28\nt. puhane\n86152 augsburg\ntel...,NaN,False,True,"['georgenstr', 't.', 'puhane', 'augsburg', 'ha...",georgenstr. <NUMBER>\nt. puhane\n<NUMBER> augs...,NaN,NaN,0.94
2971,HENRIK MANTEK\nReilstr. 74 / gegenüber Zoo\nOb...,23.05.2025/ocr-v2_DR-II_069225_Nachr_Mitlg__an...,ladung_va,henrik mantek\nreilstr. 74 / gegenüber zoo\nob...,NaN,False,True,"['henrik', 'mantek', 'reilstr', 'zoo', 'oberge...",henrik mantek\nreilstr. <NUMBER> / gegenüber z...,NaN,NaN,0.94
3223,Eschbacher Str. 40\nNICOLLE BOB\n61267 Neu-Ans...,25.07.2024/ocr-v2_DR-II_066324_Nachr_VAK-T_an_...,ladung_va,eschbacher str. 40\nnicolle bob\n61267 neu-ans...,NaN,False,True,"['eschbach', 'str', 'nicoll', 'bob', 'neu-ansp...",eschbacher str. <NUMBER>\nnicolle bob\n<NUMBER...,NaN,NaN,0.92
325,Obergerichtsvollzieherin\nJ. Ehnert\nFriedberg...,04.07.2024/ocr-v2_DR_II_461_24_An_Gl_Terminsmi...,ladung_va,obergerichtsvollzieherin\nj. ehnert\nfriedberg...,NaN,False,True,"['obergerichtsvollzieherin', 'j.', 'ehnern', '...",obergerichtsvollzieherin\nj. ehnert\nfriedberg...,NaN,NaN,0.94
3864,Isolde Pastschenko\nFleischgasse 30\nObergeric...,30.01.2025/ocr-v2_Dokument_12525_29012025_0851...,ladung_va,isolde pastschenko\nfleischgasse 30\nobergeric...,NaN,False,True,"['isolden', 'pastschenko', 'fleischgasse', 'ob...",isolde pastschenko\nfleischgasse <NUMBER>\nobe...,NaN,NaN,0.72
163,WENDELIN SCHULTE\nKirchweg 4\n46499 Hamminkeln...,02.12.2024/ocr-v2_DR-II_296124_Nachr_Gl.Nr._vo...,ladung_va,wendelin schulte\nkirchweg 4\n46499 hamminkeln...,NaN,False,True,"['wendelin', 'schulen', 'kirchweg', 'hamminkel...",wendelin schulte\nkirchweg <NUMBER>\n<NUMBER> ...,NaN,NaN,0.87
3409,Oberger ichtsvo 1 lzieher T.Boxhorn\n+49 511 6...,27.02.2025/ocr-v2_2025-01-16_17-27-36_05116009...,ladung_va,oberger ichtsvo 1 lzieher t.boxhorn\n+49 511 6...,NaN,False,True,"['oberger', 'ichtsvo', 'lzieh', 't.boxhorn', '...",oberger ichtsvo <NUMBER> lzieher t.boxhorn\n<N...,NaN,NaN,0.92
1762,10/07/2024 10:37\n095319448418\nGVTAEFFNER\nS....,14.07.2024/ocr-v2_2024-07-10_10-23-43_09531944...,ladung_va,10/07/2024 10:37\n095319448418\ngvtaeffner\n01...,NaN,False,True,"['gvtaeffner', 'obergerichtsvollzieher', 'eber...",<DATE> <NUMBER>:<NUMBER>\n<PHONE>\ngvtaeffner\...,NaN,NaN,0.94
3087,"Michael Braasch\nAdresse, Sprechstunden u. Ban...",24.06.2024/ocr-v2_DR-II_098024_Nachr_Gl__Lad__...,ladung_va,"michael braasch\nadresse, sprechstunden u. ban...",NaN,False,True,"['michael', 'braasch', 'adresse', 'sprechstund...","michael braasch\nadresse, sprechstunden u. ban...",NaN,NaN,0.85
3285,Obergerichtsvollzieherin\nAmtsgericht: Geestla...,26.02.2025/ocr-v2_Dr_ii_194_25_an_gl_terminsmi...,ladung_va,obergerichtsvollzieherin\namtsgericht: geestla...,NaN,False,True,"['obergerichtsvollzieherin', 'amtsgerichen', '...",obergerichtsvollzieherin\namtsgericht: geestla...,NaN,NaN,0.91
2233,Obergerichtsvollzieher\nAmtsgericht\nDuisburg\...,17.02.2025/ocr-v2_f1aacab4-682f-4e97-8c62-4dbe...,ladung_va,obergerichtsvollzieher\namtsgericht\nduisburg\...,NaN,False,True,"['obergerichtsvollzieher', 'amtsgericht', 'dui...",obergerichtsvollzieher\namtsgericht\nduisburg\...,NaN,NaN,0.94
3335,Ellen Seeber\nFreistaat\nObergerichtsvollziehe...,26.05.2025/ocr-v2_DRII202500487TerminVAanGLBV0...,ladung_va,ellen seeber\nfreistaat\nobergerichtsvollziehe...,NaN,False,True,"['ell', 'seeber', 'freistaat', 'obergerichtsvo...",ellen seeber\nfreistaat\nobergerichtsvollziehe...,NaN,NaN,0.81
3275,Helmut Everding\nObergerichtsvollzieher / AG P...,25.11.2024/ocr-v2_Dr_ii_2152_24_00118_gläubige...,ladung_va,helmut everding\nobergerichtsvollzieher / ag p...,NaN,False,True,"['helmut', 'everding', 'obergerichtsvollzieh',...",helmut everding\nobergerichtsvollzieher / ag p...,NaN,NaN,0.88
3103,Bitte tragen Sie ein Mund/Nasen-Schutz bei Bet...,24.07.2024/ocr-v2_DR-II_037724_Nachr_kenn_23_0...,ladung_va,bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,False,True,"['bitte', 'tragen', 'mund', 'nasen-schutz', 'b...",bitte tragen sie ein mund/nasen-schutz bei bet...,NaN,NaN,0.69
3933,Schafhausener Str. 47\n52525 Heinsberg\nClaudi...,30.07.2024/ocr-v2_DR-II_154324_Nachr_va1_29_07...,ladung_va,schafhausener str. 47\n52525 heinsberg\nclaudi...,NaN,False,True,"['schafhausen', 'str', 'heinsberg', 'claudia',...",schafhausener str. <NUMBER>\n<NUMBER> heinsber...,NaN,NaN,0.92
2484,Tangermünder Str. 8\n06124 Halle (Saale)\nSTEF...,19.02.2025/ocr-v2_b09242cc-a62c-43f1-80f9-9425...,ladung_va,tangermünder str. 8\n06124 halle (saale)\nstef...,NaN,False,True,"['tangermünd', 'str', 'halle', 'saal', 'steffe...",tangermünder str. <NUMBER>\n<NUMBER> halle (sa...,NaN,NaN,0.94
3494,Schafhausener Str. 47\n52525 Heinsberg\nClaudi...,27.06.2024/ocr-v2_DR-II_135024_Nachr_va1_26_06...,ladung_va,schafhausener str. 47\n52525 heinsberg\nclaudi...,NaN,False,True,"['schafhausen', 'str', 'heinsberg', 'claudia',...",schafhausener str. <NUMBER>\n<NUMBER> heinsber...,NaN,NaN,0.92
827,Roschstraße 4\n98527 Suhl\nTel. 03681-300995\n...,07.07.2025/ocr-v2_DR-II_057525_Nachr_Mitlg__an...,ladung_va,roschstraße 4\n98527 suhl\ntel. 03681-300995\n...,NaN,False,True,"['roschstraße', 'suhl', 'katrin', 'menzel', 'f...",roschstraße <NUMBER>\n<NUMBER> suhl\ntel. <NUM...,NaN,NaN,0.93
321,Gerichtsvollzieherin (b)\nSprechstunden im Amt...,04.06.2025/ocr-v2_Dr_ii_722_25_an_gl_terminsmi...,ladung_va,gerichtsvollzieherin (b)\nsprechstunden im amt...,NaN,False,True,"['gerichtsvollzieherin', '--', 'sprechstunden'...",gerichtsvollzieherin (b)\nsprechstunden im amt...,NaN,NaN,0.93
3856,"Martina Riemer, Obergerichtsvollzieherin\nBüro...",30.01.2025/ocr-v2_Anlage200125160132.pdf,ladung_va,"martina riemer, obergerichtsvollzieherin\nbüro...",NaN,False,True,"['martina', 'riemer', 'obergerichtsvollzieheri...","martina riemer, obergerichtsvollzieherin\nbüro...",NaN,NaN,0.93
3006,Domkauler Weg 58\n50171 Kerpen\nTel. 02275/911...,23.08.2024/ocr-v2_DR-II_097624_Nachr_Mitlg__an...,ladung_va,domkauler weg 58\n50171 kerpen\ntel. 02275/911...,NaN,False,True,"['domkauler', 'weg', 'kerpen', 'helga', 'mucke...",domkauler weg <NUMBER>\n<NUMBER> kerpen\ntel. ...,NaN,NaN,0.93
2996,Obergerichtsvollzieher am Amtsgericht Leipzig\...,23.07.2025/ocr-v2_38_dr_819_25_an_gl_terminsmi...,ladung_va,obergerichtsvollzieher am amtsgericht leipzig\...,NaN,False,True,"['obergerichtsvollzieher', 'amtsgericht', 'lei...",obergerichtsvollzieher am amtsgericht leipzig\...,NaN,NaN,0.87
1228,Gerichtsvollzieherin\nBismarckstraße 23\nC. Re...,11.04.2025/ocr-v2_Dr_ii_347_25_an_gl_terminsmi...,ladung_va,gerichtsvollzieherin\nbismarckstraße 23\nc. re...,NaN,False,True,"['gerichtsvollzieherin', 'bismarckstraßen', 'c...",gerichtsvollzieherin\nbismarckstraße <NUMBER>\...,NaN,NaN,0.89

In [102]:
import boto3
import os

# Setup S3 client with specific profile
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3_client = session.client('s3')

# Create tmp_pdfs directory if it doesn't exist
tmp_dir = os.path.join(os.getcwd(), 'tmp_pdfs')
os.makedirs(tmp_dir, exist_ok=True)

print(f"{'='*80}")
print(f"Downloading False Negative PDFs to: {tmp_dir}")
print(f"Total False Negatives: {len(model_fn_preds)}")
print(f"{'='*80}\n")

# Download PDFs for false negative predictions
downloaded = 0
failed = 0

for idx, row in model_fn_preds.iterrows():
    predicted_prob = row['predicted_prob']
    doc_type = row['document_type']
    key = row['object_key']
    s3_bucket = "pair-scanner"
    
    # Extract filename from key
    filename = os.path.basename(key)
    local_path = os.path.join(tmp_dir, filename)
    
    print(f"\n{'-'*80}")
    print(f"\033[1m\033[96m📄 Document {downloaded + failed + 1}/{len(model_fn_preds)}\033[0m")
    print(f"   \033[93mDatabase Index\033[0m       : \033[1m{idx}\033[0m")
    print(f"   \033[93mGT Document Type\033[0m     : {doc_type}")
    print(f"   \033[93mPredicted Ladung Prob\033[0m: \033[1m{predicted_prob:.4f}\033[0m")
    print(f"   \033[93mFilename\033[0m             : {filename}")
    print(f"   \033[93mS3 Path\033[0m              : s3://{s3_bucket}/{key}")
    
    try:
        s3_client.download_file(s3_bucket, key, local_path)
        print(f"   \033[92m✅ Status\033[0m            : Downloaded successfully")
        print(f"   \033[93mLocal Path\033[0m           : {local_path}")
        downloaded += 1
    except Exception as e:
        print(f"   \033[91m❌ Status\033[0m            : Failed")
        print(f"   \033[91mError\033[0m                : {e}")
        failed += 1
    
print(f"\n\033[1m{'='*80}\033[0m")
print(f"\033[1m\033[92mDownload Summary: {downloaded} succeeded\033[0m, \033[91m{failed} failed\033[0m")
print(f"\033[1m{'='*80}\033[0m")

================================================================================
Downloading False Negative PDFs to: /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs
Total False Negatives: 24
================================================================================


--------------------------------------------------------------------------------
📄 Document 1/24
   Database Index       : 1865
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9200
   Filename             : ocr-v2_Anlage101024172435.pdf
   S3 Path              : s3://pair-scanner/14.10.2024/ocr-v2_Anlage101024172435.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Anlage101024172435.pdf

--------------------------------------------------------------------------------
📄 Document 2/24
   Database Index       : 42
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_KL_002-01102024-134336.pdf
   S3 Path              : s3://pair-scanner/01.10.2024/ocr-v2_KL_002-01102024-134336.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_KL_002-01102024-134336.pdf

--------------------------------------------------------------------------------
📄 Document 3/24
   Database Index       : 2971
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_DR-II_069225_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_05_2025.pdf
   S3 Path              : s3://pair-scanner/23.05.2025/ocr-v2_DR-II_069225_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_05_2025.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_069225_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_05_2025.pdf

--------------------------------------------------------------------------------
📄 Document 4/24
   Database Index       : 3223
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9200
   Filename             : ocr-v2_DR-II_066324_Nachr_VAK-T_an_Gl__24_07_2024.pdf
   S3 Path              : s3://pair-scanner/25.07.2024/ocr-v2_DR-II_066324_Nachr_VAK-T_an_Gl__24_07_2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_066324_Nachr_VAK-T_an_Gl__24_07_2024.pdf

--------------------------------------------------------------------------------
📄 Document 5/24
   Database Index       : 325
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_DR_II_461_24_An_Gl_Terminsmitteilung_Ladung.PDF
   S3 Path              : s3://pair-scanner/04.07.2024/ocr-v2_DR_II_461_24_An_Gl_Terminsmitteilung_Ladung.PDF
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR_II_461_24_An_Gl_Terminsmitteilung_Ladung.PDF

--------------------------------------------------------------------------------
📄 Document 6/24
   Database Index       : 3864
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.7200
   Filename             : ocr-v2_Dokument_12525_29012025_085108.pdf
   S3 Path              : s3://pair-scanner/30.01.2025/ocr-v2_Dokument_12525_29012025_085108.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Dokument_12525_29012025_085108.pdf

--------------------------------------------------------------------------------
📄 Document 7/24
   Database Index       : 163
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8700
   Filename             : ocr-v2_DR-II_296124_Nachr_Gl.Nr._vom_Termin_26.11.2024.pdf
   S3 Path              : s3://pair-scanner/02.12.2024/ocr-v2_DR-II_296124_Nachr_Gl.Nr._vom_Termin_26.11.2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_296124_Nachr_Gl.Nr._vom_Termin_26.11.2024.pdf

--------------------------------------------------------------------------------
📄 Document 8/24
   Database Index       : 3409
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9200
   Filename             : ocr-v2_2025-01-16_17-27-36_051160099672_030340602951.pdf
   S3 Path              : s3://pair-scanner/27.02.2025/ocr-v2_2025-01-16_17-27-36_051160099672_030340602951.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_2025-01-16_17-27-36_051160099672_030340602951.pdf

--------------------------------------------------------------------------------
📄 Document 9/24
   Database Index       : 1762
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_2024-07-10_10-23-43_095319448418_030340602951.pdf
   S3 Path              : s3://pair-scanner/14.07.2024/ocr-v2_2024-07-10_10-23-43_095319448418_030340602951.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_2024-07-10_10-23-43_095319448418_030340602951.pdf

--------------------------------------------------------------------------------
📄 Document 10/24
   Database Index       : 3087
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8500
   Filename             : ocr-v2_DR-II_098024_Nachr_Gl__Lad__VAK_22_06_2024.pdf
   S3 Path              : s3://pair-scanner/24.06.2024/ocr-v2_DR-II_098024_Nachr_Gl__Lad__VAK_22_06_2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_098024_Nachr_Gl__Lad__VAK_22_06_2024.pdf

--------------------------------------------------------------------------------
📄 Document 11/24
   Database Index       : 3285
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9100
   Filename             : ocr-v2_Dr_ii_194_25_an_gl_terminsmitteilung_ladung.pdf
   S3 Path              : s3://pair-scanner/26.02.2025/ocr-v2_Dr_ii_194_25_an_gl_terminsmitteilung_ladung.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Dr_ii_194_25_an_gl_terminsmitteilung_ladung.pdf

--------------------------------------------------------------------------------
📄 Document 12/24
   Database Index       : 2233
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_f1aacab4-682f-4e97-8c62-4dbe789fd9cc.pdf
   S3 Path              : s3://pair-scanner/17.02.2025/ocr-v2_f1aacab4-682f-4e97-8c62-4dbe789fd9cc.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_f1aacab4-682f-4e97-8c62-4dbe789fd9cc.pdf

--------------------------------------------------------------------------------
📄 Document 13/24
   Database Index       : 3335
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8100
   Filename             : ocr-v2_DRII202500487TerminVAanGLBV004.PDF
   S3 Path              : s3://pair-scanner/26.05.2025/ocr-v2_DRII202500487TerminVAanGLBV004.PDF
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DRII202500487TerminVAanGLBV004.PDF

--------------------------------------------------------------------------------
📄 Document 14/24
   Database Index       : 3275
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8800
   Filename             : ocr-v2_Dr_ii_2152_24_00118_gläubiger_(1).pdf
   S3 Path              : s3://pair-scanner/25.11.2024/ocr-v2_Dr_ii_2152_24_00118_gläubiger_(1).pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Dr_ii_2152_24_00118_gläubiger_(1).pdf

--------------------------------------------------------------------------------
📄 Document 15/24
   Database Index       : 3103
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.6900
   Filename             : ocr-v2_DR-II_037724_Nachr_kenn_23_07_2024.pdf
   S3 Path              : s3://pair-scanner/24.07.2024/ocr-v2_DR-II_037724_Nachr_kenn_23_07_2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_037724_Nachr_kenn_23_07_2024.pdf

--------------------------------------------------------------------------------
📄 Document 16/24
   Database Index       : 3933
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9200
   Filename             : ocr-v2_DR-II_154324_Nachr_va1_29_07_2024.pdf
   S3 Path              : s3://pair-scanner/30.07.2024/ocr-v2_DR-II_154324_Nachr_va1_29_07_2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_154324_Nachr_va1_29_07_2024.pdf

--------------------------------------------------------------------------------
📄 Document 17/24
   Database Index       : 2484
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9400
   Filename             : ocr-v2_b09242cc-a62c-43f1-80f9-94251fe00c80.pdf
   S3 Path              : s3://pair-scanner/19.02.2025/ocr-v2_b09242cc-a62c-43f1-80f9-94251fe00c80.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_b09242cc-a62c-43f1-80f9-94251fe00c80.pdf

--------------------------------------------------------------------------------
📄 Document 18/24
   Database Index       : 3494
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9200
   Filename             : ocr-v2_DR-II_135024_Nachr_va1_26_06_2024.pdf
   S3 Path              : s3://pair-scanner/27.06.2024/ocr-v2_DR-II_135024_Nachr_va1_26_06_2024.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_135024_Nachr_va1_26_06_2024.pdf

--------------------------------------------------------------------------------
📄 Document 19/24
   Database Index       : 827
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9300
   Filename             : ocr-v2_DR-II_057525_Nachr_Mitlg__an_Glb_ueber_Termin_VA_04_07_2025.pdf
   S3 Path              : s3://pair-scanner/07.07.2025/ocr-v2_DR-II_057525_Nachr_Mitlg__an_Glb_ueber_Termin_VA_04_07_2025.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_057525_Nachr_Mitlg__an_Glb_ueber_Termin_VA_04_07_2025.pdf

--------------------------------------------------------------------------------
📄 Document 20/24
   Database Index       : 321
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9300
   Filename             : ocr-v2_Dr_ii_722_25_an_gl_terminsmitteilung_ladung.pdf
   S3 Path              : s3://pair-scanner/04.06.2025/ocr-v2_Dr_ii_722_25_an_gl_terminsmitteilung_ladung.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Dr_ii_722_25_an_gl_terminsmitteilung_ladung.pdf

--------------------------------------------------------------------------------
📄 Document 21/24
   Database Index       : 3856
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9300
   Filename             : ocr-v2_Anlage200125160132.pdf
   S3 Path              : s3://pair-scanner/30.01.2025/ocr-v2_Anlage200125160132.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Anlage200125160132.pdf

--------------------------------------------------------------------------------
📄 Document 22/24
   Database Index       : 3006
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.9300
   Filename             : ocr-v2_DR-II_097624_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_08_2024_3_.pdf
   S3 Path              : s3://pair-scanner/23.08.2024/ocr-v2_DR-II_097624_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_08_2024_3_.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_DR-II_097624_Nachr_Mitlg__an_Glb_ueber_Termin_VA_22_08_2024_3_.pdf

--------------------------------------------------------------------------------
📄 Document 23/24
   Database Index       : 2996
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8700
   Filename             : ocr-v2_38_dr_819_25_an_gl_terminsmitteilung_ladung.pdf
   S3 Path              : s3://pair-scanner/23.07.2025/ocr-v2_38_dr_819_25_an_gl_terminsmitteilung_ladung.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_38_dr_819_25_an_gl_terminsmitteilung_ladung.pdf

--------------------------------------------------------------------------------
📄 Document 24/24
   Database Index       : 1228
   GT Document Type     : ladung_va
   Predicted Ladung Prob: 0.8900
   Filename             : ocr-v2_Dr_ii_347_25_an_gl_terminsmitteilung_ladung.pdf
   S3 Path              : s3://pair-scanner/11.04.2025/ocr-v2_Dr_ii_347_25_an_gl_terminsmitteilung_ladung.pdf
   ✅ Status            : Downloaded successfully
   Local Path           : /Users/melih.gorgulu/Desktop/Projects/intent_recognition/tmp_pdfs/ocr-v2_Dr_ii_347_25_an_gl_terminsmitteilung_ladung.pdf

================================================================================
Download Summary: 24 succeeded, 0 failed
================================================================================

# index_needs_to_be_fixed
1) 2146 is invoice
2) 2950 is invoice
3) 1342 is invoice
4) 2613 is invoice
5) 2027 weird data, delete
6) 1071 is invoice
7) 40 is invoice
8) 3138 is invoice
9) 1070 is invoice
10) 1109 is invoice
11) 2154 is invoice
12) 1324 is invoice
13) 3139 is invoice

save the updated model, train on all dataset

In [103]:
# retrain the model with updated data
X_text_updated = data['text_w_tags']
y_updated = data['is_ladung']
X_tfidf_updated = tf_idf_vectorizer.transform(X_text_updated)
rf_classifier_updated = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier_updated.fit(X_tfidf_updated, y_updated)

RandomForestClassifier(random_state=42)

In [104]:
# save the2 trained model with dill
save_path = os.path.join(notebook_dir, "after-court/models/classification/05-02-2026_binary_ladung_rf_classifier_v1.dill")
with open(save_path, "wb") as f:
    dill.dump(rf_classifier_updated, f)