## PURPOSE: Running current classification model on random attachments, to see if we have any FN or TN

In [1]:
import os
import json
from ast import literal_eval
from datetime import datetime, timedelta

import pandas as pd
import numpy as np

from python_utilities.db_connection import DbConnection

In [2]:
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')

INFO [2025-10-15 14:09:28] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

#### Lets read attachments that are sent us in previous 2 months

In [ ]:
past_ndays=1
today = datetime.now().date()
start_date = datetime.combine(today - timedelta(days=past_ndays), datetime.min.time())
end_date = datetime.combine(today, datetime.min.time())
print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")
print(f"Fetching attachment data for last {past_ndays} days")

In [ ]:
query = """

SELECT
    a.attachment_id,
    a.zendesk_id,
    a.comment_id,
    a.file_name,
    a.file_extension,
    tj.s3_link 			  AS textract_s3_link,
    tj.job_id             AS textract_job_id,
    tj.status             AS textract_status,
    tj.created_at         AS textract_created_at,
    zt.status             AS ticket_status,
    zt.origin             AS ticket_origin,
    ap.id                 AS prediction_db_id,
    ap.model_name,
    ap.type,
    ap.subtype,
    ap.value              AS prediction_value
FROM llm_zendesk_attachments AS a
JOIN textract_jobs          AS tj
  ON tj.attachment_id = a.attachment_id
JOIN llm_zendesk_tickets    AS zt
  ON zt.zendesk_id = a.zendesk_id
 AND (
      zt.comment_id = a.comment_id
      OR (zt.comment_id IS NULL AND a.comment_id IS NULL)
     )
LEFT JOIN llm_attachments_predictions AS ap
  ON ap.attachment_id = a.attachment_id
WHERE tj.status = 'SUCCEEDED'
AND tj.created_at >= NOW() - INTERVAL 1 DAY
AND zt.status = 'processed'
ORDER BY tj.created_at DESC
"""

#data = analytics_db.sql_to_df(query)

### Result of Above Query Will be read below.

In [12]:
data = pd.read_csv('data/ATTACHMENT_sent_with_preds.csv')

In [ ]:
data

### Not get Attachment's Parsed Texts

In [ ]:
# drop null values
data = data.dropna(subset=['textract_s3_link'])
print(data.shape)

In [ ]:
# get the texts from textract_s3_link
s3_links_sampled = np.random.choice(data['textract_s3_link'].unique(), size=15000, replace=False).tolist()
print(len(s3_links_sampled))

In [ ]:
import boto3
textract_texts = {}
def get_jsons_from_s3(s3_links):
    """
    Retrieves JSON objects from given S3 addresses.
    """
    global textract_texts
    
    session = boto3.Session(profile_name='739275445236_DataScienceUser')
    s3_client = session.client('s3')

    index = 0
    for link in s3_links:
        json_object = [{"BlockType": "LINE", "Text": ""}]
        try:
            # Parse the S3 URI
            parts = link.replace("s3://", "").split("/")
            bucket_name = parts[0]
            key = "/".join(parts[1:])
            # Get the object from S3
            response = s3_client.get_object(Bucket=bucket_name, Key=key)

            # Read the content and parse JSON
            content = response['Body'].read().decode('utf-8')
            json_object = json.loads(content)
            textract_texts[link] = json_object
        except Exception as e:
            print(f"Error from {link} {e}")
            textract_texts[link] = []
        print(f"Processed {index+1}/{len(s3_links)}: {link}")
        index += 1
        
        if index % 5000 == 0:
            print(f"Checkpoint at {index} links processed.")
            # Save intermediate results to avoid data loss
            with open('data/textract_texts_intermediate.json', 'w') as f:
                json.dump(textract_texts, f)
        
    return textract_texts

s3_link_json_pairs = get_jsons_from_s3(s3_links_sampled)

In [ ]:
s3_link_json_pairs

In [ ]:
s3_link_text_pairs = {link: "\n".join([d["Text"] for d in doc if d["BlockType"] == "LINE"]) for link, doc in s3_link_json_pairs.items()}
# def get_texts_from_textract_outputs(
#         textract_jsons):
#         return [
#             "\n".join([d["Text"] for d in doc if d["BlockType"] == "LINE"])
#             for doc in textract_jsons
#        ]
# texts = get_texts_from_textract_outputs(s3_link_json_pairs)

In [ ]:
s3_link_text_pairs

In [ ]:
# save s3_link_text_pairs
with open('data/s3_link_text_pairs.json', 'w') as f:
    json.dump(s3_link_text_pairs, f)

## Continue here

In [3]:
# read s3_link_text_pairs
with open('data/s3_link_text_pairs.json', 'r') as f:
    s3_link_text_pairs = json.load(f)

#### Import pipelines from src code

In [4]:
import os
print(os.getcwd())
os.chdir('../../')
print(os.getcwd())

/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court
/Users/melih.gorgulu/Desktop/Projects/intent_recognition

In [5]:
from pathlib import Path

from src.domain.base.blueprints import AfterCourtModelBlueprint
from src.domain.attachments.attachments_entities import Attachment, CleanTexts
from src.services.attachment_processing.base_input_processor import AfterCourtAttachmentPreprocessor
from src.services.models.aftercourt_classification_model import AfterCourtClassificationModel
from src.db.database_manager import DatabaseManager
from src.services.secrets_manager import SecretsManager
from src.prod_repository.raw_zendesk_tickets_repository import RawZendeskTicketRepository

In [ ]:


models_root = Path.cwd()
aftercourt_config = AfterCourtModelBlueprint.from_json(
    str(models_root / "configs" / "models" / "after_court" / "aftercourt_classification.json")
)._update_pathes(str(models_root))

s3_text_items = list(s3_link_text_pairs.items())
attachments_for_inference = [
    Attachment(
        attachment_id=str(idx),
        created_at=datetime.utcnow(),
        status="processed_by_textract",
        clean_text=CleanTexts(original=text),
    )
    for idx, (_, text) in enumerate(s3_text_items)
]

aftercourt_preprocessor = AfterCourtAttachmentPreprocessor(
    name=aftercourt_config.name,
    preprocessing_config=aftercourt_config.preprocessing,
)
attachments_preprocessed = aftercourt_preprocessor.preprocess(attachments_for_inference)

aftercourt_model = AfterCourtClassificationModel(
    config=aftercourt_config.model,
    name=aftercourt_config.name,
 )

attachments_with_aftercourt_preds = aftercourt_model.predict_attachments(
    attachments_preprocessed
)

aftercourt_predictions = pd.DataFrame(
    [
        {
            "s3_link": link,
            **(attachment.models_outputs.aftercourt_classification or {}),
        }
        for (link, _), attachment in zip(s3_text_items, attachments_with_aftercourt_preds)
    ]
)

aftercourt_predictions.head()

In [ ]:
aftercourt_predictions

### Continue here

In [6]:
os.chdir('/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court')
#aftercourt_predictions.to_csv('data/aftercourt_predictions_on_random_attachments.csv', index=False)
aftercourt_predictions = pd.read_csv('data/aftercourt_predictions_on_random_attachments.csv')

In [7]:
ladung_documents = aftercourt_predictions[aftercourt_predictions['is_aftercourt'] == True]

In [8]:
ladung_documents

,s3_link,is_aftercourt,aftercourt_type
267,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
524,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
1308,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
1584,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
1659,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
1709,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
1938,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
2334,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
2695,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
2797,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3017,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3154,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3269,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3399,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3668,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
3969,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4013,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4015,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4019,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4197,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4314,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
4567,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
5497,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
5704,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
5951,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
6058,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
6713,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
7233,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
7581,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
7754,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
8205,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9299,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9392,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9512,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9533,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9581,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9822,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9897,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
9922,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
10011,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
10459,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
10666,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
10681,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
11588,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
11692,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
11745,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12308,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12310,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12336,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12448,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12579,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12739,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
12815,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
13083,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
13521,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
13597,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
14170,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
14487,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung
14552,s3://pair-data-engineering-new/ocr_prepared_ou...,True,ladung

In [9]:
total_documnents = len(s3_link_text_pairs)
ladung_documents_count = ladung_documents.shape[0]
ladung_documents_percentage = (ladung_documents_count / total_documnents) * 100
print(f"Total Documents: {total_documnents}")
print(f"Ladung Documents: {ladung_documents_count}")
print(f"Ladung Documents Percentage: {ladung_documents_percentage:.2f}%")

Total Documents: 15000
Ladung Documents: 59
Ladung Documents Percentage: 0.39%

In [10]:
s3_links_to_get = ladung_documents['s3_link'].tolist()

In [13]:
ladung_documents_all_data = data[data['textract_s3_link'].isin(s3_links_to_get)]

In [14]:
# add textract_text column to ladung_documents_all_data
ladung_documents_all_data['textract_text'] = ladung_documents_all_data['textract_s3_link'].map(s3_link_text_pairs)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_93067/2522587128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ladung_documents_all_data['textract_text'] = ladung_documents_all_data['textract_s3_link'].map(s3_link_text_pairs)

In [15]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,file_name,file_extension,textract_s3_link,textract_job_id,textract_status,textract_created_at,ticket_status,ticket_origin,prediction_db_id,model_name,type,subtype,prediction_value,textract_text
5614,16982887-1,16982887,NaN,Dokument_145325_13102025_165430.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,dc12ff30de567e64eb06ccd6aaf8f931f3b60344d1f8fe...,SUCCEEDED,2025-10-13 15:16:14,processed,DE,1306685.0,payment_proof,payment_proof,is_payment_proof,'False',Stefanie Herwegh\nBahnhofstraße 24\nObergerich...
5615,16982887-1,16982887,NaN,Dokument_145325_13102025_165430.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,dc12ff30de567e64eb06ccd6aaf8f931f3b60344d1f8fe...,SUCCEEDED,2025-10-13 15:16:14,processed,DE,1306686.0,payment_proof,payment_proof,payment_proof_type,'none',Stefanie Herwegh\nBahnhofstraße 24\nObergerich...
5616,16982887-1,16982887,NaN,Dokument_145325_13102025_165430.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,dc12ff30de567e64eb06ccd6aaf8f931f3b60344d1f8fe...,SUCCEEDED,2025-10-13 15:16:14,processed,DE,1306687.0,multi_attachment,multi_attachment,attachment_type,'other',Stefanie Herwegh\nBahnhofstraße 24\nObergerich...
16229,16978019-1,16978019,NaN,Anlage131025081551.PDF,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,1619c65869115ecb60504c8ddc176be64ef48b34b69cf9...,SUCCEEDED,2025-10-13 07:14:40,processed,DE,1296223.0,payment_proof,payment_proof,is_payment_proof,'False',Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...
16230,16978019-1,16978019,NaN,Anlage131025081551.PDF,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,1619c65869115ecb60504c8ddc176be64ef48b34b69cf9...,SUCCEEDED,2025-10-13 07:14:40,processed,DE,1296224.0,payment_proof,payment_proof,payment_proof_type,'none',Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655467,16645997-1,16645997,NaN,Dokument_76525_18082025_090116.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,cc3d38195855da08164938ea4635f0dfe68e8a093a5894...,SUCCEEDED,2025-08-18 08:07:37,processed,DE,738331.0,invalid_payment_proof,invalid_payment_proof,attachment_type,'other',M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...
656307,16645886-1,16645886,NaN,Dokument_77025_18082025_084727.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,014defaa6e042f7923991dc01ef3ff736e45bde8df96af...,SUCCEEDED,2025-08-18 07:09:59,processed,DE,738047.0,bank_statement,bank_statement,NaN,'False',M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...
656308,16645886-1,16645886,NaN,Dokument_77025_18082025_084727.pdf,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,014defaa6e042f7923991dc01ef3ff736e45bde8df96af...,SUCCEEDED,2025-08-18 07:09:59,processed,DE,738048.0,invalid_payment_proof,invalid_payment_proof,attachment_type,'other',M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...
666365,16638303-1,16638303,NaN,DR-II+098125+Nachr+Gl.Nr.+vom+Termin+15.08.202...,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,57190ced47f9a5995f363954c17b6be64fdc800c2e9a8a...,SUCCEEDED,2025-08-15 12:15:54,processed,DE,728100.0,bank_statement,bank_statement,NaN,'False',Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...
666366,16638303-1,16638303,NaN,DR-II+098125+Nachr+Gl.Nr.+vom+Termin+15.08.202...,pdf,s3://pair-data-engineering-new/ocr_prepared_ou...,57190ced47f9a5995f363954c17b6be64fdc800c2e9a8a...,SUCCEEDED,2025-08-15 12:15:54,processed,DE,728101.0,invalid_payment_proof,invalid_payment_proof,attachment_type,'other',Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...

In [16]:
ladung_documents_all_data = ladung_documents_all_data.drop_duplicates(subset=['attachment_id', 'model_name', 'subtype'])

In [17]:
ladung_documents_all_data["pivot_column_names"] = np.where(
    ladung_documents_all_data["subtype"].isna(),
    ladung_documents_all_data["model_name"],
    ladung_documents_all_data["model_name"] + '.' + ladung_documents_all_data["subtype"].astype(str)
)

ladung_documents_all_data.dropna(subset=['pivot_column_names'], inplace=True)

ladung_documents_all_data = ladung_documents_all_data.pivot(
    index=["attachment_id", 'zendesk_id','comment_id','textract_text'],
    columns='pivot_column_names',
    values="prediction_value"
).reset_index()

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_93067/1995249942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ladung_documents_all_data["pivot_column_names"] = np.where(
/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_93067/1995249942.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ladung_documents_all_data.dropna(subset=['pivot_column_names'], inplace=True)

In [18]:
ladung_documents_all_data

pivot_column_names,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,payment_proof.payment_proof_type,payment_proof.recipient,payment_proof.recipient_iban
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29','unknown','Liquandum Capital GmbH','DE24160800004421601501'
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02','payment_confirmation_email','Firma Liquandum Capital II GmbH','DE60360501050003078078'
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16','unknown','Aviv Germany GmbH','DE46660908000000774731'
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29','payment_confirmation_email','PAIR Finance GmbH','DE58430500010006510465'
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,'none',NaN,NaN
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
50,16976892-1,16976892,NaN,Liebigstraße 2-20\nVERA PFLUG\n22113 Hamburg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN
51,16978019-1,16978019,NaN,Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN
52,16982887-1,16982887,NaN,Stefanie Herwegh\nBahnhofstraße 24\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN
53,22199213664540-1,16761681,2.219921e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN
54,22229149714716-1,16761679,2.222915e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN

In [19]:
zendesk_ids_to_get = tuple(ladung_documents_all_data.zendesk_id.astype(int).astype(str).tolist())
all_text = pd.DataFrame()
for origin in ['DE','NL','CH','AT', 'SE']:
    query = f"""
        SELECT
            CAST(rzt.zendesk_ticket_id AS INT) AS zendesk_id,
            rzt.content as text,
            rzt.from_email as sender_email,
            rzt.to_email as receiver_email
        FROM 
            raw_zendesk_tickets as rzt
        WHERE 
            rzt.zendesk_ticket_id in {zendesk_ids_to_get}
    """
    psql_db = DbConnection('PROD', f'PROD_{origin}')
    tmp = psql_db.sql_to_df(query)
    tmp['origin']=origin
    all_text = pd.concat([all_text,tmp])

INFO [2025-10-15 14:10:23] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2025-10-15 14:10:24] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2025-10-15 14:10:24] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2025-10-15 14:10:25] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2025-10-15 14:10:25] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [20]:
all_text

,zendesk_id,text,sender_email,receiver_email,origin
0,16645886,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
1,16645997,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
2,16650437,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE
3,16657367,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE
4,16666355,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE
5,16671633,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE
6,16685127,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE
7,16686089,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE
8,16701287,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE
9,16708455,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
10,16728195,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE
11,16775138,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
12,16775248,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE
13,16775282,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
14,16842456,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE
15,16638303,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE
16,16654322,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE
17,16664086,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE
18,16669650,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE
19,16670921,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE
20,16888748,"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE
21,16724354,Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE
22,16725623,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE
23,16728458,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
24,16761046,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE
25,16761681,Ratenzahlungs\nBetreff Ratenzahlungsvereinbar...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE
26,16761679,\nAnfrage zu Forderung \nDR II 1332/25\nSehr ...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE
27,16767864,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
28,16768027,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE
29,16796988,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE
30,16798613,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE
31,16835117,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE
32,16932368,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE
33,16976139,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE
34,16881074,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE
35,16846906,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE
36,16875324,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE
37,16900645,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE
38,16976892,"DR-II 4940/25, Ihr Zeichen: 168884170643\nVERA...",vera.pflug@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
39,16978019,Sache DR II 1253/25 Liquandum Capital GmbH ./....,heuss@gvzpost.de,aftercourt@pairfinance.de,DE
40,16654606,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE
41,16656735,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
42,16656958,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE
43,16687494,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE
44,16700311,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE
45,16775530,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
46,16819769,"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE
47,16827947,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE
48,16861796,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE
49,16865228,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE
50,16866201,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE
51,16885823,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
52,16872082,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE
53,16891090,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE
54,16982887,"Ihr Zeichen: 174667085388, Mein Zeichen: DR II...",s.herwegh@gvjustiz.de,verfahren@pairfinance.de,DE

In [21]:
ladung_documents_all_data = ladung_documents_all_data.merge(
    all_text,
    how='left',
    on='zendesk_id',
    suffixes=('', '_ticket'))

In [22]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,payment_proof.payment_proof_type,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29','unknown','Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02','payment_confirmation_email','Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16','unknown','Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29','payment_confirmation_email','PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE
50,16976892-1,16976892,NaN,Liebigstraße 2-20\nVERA PFLUG\n22113 Hamburg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,"DR-II 4940/25, Ihr Zeichen: 168884170643\nVERA...",vera.pflug@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE
51,16978019-1,16978019,NaN,Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1253/25 Liquandum Capital GmbH ./....,heuss@gvzpost.de,aftercourt@pairfinance.de,DE
52,16982887-1,16982887,NaN,Stefanie Herwegh\nBahnhofstraße 24\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 174667085388, Mein Zeichen: DR II...",s.herwegh@gvjustiz.de,verfahren@pairfinance.de,DE
53,22199213664540-1,16761681,2.219921e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Ratenzahlungs\nBetreff Ratenzahlungsvereinbar...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE
54,22229149714716-1,16761679,2.222915e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,\nAnfrage zu Forderung \nDR II 1332/25\nSehr ...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE

### Apply cleaning to ticket text

In [23]:
from src.services.cleaning.detailed_text_cleaner import DetailedTextCleaner
cleaner = DetailedTextCleaner()
ladung_documents_all_data['cleaned_text'] = ladung_documents_all_data['text'].apply(lambda x: cleaner.clean_text(x))

In [24]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,payment_proof.payment_proof_type,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin,cleaned_text
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Zwang..."
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Anlag..."
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der im Be...
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29','unknown','Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla..."
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de..."
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der Zwang...
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02','payment_confirmation_email','Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16','unknown','Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n \nzu der von ..."
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE,"Guten Abend\nWar heute Gerichtsvollzieherin ,m..."
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de..."
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla..."
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE,
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29','payment_confirmation_email','PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de..."
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
50,16976892-1,16976892,NaN,Liebigstraße 2-20\nVERA PFLUG\n22113 Hamburg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,"DR-II 4940/25, Ihr Zeichen: 168884170643\nVERA...",vera.pflug@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der im Be..."
51,16978019-1,16978019,NaN,Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1253/25 Liquandum Capital GmbH ./....,heuss@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach..."
52,16982887-1,16982887,NaN,Stefanie Herwegh\nBahnhofstraße 24\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 174667085388, Mein Zeichen: DR II...",s.herwegh@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten..."
53,22199213664540-1,16761681,2.219921e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Ratenzahlungs\nBetreff Ratenzahlungsvereinbar...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\nbezüglich der ..."
54,22229149714716-1,16761679,2.222915e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,\nAnfrage zu Forderung \nDR II 1332/25\nSehr ...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\nich habe von d..."

### Translate Ticket text

In [25]:
import boto3
import awswrangler.secretsmanager as sm
import boto3
from dataclasses import dataclass
import deepl
from loguru import logger
import time


@dataclass
class SecretsManagerBlueprint:
    secret_id: str = "ds-llm-production"
    region_name: str = "eu-central-1"

def get_secret(secret_id: str, value: str, aws_region: str) -> str:
    return sm.get_secret_json(
        secret_id,
        boto3_session=boto3.Session(region_name=aws_region),
    ).get(value)


class TranslationService:
    def __init__(self):
        self.secrets_manager = SecretsManagerBlueprint()
        self._translator = deepl.Translator(get_secret(
            self.secrets_manager.secret_id,
            "deepl_token",
            self.secrets_manager.region_name
        )
        )

    def translate(self, text, target_lang="EN-GB"):
        try:
            return self._translator.translate_text(text, target_lang=target_lang).text
            # return text
        except Exception as e:
            logger.error(f'Error in translate text: {text}')
            logger.opt(exception=True).error(str(e))
            return text
        
tr = TranslationService()

INFO [2025-10-15 14:10:29] - Found credentials in shared credentials file: ~/.aws/credentials

In [26]:
ladung_documents_all_data['translated_text'] = ladung_documents_all_data['cleaned_text'].apply(lambda x: tr.translate(x, target_lang="EN-GB") if pd.notnull(x) and len(x.strip()) > 0 else x)

INFO [2025-10-15 14:10:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:34] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:40] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:41] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:41] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:10:41] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate

In [53]:
ladung_documents_all_data['translated_text_TEXTRACT'] = ladung_documents_all_data['textract_text'].apply(lambda x: tr.translate(x, target_lang="EN-GB") if pd.notnull(x) and len(x.strip()) > 0 else x)

INFO [2025-10-15 14:39:23] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:23] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:23] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:23] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:23] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:24] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:25] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:25] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:25] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:25] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:26] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:27] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:28] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:29] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:29] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:29] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:30] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:31] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:32] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:33] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:34] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:34] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:34] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:34] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:35] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:36] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:36] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:37] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:38] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:39] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:40] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:40] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:40] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:40] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:41] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:42] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:42] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:42] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:42] - Request to DeepL API method=POST url=https://api.deepl.com/v2/translate
INFO [2025-10-15 14:39:43] - DeepL API response status_code=200 url=https://api.deepl.com/v2/translate

In [27]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,payment_proof.payment_proof_type,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin,cleaned_text,translated_text
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Zwang...","Ladies and Gentlemen,\n\nin the enforcement pr..."
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Anlag...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,Case 616 DR II 362/25 mydays GmbH ./. Koca\nAn...
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der im Be...,Dear Sir or Madam\n\nIn the foreclosure matter...
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29','unknown','Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo..."
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu..."
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der Zwang...,Dear Sir or Madam\n\nIn the enforcement procee...
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02','payment_confirmation_email','Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16','unknown','Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n \nzu der von ...","Ladies and Gentlemen,\n \nThere was an instalm..."
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE,"Guten Abend\nWar heute Gerichtsvollzieherin ,m...","Good evening\nWas today bailiff, I had to file..."
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu..."
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo..."
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE,,
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29','payment_confirmation_email','PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu..."
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
50,16976892-1,16976892,NaN,Liebigstraße 2-20\nVERA PFLUG\n22113 Hamburg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,"DR-II 4940/25, Ihr Zeichen: 168884170643\nVERA...",vera.pflug@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der im Be...","Ladies and Gentlemen,\n\nin the foreclosure ma..."
51,16978019-1,16978019,NaN,Gerichtsvollzieher Heuß\nRietstraße 4 / 74740 ...,NaN,NaN,'invoice','False',NaN,NaN,'none',NaN,NaN,Sache DR II 1253/25 Liquandum Capital GmbH ./....,heuss@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
52,16982887-1,16982887,NaN,Stefanie Herwegh\nBahnhofstraße 24\nObergerich...,NaN,NaN,'other','False',NaN,NaN,'none',NaN,NaN,"Ihr Zeichen: 174667085388, Mein Zeichen: DR II...",s.herwegh@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ..."
53,22199213664540-1,16761681,2.219921e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,NaN,'False',NaN,NaN,'none',NaN,NaN,Ratenzahlungs\nBetreff Ratenzahlungsvereinbar...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\nbezüglich der ...",Dear Sir or Madam\nWith regard to the claim wi...
54,22229149714716-1,16761679,2.222915e+13,Mark Peiffer\nGerichtsvollzieher\nEuropaplatz ...,NaN,NaN,'payment_reminder','False',NaN,NaN,'none',NaN,NaN,\nAnfrage zu Forderung \nDR II 1332/25\nSehr ...,ayshemehmedovaali@gmail.com,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\nich habe von d...",Dear Sir or Madam\nI have received a letter fr...

### Lets check how we sent them to the ccenter

In [28]:
zendesk_ids_to_get = tuple(ladung_documents_all_data.zendesk_id.tolist())

query = f"""
    SELECT
        ci.zendesk_id,
        ci.comment_id,
        ci.intents,
        ci.ready_for_automation,
        ci.created_at
    FROM 
        ccenter_intents ci
    WHERE 
        ci.zendesk_id in {zendesk_ids_to_get}
"""


ccenter_intents_df = analytics_db.sql_to_df(query)

In [29]:
ccenter_intents_df

,zendesk_id,comment_id,intents,ready_for_automation,created_at
0,16638303,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-15 14:48:39
1,16645886,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 09:16:00
2,16645997,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 11:25:53
3,16650437,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 22:05:08
4,16654322,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 08:51:59
5,16654606,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 10:51:17
6,16656735,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 16:28:03
7,16656958,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 16:28:17
8,16657367,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 20:21:30
9,16664086,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-20 14:29:36
10,16666355,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-20 20:58:37
11,16669650,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 12:59:22
12,16670921,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 15:13:34
13,16671633,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 17:32:51
14,16685127,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 10:17:54
15,16686089,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 15:05:39
16,16687494,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 17:33:54
17,16700311,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-27 12:44:48
18,16701287,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-27 15:22:43
19,16708455,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-28 19:42:32
20,16724354,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-01 10:41:08
21,16725623,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 13:01:35
22,16728195,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 21:10:28
23,16728458,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 21:10:45
24,16761046,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-06 10:25:20
25,16761046,2.217480e+13,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-13 13:33:21
26,16761679,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-06 14:29:18
27,16761679,2.222915e+13,"[{""params"": {}, ""language"": null, ""ticket_id"":...",0,2025-09-09 23:58:21
28,16761681,NaN,"[{""params"": {""installment_plan_amount"": 60.0},...",1,2025-09-06 14:29:18
29,16761681,2.219921e+13,"[{""params"": {}, ""language"": null, ""ticket_id"":...",0,2025-09-08 10:16:14
30,16767864,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-08 18:43:04
31,16768027,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-08 18:43:15
32,16796988,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-12 11:03:49
33,16798613,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-12 16:37:46
34,16819769,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-16 22:25:03
35,16827947,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-18 03:07:16
36,16835117,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-19 01:27:52
37,16842456,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-19 22:56:30
38,16846906,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-21 12:44:23
39,16861796,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 01:30:30
40,16865228,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 12:40:23
41,16866201,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 15:49:05
42,16872082,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-25 14:15:24
43,16875324,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-25 23:00:29
44,16881074,NaN,"[{""params"": {}, ""language"": ""en"", ""ticket_id"":...",0,2025-09-26 20:18:05
45,16885823,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-27 18:28:12
46,16885823,2.260132e+13,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-10 01:59:41
47,16888748,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-29 11:14:02
48,16891090,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-29 17:52:57
49,16900645,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-30 19:42:53
50,16932368,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-06 13:22:44
51,16976139,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-12 11:30:22
52,16976892,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-12 17:47:33
53,16978019,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-13 08:57:25
54,16982887,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-14 00:25:02

In [30]:
ccenter_intents_df

,zendesk_id,comment_id,intents,ready_for_automation,created_at
0,16638303,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-15 14:48:39
1,16645886,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 09:16:00
2,16645997,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 11:25:53
3,16650437,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-18 22:05:08
4,16654322,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 08:51:59
5,16654606,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 10:51:17
6,16656735,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 16:28:03
7,16656958,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 16:28:17
8,16657367,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-19 20:21:30
9,16664086,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-20 14:29:36
10,16666355,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-20 20:58:37
11,16669650,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 12:59:22
12,16670921,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 15:13:34
13,16671633,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-21 17:32:51
14,16685127,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 10:17:54
15,16686089,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 15:05:39
16,16687494,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-25 17:33:54
17,16700311,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-27 12:44:48
18,16701287,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-27 15:22:43
19,16708455,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-08-28 19:42:32
20,16724354,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-01 10:41:08
21,16725623,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 13:01:35
22,16728195,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 21:10:28
23,16728458,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-01 21:10:45
24,16761046,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-06 10:25:20
25,16761046,2.217480e+13,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-13 13:33:21
26,16761679,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-06 14:29:18
27,16761679,2.222915e+13,"[{""params"": {}, ""language"": null, ""ticket_id"":...",0,2025-09-09 23:58:21
28,16761681,NaN,"[{""params"": {""installment_plan_amount"": 60.0},...",1,2025-09-06 14:29:18
29,16761681,2.219921e+13,"[{""params"": {}, ""language"": null, ""ticket_id"":...",0,2025-09-08 10:16:14
30,16767864,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-08 18:43:04
31,16768027,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-08 18:43:15
32,16796988,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-12 11:03:49
33,16798613,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-12 16:37:46
34,16819769,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-16 22:25:03
35,16827947,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-18 03:07:16
36,16835117,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-19 01:27:52
37,16842456,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-19 22:56:30
38,16846906,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-21 12:44:23
39,16861796,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 01:30:30
40,16865228,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 12:40:23
41,16866201,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-24 15:49:05
42,16872082,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-25 14:15:24
43,16875324,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-25 23:00:29
44,16881074,NaN,"[{""params"": {}, ""language"": ""en"", ""ticket_id"":...",0,2025-09-26 20:18:05
45,16885823,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-27 18:28:12
46,16885823,2.260132e+13,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-10 01:59:41
47,16888748,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1,2025-09-29 11:14:02
48,16891090,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-29 17:52:57
49,16900645,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-09-30 19:42:53
50,16932368,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-06 13:22:44
51,16976139,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-12 11:30:22
52,16976892,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-12 17:47:33
53,16978019,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-13 08:57:25
54,16982887,NaN,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0,2025-10-14 00:25:02

In [31]:
ladung_documents_all_data = ladung_documents_all_data.merge(
    ccenter_intents_df.drop(columns=['created_at']),
    how='left',
    on=['zendesk_id','comment_id'],
    suffixes=('', '_ccenter'))

In [32]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,...,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin,cleaned_text,translated_text,intents,ready_for_automation
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Zwang...","Ladies and Gentlemen,\n\nin the enforcement pr...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Anlag...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,Case 616 DR II 362/25 mydays GmbH ./. Koca\nAn...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der im Be...,Dear Sir or Madam\n\nIn the foreclosure matter...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29',...,'Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der Zwang...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02',...,'Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,NaN,NaN
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16',...,'Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n \nzu der von ...","Ladies and Gentlemen,\n \nThere was an instalm...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE,"Guten Abend\nWar heute Gerichtsvollzieherin ,m...","Good evening\nWas today bailiff, I had to file...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE,,,"[{""params"": {}, ""language"": ""en"", ""ticket_id"":...",0.0
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29',...,'PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0

In [2]:
#ladung_documents_all_data.to_csv('data/ladung_documents_all_data.csv', index=False)
ladung_documents_all_data = pd.read_csv('data/ladung_documents_all_data.csv')

### Continue here

In [34]:
# lets check the results to understand how ladung documents were sent to us

In [35]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,...,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin,cleaned_text,translated_text,intents,ready_for_automation
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Zwang...","Ladies and Gentlemen,\n\nin the enforcement pr...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Anlag...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,Case 616 DR II 362/25 mydays GmbH ./. Koca\nAn...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der im Be...,Dear Sir or Madam\n\nIn the foreclosure matter...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29',...,'Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der Zwang...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02',...,'Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,NaN,NaN
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,None,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16',...,'Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n \nzu der von ...","Ladies and Gentlemen,\n \nThere was an instalm...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE,"Guten Abend\nWar heute Gerichtsvollzieherin ,m...","Good evening\nWas today bailiff, I had to file...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE,,,"[{""params"": {}, ""language"": ""en"", ""ticket_id"":...",0.0
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29',...,'PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0

In [3]:
import os
print(os.getcwd())
os.chdir('../../')
print(os.getcwd())

/Users/melih.gorgulu/Desktop/Projects/intent_recognition/notebooks/after-court
/Users/melih.gorgulu/Desktop/Projects/intent_recognition

In [4]:
from IPython.display import display, HTML

def show_colored_params(params, key_color="#ff6b6b", value_color="#4ecdc4"):
    if not params:
        display(
            HTML(
                "<div style='font-family:monospace;background:#1e1e1e;padding:12px;border-radius:8px;color:#ff6b6b;'>No parameters extracted.</div>"
            )
        )
        return

    content = "".join(
        f"<div><span style='color:{key_color};font-weight:600;'>{key}</span>: "
        f"<span style='color:{value_color};'>{value}</span></div>" for key, value in params.items()
    )
    display(
        HTML(
            "<div style='font-family:monospace;background:#1e1e1e;padding:12px;border-radius:8px;'>"
            + content
            + "</div>"
        )
    )
    
def print_colored_text(text: str, strings: list[str]) -> None:
    text = text.lower()
    colors = [
        "\033[91m",  # red
        "\033[92m",  # green
        "\033[94m",  # blue
        "\033[95m",  # magenta
        "\033[96m",  # cyan
        "\033[93m",  # yellow
    ]
    reset = "\033[0m"
    colored_text = text
    for idx, fragment in enumerate(strings):
        if not fragment:
            continue
        color = colors[idx % len(colors)]
        colored_text = colored_text.replace(fragment, f"{color}{fragment}{reset}")
    print(colored_text)

In [5]:
from src.services.attachment_processing.aftercourt_extractors.ladung.strategy import LadungParameterExtractorStrategy
extractor = LadungParameterExtractorStrategy()

In [6]:
ladung_documents_all_data

,attachment_id,zendesk_id,comment_id,textract_text,bank_statement,invalid_payment_proof.attachment_type,multi_attachment.attachment_type,payment_proof.is_payment_proof,payment_proof.payment_amount,payment_proof.payment_date,...,payment_proof.recipient,payment_proof.recipient_iban,text,sender_email,receiver_email,origin,cleaned_text,translated_text,intents,ready_for_automation
0,16638303-1,16638303,NaN,Bindlacher Str. 3\nMarkus Rödel\n95448 Bayreut...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 0981/25, Liquandum Capital GmbH ./. Scha...",markus-roedel@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Zwang...","Ladies and Gentlemen,\n\nin the enforcement pr...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
1,16645886-1,16645886,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173354132123, Mein Zeichen: DR II...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
2,16645997-1,16645997,NaN,M. Suttmann\nGerichtsvollzieherin\nJoseph-von-...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
3,16650437-1,16650437,NaN,Gerichtsvollzieherin\nBorsigallee 10\nL. Riedl...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Sache DR II 1774/25, Ihr Aktz. 112275389636\nA...",linda.riedl@ag-bonn.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
4,16654322-1,16654322,NaN,Obergerichtsvollzieherin\nEuropaplatz 11\nBeat...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache DR II 1058/25 PAIR Finance GmbH ./. Habi...,beate.borren@ag-moenchengladbach.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
5,16654606-1,16654606,NaN,H. Schuller\nHauptgerichtsvollzieher\nLechstr....,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 46 DR 1101/25 Liquandum Capitel II GmbH ...,h.schuller@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nin der Anlag...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
6,16656735-1,16656735,NaN,A. Hornauer\nAugust-Fritzsche-Straße 10\n04838...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"DR-II 1054/25, N26 Bank SE vertr.d.d. Vorstand...",hornauer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
7,16656958-1,16656958,NaN,Gerichtsvollzieher Marc Oedekoven\nAmtsgericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,Sache 31 DR II 1052/25 Liquandum Capital II Gm...,marc.oedekoven@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
8,16657367-1,16657367,NaN,M. Krammer\nGabelsbergerstraße 52\nObergericht...,'False','other',NaN,NaN,NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171935511138, Mein Zeichen: DR II...",gv-krammer@online.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
9,16664086-1,16664086,NaN,"Lüdke\nHellersdorfer Weg 35, R.504\nObergerich...",NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 171931616477, Mein Zeichen: DR II...",ogvinluedke@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
10,16666355-1,16666355,NaN,Hauptgerichtsvollzieherin\nAmtsgericht\nRosenh...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 1 DR 858/25 E.ON Energie Deutschland Gmb...,hgv-patricia-debus@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
11,16669650-1,16669650,NaN,Obergerichtsvollzieher\nBüroanschrift\nWolfram...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 884/25 Liquandum Capital II GmbH ....,wolfram.schindler@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
12,16670921-1,16670921,NaN,B. Sieverding\nTelingskamp 11\nObergerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 173372925870, Mein Zeichen: DR II...",bernd.sieverding@ag-bocholt.nrw.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
13,16671633-1,16671633,NaN,L. Sontheimer\nSchellingstraße 33\nGerichtsvol...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 159641359520, Mein Zeichen: DR II...",l.sontheimer@gvjustiz.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
14,16685127-1,16685127,NaN,R. Kindelbacher\nDerchinger Straße 85 b\nOberg...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 1066011550570, Mein Zeichen: DR I...",r.kindelbacher@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
15,16686089-1,16686089,NaN,Obergerichtsvollzieher\nBremer Straße 78\nMarc...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,gerichtsvollzieher-kultscher@gvpost.de,verfahren@pairfinance.de,DE,Sache 616 DR II 362/25 mydays GmbH ./. Koca\nA...,Case 616 DR II 362/25 mydays GmbH ./. Koca\nAn...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
16,16687494-1,16687494,NaN,Martina Schäfner\nBahnhofstraße 17 (3. OG)\nOb...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168886034870, Mein Zeichen: DR II...",gv.schaefner@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
17,16700311-1,16700311,NaN,Dr. Schmidt Straße 7\nBernd Ackermann\n95632 W...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0801/25, Ihr Zeichen: 105089495466\nBern...",bernd.ackermann@gerichtsvollzieher.de,verfahren@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der im Be...,Dear Sir or Madam\n\nIn the foreclosure matter...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
18,16701287-1,16701287,NaN,GVin\nBayreuther Str. 9\nS. Landgraf\n95494 Ge...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR 722/25 Liquandum Capital GmbH ./. Fuc...,s.landgraf@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
19,16708455-1,16708455,NaN,Fischerstraße 12 / 3. OG\nHerbert Blomeyer\n91...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0987/25, Liquandum Capital GmbH ./. Yesi...",herbert.blomeyer@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
20,16724354-1,16724354,NaN,Guido Hilgenfeld\nBranden-\nObergerichtsvollzi...,NaN,NaN,NaN,'True','49.59','2025-08-29',...,'Liquandum Capital GmbH','DE24160800004421601501',Sache: DR II 15/25 - 153545498138 Liquandum Ca...,guidohilgenfeld@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
21,16725623-1,16725623,NaN,Obergerichtsvollzieher\n26603 Aurich\nKirchdor...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 900/25 Liquandum Capital GmbH ./. ...,habbo.freudenberg@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
22,16728195-1,16728195,NaN,S. Molzow\nHellersdorfer Weg 35\nObergerichtsv...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 169939424928, Mein Zeichen: DR II...",gv.molzow@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
23,16728458-1,16728458,NaN,Obere Eschstraße 20\nWOLFGANG EGBERS\n49179 Os...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0896/25, E.ON Energie Deutschland GmbH ....",wolfgang.egbers@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren!\n\nIn der Zwang...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
24,16761046-1,16761046,NaN,Gerichtsvollzieher\nKölner Straße 90\nHäring\n...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,Sache DR II 1405/25 Mondu Capital S.a.r.l ./. ...,roland.haering@gvzpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
25,16767864-1,16767864,NaN,Gillweg 3\nM. MEYER-HARTUNG\n14193 Berlin\nObe...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"DR-II 0690/25, Liquandum Capital GmbH ./. Stei...",m.meyer-hartung@gerichtsvollzieher.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
26,16768027-1,16768027,NaN,Kathrin Frankenberg\nKollegienwall 24\nGericht...,NaN,NaN,NaN,'False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 172141523412, Mein Zeichen: DR II...",kathrinfrankenberg@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
27,16775138-1,16775138,NaN,Annika Reinhardt\nLilly-Reich-Straße 5\nOberge...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,NaN,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
28,16775248-1,16775248,NaN,Lynn Bültert\nIn der Hagenbeck 50\nGerichtsvol...,NaN,NaN,'payment_completed','True','92.71','2025-09-02',...,'Firma Liquandum Capital II GmbH','DE60360501050003078078',GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,tech@pairfinance.com,NaN,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,NaN,NaN
29,16775282-1,16775282,NaN,Jan Grothues\nTelingskamp 11 (1. OG)\nGerichts...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,NaN,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
30,16775530-1,16775530,NaN,Obergerichtsvollzieherin\nAmtsgericht Amberg\n...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,tech@pairfinance.com,NaN,DE,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,GVZ - Scanned Brief\nDetected Slugs:\n\n 16...,NaN,NaN
31,16796988-1,16796988,NaN,Uwe Krammer\nSchragenhofstraße 27\nGerichtsvol...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 168804357601, Mein Zeichen: 16 DR...",gv-krammer-uwe@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
32,16798613-1,16798613,NaN,N. Geier\nJohannes-Flintrop-Straße 8-10\nOberg...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 155520212665, Mein Zeichen: DR II...",natalie.geier@ag-mettmann.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
33,16819769-1,16819769,NaN,Gerichtsvollzieherin Fischer\nTelefon:\n0151 1...,NaN,NaN,'payment_completed','True',NaN,'2025-09-16',...,'Aviv Germany GmbH','DE46660908000000774731',"Aw: Ihre letzte Chance, den Restbetrag der Rat...",sabinemarzinek@web.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n \nzu der von ...","Ladies and Gentlemen,\n \nThere was an instalm...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
34,16827947-1,16827947,NaN,Kölner Str. 211\n40227 Düsseldorf\nTel. 0211/3...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"DR-II 1897/25, Liquandum Capital GmbH ./. Ayd...",thorsten.koenig@ag-duesseldorf.nrw.de,aftercourt@pairfinance.de,DE,Sehr geehrte Damen und Herren\n\nIn der Zwangs...,Dear Sir or Madam\n\nIn the enforcement procee...,"[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
35,16835117-1,16835117,NaN,Obergerichtsvollzieher Gerald Haindl\nAmtsgeri...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache 97 DR 1291/25 Liquandum Capital II GmbH,...",gerald-haindl@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
36,16842456-1,16842456,NaN,Gerichtsvollzieherin\nBischof-Fischer-Str. 86\...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Re: Inkassoprozess wird fortgesetzt\nGuten Abe...,schunemanncorinna1969@gmail.com,kundenservice@pairfinance.de,DE,"Guten Abend\nWar heute Gerichtsvollzieherin ,m...","Good evening\nWas today bailiff, I had to file...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
37,16846906-1,16846906,NaN,Obergerichtsvollzieherin\nAmtsgericht\nHamburg...,NaN,NaN,'invoice','False',NaN,NaN,...,NaN,NaN,Az. 166007060394; Sache DR II 677/25 Liquandum...,c.reupsch@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
38,16861796-1,16861796,NaN,Obergerichtsvollzieherin Jeannette Palagano\nT...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 1939/25 Liquandum Capital II GmbH ...,jeannette.palagano@ag-duesseldorf.nrw.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
39,16865228-1,16865228,NaN,Benjamin Stuth\nChriststr. 17\nGerichtsvollzie...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 156183644624, Mein Zeichen: DR II...",benjamin.stuth@gvjustiz.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
40,16866201-1,16866201,NaN,Obergerichtsvollzieherin\nSchwabenstraße 57\nS...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Sache DR II 642/25, Ihr Aktz. 162020800718\nAk...",gvin.silke.saathoff@gvpost.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
41,16872082-1,16872082,NaN,G. Vassallo\nMünchner Straße 5\nGerichtsvollzi...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 165585545859, Mein Zeichen: DR II...",vassallo@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
42,16875324-1,16875324,NaN,Torsten Fichtner\nFreistaat\nObergerichtsvollz...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache: DR II 1436/25 - 163101018592 Liquandum ...,gvzfichtner@web.de,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\ndie angefügte Anla...","Dear recipient,\n\nYou are receiving the enclo...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
43,16881074-4,16881074,NaN,ana Geyer\nNutzweg 3\n/bergerichtsvollzieherin...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Fwd: 174114922779\n> \n> ﻿Hallo Zusammen,\n> \...",nazlikablan@icloud.com,verfahren@pairfinance.de,DE,NaN,NaN,"[{""params"": {}, ""language"": ""en"", ""ticket_id"":...",0.0
44,16885823-2,16885823,NaN,M. Suttmann\nJoseph-von-Eichendorff-Straße 10\...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 17338057404, Mein Zeichen: DR II ...",melanie.suttmann@gmail.com,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
45,16888748-1,16888748,NaN,Max Wolczik\nMetzstraße 6\nObergerichtsvollzie...,NaN,NaN,'payment_completed','True','37.97','2025-09-29',...,'PAIR Finance GmbH','DE58430500010006510465',"Ihr Zeichen: 165772381480, Mein Zeichen: DR II...",mwolczik@aol.com,aftercourt@pairfinance.de,DE,"Sehr geehrter Empfänger,\n\nSie erhalten in de...","Dear recipient,\n\nPlease find enclosed a docu...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",1.0
46,16891090-1,16891090,NaN,Obergerichtsvollzieherin B. Behring\nPostansch...,NaN,NaN,'payment_reminder','False',NaN,NaN,...,NaN,NaN,Sache IV DR II 800/25 Liquandum Capital GmbH ....,ogv.behring@gvpost.de,kundenservice@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
47,16900645-1,16900645,NaN,M. Schmidt\nSegelfliegerdamm 89\nObergerichtsv...,NaN,NaN,'pair_communication','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 170502904411, Mein Zeichen: DR II...",m.schmidt@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
48,16932368-1,16932368,NaN,Obergerichtsvollzieher\n53518 Adenau\nGregor T...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,Sache DR II 734/25 Travelcircus GmbH ./. Weide...,ogv.theisen@gvpost.de,verfahren@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nzu o.g. Sach...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0
49,16976139-1,16976139,NaN,Dieter Görsch\nGustav-Bergt-Str. 5\nObergerich...,NaN,NaN,'other','False',NaN,NaN,...,NaN,NaN,"Ihr Zeichen: 115967619970, Mein Zeichen: DR II...",gv.dieter.goersch.rosslau@gvzentrale.de,aftercourt@pairfinance.de,DE,"Sehr geehrte Damen und Herren,\n\nSie erhalten...","Ladies and Gentlemen,\n\nPlease find enclosed ...","[{""params"": {}, ""language"": ""de"", ""ticket_id"":...",0.0

In [ ]:
# MISCLASSIFIED DOCUMENT TEXTS:
# ALSO CHECK: Projects/after-court/document_quenstions
# 1 -> probably should be enforcement order
# 5 -> what should be this class?
# 27 - > we have a mail from tech@pairfinance.com with Email receiver:  None, the content is: GVZ - Scanned Brief
# Detected Slugs:

#     163100638366
# What is that? (This question is for index 27) -> btw the attachment looks like enforcement order
# 28 -> not ladung document, what is that? (might be enforcement order)
# 29 -> not ladung document, what is that? (might be enforcement order)
# 30 -> not ladung document, what is that? (might be enforcement order)
# 37 -> again looks like enforcement order
# 47-> again enforcement order
# 45 -> what is that?
# 53 -> interesting e-mail

In [10]:

index = 4
textract_text = ladung_documents_all_data.iloc[index]["textract_text"]
#textract_text_translated = ladung_documents_all_data.iloc[index]["translated_text_TEXTRACT"]
translated_text = ladung_documents_all_data.iloc[index]["translated_text"]
extracted_params = extractor.extract_aftercourt_parameters(textract_text)
slug = extracted_params.get("slug", "")
name, surname = extracted_params.get('debtor_name',' ').split(' ', 1) if 'debtor_name' in extracted_params else ('', '')
name = name.lower()
surname = surname.lower()
date = extracted_params.get('judicial_summon_date', '')
date = date.replace('-','.')
show_colored_params(extracted_params)
print("______________ATTACHMENT TEXT TRANSLATED______________")
print_colored_text(textract_text, [slug, name, surname, date])
print("_"*100)
print("______________EMAIL TICKET TEXT TRANSLATED______________")
print(translated_text)
print("_"*100)
print("Email sender: ", ladung_documents_all_data.iloc[index]['sender_email'])
print("Email receiver: ", ladung_documents_all_data.iloc[index]['receiver_email'])

______________ATTACHMENT TEXT TRANSLATED______________
obergerichtsvollzieherin
europaplatz 11
beate borren
41061 mönchengladbach
amtsgericht mönchengladbach
bürozeiten
montag + mittwoch
telefon
12.00 13.00 uhr
02161 9373390
dienstkonto
iban de36 3706 9252 8001 6890 20
bic genoded1ere
abs.: ogvin beate borren, europaplatz 11, 41061 mönchengla
e-mail
beate.borren@ag-moenchengladbach.nrw.de
pair finance gmbh
knesebeckstraße 62-63
10719 berlin
mein zeichen
ihr zeichen
dr ii 1058/25
159908222163
mönchengladbach, 19.08.2025
bitte immer angeben!
zwangsvollstreckungssache
pair finance gmbh, knesebeckstraße 62-63, 10719 berlin, tel. 030/340 602 950, e-mail
aftercourt@pairfinance.de
gegen
frau celina habiciak, flachsbleiche 104, 41179 mönchengladbach
sehr geehrte damen und herren,
in vorstehender angelegenheit habe ich gemäß ihrem auftrag termin zur abgabe der vermögensauskunft
auf
montag, 08.09.25, 09:40 uhr, europaplatz 11, 41061 mönchengladbach (hbf.)
bestimmt.
die erneute ladung war notwendig, da die schuldner post-zu zur ladung am 02.07.25 nicht zurückgelangt ist.
wenn sie zu diesem termin ebenfalls erscheinen wollen, informieren sie mich bitte vorher.
der schuldnerin wurde gem. § 802 f abs. 1 zpo zur begleichung ihrer forderung eine frist von zwei wochen gesetzt.
zugleich wurde für den fall, dass die forderung nach fristablauf nicht vollständig beglichen ist, obiger termin zur
abgabe der vermögensauskunft bestimmt.
nach artikel 13 der datenschutz-grundverordnung (ds-gvo) bin ich verpflichtet, sie davon in kenntnis zu setzen,
dass für die durchführung der vollstreckung ihr vor- und familienname, geburtsname sowie vollständige anschrift
gespeichert werden. die registrierten angaben werden nur für meine gesetzlichen aufgaben genutzt, nicht an dritte
übermittelt und gegen den zugriff dritter geschützt.
nach zweckerreichung sind erlangte schuldnerdaten zu löschen.
informationen zur verarbeitung personenbezogener daten in rechtssachen durch die justiz nordrhein-westfalen
finden sie unter: www.justiz.nrw/datenschutz/rechtssachen.
mit freundlichen grüßen
(beate borren)
obergerichtsvollzieherin
beim amtsgericht mönchengladbach
____________________________________________________________________________________________________
______________EMAIL TICKET TEXT TRANSLATED______________
Ladies and Gentlemen,

Please find enclosed a document on the above-mentioned matter.

With kind regards
____________________________________________________________________________________________________
Email sender:  beate.borren@ag-moenchengladbach.nrw.de
Email receiver:  aftercourt@pairfinance.de