In [1]:
import os

In [2]:
bucket_name = "pair-email-classification"
da_with_invoice_object_base = "data/aftercourt/drittauskunf_with_invoice/"
da_without_invoice_object_base = "data/aftercourt/drittauskunft_without_invoice/"
da_with_invoice_local_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/drittauskunft/with_invoice"
da_without_invoice_local_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/drittauskunft/without_invoice"

In [3]:
da_invoice_local_paths = [os.path.join(da_with_invoice_local_path, filename) for filename in os.listdir(da_with_invoice_local_path) if filename.endswith(".pdf")]
da_no_invoice_local_paths = [os.path.join(da_without_invoice_local_path, filename) for filename in os.listdir(da_without_invoice_local_path) if filename.endswith(".pdf")]

In [4]:
print(f"Found {len(da_invoice_local_paths)} PDFs with invoice and {len(da_no_invoice_local_paths)} PDFs without invoice.")

Found 26 PDFs with invoice and 27 PDFs without invoice.

In [5]:
print(da_invoice_local_paths[0], "\n", da_no_invoice_local_paths[0])

/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/drittauskunft/with_invoice/0_sammel120251218-309-jspu2c.pdf
 /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/drittauskunft/without_invoice/Dr_ii_635_25_an_gl_mitt_ergebnis_drittauskunft_ohne_hb20251219-311-1savlpi.pdf

In [6]:
import sys
sys.path.append("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation")
from utils.use_textract_utils import parse_local_pdfs_with_textract

In [7]:
da_invoice_texts = parse_local_pdfs_with_textract(
    local_pdf_paths=da_invoice_local_paths,
    s3_object_key_base=da_with_invoice_object_base,
    s3_bucket_name=bucket_name,
    use_page_markers=True,
)

In [8]:
da_no_invoice_texts = parse_local_pdfs_with_textract(
    local_pdf_paths=da_no_invoice_local_paths,
    s3_object_key_base=da_without_invoice_object_base,
    s3_bucket_name=bucket_name,
    use_page_markers=True,
)

In [9]:
import pandas as pd

output_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/classification/drittauskunft/dataset"

rows = [
    {"s3_key": k, "text": v, "label": "with_invoice"} for k, v in da_invoice_texts.items()
] + [
    {"s3_key": k, "text": v, "label": "without_invoice"} for k, v in da_no_invoice_texts.items()
]

df = pd.DataFrame(rows)
df.to_parquet(os.path.join(output_dir, "drittauskunft_objectkey_to_texts.parquet"), index=False)
print(df["label"].value_counts())

label
without_invoice    27
with_invoice       26
Name: count, dtype: int64

In [10]:
df

,s3_key,text,label
0,data/aftercourt/drittauskunf_with_invoice/0_sa...,<page_1>\nObergerichtsvollzieher Frank Schäfer...,with_invoice
1,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nAnlage zu GZ: St II 4 S 0229a KEVIZZ...,with_invoice
2,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nThomas Vetter\nJohann-Ruland-Weg 9\n...,with_invoice
3,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,with_invoice
4,data/aftercourt/drittauskunf_with_invoice/63_d...,<page_1>\nChristian Linner\nSchragenhofstraße ...,with_invoice
5,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,with_invoice
6,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,with_invoice
7,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nDaniel Arlt\nUlrich-Kaegerl-Straße 5...,with_invoice
8,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,with_invoice
9,data/aftercourt/drittauskunf_with_invoice/B_DR...,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,with_invoice
10,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,with_invoice
11,data/aftercourt/drittauskunf_with_invoice/RB_0...,<page_1>\nKriegsstr. 65\nCLAUDIUS BETZLER\n761...,with_invoice
12,data/aftercourt/drittauskunf_with_invoice/3_dr...,<page_1>\nObergerichtsvollzieher Frank Pergand...,with_invoice
13,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nGerichtsvollzieherin beim Amtsgerich...,with_invoice
14,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,with_invoice
15,data/aftercourt/drittauskunf_with_invoice/KL_0...,<page_1>\nGerichtsvollzieherin Antje Netzband\...,with_invoice
16,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nObergerichtsvollzieher\n66292 Riegel...,with_invoice
17,data/aftercourt/drittauskunf_with_invoice/Dr_1...,<page_1>\nObergerichtsvollzieherin\nAnschrift\...,with_invoice
18,data/aftercourt/drittauskunf_with_invoice/0_sa...,<page_1>\nObergerichtsvollzieher Frank Schäfer...,with_invoice
19,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nNicole Sommer\nKönigstr. 11\nGericht...,with_invoice
20,data/aftercourt/drittauskunf_with_invoice/63_d...,<page_1>\nChristian Linner\nSchragenhofstraße ...,with_invoice
21,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,with_invoice
22,data/aftercourt/drittauskunf_with_invoice/1_sa...,<page_1>\nGerichtsvollzieherin\nMozartstraße 5...,with_invoice
23,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,with_invoice
24,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,with_invoice
25,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nObergerichtsvollzieherin\nEuropaplat...,with_invoice
26,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nAmtsgericht: B...,without_invoice
27,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nPostfach 60 02...,without_invoice
28,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nNeue Büroanschrift ab 01.12.2024\nDo...,without_invoice
29,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieher\nHellersdorfe...,without_invoice
30,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nSylvia Niemeyer\nSchloßstraße 4\nObe...,without_invoice
31,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nHauptgerichtsvollzieherin\nBüroansch...,without_invoice
32,data/aftercourt/drittauskunft_without_invoice/...,"<page_1>\nJ. RIEGER\n89522 Heidenheim, Helmut-...",without_invoice
33,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nN. Stenzel\nBlücherstraße 4\nGericht...,without_invoice
34,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,without_invoice
35,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nMarion Kruska\nLilly-Reich-Str. 5\nO...,without_invoice
36,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAmtsgericht Mülheim-Ruhr\nObergerich...,without_invoice
37,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nSandra Zander\nObergerichtsvollziehe...,without_invoice
38,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nF. Häußler\nMarktplatz 6\nGerichtsvo...,without_invoice
39,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherbüro Duhnke\nAmtsg...,without_invoice
40,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nOLIVER LIEB\nStethaimerstraße 32-34\...,without_invoice
41,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nJanina Dahlhaus\nAdolf-Grimme-Straße...,without_invoice
42,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieher\n66953 Pirmas...,without_invoice
43,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nTheo Schmitz\nKölner Strasse 73\nObe...,without_invoice
44,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nNina Glöckler\nMarktplatz 3\nGericht...,without_invoice
45,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAmtsgericht\nKontakt und Information...,without_invoice
46,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nVINCENZ SCHIMA\nKnöterichpfad 13\nOb...,without_invoice
47,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nHelga Gerstl\nHauptgerichtsvollziehe...,without_invoice
48,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nR. Müller\nObergerichtsvollzieher\nL...,without_invoice
49,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,without_invoice
50,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAnne-Katrin Götz\nAmtsgericht Dortmu...,without_invoice
51,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieherin G. Samuels\...,without_invoice
52,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nKreuzgasse 17\...,without_invoice

In [11]:
print(df.iloc[0]["text"])

<page_1>
Obergerichtsvollzieher Frank Schäfer
bei dem Amtsgericht Darmstadt
Mein Zeichen:
DR II 1870/25
OGV Frank Schäfer, Mathildenplatz 12, 64283 Darmstadt
Bitte immer angeben!
Firma
Ihr Zeichen: 177398801833
PAIR Finance GmbH
Knesebeckstraße 62-63
Telefon 06150/55301,Mobil:017692264261
10719 Berlin
Telefax 06150/591668
Erzhausen, 18.12.2025
Zwangsvollstreckungssache
Firma Liquandum Capital II GmbH, Knesebeckstraße 62-63, 10719 Berlin
vertr. d.
Firma PAIR Finance GmbH, Knesebeckstraße 62-63, 10719 Berlin
gegen
Herrn Labid Ahmad, Falkenweg 7, 64331 Weiterstadt
Sehr geehrte Damen und Herren,
in oben genannter Sache teile ich Ihnen mit, dass im Termin zur Abgabe der Vermögensauskunftder Schuldner trotz
ordnungsgemäßer Ladung nicht erschienen ist.
Erlass eines Haftbefehls wurde nicht beantragt
Nach Zweckerreichung sind erlangte Schuldnerdaten zu löschen.
Die entstandenen Kosten bitte ich auf mein Dienstkonto zu überweisen. GiroCode 75,11€.
Kostenrechnung GvKostG (KV=Kostenverzeichnis) in EUR V. 18.12.25
Mit/freundlichen Grüßen
Nr. Bezeichnung
Betrag Anz. Gesamt
1
KV 100 Pers. Zustellung
12,00 1
12,00
2 KV 604 Nicht erled. Amtshandl.
18,00 1
18,00
zu 260
(Frank Schäfer)
3
KV 440 Auskunft BZSt
15,60 1
15,60
Obergerichtsvollzieher
4
KV 208 Versuch gütliche Erled.
9,60 1
9,60
beim Amtsgericht Darmstadt
5
KV 711 Wegegeld 0-10 km
1
3,25
Zwangsvollstreckungsdaten werden in meiner
6
KV 701 Entgelt Zustellung
5,62 1
5,62
EDV gespeichert! Löschung 1 Jahr n.d. Erledi-
7
KV 716 Pauschale
11,04
gungsjahr. Keine Datenweitergabe an Dritte!
8
Rechnungs- und Zahlungsbetrag
75,11
(§§ 7;11;18II HDG)
D. Kostenschuldn. ist Firma Liquandum Capital Il GmbH.
Rechtsbehelfsbelehrung: Gegen diese Kostenrechnung kann Erinnerung
beim Amtsgericht Darmstadt, 64293 Darmstadt, Mathildenplatz 15
schriftlich oder zu Protokoll der Geschäftsstelle eingelegt werden. Es ist
zweckmäßig, die Erinnerung zu begründen. Die Erinnerung kann als ein für
die Bearbeitung durch das Gericht gem. §§ 2 und 5 ERVV geeignetes
elektronisches Dokument eingereicht werden. Die verantwortende Person
muss jedes Dokument mit einer qualifizierten elektronischen Signatur
(QES) versehen und gem. § 4 ERVV oder signiert auf sicherem
Übermittlungsweg gem. § 130a Abs. 4 ZPO einreichen. Weitere
Informationen unter www.justiz.de.
Anschrift
Dienstkonto
Sprechzeiten: (tel. nur mobil erreichbar)
c/o AG Darmstadt
IBAN:DE27660908000004728599
Di. 12-13 Uhr, AG Darmstadt, RaumB019
Mathildenplatz 12
BIC:GENODE61BBB
Fr.10:30-11:30, AG Darmstadt, RaumB013
64283 Darmstadt
BBBank Karlsruhe
<page_2>
Obergerichtsvollzieher Frank Schäfer
bei dem Amtsgericht Darmstadt
Mein Zeichen:
DR II 1870/25
OGV Frank Schäfer, Mathildenplatz 12, 64283 Darmstadt
Bitte immer angeben!
Firma
Ihr Zeichen: 177398801833
PAIR Finance GmbH
Knesebeckstraße 62-63
Telefon 06150/55301,Mobil:017692264261
10719 Berlin
Telefax 06150/591668
Erzhausen, 18.12.2025
Zwangsvollstreckungssache
Firma Liquandum Capital II GmbH, Knesebeckstraße 62-63, 10719 Berlin
vertr. d.
Firma PAIR Finance GmbH, Knesebeckstraße 62-63, 10719 Berlin
gegen
Herrn Labid Ahmad, Falkenweg 7, 64331 Weiterstadt
Sehr geehrte Damen und Herren,
in o.g. Sache haben Sie mich beauftragt, eine Drittauskunft nach § 8021 ZPO beim Bundeszentralamt für Steuern
einzuholen.
Das Ergebnis teile ich Ihnen unter Übersendung einer Kopie der entsprechenden Stellen mit.
Ich weise Sie ausdrücklich darauf hin, dass die erlangten Daten nur zu Vollstreckungszwecken genutzt werden dürfen
und nach Zweckerreichung in dieser Sache zu löschen sind (§§ 802 Abs. 3, 802 d Abs. 1 ZPO). Die Weiterleitung
dieser Daten an Dritte ist unzulässig..
Nach Zweckerreichung sind erlangte Schuldnerdaten zu löschen.
Mit freundlichen Grüßen
(Frank Schäfer)
Obergerichtsvollzieher
beim Amtsgericht Darmstadt
Zwangsvollstreckungsdaten werden in meiner
EDV gespeichert! Löschung 1 Jahr n.d. Erledi-
gungsjahr. Keine Datenweitergabe an Dritte!
(§§ 7;11;18II HDG)
Anschrift
Dienstkonto
Sprechzeiten: (tel. nur mobil erreichbar)
c/o AG Darmstadt
IBAN:DE27660908000004728599
Di. 12-13 Uhr, AG Darmstadt, RaumB019
Mathildenplatz 12
BIC:GENODE61BBB
Fr.10:30-11:30, AG Darmstadt, RaumB013
64283 Darmstadt
BBBank Karlsruhe
<page_3>
Anlage zu GZ: St II 4 S 0229a KEVIZZ 2921832/25 (Bitte stets angeben)
Ergebnisse
zu der Anfrage von dem/der:
Obergerichtsvollzieher
Frank Schäfer
vom:
15.12.2025
Ihr AZ:
DR II 1870/25
mit folgenden Anhaltsdaten:
Name:
Nachname:
Ahmad
Vorname:
Labid
Geburtsdatum:
25.05.2001
Kontonummer:
N26 Bank SE
BAK-Nr.: 145827
Voltairestraße 8, 10179 Berlin
Trefferanzahl: 3
Kontonummer: DE41100110012624919180
Errichtungsdatum: 11.09.2019
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
LABID AHMAD
25.05.2001
22.12.2019
FALKENWEG 7 64331 WEITERSTADT DEU
Kontonummer: DE91100110012811132575
Errichtungsdatum: 26.11.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
LABID AHMAD
25.05.2001
26.11.2023
FALKENWEG 7 64331 WEITERSTADT DEU
Kontonummer: DE91100110012811132575
Errichtungsdatum: 26.11.2023
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
LABID AHMAD
25.05.2001
26.11.2023
FALKENWEG 7 64331 WEITERSTADT DEU
Anfrage von Obergerichtsvollzieher
Seite
1 von
2
Frank Schäfer (G06074) zu AZ DR II 1870/25
<page_4>
Anlage zu GZ: St II 4 S 0229a KEVIZZ 2921832/25 (Bitte stets angeben)
Trade Republic Bank GmbH
BAK-Nr.: 150368
Brunnenstraße 19 21, 10119 Berlin
Trefferanzahl:
2
Kontonummer: 0829461801
Errichtungsdatum: 05.03.2021
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Labid Ahmad
25.05.2001
05.03.2021
Falkenweg 7, 64331 Weiterstadt DE
Kontonummer: DE30100123450829461801
Errichtungsdatum: 29.07.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Labid Ahmad
25.05.2001
29.07.2024
Falkenweg 7, 64331 Weiterstadt DE
Klarna Bank AB, German Branch
BAK-Nr.: 157210
Chausseestr. 117, 10115 Berlin
Trefferanzahl: 1
Kontonummer: DE53100103004125963420
Errichtungsdatum: 23.04.2024
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
Labid Ahmad
25.05.2001
23.04.2024
29.07.2024
Falkenweg 7 64331 Weiterstadt
Labid Ahmad
25.05.2001
29.07.2024
Falkenweg 7 64331 Weiterstadt
Revolut Bank UAB, Zweigniederlassung Deutschland
BAK-Nr.:
161008
c/o FORA Linden Palais / Unter den Linden 40, 10117 Berlin
Trefferanzahl:
1
Kontonummer: DE16100101786625757646
Errichtungsdatum:
27.01.2025
Kontoinfo:
Auflösungsdatum:
Kontoinhaber
Geburtsdatum Seit
Bis
LABID AHMAD
25.05.2001
27.01.2025
DE Weiterstadt 64331 Franz-Seliger-Str. 10
Anfrage von Obergerichtsvollzieher
Seite
2 von
2
Frank Schäfer (G06074) zu AZ DR II 1870/25

# add new data to final_raw_dataset.csv

In [13]:
raw_data = pd.read_csv('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv')
raw_data.columns

Index(['ticket_uuid', 'attachment_id', 'text', 'object_key', 'document_type',
       'cleaned_text', 'data', 'is_pfub', 'is_ladung', 's3_link',
       'textract_job_id', 'textract_s3_link', 'is_ve_with_invoice'],
      dtype='object')

In [21]:
raw_data['is_ladung'].dtype

dtype('bool')

In [22]:
raw_data['is_pfub'].dtype

dtype('bool')

alter df (new data) to match the fields.

In [ ]:
import re
df.rename(columns={"s3_key": "object_key"}, inplace=True)
df.rename(columns={"text": "text_w_pages"}, inplace=True)
# remove page markers
page_marker_pattern = r"<page_\d+>\n"
df['text'] = df['text_w_pages'].apply(lambda x: re.sub(page_marker_pattern, " ", x))

In [16]:
df.rename(columns={"label": "is_da_with_invoice"}, inplace=True)

In [18]:
df['is_da_with_invoice'] = df['is_da_with_invoice'].apply(lambda x: True if x == "with_invoice" else False)

In [19]:
df

,object_key,text_w_pages,is_da_with_invoice,text
0,data/aftercourt/drittauskunf_with_invoice/0_sa...,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,Obergerichtsvollzieher Frank Schäfer\nbei dem...
1,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nAnlage zu GZ: St II 4 S 0229a KEVIZZ...,True,Anlage zu GZ: St II 4 S 0229a KEVIZZ 2948091/...
2,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nThomas Vetter\nJohann-Ruland-Weg 9\n...,True,Thomas Vetter\nJohann-Ruland-Weg 9\nGerichtsv...
3,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
4,data/aftercourt/drittauskunf_with_invoice/63_d...,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,Christian Linner\nSchragenhofstraße 27\nGeric...
5,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...
6,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...
7,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nDaniel Arlt\nUlrich-Kaegerl-Straße 5...,True,Daniel Arlt\nUlrich-Kaegerl-Straße 5\nOberger...
8,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,True,Obergerichtsvollzieherin\nAmtsgericht Wolfsbu...
9,data/aftercourt/drittauskunf_with_invoice/B_DR...,<page_1>\nObergerichtsvollzieherin Evelyn Häp\...,True,Obergerichtsvollzieherin Evelyn Häp\nbeim Amt...
10,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
11,data/aftercourt/drittauskunf_with_invoice/RB_0...,<page_1>\nKriegsstr. 65\nCLAUDIUS BETZLER\n761...,True,Kriegsstr. 65\nCLAUDIUS BETZLER\n76133 Karlsr...
12,data/aftercourt/drittauskunf_with_invoice/3_dr...,<page_1>\nObergerichtsvollzieher Frank Pergand...,True,Obergerichtsvollzieher Frank Pergande\nBüroan...
13,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nGerichtsvollzieherin beim Amtsgerich...,True,Gerichtsvollzieherin beim Amtsgericht Eisenac...
14,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
15,data/aftercourt/drittauskunf_with_invoice/KL_0...,<page_1>\nGerichtsvollzieherin Antje Netzband\...,True,Gerichtsvollzieherin Antje Netzband\nAmtsgeri...
16,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nObergerichtsvollzieher\n66292 Riegel...,True,Obergerichtsvollzieher\n66292 Riegelsberg\nSt...
17,data/aftercourt/drittauskunf_with_invoice/Dr_1...,<page_1>\nObergerichtsvollzieherin\nAnschrift\...,True,Obergerichtsvollzieherin\nAnschrift\nPäßler R...
18,data/aftercourt/drittauskunf_with_invoice/0_sa...,<page_1>\nObergerichtsvollzieher Frank Schäfer...,True,Obergerichtsvollzieher Frank Schäfer\nbei dem...
19,data/aftercourt/drittauskunf_with_invoice/Doku...,<page_1>\nNicole Sommer\nKönigstr. 11\nGericht...,True,Nicole Sommer\nKönigstr. 11\nGerichtsvollzieh...
20,data/aftercourt/drittauskunf_with_invoice/63_d...,<page_1>\nChristian Linner\nSchragenhofstraße ...,True,Christian Linner\nSchragenhofstraße 27\nGeric...
21,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,True,Anlage zu GZ: St Il 4 - S 0229a KEVIZZ 280992...
22,data/aftercourt/drittauskunf_with_invoice/1_sa...,<page_1>\nGerichtsvollzieherin\nMozartstraße 5...,True,Gerichtsvollzieherin\nMozartstraße 57\nV. Rup...
23,data/aftercourt/drittauskunf_with_invoice/1_dr...,<page_1>\nGerichtsvollzieherin\nWaldhofer Stra...,True,Gerichtsvollzieherin\nWaldhofer Straße 17\nKa...
24,data/aftercourt/drittauskunf_with_invoice/comb...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,True,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
25,data/aftercourt/drittauskunf_with_invoice/Dr_i...,<page_1>\nObergerichtsvollzieherin\nEuropaplat...,True,Obergerichtsvollzieherin\nEuropaplatz 11\nBea...
26,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nAmtsgericht: B...,False,Gerichtsvollzieherin\nAmtsgericht: Besigheim\...
27,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nPostfach 60 02...,False,Gerichtsvollzieherin\nPostfach 60 02 11\nS. C...
28,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nNeue Büroanschrift ab 01.12.2024\nDo...,False,Neue Büroanschrift ab 01.12.2024\nDortmunder ...
29,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieher\nHellersdorfe...,False,Obergerichtsvollzieher\nHellersdorfer Weg 35\...
30,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nSylvia Niemeyer\nSchloßstraße 4\nObe...,False,Sylvia Niemeyer\nSchloßstraße 4\nObergerichts...
31,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nHauptgerichtsvollzieherin\nBüroansch...,False,Hauptgerichtsvollzieherin\nBüroanschrift\nFis...
32,data/aftercourt/drittauskunft_without_invoice/...,"<page_1>\nJ. RIEGER\n89522 Heidenheim, Helmut-...",False,"J. RIEGER\n89522 Heidenheim, Helmut-Bornef.-S..."
33,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nN. Stenzel\nBlücherstraße 4\nGericht...,False,N. Stenzel\nBlücherstraße 4\nGerichtsvollzieh...
34,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
35,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nMarion Kruska\nLilly-Reich-Str. 5\nO...,False,Marion Kruska\nLilly-Reich-Str. 5\nObergerich...
36,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAmtsgericht Mülheim-Ruhr\nObergerich...,False,Amtsgericht Mülheim-Ruhr\nObergerichtsvollzie...
37,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nSandra Zander\nObergerichtsvollziehe...,False,Sandra Zander\nObergerichtsvollzieherin beim ...
38,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nF. Häußler\nMarktplatz 6\nGerichtsvo...,False,F. Häußler\nMarktplatz 6\nGerichtsvollzieheri...
39,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherbüro Duhnke\nAmtsg...,False,Gerichtsvollzieherbüro Duhnke\nAmtsgericht Lö...
40,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nOLIVER LIEB\nStethaimerstraße 32-34\...,False,OLIVER LIEB\nStethaimerstraße 32-34\n84034 La...
41,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nJanina Dahlhaus\nAdolf-Grimme-Straße...,False,Janina Dahlhaus\nAdolf-Grimme-Straße 3\nOberg...
42,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieher\n66953 Pirmas...,False,Obergerichtsvollzieher\n66953 Pirmasens\nStep...
43,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nTheo Schmitz\nKölner Strasse 73\nObe...,False,Theo Schmitz\nKölner Strasse 73\nObergerichts...
44,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nNina Glöckler\nMarktplatz 3\nGericht...,False,Nina Glöckler\nMarktplatz 3\nGerichtsvollzieh...
45,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAmtsgericht\nKontakt und Information...,False,Amtsgericht\nKontakt und Information\nBürospr...
46,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nVINCENZ SCHIMA\nKnöterichpfad 13\nOb...,False,VINCENZ SCHIMA\nKnöterichpfad 13\nObergericht...
47,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nHelga Gerstl\nHauptgerichtsvollziehe...,False,Helga Gerstl\nHauptgerichtsvollzieherin\nAmse...
48,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nR. Müller\nObergerichtsvollzieher\nL...,False,R. Müller\nObergerichtsvollzieher\nLerchenweg...
49,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...
50,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nAnne-Katrin Götz\nAmtsgericht Dortmu...,False,Anne-Katrin Götz\nAmtsgericht Dortmund\nOberg...
51,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nObergerichtsvollzieherin G. Samuels\...,False,Obergerichtsvollzieherin G. Samuels\nHESSEN\n...
52,data/aftercourt/drittauskunft_without_invoice/...,<page_1>\nGerichtsvollzieherin\nKreuzgasse 17\...,False,Gerichtsvollzieherin\nKreuzgasse 17\nL. Lutz\...

In [23]:
df['document_type'] = 'drittauskunft'
df['is_ladung'] = False
df['is_pfub'] = False

save the data

In [27]:
df.to_csv(os.path.join(output_dir, "add_data_drittauskunft.csv"), index=False)

add new data using update raw data script

In [28]:
from src.data_handling.update_raw_data import update_raw_data

updated_raw_data = update_raw_data(raw_data, df)
print(updated_raw_data.shape)
updated_raw_data.tail()

Starting raw data update. Raw data: 5532 rows, New data: 53 rows.
Validating required columns: ['text', 'document_type', 'is_pfub', 'is_ladung']
All required columns validated successfully.
Filling generated columns for 53 rows.
Validating dtypes between raw data and new data.
No duplicates found.
Raw data update complete. Total rows: 5585 (added 53).
(5585, 15)

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice,text_w_pages,is_da_with_invoice
5580,4f6c9081-0928-527c-9356-943ba2237293,e3a0150a-cdb8-5a9c-be4a-0f5603361356,R. Müller\nObergerichtsvollzieher\nLerchenweg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,NaN,NaN,False,False,NaN,fe02c9970e549b20806d238d71c0adfe8a6f3dccdf820a...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nR. Müller\nObergerichtsvollzieher\nL...,False
5581,50143302-3ac3-587b-ae25-047d34d94750,99d61bd2-665c-59b1-a24d-264f41c2f474,Bundeszentralamt\nfür Steuern\nPOSTANSCHRIFT\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,NaN,NaN,False,False,NaN,93e56ec1cfb7719bf463bf44585e833cdd56fb9689d4f3...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,False
5582,de97e37c-ebf7-5c0e-92be-209db058d9ae,60913326-3481-573b-a96e-72bb2ca9a9ef,Anne-Katrin Götz\nAmtsgericht Dortmund\nOberg...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,NaN,NaN,False,False,NaN,870b8fd6e0da13bafd14ed6e5cec7e79af8c7ae43cae66...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nAnne-Katrin Götz\nAmtsgericht Dortmu...,False
5583,c72625b3-d66a-5df5-a933-11f57215838a,2a6e990a-3458-5efe-a8d9-f8b988af1740,Obergerichtsvollzieherin G. Samuels\nHESSEN\n...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,NaN,NaN,False,False,NaN,6eb9335329883f671aa167608aa4108d45a5e0fcbbbb86...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nObergerichtsvollzieherin G. Samuels\...,False
5584,9d233a96-2fd2-5f56-ab60-58043398223d,f8f00142-5ef8-5940-8ec0-f211617274d8,Gerichtsvollzieherin\nKreuzgasse 17\nL. Lutz\...,data/aftercourt/drittauskunft_without_invoice/...,drittauskunft,NaN,NaN,False,False,NaN,0d1359e435b18356222e26c4fc1eeb79c53373771c782b...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN,<page_1>\nGerichtsvollzieherin\nKreuzgasse 17\...,False

In [26]:
updated_raw_data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           523
court_inbox                                346
fp_protocol                                220
fp_invoice                                 128
vermögensverzeichnis                        89
approved_attachment_and_transfer_order      64
drittauskunft                               53
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
contradiction                                3
Name: count, dtype: int64