In [4]:
import pandas as pd
from matplotlib import pyplot as plt

In [124]:
data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [125]:
data.head()

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [126]:
data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           406
court_inbox                                346
fp_protocol                                220
fp_invoice                                 128
approved_attachment_and_transfer_order      64
vermögensverzeichnis                        57
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
contradiction                                3
Name: count, dtype: int64

In [127]:
ve = data[data["document_type"] == "vermögensverzeichnis"] 
ve

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
664,60de1344-2ab7-5703-80b5-ce60fe1d791f,fe53b918-271e-5590-9702-4c8dea2aef33,Obergerichtsvollzieherin\nBüroanschriften:\nN....,06.06.2024/ocr-v2_DR_II_284_24_An_Gl_VAK_berei...,vermögensverzeichnis,obergerichtsvollzieherin\nbüroanschriften:\nn....,NaN,False,False,NaN,3c011cb7bb7b7803bf9d098c792a7dbc29a50deb38e3e6...,s3://pair-data-engineering-new/ocr_prepared_ou...
1068,b6dfe9e7-c811-5146-9bdd-5f34add6cceb,c3037a60-2f18-51c7-9552-8122deddd77f,Max Wolczik\nMetzstraße 6\nGerichtsvollzieher\...,09.10.2023/ocr-v2_AK_001_09102023_130049.pdf,vermögensverzeichnis,max wolczik\nmetzstraße 6\ngerichtsvollzieher\...,NaN,False,False,NaN,bd95aa14c53d24df9dd048bb3920eab2dbb11639846169...,s3://pair-data-engineering-new/ocr_prepared_ou...
1069,917ec4ea-8779-5626-a6af-5805ee49796f,73147286-f2bf-523c-b23b-f7499d2c2d33,Peter Lüdtke\nBrahmsstr. 42\nObergerichtsvollz...,09.10.2023/ocr-v2_AK_001_09102023_141459.pdf,vermögensverzeichnis,peter lüdtke\nbrahmsstr. 42\nobergerichtsvollz...,NaN,False,False,NaN,294908dca154dd1d8297307eb8fa002503b64c34deb011...,s3://pair-data-engineering-new/ocr_prepared_ou...
1070,212e106a-0d0f-5c62-af27-1f80bc22acfb,e6506c98-b9b1-5579-a6c1-5c0441e28964,Obergerichtsvollzieherin\n45333 Essen-Borbeck\...,09.10.2023/ocr-v2_AK_001_09102023_141500.pdf,vermögensverzeichnis,obergerichtsvollzieherin\n45333 essen-borbeck\...,NaN,False,False,NaN,318001e94d910a6b99fe0523807cf0e900c3d12f0fd777...,s3://pair-data-engineering-new/ocr_prepared_ou...
1071,525016e1-1a64-5363-b8d1-b0c8d30ba0a5,8a64d0a4-3ecf-58e6-9586-9f42dc465812,Holger Schnebel\nFriedrichstrasse 17 Postfach ...,09.10.2023/ocr-v2_AK_002_09102023_130049.pdf,vermögensverzeichnis,holger schnebel\nfriedrichstrasse 17 postfach ...,NaN,False,False,NaN,7446d2ea3ea84ec065fcc31f1b1ee0a81ea8b21cf49e9f...,s3://pair-data-engineering-new/ocr_prepared_ou...
1199,bce6743c-75c0-57f7-bb43-03a207750040,fb7b3445-8c94-56e4-baec-a35ff274b73e,Günter Rode\nLichtenhaidestraße 15\nHauptgeric...,10.12.2024/ocr-v2_Dokumente_148524_10122024_08...,vermögensverzeichnis,günter rode\nlichtenhaidestraße 15\nhauptgeric...,NaN,False,False,NaN,fdcf963c5c7fba3246b72999375b536b669ff8556598c8...,s3://pair-data-engineering-new/ocr_prepared_ou...
1317,8ea6a69f-f892-5643-bc19-92e6428b7679,b5c79083-9070-5a29-bdc5-4acb09c15ff1,Hauptgerichtsvollzieher\n80992 München\nPeer\n...,11.12.2024/ocr-v2_80_dr_792_24_05a_an_gl_vv_se...,vermögensverzeichnis,hauptgerichtsvollzieher\n80992 münchen\npeer\n...,NaN,False,False,NaN,f8b1d73712d98a9befaa03aacd118f52a3df6b6ec0fdfe...,s3://pair-data-engineering-new/ocr_prepared_ou...
1319,9f5ce57e-195d-5520-95e0-30231a0292c1,6e37447b-e882-5abd-89ec-25934abed270,Wormser Landstr. 6\nGUNTER SCHULZ\n67551 Worms...,11.12.2024/ocr-v2_DR-II_100224_Nachr_Mitlg_an_...,vermögensverzeichnis,wormser landstr. 6\ngunter schulz\n67551 worms...,NaN,False,False,NaN,489fd7adf728e86457ea80799564b0087a759bcf9bf925...,s3://pair-data-engineering-new/ocr_prepared_ou...
1321,83abddf7-5631-5273-99e7-9c32056e5a9e,118d436d-4de5-53a5-88c7-ab60cf55581d,Postanschrift:\nBianka Zinn\nJustus-Perthes-St...,11.12.2024/ocr-v2_DR-II_130824_Nachr_GKB-ERVQ_...,vermögensverzeichnis,postanschrift:\nbianka zinn\njustus-perthes-st...,NaN,False,False,NaN,c3fd789f7ee5356ef4034cc5fc70061b5267cb1a1b9eaa...,s3://pair-data-engineering-new/ocr_prepared_ou...
1323,cc684f5a-c916-533b-81ea-61147911c79d,6a19ff8c-13d0-59f4-a9fe-592685866e28,"Simone Ederer\nBahnhofstr. 1 a, Nebeneingang\n...",11.12.2024/ocr-v2_DR-II_174124_Nachr_4_15_Erte...,vermögensverzeichnis,"simone ederer\nbahnhofstr. 1 a, nebeneingang\n...",NaN,False,False,NaN,d85db52acccc94d0a8019195a1625a44fbd06708891a22...,s3://pair-data-engineering-new/ocr_prepared_ou...
1324,d185c368-dfb4-5fe0-84bb-012575644ca1,9e35aca0-d739-5de6-bcca-ab7c6b247c5e,"Simone Ederer\nBahnhofstr. 1 a, Nebeneingang\n...",11.12.2024/ocr-v2_DR-II_175424_Nachr_4_15_Erte...,vermögensverzeichnis,"simone ederer\nbahnhofstr. 1 a, nebeneingang\n...",NaN,False,False,NaN,d85db52acccc94d0a8019195a1625a44fbd06708891a22...,s3://pair-data-engineering-new/ocr_prepared_ou...
1325,f7208154-2836-5f77-9b9b-04e4ff5d30c8,caf0b948-d434-53ed-b298-10a564e12382,"Simone Ederer\nBahnhofstr. 1a, Nebeneingang\n4...",11.12.2024/ocr-v2_DR-II_175424_Nachr_4_15_Erte...,vermögensverzeichnis,"simone ederer\nbahnhofstr. 1a, nebeneingang\n4...",NaN,False,False,NaN,f30810a979b6eca93b6a5057c46b3325fc7ad2f5921490...,s3://pair-data-engineering-new/ocr_prepared_ou...
1327,bccb5424-887c-5a4f-a181-91cb3e8dedae,59446a05-c071-5ac1-b238-8633c806e281,Kleistenberg 18\nRAINER HIERONYMUS\n59757 Arns...,11.12.2024/ocr-v2_DR-II_216124_Nachr_10_12_202...,vermögensverzeichnis,kleistenberg 18\nrainer hieronymus\n59757 arns...,NaN,False,False,NaN,43fbe7fc66a21f0f2f952c1fcfbd06953efec7257bf76e...,s3://pair-data-engineering-new/ocr_prepared_ou...
1330,9a782fba-2f26-5202-a690-a6c9bf2b77e9,0f70a6e3-889f-5e39-9e37-27b2635f9bd1,Katharina Appel\nRomain-Rolland-Straße 137\nGe...,11.12.2024/ocr-v2_Dokument_114824_10122024_135...,vermögensverzeichnis,katharina appel\nromain-rolland-straße 137\nge...,NaN,False,False,NaN,053c85740471ff3b7a0fdee99224138cb2242964f6b0c7...,s3://pair-data-engineering-new/ocr_prepared_ou...
1331,f852b147-4a44-5ae3-974e-f4bb4a07c392,e5ae80b1-f270-51cb-bd1b-345ce6879a05,Dirk Dannenberg\nLeinstraße 34a\nObergerichtsv...,11.12.2024/ocr-v2_Dokument_119824_10122024_125...,vermögensverzeichnis,dirk dannenberg\nleinstraße 34a\nobergerichtsv...,NaN,False,False,NaN,ed15d904e16c00722b0d5bfbef355c1d0f356f1220f10e...,s3://pair-data-engineering-new/ocr_prepared_ou...
1336,49c932f7-280d-5382-8dcd-d7748decc7c5,3ea62d15-9db2-5d33-b090-bfb6ad70ab23,D. Lindner\nRomain-Rolland-Str. 137\nObergeric...,11.12.2024/ocr-v2_Dokumente_122624_10122024_12...,vermögensverzeichnis,d. lindner\nromain-rolland-str. 137\nobergeric...,NaN,False,False,NaN,27f5360763bf7a043bcac1b4be406b9b6f79911b605cd0...,s3://pair-data-engineering-new/ocr_prepared_ou...
1337,6f39144d-e154-59df-b211-b832fe6e7725,29c564aa-d8a3-5b26-8e20-03024909279d,M. Jödicke\nHellersdorfer Weg 35\nObergerichts...,11.12.2024/ocr-v2_Dokumente_129024_10122024_16...,vermögensverzeichnis,m. jödicke\nhellersdorfer weg 35\nobergerichts...,NaN,False,False,NaN,25eadd5bbbd843d50c10eba267f061a774aabfd9d15cf9...,s3://pair-data-engineering-new/ocr_prepared_ou...
1338,48b23150-0195-5fe4-b7cb-caa28797bd4d,050182de-0baa-5b0b-ae87-9e7042f74f0d,Kevin Göttel\nHalberstädter Str. 189\nGerichts...,11.12.2024/ocr-v2_Dokumente_143524_10122024_14...,vermögensverzeichnis,kevin göttel\nhalberstädter str. 189\ngerichts...,NaN,False,False,NaN,f57e740a4736bf28b8ea2c532088e027ad56a46f1897a9...,s3://pair-data-engineering-new/ocr_prepared_ou...
1339,ea00cb87-f273-58af-ac68-8747c94f8bb7,416b491f-f0ff-515e-8c38-08e899fe1260,Robert Loy\nNimrodstr. 9\nGerichtsvollzieher\n...,11.12.2024/ocr-v2_Dokumente_162024_11122024_08...,vermögensverzeichnis,robert loy\nnimrodstr. 9\ngerichtsvollzieher\n...,NaN,False,False,NaN,4f1646691b003c5cbe4c09119f7033bc0cd29182b452f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
1340,a55b5e66-0f42-5de4-92d2-d397481e8ffa,d976c5f6-e8ca-53a3-92f7-30e3a7fbad38,Daniel Kieren\nAuf der Reihe 39\nGerichtsvollz...,11.12.2024/ocr-v2_Dokumente_175724_10122024_09...,vermögensverzeichnis,daniel kieren\nauf der reihe 39\ngerichtsvollz...,NaN,False,False,NaN,98c06708426e89292429b4cea3fa6dd683e8451a98fcce...,s3://pair-data-engineering-new/ocr_prepared_ou...
1341,4b649055-0c26-51e1-bad0-0bb85e985180,cb70343f-09f3-5927-9c0e-483283721511,Simone Anger\nHauffstr. 2\nGerichtsvollzieheri...,11.12.2024/ocr-v2_Dokumente_209324_10122024_21...,vermögensverzeichnis,simone anger\nhauffstr. 2\ngerichtsvollzieheri...,NaN,False,False,NaN,94bf2ebe0e296013408f24804a48df654c0b941c9e55b7...,s3://pair-data-engineering-new/ocr_prepared_ou...
1342,412b0126-279c-561b-a9e7-aecee863d8c5,d5fa31bc-61e0-56f4-8988-8aa11828ba9b,Nadine Berkemeier\nRumbecker Straße 8\nGericht...,11.12.2024/ocr-v2_Dokumente_211724_10122024_14...,vermögensverzeichnis,nadine berkemeier\nrumbecker straße 8\ngericht...,NaN,False,False,NaN,1c6cf8e5d6b4d7f546650780fc66288e729a1dddf961ce...,s3://pair-data-engineering-new/ocr_prepared_ou...
1343,a4e91bfe-d95b-55b0-bee0-664c7559525a,02b8a0d3-c562-5fd7-b7b8-514f2e9aba6a,Rebecca Bürger\nDukatenweg 6\nGerichtsvollzieh...,11.12.2024/ocr-v2_Dokumente_224424_11122024_08...,vermögensverzeichnis,rebecca bürger\ndukatenweg 6\ngerichtsvollzieh...,NaN,False,False,NaN,ed54129ee5c93c4f450c455cd74891050035a105311c32...,s3://pair-data-engineering-new/ocr_prepared_ou...
1348,ac4086a8-7b09-5632-ac45-2cce377b7dcb,03142bda-c6f0-56fa-8ce1-5c202c47d635,Tobias Becker\nAnschrift\nObergerichtsvollzieh...,11.12.2024/ocr-v2_Dr_ii_1914_24_an_gl_abdruck_...,vermögensverzeichnis,tobias becker\nanschrift\nobergerichtsvollzieh...,NaN,False,False,NaN,d053489065a7d268858dc96ee3ab17a3074864fd29e603...,s3://pair-data-engineering-new/ocr_prepared_ou...
1349,9634d3b4-7a33-5ff0-8a67-511761abe732,fddb5017-9036-5a73-a78d-a2b1bc7a75ce,Gerichtsvollzieher\nHafenstr. 114\nC. Nötza\n4...,11.12.2024/ocr-v2_Dr_ii_2079_24_an_gl_abdruck_...,vermögensverzeichnis,gerichtsvollzieher\nhafenstr. 114\nc. nötza\n4...,NaN,False,False,NaN,8714d1f3c95bf537ce7992a23e199cb0aa4518b5962e47...,s3://pair-data-engineering-new/ocr_prepared_ou...
1351,d458be2f-fd94-5b8c-a56f-8b94f501a1d5,5ecc86a6-46a8-57c6-909e-ecf1763d160d,Obergerichtsvollzieher\n44135 Dortmund\nBremer...,11.12.2024/ocr-v2_Dr_ii_2406_24_an_gl_vak_bere...,vermögensverzeichnis,obergerichtsvollzieher\n44135 dortmund\nbremer...,NaN,False,False,NaN,1732147026e311e518dd7b02420815844acfeb7f2d71b5...,s3://pair-data-engineering-new/ocr_prepared_ou...
1355,94c83f92-b00f-5fe3-a405-a5c3966bb22b,0ae420c0-fabe-51e2-87fc-1b568535cb28,Obergerichtsvollzieher\nKarlstr. 2\nBrehm\n882...,11.12.2024/ocr-v2_Sammeldokument_DRNr_206024_1...,vermögensverzeichnis,obergerichtsvollzieher\nkarlstr. 2\nbrehm\n882...,NaN,False,False,NaN,4a058545360a30375e5b78a371f40fcac7f81f9ed6fdd9...,s3://pair-data-engineering-new/ocr_prepared_ou...
2142,c91a4310-526d-5b86-9c79-c3fd769d61cb,c1659ff8-9341-57bf-b38f-edb81fee3f80,Obergerichtsvollzieherin Pelz\nPostanschrift: ...,16.09.2024/ocr-v2_0_sammel12.pdf,vermögensverzeichnis,obergerichtsvollzieherin pelz\npostanschrift: ...,NaN,False,False,NaN,2670bf5f9d0f3b07201cb82e18ac34369ad7dfc25077ff...,s3://pair-data-engineering-new/ocr_prepared_ou...
2145,ed5df75f-f40e-54ad-bb1e-e5366dd0de91,acd5c68c-94e3-5c8b-8f33-fdd7f495e124,Gerichtsvollzieherin\nPlatenstraße 66 (Geb. 1/...,16.09.2024/ocr-v2_48_dr_591_24_aus_schreibmasc...,vermögensverzeichnis,gerichtsvollzieherin\nplatenstraße 66 (geb. 1/...,NaN,False,False,NaN,8ec58c47a54009980b86521d78ba3b7664b526660236c9...,s3://pair-data-engineering-new/ocr_prepared_ou...
2150,1b88e288-2e69-5304-8bca-0b12dd5167f0,e3d4cd56-5e6a-5bf2-a9f2-3d1b50934da6,Georg Hörner\nAm Hof 7 (Sprechzeiten)\nGericht...,16.09.2024/ocr-v2_Dokumente_120424_13092024_09...,vermögensverzeichnis,georg hörner\nam hof 7 (sprechzeiten)\ngericht...,NaN,False,False,NaN,084f411aaeba1aac4d4d4c9ea9b544efbf20d34375c82a...,s3://pair-data-engineering-new/ocr_prepared_ou...
2151,2bec1525-ceea-501e-b82c-4ce8ba6d883e,e622c431-cbe1-5916-a10b-4c26b8eea012,A. Weiß\nMariendorfer Weg 40 a\nObergerichtsvo...,16.09.2024/ocr-v2_Dokumente_22624_14092024_130...,vermögensverzeichnis,a. weiß\nmariendorfer weg 40 a\nobergerichtsvo...,NaN,False,False,NaN,67e7c3d32be2b2988c9abd362e56259877032fda189cb6...,s3://pair-data-engineering-new/ocr_prepared_ou...
2152,77917bc7-a090-5050-b3c6-e2cad29877cf,d360abbe-dff1-53aa-96e4-b9cf73ec9026,LOTHAR HENKEL\nTel. 0661/9429805\nObergerichts...,16.09.2024/ocr-v2_Sammelmappe2.pdf,vermögensverzeichnis,lothar henkel\ntel. 0661/9429805\nobergerichts...,NaN,False,False,NaN,13db928afd09385a35973f43b318ae424293a90264cfcb...,s3://pair-data-engineering-new/ocr_prepared_ou...
2153,eaf1bfbc-e481-5387-8e3a-b7c9d66a2f47,d1fcf449-6008-582c-ae09-fc1fa537d08b,Christian Meier\nPostanschrift: Enzer Straße 1...,16.09.2024/ocr-v2_Sammelmappe4.pdf,vermögensverzeichnis,christian meier\npostanschrift: enzer straße 1...,NaN,False,False,NaN,c1a4e4f4ecf95ab12b739594629ab6c46b323ebeababe9...,s3://pair-data-engineering-new/ocr_prepared_ou...
2476,427b4b0d-c24d-5194-84f4-1a63e81ec324,ae4ee64a-0684-5a89-b829-9c00e8db9ded,Obergerichtsvollzieher\nHöhenstr. 74\n( GV-Bür...,19.02.2025/ocr-v2_2ddb73d0-2aa9-4c3f-9faa-3dd0...,vermögensverzeichnis,obergerichtsvollzieher\nhöhenstr. 74\n( gv-bür...,NaN,False,False,NaN,4d15dac3be5a1ec0082cbc8de40f20ef55dbf2a27ce965...,s3://pair-data-engineering-new/ocr_prepared_ou...
2610,081e14d1-3dbf-527e-8f26-dd98e6f9d2c9,263280e5-bad5-5474-a39e-3afa60767916,THOMAS METHNER\nBremer Str. 40\n27749 Delmenho...,20.03.2024/ocr-v2_AK_001_20032024_090051.pdf,vermögensverzeichnis,thomas methner\nbremer str. 40\n27749 delmenho...,NaN,False,False,NaN,71e884414934c4a7cf86b3150c4b6bc8f4bc1884cd33df...,s3://pair-data-engineering-new/ocr_prepared_ou...
2634,9a68e6b5-8426-5a7d-9133-49f09c250ef8,03c4d3ec-d2a7-54d0-a416-d32434fafce5,M. Schumacher\nFuhlsbüttler Straße 118\nGerich...,20.06.2024/ocr-v2_Sammeldokument_DRNr_68624_20...,vermögensverzeichnis,m. schumacher\nfuhlsbüttler straße 118\ngerich...,NaN,False,False,NaN,9a7d9dd77b9e65f85ade49082cc42136f5cce2e6e61087...,s3://pair-data-engineering-new/ocr_prepared_ou...
2814,aeaf02c1-dac1-508d-8a53-97abccde553f,2f78d079-6d06-5f4d-8a74-1da8bbe82977,Volker Reichl\nBamberger Str. 43\nObergerichts...,22.01.2025/ocr-v2_007c9083-d3e6-46c5-9c76-3dcb...,vermögensverzeichnis,volker reichl\nbamberger str. 43\nobergerichts...,NaN,False,False,NaN,ca3a0c7c9af3a2fcdd9f3c9538e33f16230664c56c298a...,s3://pair-data-engineering-new/ocr_prepared_ou...
3133,9c711f69-4117-5905-96f2-15060f74a58c,08b99412-8ec4-5d2e-a4d2-9cdba232f019,Obergerichtsvollzieherin Christiane Klos\nBüro...,24.09.2024/ocr-v2_GVZ_0_sammel1_(2).pdf,vermögensverzeichnis,obergerichtsvollzieherin christiane klos\nbüro...,NaN,False,False,NaN,198f3981a1e1229dcc818d71e2c8717b7c81b545503ea5...,s3://pair-data-engineering-new/ocr_prepared_ou...
3135,6f50792f-c6aa-5958-a660-c3a7a415481b,bc0d88ab-52cd-5f3a-99fc-c4eb1fe5e467,Daniel Rüdiger\nHerner Straße 24\nGerichtsvoll...,24.09.2024/ocr-v2_GVZ_Dokumente_113824_1709202...,vermögensverzeichnis,daniel rüdiger\nherner straße 24\ngerichtsvoll...,NaN,False,False,NaN,74642166a4001df1fe6c119728928553999a81baa4bcd0...,s3://pair-data-engineering-new/ocr_prepared_ou...
3136,70405571-c93a-5784-82a9-38d0eed1a3ee,09b0f6ba-f027-5ff8-b759-38082dc58afb,Obergerichtsvollzieher\nAmtsgericht Wismar\nTh...,24.09.2024/ocr-v2_GVZ_Dr_ii_680_24_313_eao_vv_...,vermögensverzeichnis,obergerichtsvollzieher\namtsgericht wismar\nth...,NaN,False,False,NaN,fc578c22302e83410b645591d23d53ed2246cb49542ffb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3137,7e7f4149-dc21-5598-bfbb-47a948563b4c,d894d93b-e6a6-54f7-8c45-842c4b3491ca,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,24.09.2024/ocr-v2_GVZ_Sammelmappe10.pdf,vermögensverzeichnis,sonnenscheinpfad 28\n44879 bochum\ntel. 0234/4...,NaN,False,False,NaN,2bae7b1b27449c7242f76783d7491c500164c82b86ef7b...,s3://pair-data-engineering-new/ocr_prepared_ou...
3138,1bb466b4-6c93-50c8-bb92-66655dbc00c4,0418abf0-aee6-504c-b062-183475b5809d,Gerichtsstraße 2 -Amtsgericht-\n15907 Lübben\n...,24.09.2024/ocr-v2_GVZ_Sammelmappe11.pdf,vermögensverzeichnis,gerichtsstraße 2 -amtsgericht-\n15907 lübben\n...,NaN,False,False,NaN,6c715f4ba0ea2a00f3c2cd0eddf963881e6ae9a8eb96b2...,s3://pair-data-engineering-new/ocr_prepared_ou...
3139,58a133d3-4085-5e9b-9618-b26cf2adf9cb,bb182f24-e497-5382-9a8c-324419ab784d,Volmerswerther Str. 80 86\nFrank Ezell\n40221 ...,24.09.2024/ocr-v2_GVZ_Sammelmappe12.pdf,vermögensverzeichnis,volmerswerther str. 80 86\nfrank ezell\n40221 ...,NaN,False,False,NaN,26765b5a229e6b912668e1f9840ee3941d2762cbfdee40...,s3://pair-data-engineering-new/ocr_prepared_ou...
3140,1075e054-2517-53c3-be1c-d2a87c4a3aad,542972ee-feb8-5466-a7d3-11c4320e204b,Volmerswerther Str. 80 86\nFrank Ezell\n40221 ...,24.09.2024/ocr-v2_GVZ_Sammelmappe15.pdf,vermögensverzeichnis,volmerswerther str. 80 86\nfrank ezell\n40221 ...,NaN,False,False,NaN,26765b5a229e6b912668e1f9840ee3941d2762cbfdee40...,s3://pair-data-engineering-new/ocr_prepared_ou...
3751,0cf7b4a3-9112-5b90-b6be-481f4f846992,139dfe4e-9ee4-5561-9e26-ce256bf482fa,Anlage zur Niederschrift d.:\nGV Dominik Schna...,29.07.2024/ocr-v2_VV_46224_140674123116.pdf,vermögensverzeichnis,anlage zur niederschrift d.:\ngv dominik schna...,NaN,False,False,NaN,4696d06f240759c015063ccf50b858d6556aa52bba3773...,s3://pair-data-engineering-new/ocr_prepared_ou...
5287,73f21aef-cb62-5165-8384-b2859a5beb5b,51428247,Anlage zur Niederschrift d.:\nGV J. Korn\nvom:...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,7d526c456e0e6f7ba25db0a35ec7e496d78289d92a6071...,s3://pair-data-engineering-new/ocr_prepared_ou...
5293,249d8989-7afe-5f15-b020-57838e595fe3,51774647,Anlage zur Niederschrift d.:\nOGV Theo Schmitz...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,c8d0c898eda460364a345c4ee654ea53104924be414ada...,s3://pair-data-engineering-new/ocr_prepared_ou...
5300,3f306157-6c99-57c5-bcb3-9df4b58ae2d6,50219916,Anlage zur Niederschrift d.:\nGV Nico Stolzen\...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,c3a5f5b3c3333f6c09cfb385cc0b39d7e0aef33147ebf8...,s3://pair-data-engineering-new/ocr_prepared_ou...
5306,d0f0e78b-5994-5c26-b912-cbf628e92b12,51771792,Anlage zur Niederschrift d.:\nOGV Doreen Trieb...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,0a5f2fde998db2656f636931dd937eec56045a1524f364...,s3://pair-data-engineering-new/ocr_prepared_ou...
5323,3bc46a02-531e-5ff6-8ff7-960179af5c95,50450147,Anlage zur Niederschrift d.:\nOGV Torsten Olbr...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,6e629d0ec3f95a571c49193e693ba531ba7952eedfdc86...,s3://pair-data-engineering-new/ocr_prepared_ou...
5329,2f575e42-e662-53f4-a558-cfb690008ee0,51174964,Anlage zur Niederschrift d.:\nOGV Sascha Deter...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,6192616c01dd892e865fb330d3ea25dce67ee4004f7e24...,s3://pair-data-engineering-new/ocr_prepared_ou...
5339,b44a9bcb-2ab0-5162-af29-dbfae93edfa9,50396500,Anlage zur Niederschrift d.:\nOGVin S. Jungman...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,1c3f275fa209ee2345eb781e7084ecbe800f0d8ee18d39...,s3://pair-data-engineering-new/ocr_prepared_ou...
5342,2fadc54c-76cf-5235-8203-d5c73e8e629a,51881467,Anlage zur Niederschrift d.:\nGVin Nicole Schr...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,091294a91559890d71bbb7cc745a92bc9f95437aa0fe9d...,s3://pair-data-engineering-new/ocr_prepared_ou...
5343,3e5e56bd-9384-57c0-a364-d9feef5ac9b0,50910730,Anlage zur Niederschrift d.:\nOGV Otto Fuß\nvo...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,a62fa83b350ba5f0d56d1cae7f7f580d2a0aaff5e77dcc...,s3://pair-data-engineering-new/ocr_prepared_ou...
5344,13dd852c-767a-5a97-beb8-0905d45b64d4,51078673,Anlage zur Niederschrift d.:\nGV Günther Kaise...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,6a82a79cafa85bba483a5eace4879ed7d6811b3c1efa59...,s3://pair-data-engineering-new/ocr_prepared_ou...
5354,25fa7e82-c191-582f-bd17-1c83e68c2766,51811596,Anlage zur Niederschrift d.:\nOGV Ramona Puska...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,3488c1a90bd3140854dc917d6893ea817ed152eae65057...,s3://pair-data-engineering-new/ocr_prepared_ou...
5373,5fe55d66-37ad-5c36-afe2-96214fa48534,50427615,Anlage zur Niederschrift d.:\nGVin Sina Dötter...,NaN,vermögensverzeichnis,NaN,NaN,False,False,NaN,a1642373561e3d09da95fbd66cb5dfdf71430c6d1720d4...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [5]:
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "../../../")))

In [6]:
# lets see thed documents
from utils.prod_utils import get_data_by_attachment_id
from python_utilities.db_connection import DbConnection
import boto3

analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-04-15 15:48:44] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-04-15 15:48:45] - Found credentials in shared credentials file: ~/.aws/credentials

### Check documents vermögensverzeichnis obtained from egvp

In [130]:
# list assets available = vermögensverzeichnis

for a_id in ve.attachment_id:
    if len(a_id) == len('caf0b948-d434-53ed-b298-10a564e12382'):
        continue
    get_data_by_attachment_id(a_id, analytics_db, s3, pdf_download=True, pdf_download_dir='/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/from_egvp')

====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   51428247
File Name:       51428247_VV_124325_4892.pdf
====================================================================================================

KeyboardInterrupt:

### Check documents coming from ocr

In [ ]:
from_ocr = ve[~ve['object_key'].isna()]
from_ocr

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
664,60de1344-2ab7-5703-80b5-ce60fe1d791f,fe53b918-271e-5590-9702-4c8dea2aef33,Obergerichtsvollzieherin\nBüroanschriften:\nN....,06.06.2024/ocr-v2_DR_II_284_24_An_Gl_VAK_berei...,vermögensverzeichnis,obergerichtsvollzieherin\nbüroanschriften:\nn....,NaN,False,False,NaN,3c011cb7bb7b7803bf9d098c792a7dbc29a50deb38e3e6...,s3://pair-data-engineering-new/ocr_prepared_ou...
1324,d185c368-dfb4-5fe0-84bb-012575644ca1,9e35aca0-d739-5de6-bcca-ab7c6b247c5e,"Simone Ederer\nBahnhofstr. 1 a, Nebeneingang\n...",11.12.2024/ocr-v2_DR-II_175424_Nachr_4_15_Erte...,vermögensverzeichnis,"simone ederer\nbahnhofstr. 1 a, nebeneingang\n...",NaN,False,False,NaN,d85db52acccc94d0a8019195a1625a44fbd06708891a22...,s3://pair-data-engineering-new/ocr_prepared_ou...
1325,f7208154-2836-5f77-9b9b-04e4ff5d30c8,caf0b948-d434-53ed-b298-10a564e12382,"Simone Ederer\nBahnhofstr. 1a, Nebeneingang\n4...",11.12.2024/ocr-v2_DR-II_175424_Nachr_4_15_Erte...,vermögensverzeichnis,"simone ederer\nbahnhofstr. 1a, nebeneingang\n4...",NaN,False,False,NaN,f30810a979b6eca93b6a5057c46b3325fc7ad2f5921490...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [ ]:
from utils.prod_utils import download_pdf_from_s3

for i, row in from_ocr.iterrows():
    bucket_name = "pair-scanner"
    key = row.object_key
    download_pdf_from_s3(s3, bucket_name=bucket_name, object_key=key, download_dir="/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/from_ocr", file_name=None)

✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/from_ocr/ocr-v2_DR_II_284_24_An_Gl_VAK_bereits_geleistet.PDF.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/from_ocr/ocr-v2_DR-II_175424_Nachr_4_15_Erteilung_Vermoegensverzeichnis_an_Folgeglaeubiger_Ansch_10_12.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/from_ocr/ocr-v2_DR-II_175424_Nachr_4_15_Erteilung_Vermoegensverzeichnis_an_Folgeglaeubiger_Ansch_10_12vxv.pdf

### Note: We have 15 data for vermogensverzeichnis, 3 from OCR and 12 from egvp prod data

### Lets add more data for vermogensverzeichnis

- Check ocr dataset tables for document type 'list_of_assets_available'

In [ ]:
psql_db = DbConnection('PROD', f'PROD_DE')
doc_type = 'list_assets_available'

query = """
select *
from ocr_documents od 
where od.document_type = 'list_assets_available'
"""
data_new = psql_db.sql_to_df(query)

INFO [2026-04-15 14:24:28] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file

In [ ]:
data_new

,id,case_file_id,object_key,document_type,status,log,api_page,data,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at,source
0,124008,1315890,None,list_assets_available,processed,None,None,"{'date': '25.01.2023', 'bailiff': 'Peter Lüdtk...",2023-10-09 12:15:25.159031,2023-10-09 12:15:25.880345,10579729,ListAssetsAvailable,None,ocr-v2_AK_001_09102023_141459.pdf,application/pdf,2384369,2023-10-09 12:15:25.104278,None,None
1,124009,2966401,None,list_assets_available,processed,None,None,"{'date': '05.10.2023', 'bailiff': 'Michaela He...",2023-10-09 12:15:25.609185,2023-10-09 12:17:08.801992,10579732,ListAssetsAvailable,None,ocr-v2_AK_001_09102023_141500.pdf,application/pdf,3082012,2023-10-09 12:15:25.549045,None,None
2,178788,648723,None,list_assets_available,processed,None,None,"{'date': '14.08.2024', 'case_slug': '106484547...",2024-07-29 05:49:38.404239,2024-07-31 12:00:25.945123,17483079,ListAssetsAvailable,None,ocr-v2_DR-II_124824_Nachr_8223_26_07_2024.pdf,application/pdf,9239,2024-07-29 05:49:38.367404,None,None
3,156964,857931,None,list_assets_available,processed,None,None,"{'date': '16.11.2022', 'bailiff': 'THOMAS METH...",2024-03-20 08:01:59.247993,2024-03-20 08:02:00.180766,13596430,ListAssetsAvailable,None,ocr-v2_AK_001_20032024_090051.pdf,application/pdf,1904276,2024-03-20 08:01:59.179619,None,None
4,165128,3690247,None,list_assets_available,processed,None,None,"{'date': '17.06.2024', 'case_slug': '136899805...",2024-05-28 12:58:04.202196,2024-05-31 05:16:10.697274,15757300,ListAssetsAvailable,None,ocr-v2_DR-II_070124_Nachr_va08_28.05.2024.pdf,application/pdf,64192,2024-05-28 12:58:04.160704,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,232967,5775338,None,list_assets_available,processed,None,None,"{'date': '04.01.2024', 'case_slug': '157750716...",2025-01-22 07:29:50.286127,2025-01-22 07:29:50.660996,24198237,ListAssetsAvailable,None,ocr-v2_007c9083-d3e6-46c5-9c76-3dcb42851498.pdf,application/pdf,227388,2025-01-22 07:29:50.249199,None,None
109,236101,5387473,None,list_assets_available,processed,None,None,"{'date': '14.04.2025', 'case_slug': '153872067...",2025-01-30 08:44:07.506191,2025-01-30 13:58:36.368298,24500411,ListAssetsAvailable,None,ocr-v2_Anlage200125160132.pdf,application/pdf,308432,2025-01-30 08:44:07.457362,None,None
110,280020,6893213,None,list_assets_available,processed,None,None,"{'date': '15.07.2025', 'case_slug': '168929471...",2025-06-17 07:24:44.807665,2025-06-17 07:28:16.274801,32340785,ListAssetsAvailable,None,ocr-v2_DR-II_024325_Nachr_Mittlg__Glaeubiger_v...,application/pdf,359318,2025-06-17 07:24:44.763894,None,None
111,338300,4426335,None,list_assets_available,processed,None,None,"{'date': '29.01.2026', 'case_slug': '144260680...",2025-11-26 07:18:53.128742,2025-11-26 07:46:09.723319,45042948,ListAssetsAvailable,None,ocr-v2_DR-II_129125_Nachr_Terminsmitteilung_Gl...,application/pdf,27613,2025-11-26 07:18:53.083682,None,None
112,349625,8598852,None,list_assets_available,processed,None,None,"{'date': '20.01.2026', 'case_slug': '185985861...",2025-12-23 08:19:15.037720,2025-12-23 08:21:02.033945,47579407,ListAssetsAvailable,None,ocr-v2_DR-II_061725_Nachr_Mittlg__Glaeubiger_v...,application/pdf,358998,2025-12-23 08:19:14.932056,None,None

In [ ]:
data_new['object_key'].isna().sum()

np.int64(113)

object keys are missing, create object key for them.

In [ ]:
data_new['created_at'].iloc[0]

Timestamp('2023-10-09 12:15:25.159031')

In [ ]:
def create_object_key(row):
    created_at = row.created_at
    year, month, day = created_at.year, created_at.month, created_at.day
    
    if month < 10:
        month = f"0{month}"
    if day < 10:
        day = f"0{day}"
    
    date_folder = f"{day}.{month}.{year}/"
    object_key = date_folder + row.document_file_name
    return object_key

In [ ]:
data_new['object_key'] = data_new.apply(create_object_key, axis=1)

In [ ]:
data_new

,id,case_file_id,object_key,document_type,status,log,api_page,data,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at,source
0,124008,1315890,09.10.2023/ocr-v2_AK_001_09102023_141459.pdf,list_assets_available,processed,None,None,"{'date': '25.01.2023', 'bailiff': 'Peter Lüdtk...",2023-10-09 12:15:25.159031,2023-10-09 12:15:25.880345,10579729,ListAssetsAvailable,None,ocr-v2_AK_001_09102023_141459.pdf,application/pdf,2384369,2023-10-09 12:15:25.104278,None,None
1,124009,2966401,09.10.2023/ocr-v2_AK_001_09102023_141500.pdf,list_assets_available,processed,None,None,"{'date': '05.10.2023', 'bailiff': 'Michaela He...",2023-10-09 12:15:25.609185,2023-10-09 12:17:08.801992,10579732,ListAssetsAvailable,None,ocr-v2_AK_001_09102023_141500.pdf,application/pdf,3082012,2023-10-09 12:15:25.549045,None,None
2,178788,648723,29.07.2024/ocr-v2_DR-II_124824_Nachr_8223_26_0...,list_assets_available,processed,None,None,"{'date': '14.08.2024', 'case_slug': '106484547...",2024-07-29 05:49:38.404239,2024-07-31 12:00:25.945123,17483079,ListAssetsAvailable,None,ocr-v2_DR-II_124824_Nachr_8223_26_07_2024.pdf,application/pdf,9239,2024-07-29 05:49:38.367404,None,None
3,156964,857931,20.03.2024/ocr-v2_AK_001_20032024_090051.pdf,list_assets_available,processed,None,None,"{'date': '16.11.2022', 'bailiff': 'THOMAS METH...",2024-03-20 08:01:59.247993,2024-03-20 08:02:00.180766,13596430,ListAssetsAvailable,None,ocr-v2_AK_001_20032024_090051.pdf,application/pdf,1904276,2024-03-20 08:01:59.179619,None,None
4,165128,3690247,28.05.2024/ocr-v2_DR-II_070124_Nachr_va08_28.0...,list_assets_available,processed,None,None,"{'date': '17.06.2024', 'case_slug': '136899805...",2024-05-28 12:58:04.202196,2024-05-31 05:16:10.697274,15757300,ListAssetsAvailable,None,ocr-v2_DR-II_070124_Nachr_va08_28.05.2024.pdf,application/pdf,64192,2024-05-28 12:58:04.160704,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,232967,5775338,22.01.2025/ocr-v2_007c9083-d3e6-46c5-9c76-3dcb...,list_assets_available,processed,None,None,"{'date': '04.01.2024', 'case_slug': '157750716...",2025-01-22 07:29:50.286127,2025-01-22 07:29:50.660996,24198237,ListAssetsAvailable,None,ocr-v2_007c9083-d3e6-46c5-9c76-3dcb42851498.pdf,application/pdf,227388,2025-01-22 07:29:50.249199,None,None
109,236101,5387473,30.01.2025/ocr-v2_Anlage200125160132.pdf,list_assets_available,processed,None,None,"{'date': '14.04.2025', 'case_slug': '153872067...",2025-01-30 08:44:07.506191,2025-01-30 13:58:36.368298,24500411,ListAssetsAvailable,None,ocr-v2_Anlage200125160132.pdf,application/pdf,308432,2025-01-30 08:44:07.457362,None,None
110,280020,6893213,17.06.2025/ocr-v2_DR-II_024325_Nachr_Mittlg__G...,list_assets_available,processed,None,None,"{'date': '15.07.2025', 'case_slug': '168929471...",2025-06-17 07:24:44.807665,2025-06-17 07:28:16.274801,32340785,ListAssetsAvailable,None,ocr-v2_DR-II_024325_Nachr_Mittlg__Glaeubiger_v...,application/pdf,359318,2025-06-17 07:24:44.763894,None,None
111,338300,4426335,26.11.2025/ocr-v2_DR-II_129125_Nachr_Terminsmi...,list_assets_available,processed,None,None,"{'date': '29.01.2026', 'case_slug': '144260680...",2025-11-26 07:18:53.128742,2025-11-26 07:46:09.723319,45042948,ListAssetsAvailable,None,ocr-v2_DR-II_129125_Nachr_Terminsmitteilung_Gl...,application/pdf,27613,2025-11-26 07:18:53.083682,None,None
112,349625,8598852,23.12.2025/ocr-v2_DR-II_061725_Nachr_Mittlg__G...,list_assets_available,processed,None,None,"{'date': '20.01.2026', 'case_slug': '185985861...",2025-12-23 08:19:15.037720,2025-12-23 08:21:02.033945,47579407,ListAssetsAvailable,None,ocr-v2_DR-II_061725_Nachr_Mittlg__Glaeubiger_v...,application/pdf,358998,2025-12-23 08:19:14.932056,None,None

In [ ]:
# check if we have same data in original final raw data
new_data_key = set(data_new['object_key'])
data_keys = set(data['object_key'])
len(new_data_key.intersection(data_keys))

96

check intersected data - Note: This intersection is handled, new vermogenzeichnis labels are craetead + some corrections in ladung labels

In [ ]:
check = data[data['object_key'].isin(new_data_key.intersection(data_keys))]
check #

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
16,5742d338-74eb-507f-bea8-d57d2dbfe881,eb03d83a-56ce-572b-b87d-1637b1dd5d2a,In der Hagenbeck 50\n45143 Essen\nTel. 0201 87...,01.07.2024/ocr-v2_RB_001_25062024_114948.pdf,ladung_va,in der hagenbeck 50\n45143 essen\ntel. 0201 87...,NaN,False,True,NaN,e08f50c7b7be8d10d9f5ff69a0645f978568c9e9d22672...,s3://pair-data-engineering-new/ocr_prepared_ou...
107,2995ca3d-bdb7-5645-85e3-7fc5ea3fa01d,02854043-3783-526b-b1ad-35a425037840,NORBERT LINHA\nAugsburger Straße 60\n89312 Gün...,02.07.2024/ocr-v2_2024-07-01_DR-II_048524_Nach...,ladung_va,norbert linha\naugsburger straße 60\n89312 gün...,NaN,False,True,NaN,0db00869f528f4fe4394b0df6c12944805284a5a12e424...,s3://pair-data-engineering-new/ocr_prepared_ou...
122,132d8f32-6b01-560f-9788-ebfa878259bc,f36b121c-05f0-5901-a0d4-e75f08cf5f18,NORBERT LINHA\nAugsburger Straße 60\n89312 Gün...,02.07.2025/ocr-v2_2025-07-01_DR_045625_Nachr_T...,ladung_va,norbert linha\naugsburger straße 60\n89312 gün...,NaN,False,True,NaN,0db00869f528f4fe4394b0df6c12944805284a5a12e424...,s3://pair-data-engineering-new/ocr_prepared_ou...
200,cfe56042-ad41-5c48-8d09-ea749a36df5b,caba6650-da36-53ac-a9e1-78a1f35d6fbf,In der Hagenbeck 50\n45143 Essen\nTel. 0201 87...,03.04.2025/ocr-v2_RB_001_03042025_102821.pdf,ladung_va,in der hagenbeck 50\n45143 essen\ntel. 0201 87...,NaN,False,True,NaN,e08f50c7b7be8d10d9f5ff69a0645f978568c9e9d22672...,s3://pair-data-engineering-new/ocr_prepared_ou...
235,59feb726-674e-51b2-ad8e-6c01e86937eb,900e9855-b7be-53fb-a585-077db29f3baf,2. Juli 2024 15:49\nNr. 8325 S. 1\nRoisdorfer ...,03.07.2024/ocr-v2_2024-07-02_18-32-48_02232920...,ladung_va,2. juli 2024 15:49\nnr. 8325 s. 1\nroisdorfer ...,NaN,False,True,NaN,6548f9d8e5b5dfc93135183f4aff1b805014be0f562f04...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
3694,c0d3f18c-14c5-54e7-bc11-e148c614834e,f667dc89-f8b8-57fb-bbb0-78fbbaa00c4a,Melina Wittig\nVolksparkstraße 52\nObergericht...,28.08.2024/ocr-v2_Dokument_205424_22082024_135...,ladung_va,melina wittig\nvolksparkstraße 52\nobergericht...,NaN,False,True,NaN,1c59832cd41cb243d5610e419c6ee7b997a89cba2942b1...,s3://pair-data-engineering-new/ocr_prepared_ou...
3749,bdc061c2-4bb5-5644-b73d-a23df91f4c2f,15f3943f-5b4f-569c-9a9b-199ce77f5dc0,Ulmer Straße 131\n86156 AUGSBURG\nTel. 0821 21...,29.07.2024/ocr-v2_DR-II_124824_Nachr_8223_26_0...,ladung_va,ulmer straße 131\n86156 augsburg\ntel. 0821 21...,NaN,False,True,NaN,6204d0ab0177d6a6df1fec98fb04e9d5e68931ba99a083...,s3://pair-data-engineering-new/ocr_prepared_ou...
3751,0cf7b4a3-9112-5b90-b6be-481f4f846992,139dfe4e-9ee4-5561-9e26-ce256bf482fa,Anlage zur Niederschrift d.:\nGV Dominik Schna...,29.07.2024/ocr-v2_VV_46224_140674123116.pdf,fp_invoice,anlage zur niederschrift d.:\ngv dominik schna...,NaN,False,False,NaN,4696d06f240759c015063ccf50b858d6556aa52bba3773...,s3://pair-data-engineering-new/ocr_prepared_ou...
3854,4764114f-71e3-5d4d-831e-56e35b226693,6e143ef1-36b1-532b-9617-0f8ba62ce248,"Martina Riemer, Obergerichtsvollzieherin\nBüro...",30.01.2025/ocr-v2_Anlage200125160132.pdf,ladung_va,"martina riemer, obergerichtsvollzieherin\nbüro...",NaN,False,True,NaN,8dbfcf188f2d308e383c3de62dd7fd6b1ef376405c92a4...,s3://pair-data-engineering-new/ocr_prepared_ou...
3990,90dab409-4f2b-5cd4-b175-c8bc143ff513,1ba11bf5-bedc-5a5c-90e3-41090449d738,In der Hagenbeck 50\n45143 Essen\nTel. 0201 87...,31.01.2025/ocr-v2_KL_001_31012025_131400.pdf,ladung_va,in der hagenbeck 50\n45143 essen\ntel. 0201 87...,NaN,False,True,NaN,e08f50c7b7be8d10d9f5ff69a0645f978568c9e9d22672...,s3://pair-data-engineering-new/ocr_prepared_ou...

get not intersected data, meaning new data that can be added to the dataset

In [ ]:
not_intersected_keys = new_data_key.difference(data_keys)
len(not_intersected_keys)

17

In [ ]:
check = data_new[data_new['object_key'].isin(not_intersected_keys)]
check

,id,case_file_id,object_key,document_type,status,log,api_page,data,created_at,updated_at,attachment_id,type,textract_job_id,document_file_name,document_content_type,document_file_size,document_updated_at,deleted_at,source
33,331802,6558660,07.11.2025/ocr-v2_FA_004-07112025-074609.pdf,list_assets_available,processed,None,None,"{'date': '15.12.2025', 'case_slug': '165583945...",2025-11-07 06:48:19.346332,2025-11-07 08:07:32.807383,43130090,ListAssetsAvailable,None,ocr-v2_FA_004-07112025-074609.pdf,application/pdf,674494,2025-11-07 06:48:19.296724,None,None
34,351352,6720265,29.12.2025/ocr-v2_7_dr_ii_2289_25_aus_schreibm...,list_assets_available,processed,None,None,"{'date': '18.05.2026', 'case_slug': '167199990...",2025-12-29 09:57:37.154300,2025-12-29 12:13:04.457187,48023455,ListAssetsAvailable,None,ocr-v2_7_dr_ii_2289_25_aus_schreibmaschine.pdf,application/pdf,513820,2025-12-29 09:57:37.102855,None,None
35,351341,7056110,29.12.2025/ocr-v2_7_dr_ii_2235_25_aus_schreibm...,list_assets_available,processed,None,None,"{'date': '27.04.2026', 'case_slug': '170558441...",2025-12-29 09:34:24.679078,2025-12-29 12:14:06.102990,48023459,ListAssetsAvailable,None,ocr-v2_7_dr_ii_2235_25_aus_schreibmaschine.pdf,application/pdf,517164,2025-12-29 09:34:24.628381,None,None
36,351333,7946191,29.12.2025/ocr-v2_7_dr_ii_2211_25_aus_schreibm...,list_assets_available,processed,None,None,"{'date': '27.04.2026', 'case_slug': '179459254...",2025-12-29 09:29:53.577606,2025-12-29 12:14:30.288305,48023461,ListAssetsAvailable,None,ocr-v2_7_dr_ii_2211_25_aus_schreibmaschine.pdf,application/pdf,510556,2025-12-29 09:29:53.467195,None,None
37,351332,7792034,29.12.2025/ocr-v2_7_dr_ii_2203_25_aus_schreibm...,list_assets_available,processed,None,None,"{'date': '27.04.2026', 'case_slug': '177917683...",2025-12-29 09:29:51.949860,2025-12-29 13:54:09.704361,48025687,ListAssetsAvailable,None,ocr-v2_7_dr_ii_2203_25_aus_schreibmaschine.pdf,application/pdf,19357,2025-12-29 09:29:51.875813,None,None
38,372186,8948770,09.02.2026/ocr-v2_7_dr_ii_111_26_an_gl_termins...,list_assets_available,processed,None,None,"{'date': '18.05.2026', 'case_slug': '189485046...",2026-02-09 12:55:15.910293,2026-02-10 08:46:55.280918,52412335,ListAssetsAvailable,None,ocr-v2_7_dr_ii_111_26_an_gl_terminsmitteilung_...,application/pdf,513835,2026-02-09 12:55:15.842778,None,ocr
39,412310,2588475,30.03.2026/ocr-v2_DR-II_040526_Nachr_Mitteilun...,list_assets_available,processed,None,None,"{'date': '16.04.2026', 'case_slug': '125882078...",2026-03-30 06:22:05.308364,2026-03-30 09:21:37.405212,57842008,ListAssetsAvailable,None,ocr-v2_DR-II_040526_Nachr_Mitteilung_Gl__VAK-T...,application/pdf,64293,2026-03-30 06:22:05.257565,None,ocr
40,413641,7473491,31.03.2026/ocr-v2_7_DR_II_383_26_aus_Schreibma...,list_assets_available,processed,None,None,"{'date': '28.08.2026', 'case_slug': '174732259...",2026-03-31 07:49:18.809762,2026-04-01 07:14:40.980157,58124706,ListAssetsAvailable,None,ocr-v2_7_DR_II_383_26_aus_Schreibmaschine.PDF,application/pdf,511826,2026-03-31 07:49:18.752321,None,ocr
78,331083,7944586,05.11.2025/ocr-v2_ocr-v2_DR-II_120825_Nachr_GV...,list_assets_available,processed,None,None,"{'date': '03.12.2025', 'case_slug': '179443201...",2025-11-05 08:14:25.649965,2025-11-05 08:15:35.897240,43046691,ListAssetsAvailable,None,ocr-v2_ocr-v2_DR-II_120825_Nachr_GV_168a_BY_-_...,application/pdf,8526,2025-11-05 08:14:25.604329,None,None
79,331091,6719751,05.11.2025/ocr-v2_ocr-v2_DRII202501056TerminVA...,list_assets_available,processed,None,None,"{'date': '26.11.2025', 'case_slug': '167194854...",2025-11-05 08:18:49.197439,2025-11-05 08:21:16.110521,43046842,ListAssetsAvailable,None,ocr-v2_ocr-v2_DRII202501056TerminVAanGLBV001.pdf,application/pdf,109839,2025-11-05 08:18:49.151442,None,None
80,332449,7374839,10.11.2025/ocr-v2_Dr_ii_1462_25_an_gl_terminsm...,list_assets_available,processed,None,None,"{'date': '08.12.2025', 'case_slug': '173745732...",2025-11-10 07:29:44.089508,2025-11-10 07:42:15.090402,43395082,ListAssetsAvailable,None,ocr-v2_Dr_ii_1462_25_an_gl_terminsmitteilung_l...,application/pdf,450906,2025-11-10 07:29:44.040212,None,None
81,348035,8003600,18.12.2025/ocr-v2_ocr-v2_DR-II_134625_Nachr_GV...,list_assets_available,processed,None,None,"{'date': '07.01.2026', 'case_slug': '180033344...",2025-12-18 13:30:21.747128,2025-12-18 13:34:48.221820,47201761,ListAssetsAvailable,None,ocr-v2_ocr-v2_DR-II_134625_Nachr_GV_168a_BY_-_...,application/pdf,8502,2025-12-18 13:30:21.696142,None,None
82,373482,8948280,10.02.2026/ocr-v2_2026-02-09_DR_012126_Nachr_T...,list_assets_available,processed,None,None,"{'date': '09.02.2026', 'case_slug': '189480140...",2026-02-10 07:03:07.426815,2026-02-10 07:03:07.820000,52404484,ListAssetsAvailable,None,ocr-v2_2026-02-09_DR_012126_Nachr_Terminsmitte...,application/pdf,29831,2026-02-10 07:03:07.374289,None,ocr
83,373486,7944321,10.02.2026/ocr-v2_Dokumente_220425_09022026_10...,list_assets_available,processed,None,None,"{'date': '12.06.2024', 'case_slug': '179440554...",2026-02-10 07:04:07.947382,2026-02-10 07:04:08.458077,52404510,ListAssetsAvailable,None,ocr-v2_Dokumente_220425_09022026_104852_signed...,application/pdf,242948,2026-02-10 07:04:07.895522,None,ocr
84,295559,1250978,18.08.2025/ocr-v2_Dr_ii_1520_25_an_gl_terminsm...,list_assets_available,processed,None,None,"{'date': '09.09.2025', 'case_slug': '112507109...",2025-08-18 06:32:47.452999,2025-08-18 07:33:41.329913,36475840,ListAssetsAvailable,None,ocr-v2_Dr_ii_1520_25_an_gl_terminsmitteilung_l...,application/pdf,330152,2025-08-18 06:32:47.411069,None,None
111,338300,4426335,26.11.2025/ocr-v2_DR-II_129125_Nachr_Terminsmi...,list_assets_available,processed,None,None,"{'date': '29.01.2026', 'case_slug': '144260680...",2025-11-26 07:18:53.128742,2025-11-26 07:46:09.723319,45042948,ListAssetsAvailable,None,ocr-v2_DR-II_129125_Nachr_Terminsmitteilung_Gl...,application/pdf,27613,2025-11-26 07:18:53.083682,None,None
112,349625,8598852,23.12.2025/ocr-v2_DR-II_061725_Nachr_Mittlg__G...,list_assets_available,processed,None,None,"{'date': '20.01.2026', 'case_slug': '185985861...",2025-12-23 08:19:15.037720,2025-12-23 08:21:02.033945,47579407,ListAssetsAvailable,None,ocr-v2_DR-II_061725_Nachr_Mittlg__Glaeubiger_v...,application/pdf,358998,2025-12-23 08:19:14.932056,None,None

In [ ]:
from utils.prod_utils import download_pdf_from_s3
# download them to see if there are vermogensverzeichnis 
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new"


for i, row in check.iterrows():
    bucket_name = "pair-scanner"
    key = row.object_key
    download_pdf_from_s3(s3, bucket_name=bucket_name, object_key=key, download_dir=download_dir, file_name=None)

✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_FA_004-07112025-074609.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_dr_ii_2289_25_aus_schreibmaschine.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_dr_ii_2235_25_aus_schreibmaschine.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_dr_ii_2211_25_aus_schreibmaschine.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_dr_ii_2203_25_aus_schreibmaschine.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_dr_ii_111_26_an_gl_terminsmitteilung_ladung.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_DR-II_040526_Nachr_Mitteilung_Gl__VAK-Termin_m_Zahlungsfrist__nat__Person__27_03_2026.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_7_DR_II_383_26_aus_Schreibmaschine.PDF.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_ocr-v2_DR-II_120825_Nachr_GV_168a_BY_-_Terminsnachricht_fuer_Glaeubiger_04_11_2025.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_ocr-v2_DRII202501056TerminVAanGLBV001.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_Dr_ii_1462_25_an_gl_terminsmitteilung_ladung.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_ocr-v2_DR-II_134625_Nachr_GV_168a_BY_-_Terminsnachricht_fuer_Glaeubiger_16_12_2025.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_2026-02-09_DR_012126_Nachr_Terminsmitteilung_VAK_an_Glaeubiger.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_Dokumente_220425_09022026_104852_signed.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_Dr_ii_1520_25_an_gl_terminsmitteilung_ladung.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_DR-II_129125_Nachr_Terminsmitteilung_Gl-_Oase_25_11_2025.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new/ocr-v2_DR-II_061725_Nachr_Mittlg__Glaeubiger_vom_Termin_VA_22_12_2025.pdf

Above only 1 document is vermogenzeignis. Now use the examples from anni

In [ ]:
# sitution: i have documents as pdf files in my local, inject them into final raw dataset
# step 1) uplaod them to s3 in specific location 
# uploaded under s3://pair-email-classification/data/aftercourt/vermögensverzeichnis_without_invoice/ and s3://pair-email-classification/data/aftercourt/vermögensverzeichnis_with_invoice/
# step 2) using s3 location and textrat usage code, extract textract text from docs
# step 3) using data injection script,add new data to final raw dataset

In [ ]:
from utils.use_textract_utils import parse_pdfs_with_textract

# 1) without invoice
local_dir_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new_real/without_invoice"

f_names = os.listdir(local_dir_path)
s3_object_key_base = "data/aftercourt/vermögensverzeichnis_without_invoice/"
s3_bucket_name = "pair-email-classification"
object_keys = []
for file_name in f_names:
    if ".DS_Store" in file_name:
        continue
    
    object_key = os.path.join(s3_object_key_base, file_name)
    object_keys.append(object_key)

key_to_text_ve_no_invoice = parse_pdfs_with_textract(object_keys)

--- Logging error ---
Traceback (most recent call last):
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_5026/879076624.py", line 17, in <module>
    key_to_text_ve_no_invoice = parse_pdfs_with_textract(object_keys)
  File "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/utils/use_textract_utils.py", line 399, in parse_pdfs_with_textract
    textract_outputs = aws_textract_pipeline(object_keys, max_workers=2)
  File "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/utils/use_textract_utils.py", line 326, in aws_textract_pipeline
    logger.info("Starting AWS Textract Jobs with batch processing (max {} jobs at a time)", max_workers)
Message: 'Starting AWS Textract Jobs with batch processing (max {} jobs at a time)'
Arguments: (2,)
INFO [2026-04-15 15:20:56] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-04-15 15:20:57] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_without_invoice/combined_pdf_VV_281251_Dokument_158725_16122025_11032020251217-309-1njbrct.pdf' with job_id '4dc156942f427a2225413a70d07fb7ba10dbeb40ad09362d5fda1e0ec55d5f6b'
INFO [2026-04-15 15:20:57] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_without_invoice/dr_ii_44_26_an_gl_vak_bereits_geleistet20260204-307-1tvy4eq.pdf' with job_id '4f26fe835af01890b6f08ab42a872ccb5bda883dc38341dc66a605f93fef5d55'
INFO [2026-04-15 15:20:58] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_without_invoice/ocr-v2_Dokumente_220425_09022026_104852_signed.pdf' with job_id '74682862cc4038656878347c274b43c0525dec8b6190d575995e051ae68dc285'
INFO [2026-04-15 15:20:58] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_without_invoice/4_dr_1571_25_an_gl_vak_bereits_geleistet20251106-307-euptr3.pdf' with job_id '8220474197e32896a5cf41b0880cf39916ce399ac0438863370490ab2697adcb'
INFO [2026-04-15 15:21:00] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_without_invoice/902_dr_ii_1350_25_an_gl_abdruck_vv_senden20251110-303-u0fk0i.pdf' with job_id 'dc07831d96c0a2b7a0952bc3b196f35f3b41ed8bbec21a4f8dc8655989ed3205'
INFO [2026-04-15 15:21:00] - Submitted batch 1: 5 jobs
INFO [2026-04-15 15:22:05] - Job Completed for job_id '4dc156942f427a2225413a70d07fb7ba10dbeb40ad09362d5fda1e0ec55d5f6b' (document: data/aftercourt/vermögensverzeichnis_without_invoice/combined_pdf_VV_281251_Dokument_158725_16122025_11032020251217-309-1njbrct.pdf)
INFO [2026-04-15 15:22:07] - Job Completed for job_id '4f26fe835af01890b6f08ab42a872ccb5bda883dc38341dc66a605f93fef5d55' (document: data/aftercourt/vermögensverzeichnis_without_invoice/dr_ii_44_26_an_gl_vak_bereits_geleistet20260204-307-1tvy4eq.pdf)
INFO [2026-04-15 15:22:10] - Job Completed for job_id '74682862cc4038656878347c274b43c0525dec8b6190d575995e051ae68dc285' (document: data/aftercourt/vermögensverzeichnis_without_invoice/ocr-v2_Dokumente_220425_09022026_104852_signed.pdf)
INFO [2026-04-15 15:22:12] - Job Completed for job_id '8220474197e32896a5cf41b0880cf39916ce399ac0438863370490ab2697adcb' (document: data/aftercourt/vermögensverzeichnis_without_invoice/4_dr_1571_25_an_gl_vak_bereits_geleistet20251106-307-euptr3.pdf)
INFO [2026-04-15 15:22:15] - Job Completed for job_id 'dc07831d96c0a2b7a0952bc3b196f35f3b41ed8bbec21a4f8dc8655989ed3205' (document: data/aftercourt/vermögensverzeichnis_without_invoice/902_dr_ii_1350_25_an_gl_abdruck_vv_senden20251110-303-u0fk0i.pdf)
INFO [2026-04-15 15:22:15] - Completed batch 1: 5/5 jobs
INFO [2026-04-15 15:22:15] - AWS Textract pipeline completed: 5 successful, 0 failed
INFO [2026-04-15 15:22:15] - Final results: 5 successful, 0 failed (including cached)

In [ ]:
key_to_text_ve_no_invoice

{'data/aftercourt/vermögensverzeichnis_without_invoice/combined_pdf_VV_281251_Dokument_158725_16122025_11032020251217-309-1njbrct.pdf': 'Anlage zur Niederschrift d.:\nGV J. Hertel\nvom: 10.07.2025\nDR II 281/25, 287/25, 674/25,\n1459/24\nbei dem Amtsgericht:\nObernburg\nVermögensverzeichnis\ndes/der\nTitel\nNamensvorsatz (z.b. von, zu)\nVorname(n)\nMariana\nRufname (soweit vom Vornamen abweichend)\nGeschlecht\nweiblich\nName (frühere Namen und Geburtsname in separate Felder eintragen)\nIbrian\nWeitere Namen (z.B. bei mehrfach geschiedenen Personen)\nAlias (z.B. Künstler- oder Ordensname)\nGeburtsname (falls vom Namen abweichend)\nGeburtsdatum\n13.05.1986\nGeburtsort (ggf. auch Kreis und Bezirk angeben)\nGeburtsland\nJud.BC Mun. Bacău\nRumänien\nGesetzliche Vertreterin / Gesetzlicher Vertreter, Betreuer/in der Schuldnerin / des Schuldners\nAnschriftenzusatz (z.B. c/o)\nAnschrift (Straße und Hausnummer)\nHauptstraße 81\nAnschrift (Postleitzahl, Ort)\nAnschrift (Ortsteil)\n63931 Kirchzell\nerlernter Beruf\nzur Zeit tätig als\nkeiner\nselbständig\nFamilienstand\nBezieht Ihr/e Ehegattin/Ehegatte\nLebenspartnerin/Lebenspartner eigenes Einkommen?\nledig\nUmfang der Tätigkeit:\nName des Ehe-/Lebenspartners / Ehe-/Lebenspartnerin:\nGüterstand\nEhe-\nNotar(in):\nGüterrechtsregister beim\nGeschäftsnummer:\nLebenspartnerschaftsvertrag\nAmtsgericht/Standesamt:\nDatum:\nAnzahl der unterhaltsberechtigten Kinder (jeweils Geburtsdatum und Wohnort angeben):\nElena Anastasia Tanta, *15.10.2017, wohnhaft bei mir.\nAnzahl der im Haushalt der Schuldnerin/ des Schuldners lebenden Kinder:\nVerfügen Ihre Kinder über ein eigenes Einkommen? (für jedes Kind: Art und Höhe des Einkommens):\nNein\nArt und Höhe des an die Kinder geleisteten Unterhalts (Naturalunterhalt und/oder Geldbetrag)\nNaturalunterhalt\nSeite 1 von 6 des Vermögensverzeichnisses d. Mariana Ibrian\nA. Bewegliche Sachen\nZu Nrn. 1 bis 9: Befinden sich Ihnen gehörige Gegenstände zurzeit nicht in Ihrem Besitz\n(Gewahrsam), so müssen Sie jeweils hinzufügen, wo sie sich befinden (z. B. ,,ausgeliehen\nan ..."). Bei Sachen, die Ihnen nicht allein gehören, Mitberechtigte(n) angeben! Unter\nEigentumsvorbehalt erworbene, verpfändete, zur Sicherung übereignete oder gepfändete\nSachen sind nur unter Nr. 9 anzuführen. Es sind auch geliehene, gemietete oder geleaste\nGegenstände unter Angabe der Eigentumsverhältnisse - aufzuführen.\n1.\nBargeld\nJa, und zwar Euro: ca. 200,-\nWo befindet es sich ?\nandere Währungen: Nein\nEs befindet sich im Geldbeutel\n2.\nWertpapiere\nNein\n(z.B. Wechsel, Schecks, Pfandbriefe, Aktien,\nFondanteile usw.)\nGenau bezeichnen!\n3.\na)\nWohnungseinrichtung und Haushaltswäsche\nnur Sachen im Rahmen bescheidener Lebensführung\nb)\nKleidungsstücke\nnur Sachen im Rahmen bescheidener Lebensführung und\n(bei wertvollen Gegenständen Art, Material und Größe\nder Berufstätigkeit\nangeben)\n4.\nKunstgegenstände und Sammlungen\nNein\nunter Angabe der Art und Weise des Wertes\n5.\nUhren, Schmuck, Gold und ähnliche\nNur Modeschmuck ohne besonderen Wert\nWertsachen\nunter Angabe der Art, des Materials und des Wertes\n6.\nWertvolle Gebrauchsgegenstände\nNur Geräte ohne besonderen Wert\n(anzugeben sind insbesondere Fernsehgeräte,\nFotoapparate, Film- und Videokameras, Smartphone,\nSpielekonsole, Sportgeräte, Jagd- und Sportwaffen,\noptische Geräte, Computer, Laptop, I-Pad, Werkzeuge,\nBücher, Solarien usw.)\n7.\na)\nFahrzeuge\nNein\nauch Fahrräder, Motorräder, Motorroller, Wohnwagen (\n-anhänger), Quads, Wohnmobile (Bei\nKraftfahrzeugen Typ, Baujahr, aktueller\nKilometerstand, amtl. Kennzeichen angeben!)\nFür sicherungsübereignete Fahrzeuge siehe Nr. 9 b)\nb)\nNutzfahrzeuge\nNein\nz.B. Rasentraktor, Traktor, Anhänger usw.\nBei wem befindet sich der Kfz-Brief bzw. die\nZulassungsbescheinigung II?\n8.\nWeitere Sachen von Wert\nNein\n(z.B. wie Gartenhäuser, die nicht der ständigen\nUnterkunft dienen, Behelfsheime, Verkaufsstände,\nwertvolle Haustiere, Viehbestände, Zuchttiere,\nReitpferde -)\n9.\na)\nHaben Sie Sachen auf Abzahlung unter\nNein\nEigentumsvorbehalt gekauft (Ratenzahlung)?\n(Anschrift der Verkäuferin / des Verkäufers, Kaufpreis\nund Restschuld angeben!)\nb)\nHaben Sie Sachen (auch Fahrzeuge) freiwillig\nNein\nverpfändet oder zur Sicherheit übereignet?\n(Genaue Anschrift, Schuldgrund und -höhe angeben!)\nc)\nSind bereits Sachen gepfändet, wann und für\nNein\nwelche Forderung?\nB. Forderungen, Guthaben und ähnliche Rechte\n10. Monatliche Einkünfte\nggf. besondere Aufstellung beifügen\nArbeitseinkommen,\nNein\nsonstige Ansprüche aus Arbeitsverhältnissen\nLeistungen nach dem SGB II, SGB III und SGB\nNein\nXII, sonstige Leistungen\nSeite 2 von 6 des Vermögensverzeichnisses d. Mariana Ibrian\nWohngeld (nach WoGG)\nNein\nBedarfe für Unterkunft und Heizung, (soweit\nNein\nnicht nach SGB II)\nElterngeld, BAföG, Ausbildungsgeld,\nNein\nAusbildungsvergütung\nRenten\nNein\n(im In- und Ausland)\nRentenanwartschaften, Versorgungsbezüge\nNein\nPrivate oder betriebliche Altersvorsorge (z.B.\nNein\nRiester- oder Rürup-Rente)\n(siehe Anlage III betr. Lebensversicherungen)\nRenten-, Versicherungs- oder Geschäftsnummer:\nSachleistungen\nNein\nprivat genutzter PKW, Wohnung\nUnterhaltsansprüche\nNein\nAnzahl der Kinder:\n1\nKindergeld\nmonatlich 255,00 EUR (1 Kind)\nLeistungsverpflichtete, Leistungsverpflichtender,\nauszahlende Stelle: Familienkasse Aschaffenburg\nLiegen Pfändungen oder Abtretungen vor?\nNein\nBestehen Forderungen aus früheren\nNein\nArbeitsverhältnissen?\nWerden oder wurden vermögenswirksame\nNein\nLeistungen (z.B. aus Bausparvertrag, Aktien,\nFonds) seitens der/ des jetzigen oder\neiner/eines vorherigen Arbeitgeberin/\nArbeitgebers erbracht?\nEinnahmen aus Photovoltaik, Windkraft о.ä.\nNein\nZuwendungen Dritter\nNein\n11.\nAnsprüche aus Nebenverdienst\nNein\n(wie z.B. Nachhilfeunterricht, Übungsleitervergütung\nusw.)\n12.\nIch führe ein Erwerbsgeschäft\nJa, habe ich im Ergänzungsblatt I aufgeführt. Das Gewerbe\nwird bis Ende August abgemeldet.\nMonatlicher Umsatz: 5.000,-\nMonatlicher Gewinn: 1.000,-\n13.\nIch habe -sonst- keinerlei Einkommen. Meinen\nIch habe nur die in diesem Vermögensverzeichnis\nLebensunterhalt bestreite ich wie folgt.\nangegebenen Einkünfte.\n14.\nAnsprüche auf Rückerstattung/ Vergütung von\nJa, und zwar Einkommensteuer\nSteuern\nZuständiges Finanzamt: Finanzamt Obernburg a. Main m.\nAußenstelle Amorbach\nIm vergangenen Jahr bin ich einer\nNein\nsteuerpflichtigen Tätigkeit nachgegangen:\nErstattungsantrag bereits gestellt?\nJa, bereits ausgezahlt.\n15.\nKonten\nJa, und zwar (es sind auch Konten ohne derzeitiges\ninsbesondere\nGuthaben sowie Konten von Dritten, sofern diese benutzt\nSparguthaben\nwerden, anzugeben! Bei einem Pfändungsschutzkonto bitte\nGehaltskonten\nein "P" und bei einem Konto nur für die Zahlung von\nGeschäftskonten\nSozialleistungen bitte ein "S" hinter der IBAN-Nummer\nGirokonten\nPaypalkonto\nangeben.\nBausparverträge, die ohne vermögenswirksame\nLeistungen angespart werden\nKontoart und Bank/Bausparkasse:\nGirokonto, Spk Miltenberg-Obernb.-alt-\nInhaberin/Inhaber (Name, Anschrift): ich selbst\nIBAN-Nr.: DE61 7965 0000 0501 6158 43\nKontostand (EUR): ca. 0,-\nZahlungen mir zustehender Gelder erfolgen nicht auf Konten\nDritter.\n16.\nDigitale Währungen\nNein\n(z.B. Bitcoin, Ethereum)\n17.\nLebensversicherungen, Sterbekassen\nNein\n18.\nMitgliedschaften bei Genossenschaften\nNein\n(z.B. Volks- und Raiffeisenbanken,\nWohnungsgenossenschaften)\nSeite 3 von 6 des Vermögensverzeichnisses d. Mariana Ibrian\nBeteiligungen an\nNein\nGesellschaften/Partnerschaften\n19.\nAnsprüche aus Pacht-, Miet-und\nNein, es wurde keine Mietkaution vereinbart.\nLeasingverträgen,\nauch Untermiete und Ansprüche auf Rückzahlung\nWurde die Zahlung der Nebenkosten durch einen Dritten als\ngeleisteter Mietkautionen und Nebenkosten ggf. bes.\nDarlehen geleistet?\nAufstellung beifügen\nNein\n20.\nHaben Sie Rechte an\nNein\nGrundstücken (außer Eigentum und\ngrundstücksgleichen Rechten, S. Nr. 24 a)\nErfindungen (Patente), Urheberrechte,\nNein\nVerlagsrechte, Internetdomain usw.\nAnteile an Erbengemeinschaften und an\nNein\nfortgesetzten Gütergemeinschaften,\nPflichtteilsansprüche, Erbersatzanspruch\n21.\nSonstige Forderungen\nNein\nAnzugeben sind u. a. Forderungen aus Kauf- und\nDarlehensverträgen, Rückerstattungs- und/oder\nErsatzansprüche, Bezugsrechte an/ aus Versicherungen\n(auch Sachversicherungen), auf Abzahlung gekaufte\nund noch nicht gelieferte Gegenstände,\nSchadensersatzansprüche, Ansprüche auf\nRückerstattung von Versicherungs- und\nMitgliedsbeiträgen, von Energiekosten (Strom, Wasser,\nGas) Internetdomaine, Prepaid-Karten\n22.\nVerfügen Sie über einen Titel\nNein\n(Urteil, Beschluss usw.), aus dem hinsichtlich der unter\nNr. 10 21 bezeichneten Forderungen die\nZwangsvollstreckung betrieben werden kann?\n23.\nWelche unter Nr. 11 bis 20 angeführten\nFolgende (Gläubiger/in sowie Art und Höhe der Forderung\nAnsprüche sind freiwillig verpfändet oder\nangeben): Claudia Kohl Inkasso, ca. 3.000,- €\nabgetreten bzw. gepfändet?\n24.\na)\nGrundvermögen\nNein\n(Grundstücke, Wohnungs- oder Teileigentum, sonstige\ngrundstücksgleiche Rechte, z.B. Erbbaurecht auch im\nAusland -)\nb)\nSchiffe, Schiffsbauwerke, auch Flugzeuge,\nNein\nSportflugzeuge oder Anteile daran\n25.\nAnderes land- und forstwirtschaftliches\nNein\nVermögen?\nC. Veräußerungen von Vermögensgegenständen auch Forderungen in der Vergangenheit\n26.\nHaben Sie innerhalb der letzten zwei Jahre,\nNein\nvor dem ersten zur Abgabe der\nVermögensauskunft anberaumten Termin,\nGegenstände an eine der nachgenannten\nPersonen entgeltlich veräußert?\nmeine Ehegattin / meinen Ehegatten (vor, während\noder nach der Ehe)\nmeine oder meiner Ehegattin / meines Ehegatten\nEltern, Großeltern, Kinder, Enkelkinder\nmeine oder meines Ehegatten Geschwister und\nHalbgeschwister\ndie Ehegatten der zuvor genannten Personen\nmeiner Lebenspartnerin / meinem Lebenspartner\nPersonen, mit denen ich in häuslicher Gemeinschaft\nlebe oder im letzten Jahr vor der Handlung gelebt habe\nandere Personen des § 138 InsO\n27.\nHaben Sie innerhalb der letzten vier Jahre vor\nNein\ndem ersten zur Abgabe der\nVermögensauskunft anberaumten Termin\nunentgeltlich über Gegenstände (auch Geld)\nverfügt?\nGebräuchliche Gelegenheitsgeschenke sind nicht\nanzugeben.\nErgänzungen zu den obigen Angaben:\nKeine\nSeite 4 von 6 des Vermögensverzeichnisses d. Mariana Ibrian\nOrt, Datum\nUnterschrift befindet sich im Vermögensauskunfts-Protokol\nObernburg am Main, 10.07.2025\nDas Vermögensverzeichnis wird seit 2013 elektronisch erfasst. Das Dokument ist\ndann generell nicht unterschrieben.\nVermerke der Gerichtsvollzieherin / des Gerichtsvollziehers:\nDie Angaben im Vermögensverzeichnis wurden dem / der Schuldner(in) vor Abgabe der Versicherung nach §802c Abs. 3 ZPO\nvorgelesen.\nDie Angaben im Vermögensverzeichnis wurden dem / der Schuldner(in) vor Abgabe der Versicherung nach §802c Abs. 3 ZPO\nzur Durchsicht auf einem Bildschirm wiedergegeben.\nDer/ Die Schuldner(in) bat um Erteilung eines Ausdrucks.\nBei Ergänzung / Nachbesserung:\nDie Versicherung an Eides statt für das Vermögensverzeichnis ist erstmals erfolgt am:\nHinweise für den Gläubiger, auf Grund dessen Antrag die Erklärung erfolgt ist:\nDer vorstehende Ausdruck / dieses elektronische Dokument stimmt mit dem Inhalt des Vermögensverzeichnisses überein (§ 5 Abs.\n4 VermVV).\nHinweise für alle Gläubiger:\nSie dürfen die erlangten Daten nur zu Vollstreckungszwecken nutzen. Die Daten bzw. der Ausdruck sind\nunverzüglich nach Zweckerreichung zu vernichten (§ 802 d Abs.1 Satz 3 ZPO).\nDatum, Unterschrift der Gerichtsvollzieherin / des Gerichtsvollziehers:\n(bei elektronischer Übermittlung auch ohne Unterschrift gültig)\nSeite 5 von 6 des Vermögensverzeichnisses d. Mariana Ibrian\nGewerbetreibende; Geschäftsinhaber; Handelsgesellschaften\nErgänzungsblatt I zu Nr. 12 des Vermögensverzeichnisses\nName d. Schuldners/Schuldnerin:\nMariana Ibrian\nGeschäftszweig des Erwerbsgeschäfts\nSitz (vollständige Anschrift)\nHauptstraße 81, 63931 Kirchzell\nEintragung im Handelsregister\nLage des Geschäfts- und Lagerräume (vollständige Anschrift)\nHauptstraße 81, 63931 Kirchzell\nVermögensgegenstände, die Sie noch aus einem früheren Erwerbsgeschäft besitzen, sind nicht hier, sondern im\nHauptblatt des Verzeichnisses einzutragen. Miteigentumsrechte, Verpfändungen, Sicherungsübereignungen und\nPfändungen sind zu jeder der folgenden Nummern genau zu vermerken -vgl. Nr. 9 des Hauptblattes -.\n1.\nBüroeinrichtung\n1 Drucker, HP, Kaufpreis: ca. 200,-, Kaufdatum: 2019\n(Möbel, Büromaschinen, Schreib- und Zeichenbedarf)\n2.\nLaden- und Lagereinrichtung\nJa, und zwar Biergartenmöbel, 11 Tische, 22 Bänke,\n(Theken, Gestelle, usw.)\nKaufpreis: 3.000,-, Kaufdatum: 02/2020\n1 Kühlschrank, Kaufpreis: ca. 1.000,-, Kaufdatum: 2021\n1 Gefrierschrank, Kaufpreis: ca. 1.000,-, Kaufdatum:\n2021\n1 Pizzaofen, Kaufpreis: ca. 1.200,-, Kaufdatum:\n10/2019\n1 Gemüseschäler, Kaufpreis: ca. 300,-, Kaufdatum:\n2021\n3.\nWerkstätten-, Wirtschafts- oder\nNein\nFabrikeinrichtungen\n(Werkbänke, Arbeits- und Werkzeugmaschinen,\nWerkzeuge, usw.)\n4.\nWarenvorräte\nNein\n5.\nVorräte an\nJa, und zwar ca. 400,- an Zutaten für Lebensmittel und\na) Rohstoffen\nca. 400,- Getränke\nb) Halbfertigerzeugnissen\nc) Verpackungsstoffen, Kisten, Packpapier,\nusw.\n6.\nFahrzeuge auch Fahrräder\nNein\n(Bei Kraftfahrzeugen Typ, Baujahr und amtliches\nKennzeichen angeben)\nBei wem befindet sich der Kfz.-Brief ?\n7.\nAnderes Inventar und Arbeitsgerät\nNein\n8.\nLiegen Aufträge vor?\nNein\n9.\nHaben Sie Außenstände?\nNein\nSeite 6 von 6 des Erg. Blatt I d. Mariana Ibrian\nJ. Hertel\nKapellengasse 6\nGerichtsvollzieher\n63785 Obernburg am Main\nE-Mail: gv-hertel@t-online.de\nSprechstunden:\nMi 09.00 10.00 Uhr\nDas Büro ist vom 22.12.2025 06.01.2026\nDo 13:00 14:00 Uhr\ngeschlossen!\nTelefon 01573 2638488\nEGVP-Nutzer-ID für ERV:\nAbs. GV Hertel, Kapellengasse 6, 63785 Obernburg am Main\nDE.Justiz.644c2b4c-1ae3-48f8-b814-\ndd7e7d8eb162.b651\nFirma\nDienstkonto:\nPAIR Finance GmbH\nEmpfänger: J. Hertel\nvertr. d. d. GF\nIBAN: DE62 7955 0000 0501 6219 81\nKnesebeckstraße 62-63\nBIC: BYLADEM1ASA\n10719 Berlin\nBank: Spk Aschaffenburg Miltenberg\nDR II 1587/25\nBitte bei Schreiben und Zahlungen angeben!\n173607055469\nObernburg am Main, 16.12.2025\nZwangsvollstreckungssache\nFirma E.ON Energie Deutschland GmbH, vertr. d. d. GF, Arnulfstraße 203, 80634 München\nvertreten durch: Firma PAIR Finance GmbH, vertr. d. d. GF, Knesebeckstraße 62-63, 10719 Berlin, Az.173607055469\ngegen\nFrau Mariana Ibrian, Hauptstraße 81, 63931 Kirchzell\nKORREKTUR!\nSehr geehrte Damen und Herren,\nbezugnehemend auf Ihr Schreiben vom 12.12.2025 erhalten Sie anbei das korrekte Vermögensverzeichnis z. w.V.\nDas Versehen bitte ich zu entschuldigen.\nMit freundlichen Grüßen\nHertel\nGerichtsvollzieher\nbeim Amtsgericht Obernburg\nInformationen zum Datenschutz erhalten Sie unter https://www.justiz.bayern.de/gerichte-und-behoerden/amtsgerichte/obernburg-am-main/datenschutz.php ode\nüber die oben stehenden Kontaktdaten.\n--->PAIR Finance GmbH per EGVP an DE.Justiz.4f8ec623-a388-44be-8aab-f936a862957f.c946 am 16.12.2025\nDR II 1587/25, Seite 1',

In [ ]:
from utils.use_textract_utils import parse_pdfs_with_textract

# 1) with invoice
local_dir_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/ocr_dataset/list_assets_available/add_from_ocr_new_real/with_invoice"

f_names = os.listdir(local_dir_path)
s3_object_key_base = "data/aftercourt/vermögensverzeichnis_with_invoice/"
s3_bucket_name = "pair-email-classification"
object_keys = []
for file_name in f_names:
    if ".DS_Store" in file_name:
        continue
    
    object_key = os.path.join(s3_object_key_base, file_name)
    object_keys.append(object_key)

key_to_text_ve_with_invoice = parse_pdfs_with_textract(object_keys)

--- Logging error ---
Traceback (most recent call last):
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/melih.gorgulu/miniconda3/envs/aftercourt-automation/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_5026/3561769885.py", line 17, in <module>
    key_to_text_ve_with_invoice = parse_pdfs_with_textract(object_keys)
  File "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/utils/use_textract_utils.py", line 399, in parse_pdfs_with_textract
    textract_outputs = aws_textract_pipeline(object_keys, max_workers=2)
  File "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/utils/use_textract_utils.py", line 326, in aws_textract_pipeline
    logger.info("Starting AWS Textract Jobs with batch processing (max {} jobs at a time)", max_workers)
Message: 'Starting AWS Textract Jobs with batch processing (max {} jobs at a time)'
Arguments: (2,)
INFO [2026-04-15 15:24:29] - Found credentials in shared credentials file: ~/.aws/credentials
INFO [2026-04-15 15:24:29] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/2_dr_83_26_an_gl_vak_bereits_geleistet20260226-287-1gjgah3.pdf' with job_id 'bf11c90b8bceed973112a1921ac87e5d86ea7a46c512aada14411645bd1df66e'
INFO [2026-04-15 15:24:29] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_1752_25_an_gl_vak_bereits_geleistet20251118-307-gtynn0.pdf' with job_id '07ea4bda1e98f973eeb06000e7e3635ec905fdce558cab01a4dbd0171817d8d3'
INFO [2026-04-15 15:24:31] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_VV_177525_15508-signed_Dokument_185425_16122025_08024720251217-311-1f5mva.pdf' with job_id '13036544a6df675a7dec7358842ef23f13a379155f5d36354beda7764ad8d6dc'
INFO [2026-04-15 15:24:31] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_1576_25_an_gl_sch_hat_vak_abgegeben20251215-306-nmm7kn.pdf' with job_id '6d01faf59f77588b59375094ffd12cea40ede8c4fc7cad13b3f954d1a7cea876'
INFO [2026-04-15 15:24:31] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/kl_001-11112025-084453.pdf' with job_id '10b74c33241b5717634340b1b1fd5215399467c19ae726aa8a352d03fd5c351c'
INFO [2026-04-15 15:24:32] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/0_sammel120251127-308-11qk5b6.pdf' with job_id '3ead7af90e22850da65de942eb5bcf6cc21de4277d6006740f0762a493d9d558'
INFO [2026-04-15 15:24:32] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_72_26_an_gl_vak_bereits_geleistet20260121-308-1c71s3m.pdf' with job_id '25d8721f420a2685f7ff648f1fa74f8a76b1adf2b674606b0f1850bd14e4f0ae'
INFO [2026-04-15 15:24:32] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_148825_26112025_142706-signed20251127-308-1s9sl3e.pdf' with job_id 'b9769a5cb92305bc24adb336fb7938c8c4d195386c7bf7b745597daa38cb612d'
INFO [2026-04-15 15:24:33] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_923_25_vak_abgegeben_mit_kostenrechnung20260109-310-1k5hu0d.pdf' with job_id 'c284020226c34f94ae9a3bbf4c2d190aff5964527e4d701c272dfc3a1e2eb597'
INFO [2026-04-15 15:24:33] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/Dr_ii_2752_25_an_gl_sch_hat_ev_abgegeben20260102-307-p0wdte.pdf' with job_id '247fd9c06641a06c850d0e69d5f93db36a25138da3594cb38b9eb81ace5b618c'
INFO [2026-04-15 15:24:34] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_143625_06112025_155706_signed20251110-312-slc0uf.pdf' with job_id '898ad238b80246455533b35be87aa64ecd0d34bcec787336014b142920dab2a4'
INFO [2026-04-15 15:24:34] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_58225_03112025_100242_signed20251104-311-1a137zd.pdf' with job_id '80bb1e3c78f678c6610e006b4dcd6e03a917b823e39d85ac6e96308d1cee03dd'
INFO [2026-04-15 15:24:35] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_vv_v-11_09_2025_mahnke-signed_dr-ii_138325_nachr_zuleitung_va_gem_802c_an_folgeglaeubiger_elektr_27_11_202520251128-308-1xvoqmh.pdf' with job_id '67ee64d5c12be2cda7cc430923f64ce09ce45dbf5448d20e5745d063724cb00f'
INFO [2026-04-15 15:24:35] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/VA + RG.pdf' with job_id 'fdbcf5e168d78fbd82fd67f490a755befa9123c21cdb3d7f612fc0a936560fa1'
INFO [2026-04-15 15:24:35] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/0_sammel120251216-308-1jlwrsh (1).pdf' with job_id 'ada98e748df01988a650958ff7f90770ed5da29f80572ff946a1211b146dd30a'
INFO [2026-04-15 15:24:37] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/4_dr_1685_25_3006_an_gl_vv_u_prot_drittglubiger_per_post20251217-309-1jfduug.pdf' with job_id 'b0fe07e8045def75b8c29b3037c9132cda95bb749e0c29f1d8f88166bd41757e'
INFO [2026-04-15 15:24:37] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_VV-signed_DR-II_203925_Nachr_18_12_202520251219-312-1uy37et.pdf' with job_id '25f2e8abf5b54181bc96713ba9921103a343dec0daf3be3e36011e39c466fa23'
INFO [2026-04-15 15:24:38] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_143_26_an_gl_vak_bereits_geleistet20260204-312-1phy6uz.pdf' with job_id '8499388abb8837283b8e1053641fa69b89b8797d9aa3e303b1fbc08738a05257'
INFO [2026-04-15 15:24:38] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_eintrag_DR-II_185425_Nachr_Mitlg_an_Glb__S_hat_VA_geleistet__802d_15_12_2025_2_20251216-305-gdi3ua (1).pdf' with job_id 'eba7857075e1d454fe33fe5d08f8d8befefa23a29740b4696504dae8cbb0b723'
INFO [2026-04-15 15:24:40] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/Sammeldokument_DRNr_135325_1612202520251217-312-1st9ko2 (1).pdf' with job_id 'e57c10076d06884ee30a08ed520c910c1cefe185fa3604e9daa01bfe50442a81'
INFO [2026-04-15 15:24:40] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/Dr_ii_105_26_an_gl_sch_hat_ev_abgegeben_abgendert_neues_recht20260226-293-1d3dbbe (1).pdf' with job_id '6a348fa21c1ab029b60d8e27a6fe7138882de206e0097ad6269f9dfec710f69e'
INFO [2026-04-15 15:24:41] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_eintrag-signed_dr-ii_115525_nachr_gkb-ervq_14_11_202520251117-306-1osgnbd.pdf' with job_id '9afabbf39139be0a645599693234fce4817ab3ada7b2af75d1306b545d15b26a'
INFO [2026-04-15 15:24:41] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/RG_3_dr_ii_886_25_an_gl_vak_bereits_geleistet20251107-308-1h86hhu.pdf' with job_id '83480e2250252518e7965dc71ac609568f010b755ee3a619eb27ab0eaa04e9a5'
INFO [2026-04-15 15:24:41] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_108_26_an_gl_vak_bereits_geleistet20260226-296-82kkra.pdf' with job_id '3f2204d185c5954389d8f60303003267abf3f5c709a6aef7b37ca207c33d5742'
INFO [2026-04-15 15:24:42] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/1_dr_ii_290_26_an_gl_vak_bereits_geleistet20260226-293-113jlcd (1).pdf' with job_id 'fde4072160508868501d2c53013e962f7f13beae7db3d749baeb4dda16c30b90'
INFO [2026-04-15 15:24:42] - Submitted batch 1: 25 jobs
INFO [2026-04-15 15:25:19] - Job Completed for job_id 'bf11c90b8bceed973112a1921ac87e5d86ea7a46c512aada14411645bd1df66e' (document: data/aftercourt/vermögensverzeichnis_with_invoice/2_dr_83_26_an_gl_vak_bereits_geleistet20260226-287-1gjgah3.pdf)
INFO [2026-04-15 15:25:26] - Job Completed for job_id '07ea4bda1e98f973eeb06000e7e3635ec905fdce558cab01a4dbd0171817d8d3' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_1752_25_an_gl_vak_bereits_geleistet20251118-307-gtynn0.pdf)
INFO [2026-04-15 15:25:28] - Job Completed for job_id '13036544a6df675a7dec7358842ef23f13a379155f5d36354beda7764ad8d6dc' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_VV_177525_15508-signed_Dokument_185425_16122025_08024720251217-311-1f5mva.pdf)
INFO [2026-04-15 15:25:31] - Job Completed for job_id '6d01faf59f77588b59375094ffd12cea40ede8c4fc7cad13b3f954d1a7cea876' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_1576_25_an_gl_sch_hat_vak_abgegeben20251215-306-nmm7kn.pdf)
INFO [2026-04-15 15:25:35] - Job Completed for job_id '10b74c33241b5717634340b1b1fd5215399467c19ae726aa8a352d03fd5c351c' (document: data/aftercourt/vermögensverzeichnis_with_invoice/kl_001-11112025-084453.pdf)
INFO [2026-04-15 15:25:40] - Job Completed for job_id '3ead7af90e22850da65de942eb5bcf6cc21de4277d6006740f0762a493d9d558' (document: data/aftercourt/vermögensverzeichnis_with_invoice/0_sammel120251127-308-11qk5b6.pdf)
INFO [2026-04-15 15:25:43] - Job Completed for job_id '25d8721f420a2685f7ff648f1fa74f8a76b1adf2b674606b0f1850bd14e4f0ae' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_72_26_an_gl_vak_bereits_geleistet20260121-308-1c71s3m.pdf)
INFO [2026-04-15 15:25:47] - Job Completed for job_id 'b9769a5cb92305bc24adb336fb7938c8c4d195386c7bf7b745597daa38cb612d' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_148825_26112025_142706-signed20251127-308-1s9sl3e.pdf)
INFO [2026-04-15 15:25:50] - Job Completed for job_id 'c284020226c34f94ae9a3bbf4c2d190aff5964527e4d701c272dfc3a1e2eb597' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_923_25_vak_abgegeben_mit_kostenrechnung20260109-310-1k5hu0d.pdf)
INFO [2026-04-15 15:25:53] - Job Completed for job_id '247fd9c06641a06c850d0e69d5f93db36a25138da3594cb38b9eb81ace5b618c' (document: data/aftercourt/vermögensverzeichnis_with_invoice/Dr_ii_2752_25_an_gl_sch_hat_ev_abgegeben20260102-307-p0wdte.pdf)
INFO [2026-04-15 15:25:55] - Job Completed for job_id '898ad238b80246455533b35be87aa64ecd0d34bcec787336014b142920dab2a4' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_143625_06112025_155706_signed20251110-312-slc0uf.pdf)
INFO [2026-04-15 15:25:58] - Job Completed for job_id '80bb1e3c78f678c6610e006b4dcd6e03a917b823e39d85ac6e96308d1cee03dd' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dokumente_58225_03112025_100242_signed20251104-311-1a137zd.pdf)
INFO [2026-04-15 15:26:00] - Job Completed for job_id '67ee64d5c12be2cda7cc430923f64ce09ce45dbf5448d20e5745d063724cb00f' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_vv_v-11_09_2025_mahnke-signed_dr-ii_138325_nachr_zuleitung_va_gem_802c_an_folgeglaeubiger_elektr_27_11_202520251128-308-1xvoqmh.pdf)
INFO [2026-04-15 15:26:05] - Job Completed for job_id 'fdbcf5e168d78fbd82fd67f490a755befa9123c21cdb3d7f612fc0a936560fa1' (document: data/aftercourt/vermögensverzeichnis_with_invoice/VA + RG.pdf)
INFO [2026-04-15 15:26:10] - Job Completed for job_id 'ada98e748df01988a650958ff7f90770ed5da29f80572ff946a1211b146dd30a' (document: data/aftercourt/vermögensverzeichnis_with_invoice/0_sammel120251216-308-1jlwrsh (1).pdf)
INFO [2026-04-15 15:26:14] - Job Completed for job_id 'b0fe07e8045def75b8c29b3037c9132cda95bb749e0c29f1d8f88166bd41757e' (document: data/aftercourt/vermögensverzeichnis_with_invoice/4_dr_1685_25_3006_an_gl_vv_u_prot_drittglubiger_per_post20251217-309-1jfduug.pdf)
INFO [2026-04-15 15:26:16] - Job Completed for job_id '25f2e8abf5b54181bc96713ba9921103a343dec0daf3be3e36011e39c466fa23' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_VV-signed_DR-II_203925_Nachr_18_12_202520251219-312-1uy37et.pdf)
INFO [2026-04-15 15:26:19] - Job Completed for job_id '8499388abb8837283b8e1053641fa69b89b8797d9aa3e303b1fbc08738a05257' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_143_26_an_gl_vak_bereits_geleistet20260204-312-1phy6uz.pdf)
INFO [2026-04-15 15:26:21] - Job Completed for job_id 'eba7857075e1d454fe33fe5d08f8d8befefa23a29740b4696504dae8cbb0b723' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_eintrag_DR-II_185425_Nachr_Mitlg_an_Glb__S_hat_VA_geleistet__802d_15_12_2025_2_20251216-305-gdi3ua (1).pdf)
INFO [2026-04-15 15:26:24] - Job Completed for job_id 'e57c10076d06884ee30a08ed520c910c1cefe185fa3604e9daa01bfe50442a81' (document: data/aftercourt/vermögensverzeichnis_with_invoice/Sammeldokument_DRNr_135325_1612202520251217-312-1st9ko2 (1).pdf)
INFO [2026-04-15 15:26:26] - Job Completed for job_id '6a348fa21c1ab029b60d8e27a6fe7138882de206e0097ad6269f9dfec710f69e' (document: data/aftercourt/vermögensverzeichnis_with_invoice/Dr_ii_105_26_an_gl_sch_hat_ev_abgegeben_abgendert_neues_recht20260226-293-1d3dbbe (1).pdf)
INFO [2026-04-15 15:26:31] - Job Completed for job_id '9afabbf39139be0a645599693234fce4817ab3ada7b2af75d1306b545d15b26a' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_eintrag-signed_dr-ii_115525_nachr_gkb-ervq_14_11_202520251117-306-1osgnbd.pdf)
INFO [2026-04-15 15:26:38] - Job Completed for job_id '83480e2250252518e7965dc71ac609568f010b755ee3a619eb27ab0eaa04e9a5' (document: data/aftercourt/vermögensverzeichnis_with_invoice/RG_3_dr_ii_886_25_an_gl_vak_bereits_geleistet20251107-308-1h86hhu.pdf)
INFO [2026-04-15 15:26:41] - Job Completed for job_id '3f2204d185c5954389d8f60303003267abf3f5c709a6aef7b37ca207c33d5742' (document: data/aftercourt/vermögensverzeichnis_with_invoice/dr_ii_108_26_an_gl_vak_bereits_geleistet20260226-296-82kkra.pdf)
INFO [2026-04-15 15:26:46] - Job Completed for job_id 'fde4072160508868501d2c53013e962f7f13beae7db3d749baeb4dda16c30b90' (document: data/aftercourt/vermögensverzeichnis_with_invoice/1_dr_ii_290_26_an_gl_vak_bereits_geleistet20260226-293-113jlcd (1).pdf)
INFO [2026-04-15 15:26:46] - Completed batch 1: 25/27 jobs
INFO [2026-04-15 15:26:46] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_Dr_ii_1523_25_aus_schreibmaschine_25-1523PDFDokument25-1523_VAK_GVSwwuqcvgkpdf_25-1523DRII152325000011-VAK-ProtokollAbnahme20251218-309-kxyzw0.pdf' with job_id 'a56adffba3604a2524926792ff41a8ccf8b4d2c194f5fadc13b44985809de208'
INFO [2026-04-15 15:26:47] - Textract job submitted for document 'data/aftercourt/vermögensverzeichnis_with_invoice/Dokumente_52726_25022026_16244220260226-292-1byoj84 (1).pdf' with job_id '5d6fd8cc880944c0c41a452fee2003463749e0e348f7dd394e03f112ce537d69'
INFO [2026-04-15 15:26:47] - Submitted batch 2: 2 jobs
INFO [2026-04-15 15:26:57] - Job Completed for job_id 'a56adffba3604a2524926792ff41a8ccf8b4d2c194f5fadc13b44985809de208' (document: data/aftercourt/vermögensverzeichnis_with_invoice/combined_pdf_Dr_ii_1523_25_aus_schreibmaschine_25-1523PDFDokument25-1523_VAK_GVSwwuqcvgkpdf_25-1523DRII152325000011-VAK-ProtokollAbnahme20251218-309-kxyzw0.pdf)
INFO [2026-04-15 15:27:04] - Job Completed for job_id '5d6fd8cc880944c0c41a452fee2003463749e0e348f7dd394e03f112ce537d69' (document: data/aftercourt/vermögensverzeichnis_with_invoice/Dokumente_52726_25022026_16244220260226-292-1byoj84 (1).pdf)
INFO [2026-04-15 15:27:04] - Completed batch 2: 27/27 jobs
INFO [2026-04-15 15:27:04] - AWS Textract pipeline completed: 27 successful, 0 failed

In [ ]:
ve_with_invoice = pd.DataFrame.from_dict(key_to_text_ve_with_invoice, orient='index', columns=['text'])
ve_with_invoice = ve_with_invoice.reset_index().rename(columns={'index': 'object_key'})
ve_with_invoice['is_ve_with_invoice'] = True

ve_without_invoice = pd.DataFrame.from_dict(key_to_text_ve_no_invoice, orient='index', columns=['text'])
ve_without_invoice = ve_without_invoice.reset_index().rename(columns={'index': 'object_key'})
ve_without_invoice['is_ve_with_invoice'] = False


ve_data_to_add = pd.concat([ve_with_invoice, ve_without_invoice], axis=0)
ve_data_to_add

,object_key,text,is_ve_with_invoice
0,data/aftercourt/vermögensverzeichnis_with_invo...,Helga Gerstl\nHauptgerichtsvollzieherin\nAmsel...,True
1,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieherin\n56290 Macken\nMichae...,True
2,data/aftercourt/vermögensverzeichnis_with_invo...,Anlage zur Niederschrift d.:\nOGV Kolja Maletz...,True
3,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieherin\nRutesheimer Str. 50/2A\n...,True
4,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieher\nSchloßstr. 42 (Eingang...,True
5,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieherin\nPoststraße 1\nSand\n5917...,True
6,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieher beim Amtsgericht Böblingen\...,True
7,data/aftercourt/vermögensverzeichnis_with_invo...,Andreas Lechte\nBahnhofstraße 42\nObergerichts...,True
8,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieher\nMagdeburger Platz 1 (Z...,True
9,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieher\nAG Lichtenberg\nKollecker\...,True
10,data/aftercourt/vermögensverzeichnis_with_invo...,Kai Ederleh\nHeinrich-Sohnrey-Str. 17\nOberger...,True
11,data/aftercourt/vermögensverzeichnis_with_invo...,S. Graffenberger\nSegelfliegerdamm 89\nGericht...,True
12,data/aftercourt/vermögensverzeichnis_with_invo...,Anlage zur Niederschrift d. Obergerichtsvollzi...,True
13,data/aftercourt/vermögensverzeichnis_with_invo...,N. Stenzel\nBlücherstraße 4\nGerichtsvollziehe...,True
14,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieher\nAm Kalkberg 18\nS. Wul...,True
15,data/aftercourt/vermögensverzeichnis_with_invo...,Reiner Herrling\nHauptgerichtsvollzieher am Am...,True
16,data/aftercourt/vermögensverzeichnis_with_invo...,Anlage zur Niederschrift d. Obergerichtsvollzi...,True
17,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieherin\nSchöttlinstr. 1\nSabine ...,True
18,data/aftercourt/vermögensverzeichnis_with_invo...,Anlage zur Niederschrift d. Obergerichtsvollzi...,True
19,data/aftercourt/vermögensverzeichnis_with_invo...,Alina Greve\nPostfach 12 27\nGerichtsvollziehe...,True
20,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieherin B. Schulz\nBüro /\nBü...,True
21,data/aftercourt/vermögensverzeichnis_with_invo...,Anlage zur Niederschrift d. JHS als Gerichtsvo...,True
22,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieherin Paul\nDienstkonto\nGa...,True
23,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieher\nAmtsgericht: Neubrande...,True
24,data/aftercourt/vermögensverzeichnis_with_invo...,Gerichtsvollzieher beim Amtsgericht Lahr\n7793...,True
25,data/aftercourt/vermögensverzeichnis_with_invo...,Obergerichtsvollzieherin\nBogenstraße 15\nN. S...,True
26,data/aftercourt/vermögensverzeichnis_with_invo...,Christina Sander\nKnippingweg 1\nGerichtsvollz...,True
0,data/aftercourt/vermögensverzeichnis_without_i...,Anlage zur Niederschrift d.:\nGV J. Hertel\nvo...,False
1,data/aftercourt/vermögensverzeichnis_without_i...,Obergerichtsvollzieherin Kerstin Gernert\n1551...,False
2,data/aftercourt/vermögensverzeichnis_without_i...,Gerichtsvollzieherin Sülzle\nBüroanschrift:\nA...,False
3,data/aftercourt/vermögensverzeichnis_without_i...,Obergerichtsvollzieher T. Eberl\nAmtsgericht S...,False
4,data/aftercourt/vermögensverzeichnis_without_i...,Amtsgericht Hamburg-St.Georg\nGerichtsvollzieh...,False

In [ ]:
data

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5378,eae76ab8-0752-5c44-8726-5f920f8e6f0a,51170436,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,NaN,fp_invoice,NaN,NaN,False,False,NaN,080d5f6c1c195c1abfcf9107e6bcf70367e6bd8c521df1...,s3://pair-data-engineering-new/ocr_prepared_ou...
5379,c6723ec9-b3bd-53f3-a7ba-121f8e6d708a,52618215,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,NaN,bailiff_ip,NaN,NaN,False,False,NaN,dcbb82c7982aa1a6f43b73f48cf71e520983dfeaf361f4...,s3://pair-data-engineering-new/ocr_prepared_ou...
5380,d66ee21e-705e-5729-9a82-d5821667f99d,50758910,André Rucks\nSittarder Str. 72\n52511 Geilenki...,NaN,tbd,NaN,NaN,False,False,NaN,e60667129a00c38ab5c8e70001a2ebbd49c13e9eb6e0f3...,s3://pair-data-engineering-new/ocr_prepared_ou...
5381,33751aae-53eb-5874-910a-65d80b66e082,51118089,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,NaN,fp_invoice,NaN,NaN,False,False,NaN,01a1a0d3674e331b26566e92f62e666c0a295ef7eca672...,s3://pair-data-engineering-new/ocr_prepared_ou...
5382,353f4e7f-5046-522f-a69b-b6965f7a60b5,50427647,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,NaN,fp_invoice,NaN,NaN,False,False,NaN,709cd8bf8f5a1f979b83897c6a4a2ca933a8bfbd47a5d9...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [2]:
ve_data_to_add = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/classification/vermögensverzeichnis/sil.csv")

In [7]:
from utils.intent_recog_utils import apply_text_cleaning
from src.data_handling.update_raw_data import update_raw_data

final_raw_data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

# add required columns
ve_data_to_add['document_type'] = 'vermögensverzeichnis'
ve_data_to_add['is_pfub'] = False
ve_data_to_add['is_ladung'] = False
ve_data_to_add['cleaned_text'] = ve_data_to_add['text'].fillna("").apply(apply_text_cleaning)

df_to_save = update_raw_data(final_raw_data, ve_data_to_add)

In [9]:
df_to_save

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice
0,0bb04c7d-e0a5-54c2-b9ef-b6ff6394e864,7a78745c-e4ff-5d1f-abd0-39b5f517109b,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
1,722c7224-fa7c-5942-a4cf-c2ddb70c1e94,8eb7ea40-2bb6-5828-98af-5c8686c67a34,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
2,16e88ab5-96dc-5afa-8447-7d068aacc6a7,dcf3e789-6aa7-595d-94c7-9133ae2b2375,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
3,6f59a98b-d33d-5a0c-9bc4-05800e95c2b2,f04f445f-dcd7-5044-8a7f-5d6f37a8e608,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
4,19e6fa9c-6c9b-5701-a805-05b6bce007e8,ff5c534d-1dd9-5dac-be2e-b57f812f36ac,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410,c32daff3-49d9-5c6a-baef-ff36585d7fdc,20cd18e4-97d2-579b-8238-0465dd3c6253,Anlage zur Niederschrift d.:\nGV J. Hertel\nvo...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,anlage zur niederschrift d.:\ngv j. hertel\nvo...,NaN,False,False,NaN,5d38e9b4b6c5c862faf7cf5255a9a00550dfb4b0deedc9...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5411,4aa68493-cf56-5f8d-b10d-e38a44ec2d2d,4fdca78f-66dc-570d-b40c-0b520b892af5,Obergerichtsvollzieherin Kerstin Gernert\n1551...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,obergerichtsvollzieherin kerstin gernert\n1551...,NaN,False,False,NaN,63d4af42eca48e863ff72433c51f65ed627c4167d6a6ba...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5412,2e39888c-cc06-574f-90ae-348009e802af,9ee5bc1d-b55f-5250-98b7-2ab4bcf8bff0,Gerichtsvollzieherin Sülzle\nBüroanschrift:\nA...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,gerichtsvollzieherin sülzle\nbüroanschrift:\na...,NaN,False,False,NaN,0d9f9857bac053a6bdf1278afcef872f84a19d01385fd0...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5413,d8b85e90-59ba-5985-9699-1fab6c6a974e,071beb4b-a61e-5492-b016-ab7e4887509f,Obergerichtsvollzieher T. Eberl\nAmtsgericht S...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,obergerichtsvollzieher t. eberl\namtsgericht s...,NaN,False,False,NaN,a0b9a8854c8fc28fec0e95cb6f9433ee0adc2dbd3bdaea...,s3://pair-data-engineering-new/ocr_prepared_ou...,False
5414,d95b8c60-7670-57b3-a824-ae999125ee77,7142425f-6487-533c-bdc2-83010c516ee0,Amtsgericht Hamburg-St.Georg\nGerichtsvollzieh...,data/aftercourt/vermögensverzeichnis_without_i...,vermögensverzeichnis,amtsgericht hamburg-st.georg\ngerichtsvollzieh...,NaN,False,False,NaN,f4096ea2d73add08017d42ca48661a617ed13f1953db5a...,s3://pair-data-engineering-new/ocr_prepared_ou...,False

In [10]:
# --- Comprehensive comparison of final_raw_data vs df_to_save ---

print("=" * 60)
print("SHAPE COMPARISON")
print("=" * 60)
print(f"final_raw_data: {final_raw_data.shape[0]} rows, {final_raw_data.shape[1]} cols")
print(f"df_to_save:     {df_to_save.shape[0]} rows, {df_to_save.shape[1]} cols")
print(f"New rows added:  {df_to_save.shape[0] - final_raw_data.shape[0]}")
new_cols = set(df_to_save.columns) - set(final_raw_data.columns)
removed_cols = set(final_raw_data.columns) - set(df_to_save.columns)
if new_cols:
    print(f"New columns:     {new_cols}")
if removed_cols:
    print(f"Removed columns: {removed_cols}")

print("\n" + "=" * 60)
print("DOCUMENT TYPE DISTRIBUTION COMPARISON")
print("=" * 60)
dist_old = final_raw_data['document_type'].value_counts()
dist_new = df_to_save['document_type'].value_counts()
dist_comparison = pd.DataFrame({'before': dist_old, 'after': dist_new}).fillna(0).astype(int)
dist_comparison['diff'] = dist_comparison['after'] - dist_comparison['before']
print(dist_comparison)

print("\n" + "=" * 60)
print("NEW ROWS DETAIL")
print("=" * 60)
if 'object_key' in df_to_save.columns:
    old_keys = set(final_raw_data['object_key'].dropna())
    new_keys = set(df_to_save['object_key'].dropna())
    added_keys = new_keys - old_keys
    print(f"New object_keys added: {len(added_keys)}")
    new_rows = df_to_save[df_to_save['object_key'].isin(added_keys)]
    print(f"\nNew rows breakdown by document_type:")
    print(new_rows['document_type'].value_counts())
    if 'is_ve_with_invoice' in new_rows.columns:
        print(f"\nNew rows breakdown by is_ve_with_invoice:")
        print(new_rows['is_ve_with_invoice'].value_counts())
    print(f"\nSample of newly added rows:")
    display(new_rows.head(10))
else:
    new_rows = df_to_save.iloc[final_raw_data.shape[0]:]
    print(f"New rows (by index): {len(new_rows)}")
    display(new_rows.head(10))

print("\n" + "=" * 60)
print("NULL VALUE COMPARISON")
print("=" * 60)
nulls_old = final_raw_data.isnull().sum()
nulls_new = df_to_save.isnull().sum()
common_cols = sorted(set(final_raw_data.columns) & set(df_to_save.columns))
null_comparison = pd.DataFrame({
    'before_nulls': nulls_old.reindex(common_cols),
    'after_nulls': nulls_new.reindex(common_cols)
}).fillna(0).astype(int)
null_comparison['diff'] = null_comparison['after_nulls'] - null_comparison['before_nulls']
null_comparison = null_comparison[null_comparison['diff'] != 0]
if not null_comparison.empty:
    print(null_comparison)
else:
    print("No change in null counts across shared columns.")

print("\n" + "=" * 60)
print("DUPLICATE CHECK")
print("=" * 60)
if 'object_key' in df_to_save.columns:
    dupes = df_to_save[df_to_save['object_key'].duplicated(keep=False) & df_to_save['object_key'].notna()]
    print(f"Duplicate object_keys in df_to_save: {dupes['object_key'].nunique()} keys ({len(dupes)} rows)")
    if not dupes.empty:
        display(dupes.head(10))

============================================================
SHAPE COMPARISON
============================================================
final_raw_data: 5383 rows, 12 cols
df_to_save:     5415 rows, 13 cols
New rows added:  32
New columns:     {'is_ve_with_invoice'}

============================================================
DOCUMENT TYPE DISTRIBUTION COMPARISON
============================================================
                                        before  after  diff
document_type
approved_attachment_and_transfer_order      64     64     0
approved_seizure                           406    406     0
attachment_and_transfer_order              535    535     0
bailiff_ip                                  20     20     0
contradiction                                3      3     0
court_inbox                                346    346     0
enforcement_order                           23     23     0
fp_invoice                                 128    128     0
fp_protocol                                220    220     0
ladung_va                                 2030   2030     0
mail_attachments                           984    984     0
monierung_mb                               545    545     0
tbd                                         22     22     0
vermögensverzeichnis                        57     89    32

============================================================
NEW ROWS DETAIL
============================================================
New object_keys added: 32

New rows breakdown by document_type:
document_type
vermögensverzeichnis    32
Name: count, dtype: int64

New rows breakdown by is_ve_with_invoice:
is_ve_with_invoice
True     27
False     5
Name: count, dtype: int64

Sample of newly added rows:

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link,is_ve_with_invoice
5383,21ff29f9-0939-5ba3-b632-b77ea3077483,f0ac7d1c-7e27-5c24-9f8f-7a4e40ed833a,Helga Gerstl\nHauptgerichtsvollzieherin\nAmsel...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,helga gerstl\nhauptgerichtsvollzieherin\namsel...,NaN,False,False,NaN,74100a5823898009a4d7353a183d4c3b4582a47e517872...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5384,ad7254c5-f694-5f0b-8562-6148f0881523,7def55aa-6fcc-5904-b12f-dc882a2ca729,Obergerichtsvollzieherin\n56290 Macken\nMichae...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,obergerichtsvollzieherin\n56290 macken\nmichae...,NaN,False,False,NaN,5778354e083065fbd872030f4543c9cdaa3505e90f084b...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5385,6114ea8c-0415-539d-bbb2-43f2d8d5efcd,0c44f470-a74a-51b1-9e4a-fd47bbf492d8,Anlage zur Niederschrift d.:\nOGV Kolja Maletz...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,anlage zur niederschrift d.:\nogv kolja maletz...,NaN,False,False,NaN,a191eac636fe9af6461cbb909f54ff0246c932c396e91c...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5386,8275e126-f6f4-563b-9336-3e4b41dd1522,09d7bb75-16a0-5049-9feb-c6b00372861c,Gerichtsvollzieherin\nRutesheimer Str. 50/2A\n...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,gerichtsvollzieherin\nrutesheimer str. 50/2a\n...,NaN,False,False,NaN,c800ae702e2d6c6e8a6cf8189a7dbc6dc9288f3afc3407...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5387,4fdd851e-46a8-5d56-aa42-dbaa786fb942,91c4d2a0-c7d4-5762-acdf-a38ee8bec7f2,Obergerichtsvollzieher\nSchloßstr. 42 (Eingang...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,obergerichtsvollzieher\nschloßstr. 42 (eingang...,NaN,False,False,NaN,9d7d5e83b6b9d02a71971451538ba4ffa0497219b728a3...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5388,fa82e542-c3a6-5eea-b252-a9e4e3e8bed3,347853fc-8b9f-522a-a40d-21bf915b1af9,Gerichtsvollzieherin\nPoststraße 1\nSand\n5917...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,gerichtsvollzieherin\npoststraße 1\nsand\n5917...,NaN,False,False,NaN,65242bc83a74426a92a6fc577918aedb088334c6195647...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5389,37e5aa21-b9ac-5544-b67c-defb0d02d34b,2ad6769d-9f53-5fd3-97d3-e107d3496354,Gerichtsvollzieher beim Amtsgericht Böblingen\...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,gerichtsvollzieher beim amtsgericht böblingen\...,NaN,False,False,NaN,bca0b83de6df3ee836ba6ecf704633a18ab88f12d10099...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5390,0d50200f-2238-5dc4-a771-ef15c6020d67,dbc0ffce-d8cc-5eef-8a29-9ddfa3723231,Andreas Lechte\nBahnhofstraße 42\nObergerichts...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,andreas lechte\nbahnhofstraße 42\nobergerichts...,NaN,False,False,NaN,2e3e07c8dddf4aea03af3555c416682e48d7d99da42d2f...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5391,8d7dc95b-999f-5b18-b5c9-4d7f0dbbe7ad,4f80190a-90a0-521d-95dc-de069ebcf4be,Obergerichtsvollzieher\nMagdeburger Platz 1 (Z...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,obergerichtsvollzieher\nmagdeburger platz 1 (z...,NaN,False,False,NaN,ec2a62363060de01c46f86c88dec436e5cad7d36bd1e65...,s3://pair-data-engineering-new/ocr_prepared_ou...,True
5392,31a85cdb-86b4-57d7-9b0c-89415a48f507,edce0698-7b9e-5f1c-990b-f2cc20414f7c,Gerichtsvollzieher\nAG Lichtenberg\nKollecker\...,data/aftercourt/vermögensverzeichnis_with_invo...,vermögensverzeichnis,gerichtsvollzieher\nag lichtenberg\nkollecker\...,NaN,False,False,NaN,15488e7c53930fa04e1062b249461b5a94ef54167e334b...,s3://pair-data-engineering-new/ocr_prepared_ou...,True

============================================================
NULL VALUE COMPARISON
============================================================
         before_nulls  after_nulls  diff
data             4918         4950    32
s3_link          5171         5203    32

============================================================
DUPLICATE CHECK
============================================================
Duplicate object_keys in df_to_save: 0 keys (0 rows)

In [ ]:
#df_to_save.to_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv", index=False)

temsili

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv")

In [3]:
data.document_type.value_counts()

document_type
ladung_va                                 2030
mail_attachments                           984
monierung_mb                               545
attachment_and_transfer_order              535
approved_seizure                           406
court_inbox                                346
fp_protocol                                220
fp_invoice                                 128
vermögensverzeichnis                        89
approved_attachment_and_transfer_order      64
enforcement_order                           23
tbd                                         22
bailiff_ip                                  20
contradiction                                3
Name: count, dtype: int64