In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/letters/June_16_App_Preds/egvp_results_16June.csv")

In [ ]:
data.s

In [5]:
data

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
0,18854854,28200228494492,2026-06-16 05:06:02.815203,Detected Slugs:\n\n 142367003258,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200228494492-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200228494492-1.pdf,<page_1>\nObergerichtsvollzieherin Ann-Katrin ...,\nObergerichtsvollzieherin Ann-Katrin Walter\n...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
1,18854876,28200311509020,2026-06-16 05:09:02.199376,Detected Slugs:\n\n 181411092461,1st Level (in after-court area)\nDetected Slug...,28200311509020-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200311509020-1.pdf,<page_1>\nStefan Lüddecke\nSaarlandring 20 b\n...,\nStefan Lüddecke\nSaarlandring 20 b\nObergeri...,...,False,False,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
2,18854878,28200251076892,2026-06-16 05:09:25.827504,Detected Slugs:\n\n 185906618540,1st Level (in after-court area)\nDetected Slug...,28200251076892-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200251076892-1.pdf,<page_1>\n3\nAmtsgericht Wiesbaden\nVom Gerich...,\n3\nAmtsgericht Wiesbaden\nVom Gericht auszuf...,...,NaN,False,NaN,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,NaN,False,NaN,NaN
3,18854889,28200321146908,2026-06-16 05:11:12.137124,Detected Slugs:\n\n 110114027755,1st Level (in after-court area)\nDetected Slug...,28200321146908-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200321146908-1.pdf,<page_1>\nSt.-Joseph-Str. 3\n93059 Regensburg\...,\nSt.-Joseph-Str. 3\n93059 Regensburg\nT. Pörn...,...,False,False,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
4,18854901,28200327610524,2026-06-16 05:13:04.686800,Detected Slugs:\n\n 179632575793,1st Level (in after-court area)\nDetected Slug...,28200327610524-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200327610524-1.pdf,<page_1>\nObergerichtsvollzieher Schön Gütlich...,\nObergerichtsvollzieher Schön Gütliche Erledi...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,18854746,28199977266076,2026-06-16 04:33:38.821115,Detected Slugs:\n\n Case file slug not dete...,Sonstige Nachgerichtliche Post - Scanned Brief...,28199977266076-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199977266076-1.pdf,<page_1>\nLiquandum Capital GmbH\n27. Mai 2026...,\nLiquandum Capital GmbH\n27. Mai 2026\nAmtsge...,...,False,False,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
1306,18855046,28200426431388,2026-06-16 05:27:41.332530,Detected Slugs:\n\n 135791591799,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200426431388-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200426431388-1.pdf,<page_1>\nBjörn Ellendt\nStraße am Hochwald 21...,\nBjörn Ellendt\nStraße am Hochwald 21\nOberge...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
1307,18855047,28200459659804,2026-06-16 05:28:07.094424,Detected Slugs:\n\n 127028559350,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200459659804-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200459659804-1.pdf,<page_1>\nOliver Schnitzer\nHelmholtzstraße 39...,\nOliver Schnitzer\nHelmholtzstraße 39\nOberge...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
1308,18855051,28200470768412,2026-06-16 05:28:46.581944,Detected Slugs:\n\n 130401562272,GVZ - Scanned Brief\nDetected Slugs:\n\n 13...,28200470768412-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200470768412-1.pdf,<page_1>\nTina Herrmann\nPostfach 10 12\nOberg...,\nTina Herrmann\nPostfach 10 12\nObergerichtsv...,...,False,False,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
1309,18855054,28200495348508,2026-06-16 05:29:08.747800,Detected Slugs:\n\n 192449854111,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28200495348508-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200495348508-1.pdf,<page_1>\nWOLFGANG RADHOFF\nBahnhofstr. 1a/Neb...,\nWOLFGANG RADHOFF\nBahnhofstr. 1a/Nebeneingan...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0

In [7]:
data.columns

Index(['zendesk_id', 'comment_id', 'created_at', 'body', 'content',
       'attachment_id', 'attachment_url', 's3_object_key',
       'text_with_page_markers', 'text',
       'egvp__aftercourt_classification_ladung',
       'aftercourt_classification_ladung__aftercourt_type',
       'aftercourt_classification_ladung__class_pred',
       'aftercourt_classification_ladung__class_prob',
       'aftercourt_classification_ladung__debtor_name',
       'aftercourt_classification_ladung__judicial_summon_date',
       'aftercourt_classification_ladung__slug',
       'egvp__aftercourt_classification_pfub',
       'aftercourt_classification_pfub__aftercourt_type',
       'aftercourt_classification_pfub__class_pred',
       'aftercourt_classification_pfub__class_prob', 'meta_has_page_markers',
       'egvp__pfub_erlass_egvp', 'pfub_erlass_egvp__aftercourt_type',
       'pfub_erlass_egvp__class_pred', 'pfub_erlass_egvp__creditor_name',
       'pfub_erlass_egvp__debtor_name', 'pfub_erlass_egvp__is_invoice_inside',
       'pfub_erlass_egvp__is_pfub', 'pfub_erlass_egvp__slug',
       'egvp__invoice_detection_egvp', 'invoice_detection_egvp__end_page',
       'invoice_detection_egvp__is_invoice_inside',
       'invoice_detection_egvp__start_page', 'egvp__egvp_standalone_invoice',
       'egvp_standalone_invoice__invoice', 'egvp_standalone_invoice__reason',
       'egvp_standalone_invoice__slug', 'egvp__vermogenverzeichnis_egvp',
       'vermogenverzeichnis_egvp__aftercourt_type',
       'vermogenverzeichnis_egvp__class_pred',
       'vermogenverzeichnis_egvp__end_page',
       'vermogenverzeichnis_egvp__is_invoice_inside',
       'vermogenverzeichnis_egvp__is_va',
       'vermogenverzeichnis_egvp__start_page', 'egvp__drittauskunft_egvp',
       'drittauskunft_egvp__aftercourt_type', 'drittauskunft_egvp__class_pred',
       'drittauskunft_egvp__end_page', 'drittauskunft_egvp__is_dritt',
       'drittauskunft_egvp__is_invoice_inside',
       'drittauskunft_egvp__start_page'],
      dtype='object')

In [8]:
data.vermogenverzeichnis_egvp__class_pred

vermogenverzeichnis_egvp__class_pred
False    1236
True       74
Name: count, dtype: int64

In [13]:
# vermogenverzeichnis without invoice

sample_va_no_invoice = data[(data["vermogenverzeichnis_egvp__class_pred"] == True) & (data["vermogenverzeichnis_egvp__is_invoice_inside"] == False)]
sample_va_no_invoice

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
458,18854622,28199939803676,2026-06-16 04:31:26.274339,Detected Slugs:\n\n 191179460982,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28199939803676-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199939803676-1.pdf,<page_1>\nObergerichtsvollzieherin D. Donner\n...,\nObergerichtsvollzieherin D. Donner\nDienstko...,...,False,True,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
638,18854133,28199334466972,2026-06-16 03:14:41.521475,Detected Slugs:\n\n 436818146145\n 10386...,Insolvenz - Scanned Brief\nDetected Slugs:\n\n...,28199334466972-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199334466972-1.pdf,<page_1>\n31 S 133/26z 11\n(Bitte in allen Ein...,\n31 S 133/26z 11\n(Bitte in allen Eingaben an...,...,False,True,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
985,18857497,28203949457948,2026-06-16 08:08:00.557089,Detected Slugs:\n\n 196968318028,Vermögensverzeichnis/Drittauskunft\nDetected S...,28203949457948-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203949457948-1.pdf,<page_1>\nStefan Köppler\nObergerichtsvollzieh...,\nStefan Köppler\nObergerichtsvollzieher\nbeim...,...,False,True,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0

In [16]:
# vermogenverzeichnis with invoice

sample_va_with_invoice = data[(data["vermogenverzeichnis_egvp__class_pred"] == True) & (data["vermogenverzeichnis_egvp__is_invoice_inside"] == True)].sample(15)
sample_va_with_invoice

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
1102,18858137,28205077763740,2026-06-16 08:46:05.353722,Detected Slugs:\n\n 193006150307,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205077763740-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205077763740-1.pdf,<page_1>\nObergerichtsvollzieher am AG Sulinge...,\nObergerichtsvollzieher am AG Sulingen\nPosta...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
596,18855406,28200937858076,2026-06-16 06:06:01.711515,Detected Slugs:\n\n 110754858931,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200937858076-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200937858076-1.pdf,<page_1>\nObergerichtsvollzieher\nDavid Gabrie...,\nObergerichtsvollzieher\nDavid Gabriel\nBüroa...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
896,18856321,28202103768348,2026-06-16 07:04:19.844299,Detected Slugs:\n\n 125637016242,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202103768348-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202103768348-1.pdf,"<page_1>\nMustafa Assaf\nLiebigstraße 2-20, Ha...","\nMustafa Assaf\nLiebigstraße 2-20, Haus 12, 3...",...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
1113,18858320,28205438551836,2026-06-16 08:58:06.815642,Detected Slugs:\n\n 197501703262,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205438551836-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205438551836-1.pdf,<page_1>\nVerhülsdonk\n24306 Plön\nObergericht...,\nVerhülsdonk\n24306 Plön\nObergerichtsvollzie...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
1092,18858060,28204954863004,2026-06-16 08:41:48.881961,Detected Slugs:\n\n 171510138141,Vermögensverzeichnis/Drittauskunft\nDetected S...,28204954863004-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204954863004-1.pdf,<page_1>\nHoffmann\nPOSTANSCHRIFT: Postfach 18...,\nHoffmann\nPOSTANSCHRIFT: Postfach 18\nGerich...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
779,18855037,28200433566108,2026-06-16 05:26:25.618162,Detected Slugs:\n\n 181343183412,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200433566108-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200433566108-1.pdf,<page_1>\nObergerichtsvollzieher\nBüroanschrif...,\nObergerichtsvollzieher\nBüroanschrift\nJoach...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,1.0
449,18854610,28199874311580,2026-06-16 04:31:14.995548,Detected Slugs:\n\n 922595013000348\n 19...,GVZ - Scanned Brief\nDetected Slugs:\n\n 92...,28199874311580-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199874311580-1.pdf,<page_1>\nObergerichtsvollzieher\nAmtsgericht\...,\nObergerichtsvollzieher\nAmtsgericht\nHildesh...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,1.0
772,18854906,28200353826716,2026-06-16 05:13:47.416223,Detected Slugs:\n\n 195057671685,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200353826716-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200353826716-1.pdf,<page_1>\nMarco Jakobs\nKölner Straße 91\nGeri...,\nMarco Jakobs\nKölner Straße 91\nGerichtsvoll...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
667,18854423,28199919718684,2026-06-16 04:27:26.130599,Detected Slugs:\n\n 015123983879\n 19502...,GVZ - Scanned Brief\nDetected Slugs:\n\n 01...,28199919718684-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199919718684-1.pdf,<page_1>\nObergerichtsvollzieher Rainer Bartsc...,\nObergerichtsvollzieher Rainer Bartsch\nAmtsg...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
986,18857225,28203650589980,2026-06-16 08:00:06.915316,Detected Slugs:\n\n 195572631578,Vermögensverzeichnis/Drittauskunft\nDetected S...,28203650589980-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203650589980-1.pdf,<page_1>\nObergerichtsvollzieher\nPostanschrif...,\nObergerichtsvollzieher\nPostanschrift\nMarku...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
1158,18858407,28205714068508,2026-06-16 09:04:35.567825,Detected Slugs:\n\n 183671610271,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205714068508-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205714068508-1.pdf,<page_1>\nYvonne Kramp\nDettumer Straße 12\nOb...,\nYvonne Kramp\nDettumer Straße 12\nObergerich...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
38,18855520,28201191871900,2026-06-16 06:18:56.412653,Detected Slugs:\n\n 181522533866,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201191871900-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201191871900-1.pdf,"<page_1>\nMarkus Herzog\nReichenaustraße 11, 3...","\nMarkus Herzog\nReichenaustraße 11, 3. OG.\nG...",...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
59,18855557,28201240094364,2026-06-16 06:22:42.506672,Detected Slugs:\n\n 198084691155,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201240094364-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201240094364-1.pdf,<page_1>\nChristoph Sowa\nPostfach 24 05\nGeri...,\nChristoph Sowa\nPostfach 24 05\nGerichtsvoll...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
628,18854418,28199857391772,2026-06-16 04:27:20.043587,Detected Slugs:\n\n 616609080000065\n 40...,GVZ - Scanned Brief\nDetected Slugs:\n\n 61...,28199857391772-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199857391772-1.pdf,<page_1>\nKaiserstr. 50 (Hintereingang)\n76437...,\nKaiserstr. 50 (Hintereingang)\n76437 Rastatt...,...,True,True,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
96,18854495,28199888543004,2026-06-16 04:28:39.608948,Detected Slugs:\n\n 196959790391\n 63100...,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28199888543004-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199888543004-1.pdf,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,\nObergerichtsvollzieherin\nAmtsgericht: Darms...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0

In [34]:
# drittauskunft without invoice
sample_da_no_invoice = data[(data["drittauskunft_egvp__class_pred"] == True) & (data["drittauskunft_egvp__is_invoice_inside"] == False)].sample(15)
sample_da_no_invoice

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
1088,18858033,28204871714716,2026-06-16 08:39:31.218140,Detected Slugs:\n\n 195856728496,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28204871714716-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204871714716-1.pdf,<page_1>\nGerichtsvollzieher\nHauptstraße 72\n...,\nGerichtsvollzieher\nHauptstraße 72\nDustin R...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
480,18854658,28199941049500,2026-06-16 04:32:09.981488,Detected Slugs:\n\n 406145005010004\n 14...,GVZ - Scanned Brief\nDetected Slugs:\n\n 40...,28199941049500-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199941049500-1.pdf,<page_1>\nGerichtsvollzieher Ingo Herget\nAmts...,\nGerichtsvollzieher Ingo Herget\nAmtsgericht ...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
935,18856763,28202872377116,2026-06-16 07:30:12.610226,Detected Slugs:\n\n 156191864750,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202872377116-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202872377116-1.pdf,"<page_1>\nOliver Thihatmar\nWindstraße 1, 4856...","\nOliver Thihatmar\nWindstraße 1, 48565 Steinf...",...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
843,18855809,28201587694108,2026-06-16 06:40:07.187114,Detected Slugs:\n\n 140022717825,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201587694108-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201587694108-1.pdf,<page_1>\nVEIT FITZLER\nKippingstraße 32\n2014...,\nVEIT FITZLER\nKippingstraße 32\n20144 Hambur...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
975,18857263,28203748445852,2026-06-16 08:02:31.938704,Detected Slugs:\n\n 194564108281,Vermögensverzeichnis/Drittauskunft\nDetected S...,28203748445852-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203748445852-1.pdf,<page_1>\nS. Molzow\nHellersdorfer Weg 35\nObe...,\nS. Molzow\nHellersdorfer Weg 35\nObergericht...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
850,18855914,28201661048092,2026-06-16 06:46:21.893148,Detected Slugs:\n\n 189363472698,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201661048092-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201661048092-1.pdf,<page_1>\nObergerichtsvollzieherin\nFlurstraße...,\nObergerichtsvollzieherin\nFlurstraße 12 (Hin...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
954,18856860,28203057612444,2026-06-16 07:37:14.011278,Detected Slugs:\n\n 194836230772,Vermögensverzeichnis/Drittauskunft\nDetected S...,28203057612444-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203057612444-1.pdf,<page_1>\nNina Ruppert\nKarlstraße 29\nGericht...,\nNina Ruppert\nKarlstraße 29\nGerichtsvollzie...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
1093,18858068,28204957396380,2026-06-16 08:43:28.089382,Detected Slugs:\n\n 127079326550,Vermögensverzeichnis/Drittauskunft\nDetected S...,28204957396380-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204957396380-1.pdf,<page_1>\nBundeszentralamt\nfür Steuern\nPOSTA...,\nBundeszentralamt\nfür Steuern\nPOSTANSCHRIFT...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
1122,18858215,28205189951516,2026-06-16 08:50:01.705305,Detected Slugs:\n\n 141225194234,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205189951516-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205189951516-1.pdf,<page_1>\nJasmin Schauer\nAm Neuwalzwerk 3\nOb...,\nJasmin Schauer\nAm Neuwalzwerk 3\nObergerich...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
254,18853991,28199306850076,2026-06-16 03:12:25.792180,Detected Slugs:\n\n 121501712099,Insolvenz - Scanned Brief\nDetected Slugs:\n\n...,28199306850076-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199306850076-1.pdf,<page_1>\nWEILAND\nRECHTSANWÄLTE\nHAMBURG PARI...,\nWEILAND\nRECHTSANWÄLTE\nHAMBURG PARIS STUTTG...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
909,18856414,28202274664860,2026-06-16 07:08:36.581165,Detected Slugs:,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202274664860-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202274664860-1.pdf,<page_1>\nGerichtsvollzieherin Bez\nbeim Amtsg...,\nGerichtsvollzieherin Bez\nbeim Amtsgericht R...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
7,18855311,28200739904412,2026-06-16 05:55:02.079407,Detected Slugs:\n\n 183800486007,Vermögensverzeichnis/Drittauskunft\nDetected S...,28200739904412-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200739904412-1.pdf,<page_1>\nPestalozzistraße 6\n02826 Görlitz\nT...,\nPestalozzistraße 6\n02826 Görlitz\nTel. 0358...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
1138,18858302,28205411730844,2026-06-16 08:56:36.443770,Detected Slugs:\n\n 170631680056,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205411730844-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205411730844-1.pdf,<page_1>\nAnlage zu GZ: St Il 4 - S 0229a KEVI...,\nAnlage zu GZ: St Il 4 - S 0229a KEVIZZ 13419...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
718,18854662,28199896930204,2026-06-16 04:32:14.212828,Detected Slugs:\n\n 189527648050,GVZ - Scanned Brief\nDetected Slugs:\n\n 18...,28199896930204-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199896930204-1.pdf,<page_1>\nGerichtsvollzieher beim Amtsgericht ...,\nGerichtsvollzieher beim Amtsgericht Achern\n...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0
1025,18857681,28204284733084,2026-06-16 08:18:27.964161,Detected Slugs:\n\n 186407468914,Vermögensverzeichnis/Drittauskunft\nDetected S...,28204284733084-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204284733084-1.pdf,<page_1>\nObergerichtsvollzieherin\nKäthe-Koll...,\nObergerichtsvollzieherin\nKäthe-Kollwitz-Str...,...,False,False,-1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,-1.0,True,False,-1.0

In [18]:
# drittauskunft with invoice
sample_da_with_invoice = data[(data["drittauskunft_egvp__class_pred"] == True) & (data["drittauskunft_egvp__is_invoice_inside"] == True)].sample(15)
sample_da_with_invoice

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
900,18856457,28202304912284,2026-06-16 07:10:45.996731,Detected Slugs:\n\n 172807571861,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202304912284-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202304912284-1.pdf,<page_1>\nObergerichtsvollzieherin Dingel\nAmt...,\nObergerichtsvollzieherin Dingel\nAmtsgericht...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
930,18856612,28202516550172,2026-06-16 07:18:44.094437,Detected Slugs:\n\n 130336553826,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202516550172-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202516550172-1.pdf,<page_1>\nObergerichtsvollzieherin K. Rippich\...,\nObergerichtsvollzieherin K. Rippich\nDienstk...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
992,18857347,28203872007068,2026-06-16 08:06:03.673682,Detected Slugs:\n\n 156116413899,Vermögensverzeichnis/Drittauskunft\nDetected S...,28203872007068-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203872007068-1.pdf,<page_1>\nS. Horch\nbei dem Amtsgericht Herfor...,\nS. Horch\nbei dem Amtsgericht Herford\nOberg...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
804,18855532,28201195161628,2026-06-16 06:20:04.214398,Detected Slugs:\n\n 164800649273,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201195161628-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201195161628-1.pdf,<page_1>\nObergerichtsvollzieher Bernd Zölitz\...,\nObergerichtsvollzieher Bernd Zölitz\nDienstk...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
1057,18857837,28204519096604,2026-06-16 08:27:35.340963,Detected Slugs:\n\n 170514620245,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,28204519096604-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204519096604-1.pdf,<page_1>\nSven Neth\nLandrat-Christians-Str. 6...,\nSven Neth\nLandrat-Christians-Str. 67\nGeric...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
1132,18858271,28205345969052,2026-06-16 08:54:15.301557,Detected Slugs:\n\n 181462839125,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205345969052-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205345969052-1.pdf,<page_1>\nOliver Zielasko\nDortmunder Straße 1...,\nOliver Zielasko\nDortmunder Straße 14\nOberg...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
487,18854676,28199975137052,2026-06-16 04:32:25.789447,Detected Slugs:\n\n 183645506407\n 79217...,GVZ - Scanned Brief\nDetected Slugs:\n\n 18...,28199975137052-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199975137052-1.pdf,<page_1>\nGartenstr. 10\n24896 Treia\nTel. 015...,\nGartenstr. 10\n24896 Treia\nTel. 0151-634586...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,3.0,True,True,1.0
1043,18857821,28204475800732,2026-06-16 08:26:16.457489,Detected Slugs:\n\n 194916197057,Vermögensverzeichnis/Drittauskunft\nDetected S...,28204475800732-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204475800732-1.pdf,<page_1>\nObergerichtsvollzieher\nAmtsgericht:...,\nObergerichtsvollzieher\nAmtsgericht: Benshei...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
594,18854753,28199928479772,2026-06-16 04:33:44.846848,Detected Slugs:\n\n 068819627827\n 17220...,GVZ - Scanned Brief\nDetected Slugs:\n\n 06...,28199928479772-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199928479772-1.pdf,<page_1>\nInformationen zur DSGVO (insbes. Art...,"\nInformationen zur DSGVO (insbes. Art. 13,14)...",...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
96,18854495,28199888543004,2026-06-16 04:28:39.608948,Detected Slugs:\n\n 196959790391\n 63100...,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28199888543004-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199888543004-1.pdf,<page_1>\nObergerichtsvollzieherin\nAmtsgerich...,\nObergerichtsvollzieherin\nAmtsgericht: Darms...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
1041,18857801,28204482979868,2026-06-16 08:24:55.593523,Detected Slugs:\n\n 194901518515,Vermögensverzeichnis/Drittauskunft\nDetected S...,28204482979868-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204482979868-1.pdf,<page_1>\nDaniel Rüdiger\nDortmunder Straße 14...,\nDaniel Rüdiger\nDortmunder Straße 14\nGerich...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
825,18855714,28201507573788,2026-06-16 06:35:17.932738,Detected Slugs:\n\n 134125918224,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201507573788-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201507573788-1.pdf,<page_1>\nGerichtsvollzieher\nOtto-Lilienthal-...,\nGerichtsvollzieher\nOtto-Lilienthal-Straße 6...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
928,18856580,28202509839516,2026-06-16 07:16:58.775767,Detected Slugs:\n\n 192800047594,Vermögensverzeichnis/Drittauskunft\nDetected S...,28202509839516-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202509839516-1.pdf,<page_1>\nHubertus Kohlrautz\nAlfred-Delp-Weg ...,\nHubertus Kohlrautz\nAlfred-Delp-Weg 2\nOberg...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,2.0,True,True,1.0
836,18855816,28201589124252,2026-06-16 06:40:33.671054,Detected Slugs:\n\n 160908473194,Vermögensverzeichnis/Drittauskunft\nDetected S...,28201589124252-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201589124252-1.pdf,<page_1>\nD. Lindner\nRomain-Rolland-Str. 137\...,\nD. Lindner\nRomain-Rolland-Str. 137\nOberger...,...,True,False,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0
1153,18858384,28205650317724,2026-06-16 09:03:34.897692,Detected Slugs:\n\n 195057412205,Vermögensverzeichnis/Drittauskunft\nDetected S...,28205650317724-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205650317724-1.pdf,<page_1>\nDirk Förster\nMeißering 9\n29693 Hod...,\nDirk Förster\nMeißering 9\n29693 Hodenhagen\...,...,True,True,1.0,"{""is_dritt"": true, ""class_pred"": true, ""afterc...",drittauskunft,True,1.0,True,True,1.0

In [19]:
# standalone egvp
data.columns

Index(['zendesk_id', 'comment_id', 'created_at', 'body', 'content',
       'attachment_id', 'attachment_url', 's3_object_key',
       'text_with_page_markers', 'text',
       'egvp__aftercourt_classification_ladung',
       'aftercourt_classification_ladung__aftercourt_type',
       'aftercourt_classification_ladung__class_pred',
       'aftercourt_classification_ladung__class_prob',
       'aftercourt_classification_ladung__debtor_name',
       'aftercourt_classification_ladung__judicial_summon_date',
       'aftercourt_classification_ladung__slug',
       'egvp__aftercourt_classification_pfub',
       'aftercourt_classification_pfub__aftercourt_type',
       'aftercourt_classification_pfub__class_pred',
       'aftercourt_classification_pfub__class_prob', 'meta_has_page_markers',
       'egvp__pfub_erlass_egvp', 'pfub_erlass_egvp__aftercourt_type',
       'pfub_erlass_egvp__class_pred', 'pfub_erlass_egvp__creditor_name',
       'pfub_erlass_egvp__debtor_name', 'pfub_erlass_egvp__is_invoice_inside',
       'pfub_erlass_egvp__is_pfub', 'pfub_erlass_egvp__slug',
       'egvp__invoice_detection_egvp', 'invoice_detection_egvp__end_page',
       'invoice_detection_egvp__is_invoice_inside',
       'invoice_detection_egvp__start_page', 'egvp__egvp_standalone_invoice',
       'egvp_standalone_invoice__invoice', 'egvp_standalone_invoice__reason',
       'egvp_standalone_invoice__slug', 'egvp__vermogenverzeichnis_egvp',
       'vermogenverzeichnis_egvp__aftercourt_type',
       'vermogenverzeichnis_egvp__class_pred',
       'vermogenverzeichnis_egvp__end_page',
       'vermogenverzeichnis_egvp__is_invoice_inside',
       'vermogenverzeichnis_egvp__is_va',
       'vermogenverzeichnis_egvp__start_page', 'egvp__drittauskunft_egvp',
       'drittauskunft_egvp__aftercourt_type', 'drittauskunft_egvp__class_pred',
       'drittauskunft_egvp__end_page', 'drittauskunft_egvp__is_dritt',
       'drittauskunft_egvp__is_invoice_inside',
       'drittauskunft_egvp__start_page'],
      dtype='object')

In [20]:
data.egvp_standalone_invoice__reason.value_counts()

egvp_standalone_invoice__reason
not_invoice        700
multiple_docs      460
must_pay           146
do_not_transfer      2
Name: count, dtype: int64

In [27]:
egvp_standalone_invoice = data[(data["egvp_standalone_invoice__reason"] == "must_pay")]
egvp_standalone_invoice = egvp_standalone_invoice[egvp_standalone_invoice['egvp_standalone_invoice__invoice']==True]
egvp_standalone_invoice_sample = egvp_standalone_invoice.sample(15)

In [30]:
egvp_standalone_invoice_sample

,zendesk_id,comment_id,created_at,body,content,attachment_id,attachment_url,s3_object_key,text_with_page_markers,text,...,vermogenverzeichnis_egvp__is_invoice_inside,vermogenverzeichnis_egvp__is_va,vermogenverzeichnis_egvp__start_page,egvp__drittauskunft_egvp,drittauskunft_egvp__aftercourt_type,drittauskunft_egvp__class_pred,drittauskunft_egvp__end_page,drittauskunft_egvp__is_dritt,drittauskunft_egvp__is_invoice_inside,drittauskunft_egvp__start_page
1286,18854528,28199889704732,2026-06-16 04:29:47.467905,Detected Slugs:\n\n 605262404908\n 16662...,Sonstige Nachgerichtliche Post - Scanned Brief...,28199889704732-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199889704732-1.pdf,"<page_1>\nLANDESJUSTIZKASSE BAMBERG, Heiliggra...","\nLANDESJUSTIZKASSE BAMBERG, Heiliggrabstraße ...",...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
883,18856237,28201989244956,2026-06-16 06:59:27.209044,Detected Slugs:\n\n 159673321653,1st Level (in after-court area)\nDetected Slug...,28201989244956-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201989244956-1.pdf,<page_1>\nHelvi Lorenz\nHellersdorfer Weg 35\n...,\nHelvi Lorenz\nHellersdorfer Weg 35\nObergeri...,...,False,False,-1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,-1.0,False,False,-1.0
89,18854532,28199871588380,2026-06-16 04:29:48.045685,Detected Slugs:\n\n 626262454109\n 19586...,Sonstige Nachgerichtliche Post - Scanned Brief...,28199871588380-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199871588380-1.pdf,"<page_1>\nLANDESJUSTIZKASSE BAMBERG, Heiliggra...","\nLANDESJUSTIZKASSE BAMBERG, Heiliggrabstraße ...",...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
1118,18858214,28205188538908,2026-06-16 08:49:45.548870,Detected Slugs:\n\n 196133324612,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28205188538908-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28205188538908-1.pdf,<page_1>\nGrünstraße 61\nMICHAEL ARNDT\n17309 ...,\nGrünstraße 61\nMICHAEL ARNDT\n17309 Pasewalk...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
780,18855220,28200635453724,2026-06-16 05:44:21.685579,Detected Slugs:\n\n 110004884943,1st Level (in after-court area)\nDetected Slug...,28200635453724-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200635453724-1.pdf,<page_1>\nGerichtsvollzieherin\nKatharinenstra...,\nGerichtsvollzieherin\nKatharinenstraße 6\nS....,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
874,18856272,28202013902620,2026-06-16 07:00:56.307808,Detected Slugs:\n\n 118790325799,GVZ - Scanned Brief\nDetected Slugs:\n\n 11...,28202013902620-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28202013902620-1.pdf,<page_1>\nObergerichtsvollzieher\nErkrather St...,"\nObergerichtsvollzieher\nErkrather Str. 65, 4...",...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,1.0
859,18855996,28201830168092,2026-06-16 06:51:47.292561,Detected Slugs:\n\n 131323913635,GVZ - Scanned Brief\nDetected Slugs:\n\n 13...,28201830168092-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28201830168092-1.pdf,<page_1>\nL. Rasilier\nBismarckstr. 11\nGerich...,\nL. Rasilier\nBismarckstr. 11\nGerichtsvollzi...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
950,18856952,28203194205340,2026-06-16 07:43:20.307144,Detected Slugs:,GVZ - Scanned Brief\nDetected Slugs:,28203194205340-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203194205340-1.pdf,<page_1>\nObergerichtsvollzieher\nPostfach 18 ...,\nObergerichtsvollzieher\nPostfach 18 44\nWetz...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
23,18854881,28200272211612,2026-06-16 05:09:45.316290,Detected Slugs:\n\n 183595858501,GVZ - Scanned Brief\nDetected Slugs:\n\n 18...,28200272211612-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200272211612-1.pdf,<page_1>\nÖmer Seyis\nBahnhofstraße 52\nGerich...,\nÖmer Seyis\nBahnhofstraße 52\nGerichtsvollzi...,...,True,False,2.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,2.0
726,18854832,28200159412380,2026-06-16 05:01:00.472578,Detected Slugs:\n\n 149153800912,1st Level (in after-court area)\nDetected Slug...,28200159412380-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200159412380-1.pdf,<page_1>\nHeike Montebaur\nAdelheidstraße 18\n...,\nHeike Montebaur\nAdelheidstraße 18\nObergeri...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
964,18857157,28203546034972,2026-06-16 07:55:45.548641,Detected Slugs:\n\n 127014383435,GVZ - Scanned Brief\nDetected Slugs:\n\n 12...,28203546034972-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28203546034972-1.pdf,<page_1>\nLehmkuhle 4\nH.J. HEYMING\n47533 Kle...,\nLehmkuhle 4\nH.J. HEYMING\n47533 Kleve\nGeri...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
494,18854686,28199943855900,2026-06-16 04:32:37.129291,Detected Slugs:\n\n 871260163287\n 19499...,Sonstige Nachgerichtliche Post - Scanned Brief...,28199943855900-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199943855900-1.pdf,"<page_1>\nLANDESJUSTIZKASSE BAMBERG, Heiliggra...","\nLANDESJUSTIZKASSE BAMBERG, Heiliggrabstraße ...",...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
539,18854700,28199975859996,2026-06-16 04:32:52.047171,Detected Slugs:\n\n 544404003702134,GVZ - Scanned Brief\nDetected Slugs:\n\n 54...,28199975859996-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28199975859996-1.pdf,<page_1>\nObergerichtsvollzieher Reimund Gappa...,\nObergerichtsvollzieher Reimund Gappa\nDienst...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0
1071,18857949,28204792376476,2026-06-16 08:35:32.277341,Detected Slugs:\n\n 171120514772,GVZ - Scanned Brief\nDetected Slugs:\n\n 17...,28204792376476-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28204792376476-1.pdf,<page_1>\nObergerichtsvollzieherin\nSandra Est...,\nObergerichtsvollzieherin\nSandra Ester\nJahn...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,2.0,False,True,1.0
57,18855005,28200397131932,2026-06-16 05:20:21.971156,Detected Slugs:\n\n 194249191660,GVZ - Scanned Brief\nDetected Slugs:\n\n 19...,28200397131932-1,https://support.pairfinance.de/attachments/tok...,ocr_source_files/letters/28200397131932-1.pdf,<page_1>\nIRMGARD ALLGÖWER\nHiltenburgstraße 1...,\nIRMGARD ALLGÖWER\nHiltenburgstraße 11\n73312...,...,True,False,1.0,"{""is_dritt"": false, ""class_pred"": false, ""afte...",NaN,False,1.0,False,True,1.0

In [ ]:
download_path = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check"


# dfs = [sample_va_no_invoice, sample_va_with_invoice, sample_da_no_invoice, sample_da_with_invoice, egvp_standalone_invoice_sample]
# names = ["sample_va_no_invoice", "sample_va_with_invoice", "sample_da_no_invoice", "sample_da_with_invoice", "egvp_standalone_invoice_sample"]

In [35]:
dfs = [sample_da_no_invoice]
names = ["sample_da_no_invoice"]

In [36]:
import sys
import boto3
import os
sys.path.append('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation')
from utils.prod_utils import download_pdf_from_s3

session = boto3.Session(
    region_name="eu-central-1",
    profile_name="739275445236_DataScienceUser",
)
s3 = session.client("s3")

S3_BUCKET = "pair-email-classification"

for df, name in zip(dfs, names):
    group_dir = os.path.join(download_path, name)
    os.makedirs(group_dir, exist_ok=True)
    print(f"\n--- Downloading {len(df)} files into {group_dir} ---")
    for _, row in df.iterrows():
        try:
            download_pdf_from_s3(
                s3=s3,
                bucket_name=S3_BUCKET,
                object_key=row["s3_object_key"],
                download_dir=group_dir,
            )
        except Exception as e:
            print(f"  ❌ Failed for {row['s3_object_key']}: {e}")

--- Downloading 15 files into /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice ---
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28204871714716-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28199941049500-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28202872377116-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28201587694108-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28203748445852-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28201661048092-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28203057612444-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28204957396380-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28205189951516-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28199306850076-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28202274664860-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28200739904412-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28205411730844-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28199896930204-1.pdf
✅ PDF downloaded successfully: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp_letter_check/sample_da_no_invoice/28204284733084-1.pdf