In [1]:
from python_utilities.db_connection import DbConnection
import boto3
import json
import os
import pandas as pd
import ast

analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-07-06 15:30:24] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-07-06 15:30:25] - Found credentials in shared credentials file: ~/.aws/credentials

In [15]:
# egvp intents egvp_id = None -> zendesk-letter and zendesk-email data

temp start

In [2]:
from python_utilities.db_connection import DbConnection
import boto3
import json
import os
import pandas as pd
import ast

analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-07-06 15:30:27] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-07-06 15:30:27] - Found credentials in shared credentials file: ~/.aws/credentials

In [10]:
query = """
SELECT *
FROM llm_attachments_predictions lap
WHERE lap.created_at >= '2026-07-03'
AND (
    (type = 'drittauskunft_egvp' AND subtype='is_dritt' AND value = "'True'")
    OR (type = 'vermogenverzeichnis_egvp' AND subtype='is_va' AND value = "'True'")
    OR (type = 'egvp_standalone_invoice' AND value = "'True'")
)
"""
data = analytics_db.sql_to_df(query)

In [11]:
data

,id,created_at,model_name,type,subtype,value,attachment_id
0,12167952,2026-07-03 00:53:50,egvp_standalone_invoice,egvp_standalone_invoice,invoice,'True',70758299
1,12177274,2026-07-03 05:59:10,drittauskunft_egvp,drittauskunft_egvp,is_dritt,'True',70796006
2,12177350,2026-07-03 05:59:15,egvp_standalone_invoice,egvp_standalone_invoice,invoice,'True',70796007
3,12182805,2026-07-03 06:42:38,drittauskunft_egvp,drittauskunft_egvp,is_dritt,'True',70798131
4,12182860,2026-07-03 06:42:42,egvp_standalone_invoice,egvp_standalone_invoice,invoice,'True',70798130
...,...,...,...,...,...,...,...
252,12342908,2026-07-06 13:28:57,drittauskunft_egvp,drittauskunft_egvp,is_dritt,'True',71145614
253,12342930,2026-07-06 13:28:58,drittauskunft_egvp,drittauskunft_egvp,is_dritt,'True',71145645
254,12342998,2026-07-06 13:29:02,vermogenverzeichnis_egvp,vermogenverzeichnis_egvp,is_va,'True',71145571
255,12343119,2026-07-06 13:29:10,drittauskunft_egvp,drittauskunft_egvp,is_dritt,'True',71145613
256,12343210,2026-07-06 13:29:16,vermogenverzeichnis_egvp,vermogenverzeichnis_egvp,is_va,'True',71145643

In [26]:
import sys
sys.path.append('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation')
from utils.prod_utils import pivot_attachment_predictions, get_data_by_attachment_id

In [14]:
pred = pivot_attachment_predictions(data)

In [15]:
pred

,attachment_id,drittauskunft_egvp_is_dritt,egvp_standalone_invoice_invoice,vermogenverzeichnis_egvp_is_va
0,70758299,none,True,none
1,70796006,True,none,none
2,70796007,none,True,none
3,70798130,none,True,none
4,70798131,True,none,none
...,...,...,...,...
245,71145644,none,True,none
246,71145645,True,none,none
247,71145657,none,True,none
248,71145658,True,none,none
249,71145659,none,True,none

In [24]:
cols = ['drittauskunft_egvp_is_dritt', 'vermogenverzeichnis_egvp_is_va', 'egvp_standalone_invoice_invoice']

send_dfs = []
for col in cols:
    subset = pred[pred[col] == 'True']
    subset_sample = subset.sample(n=15, random_state=42)
    send_dfs.append(subset_sample)
    
final_df = pd.concat(send_dfs)

In [ ]:
from python_utilities.db_connection import DbConnection
import boto3
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
# Create session with specific profile
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

In [27]:
download_dir = "/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send"

In [33]:
for df_name, df in zip(cols, send_dfs):
    for attachment_id in df['attachment_id']:
        download_full_path = os.path.join(download_dir, df_name)
        os.makedirs(download_full_path, exist_ok=True)
        get_data_by_attachment_id(attachment_id, analytics_db, s3, pdf_download=True, pdf_download_dir=download_full_path)

====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   71021096
File Name:       71021096_Dokumente_58326_04072026_183056-signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-04/egvp_id_404181/71021096_Dokumente_58326_04072026_183056-signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/92183cad7d376678e77118d16990ecc844d632f9d81c2fd7ff5b2eab027975b0.json
│
│ 📊 Text Length:  3890 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/71021096.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.08'
│    Prob Pfub:                '0.03'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '2'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70800428
File Name:       70800428_DRII-016926_BZSt_Ergebnis_1_29_06_2026.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_402397/70800428_DRII-016926_BZSt_Ergebnis_1_29_06_2026.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/b8221eb9a0794d8661063fd2a98de719f9d84ca3d0b004661aa6b9640d7d4b34.json
│
│ 📊 Text Length:  3624 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70800428.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.06'
│    Prob Pfub:                '0.03'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70813162
File Name:       70813162_Dokumente_220926_03072026_123103.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_403661/70813162_Dokumente_220926_03072026_123103.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/0a130969578da3e4bbd28e0e89ac585cb8c77b68f7eaf0bfc781c3f67df4dfde.json
│
│ 📊 Text Length:  3709 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70813162.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.1'
│    Prob Pfub:                '0.04'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '1'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70818146
File Name:       70818146_DR_II_901_26_Information_Kontenabrufersuchen_2-signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_404109/70818146_DR_II_901_26_Information_Kontenabrufersuchen_2-signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/815e877fedd89b4c25a522448e6b72c27eae8f618ffaa8da72766c8236a0afb4.json
│
│ 📊 Text Length:  3591 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70818146.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.1'
│    Prob Pfub:                '0.03'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70805393
File Name:       70805393_Dokumente_160226_03072026_085935_signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_402927/70805393_Dokumente_160226_03072026_085935_signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/f7bb372f9b2c38cd904150ebee4348e099cdd210dd151bb51eb2d0e3feae32cf.json
│
│ 📊 Text Length:  7554 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70805393.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.09'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '1'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70814740
File Name:       70814740_DR_II_975_26_08a_An_Gl_Mitt_Ergebnis_BZSt.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_403973/70814740_DR_II_975_26_08a_An_Gl_Mitt_Ergebnis_BZSt.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/37193b4bf662ec1b547899aa3ac7494b2ca26e3632992974dd24d158b8a78f07.json
│
│ 📊 Text Length:  5374 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70814740.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.03'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '2'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70818903
File Name:       70818903_Dokumente_188026_03072026_210113.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_404123/70818903_Dokumente_188026_03072026_210113.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/26e36e0f269a7069f7ea4bfdd1dd2cef5da40bef30c1622042ad7797267da6df.json
│
│ 📊 Text Length:  14705 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70818903.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.01'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '1'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70817759
File Name:       70817759_Dokumente_96326_03072026_165651_signed.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_404092/70817759_Dokumente_96326_03072026_165651_signed.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/90ae3012280d635bea20839fb315b4492af745647f7e98abb5b95287ad609863.json
│
│ 📊 Text Length:  15280 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70817759.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.01'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '1'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70814787
File Name:       70814787_7_DR_II_599_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_403984/70814787_7_DR_II_599_26_An_Gl_Mitt_Ergebnis_Drittauskunft.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/de715ebf3a82be25fa43dde8ac84ce18bd831e4a92961b20aea3e5af3f9d092c.json
│
│ 📊 Text Length:  5731 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70814787.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.09'
│    Prob Pfub:                '0.07'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70805402
File Name:       70805402_DR_II_602_26_aus_Schreibmaschine.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_402928/70805402_DR_II_602_26_aus_Schreibmaschine.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/4ac17305b4f23533ed21717bbc06e299f844ec80670c6c69ba912ca73359386a.json
│
│ 📊 Text Length:  3561 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70805402.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.06'
│    Prob Pfub:                '0.1'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '1'
│    End Page:          '2'
│    Is Invoice Inside: 'True'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'True'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   71095289
File Name:       71095289_DR_II_213_26_Information_Kontenabrufersuchen.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-05/egvp_id_404236/71095289_DR_II_213_26_Information_Kontenabrufersuchen.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/113e6423e42a7e5fe85cfd064ea8b97cf87c12e5e85f473fd3b67728b17138fc.json
│
│ 📊 Text Length:  3037 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/71095289.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.07'
│    Prob Pfub:                '0.03'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70813072
File Name:       70813072_636.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_403645/70813072_636.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/ef403a285c4b31bcbc07344624aea7817ae745259f9459e9108477e291d4867d.json
│
│ 📊 Text Length:  1071 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70813072.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.02'
│    Prob Pfub:                '0.0'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   71094018
File Name:       71094018_MarkoMartin.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-05/egvp_id_404196/71094018_MarkoMartin.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/c7dc941af5a3bdd9898f0bbb469e32ca5a34d875ffc58bdd6b9df8b36ff28471.json
│
│ 📊 Text Length:  4115 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/71094018.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.08'
│    Prob Pfub:                '0.02'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   71145645
File Name:       71145645_DR_II_838_26_Information_Kontenabrufersuchen_2.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-06/egvp_id_404318/71145645_DR_II_838_26_Information_Kontenabrufersuchen_2.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/e8a4909433cb91998f9ad59260bc4f7069e9345d1d85a5a9d6a6e37831b6bea3.json
│
│ 📊 Text Length:  436 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/71145645.pdf
│
│ 🤖 PREDICTIONS:
│    ⚠️  NOT LADUNG OR PFUB!
│    Prob Ladung:              '0.06'
│    Prob Pfub:                '0.01'
│    Prob Vermogenverzeichnis: N/A
│    — invoice_detection_egvp —
│    Start Page:        '-1'
│    End Page:          '-1'
│    Is Invoice Inside: 'False'
│    — pfub_erlass_egvp —
│    Is Pfub:           'False'
│    Is Invoice Inside: 'False'
└──────────────────────────────────────────────────────────────────────────────────────────────────


====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   70807828
File Name:       70807828_DR_II_460_26_An_Gl_Nachricht_HBAntrag.PDF
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-07-03/egvp_id_403354/70807828_DR_II_460_26_An_Gl_Nachricht_HBAntrag.PDF
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/a1c323dc834f3c2d813c6b431b1f907c16719cf0f9604473941f49038fd2dcc2.json
│
│ 📊 Text Length:  6095 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/send/drittauskunft_egvp_is_dritt/70807828.pdf
│
│ 🤖 PREDICTIONS:

temp end

In [16]:
query = """
SELECT *
FROM egvp_intents ei
WHERE ei.egvp_id IS NULL
"""
data = analytics_db.sql_to_df(query)

In [18]:
data.shape

(4826, 11)

In [23]:
print(f"Date between : {data['created_at'].min().date()} - {data['created_at'].max().date()}")

Date between : 2026-06-15 - 2026-07-06

In [26]:
data.ready_for_automation.value_counts()

ready_for_automation
0    4696
1     130
Name: count, dtype: int64

In [28]:
rfa = data[data.ready_for_automation == True]
rfa

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at
0,39470,27432456-0da5-5c5e-8296-5fa101583f4e,28171800296348-1,None,2026-06-15 12:38:22,"[{""params"": {""slug"": ""196302948324"", ""debtor_n...",1,sent,0,egvp,2026-06-15 12:38:22
1,39472,208d0153-2109-56ed-8bd6-a261d66c494e,28172046035356-1,None,2026-06-15 14:08:45,"[{""params"": {""slug"": ""192298781407"", ""debtor_n...",1,sent,0,egvp,2026-06-15 14:08:45
2,39473,fe1d5a63-52e9-5802-a4d9-9f6a5411ad0c,28172638247964-1,None,2026-06-15 14:09:05,"[{""params"": {""slug"": ""177394173211"", ""debtor_n...",1,sent,0,egvp,2026-06-15 14:09:05
3,39474,50e1fc04-9265-55ac-b909-d14ba17d9fe4,28172903254428-1,None,2026-06-15 14:09:39,"[{""params"": {""slug"": ""127103324753"", ""debtor_n...",1,sent,0,egvp,2026-06-15 14:09:39
4,40116,59b85aa0-8473-56a1-b90f-08307764baa2,28200468095516-1,None,2026-06-16 09:59:41,"[{""params"": {""slug"": ""181396289017"", ""debtor_n...",1,sent,0,egvp,2026-06-16 09:59:41
...,...,...,...,...,...,...,...,...,...,...,...
3858,52413,65517563-a47d-5b54-8493-ce3ccb879a41,28649994484252-1,None,2026-07-03 17:22:01,"[{""params"": {""slug"": ""198384884153"", ""debtor_n...",1,sent,0,egvp,2026-07-03 17:22:01
3859,52414,c5f054b4-88e0-56ae-a68f-2510f85ef06e,28650226046876-1,None,2026-07-03 17:22:01,"[{""params"": {""slug"": ""171923686264"", ""debtor_n...",1,sent,0,egvp,2026-07-03 17:22:01
3860,52415,7637653a-a869-5856-9f14-f995daa5578b,28649889336348-1,None,2026-07-03 17:22:08,"[{""params"": {""slug"": ""142339270670"", ""debtor_n...",1,sent,0,egvp,2026-07-03 17:22:08
3861,52416,5065e5df-e9cc-5663-8c10-4d138ed2df3f,28649972137116-1,None,2026-07-03 17:22:11,"[{""params"": {""slug"": ""165653326372"", ""debtor_n...",1,sent,0,egvp,2026-07-03 17:22:11
4660,53421,d38a71e1-5598-526d-a1ef-cbe34c296b47,28687935609884-1,None,2026-07-06 01:17:03,"[{""params"": {""slug"": ""194972152921"", ""debtor_n...",1,sent,0,egvp,2026-07-06 01:17:03

In [37]:
import json
rfa['intents'] = rfa['intents'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/747993890.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfa['intents'] = rfa['intents'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)

In [40]:
rfa['intents'].isnull().sum()

np.int64(0)

In [43]:
lengths = rfa['intents'].apply(lambda x: len(x) if isinstance(x, list) else 0)
lengths.value_counts()

intents
1    130
Name: count, dtype: int64

In [44]:
rfa['channel'] = rfa['intents'].apply(lambda x: x[0]['channel'] if isinstance(x, list) and len(x) > 0 and 'channel' in x[0] else None)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/1689248179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfa['channel'] = rfa['intents'].apply(lambda x: x[0]['channel'] if isinstance(x, list) and len(x) > 0 and 'channel' in x[0] else None)

In [45]:
rfa['channel'].value_counts()

channel
zendesk           89
zendesk-email     39
zendesk-letter     2
Name: count, dtype: int64

In [46]:
rfa['channel'] = rfa['channel'].apply(lambda x: 'zendesk-email' if x == 'zendesk' else x)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/864601171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfa['channel'] = rfa['channel'].apply(lambda x: 'zendesk-email' if x == 'zendesk' else x)

In [47]:
rfa['channel'].value_counts()

channel
zendesk-email     128
zendesk-letter      2
Name: count, dtype: int64

In [49]:
rfa

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel
0,39470,27432456-0da5-5c5e-8296-5fa101583f4e,28171800296348-1,None,2026-06-15 12:38:22,"[{'params': {'slug': '196302948324', 'debtor_n...",1,sent,0,egvp,2026-06-15 12:38:22,zendesk-email
1,39472,208d0153-2109-56ed-8bd6-a261d66c494e,28172046035356-1,None,2026-06-15 14:08:45,"[{'params': {'slug': '192298781407', 'debtor_n...",1,sent,0,egvp,2026-06-15 14:08:45,zendesk-email
2,39473,fe1d5a63-52e9-5802-a4d9-9f6a5411ad0c,28172638247964-1,None,2026-06-15 14:09:05,"[{'params': {'slug': '177394173211', 'debtor_n...",1,sent,0,egvp,2026-06-15 14:09:05,zendesk-email
3,39474,50e1fc04-9265-55ac-b909-d14ba17d9fe4,28172903254428-1,None,2026-06-15 14:09:39,"[{'params': {'slug': '127103324753', 'debtor_n...",1,sent,0,egvp,2026-06-15 14:09:39,zendesk-email
4,40116,59b85aa0-8473-56a1-b90f-08307764baa2,28200468095516-1,None,2026-06-16 09:59:41,"[{'params': {'slug': '181396289017', 'debtor_n...",1,sent,0,egvp,2026-06-16 09:59:41,zendesk-email
...,...,...,...,...,...,...,...,...,...,...,...,...
3858,52413,65517563-a47d-5b54-8493-ce3ccb879a41,28649994484252-1,None,2026-07-03 17:22:01,"[{'params': {'slug': '198384884153', 'debtor_n...",1,sent,0,egvp,2026-07-03 17:22:01,zendesk-email
3859,52414,c5f054b4-88e0-56ae-a68f-2510f85ef06e,28650226046876-1,None,2026-07-03 17:22:01,"[{'params': {'slug': '171923686264', 'debtor_n...",1,sent,0,egvp,2026-07-03 17:22:01,zendesk-email
3860,52415,7637653a-a869-5856-9f14-f995daa5578b,28649889336348-1,None,2026-07-03 17:22:08,"[{'params': {'slug': '142339270670', 'debtor_n...",1,sent,0,egvp,2026-07-03 17:22:08,zendesk-email
3861,52416,5065e5df-e9cc-5663-8c10-4d138ed2df3f,28649972137116-1,None,2026-07-03 17:22:11,"[{'params': {'slug': '165653326372', 'debtor_n...",1,sent,0,egvp,2026-07-03 17:22:11,zendesk-email
4660,53421,d38a71e1-5598-526d-a1ef-cbe34c296b47,28687935609884-1,None,2026-07-06 01:17:03,"[{'params': {'slug': '194972152921', 'debtor_n...",1,sent,0,egvp,2026-07-06 01:17:03,zendesk-email

In [57]:
import copy
def find_how_automated(row):
    intent = copy.deepcopy(row['intents'][0])
    intent = str(intent)  # Convert intent to string if it's not already
    if intent:
        try:
            intent = intent.lower()
        except:
            return "none"
        if "ladung_va" in intent:
            return "ladung_va"
        elif "pfub_erlass" in intent:
            return "pfub_erlass"
        elif "vermogen" in intent:
            return "va"
        elif "dritt" in intent:
            return "dritt"
        elif '"aftercourt_type": "invoice"' in intent:
            return "invoice"
        else:
            return "none"
    else:
        return "none"

In [58]:
rfa['auto_type'] = rfa.apply(find_how_automated, axis=1)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/1462749539.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfa['auto_type'] = rfa.apply(find_how_automated, axis=1)

In [61]:
rfa['auto_type'].value_counts()

auto_type
ladung_va    130
Name: count, dtype: int64

In [63]:
rfa.groupby(['channel', 'auto_type']).size().reset_index(name='counts')

          channel  auto_type  counts
0   zendesk-email  ladung_va     128
1  zendesk-letter  ladung_va       2

Result: We only automate for ladung va -> Why this is happening?

Check-> Not automated data

In [64]:
no_auto = data[data.ready_for_automation == False]

In [65]:
no_auto

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at
66,44469,c0cb6821-217b-5af3-9b40-7e4fdc2fec76,28421403923100-1,None,2026-06-24 18:32:44,"[{""params"": {""debtor_name"": ""Nanette Araneta"",...",0,sent,0,egvp,2026-06-24 18:32:44
73,45328,dbd25f59-a372-5c7b-a4fa-d4dd7bcb2e51,28468000637212-1,None,2026-06-26 13:12:03,"[{""params"": {""slug"": ""178921897074"", ""judicial...",0,sent,0,egvp,2026-06-26 13:12:03
76,45424,388417c6-a71d-51fc-b2fa-749282d1cd8e,28472281962780-1,None,2026-06-26 14:57:09,"[{""params"": {""debtor_name"": ""Yvonne Langosch"",...",0,sent,0,egvp,2026-06-26 14:57:09
98,46324,1064ad3f-edc5-5f56-b9f3-d3e3a3f6bba8,28555789622940-1,None,2026-06-30 12:53:15,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-06-30 12:53:15
99,46325,3aa5cc8c-15f8-5efd-a38d-ddd88a29726e,28555867886108-1,None,2026-06-30 12:53:27,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-06-30 12:53:27
...,...,...,...,...,...,...,...,...,...,...,...
4821,53594,e60533f2-53ef-559e-ae47-5b2cca079b6e,28695225004956-1,None,2026-07-06 08:32:48,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-07-06 08:32:48
4822,53595,b6d87e6e-c62f-5429-ab45-ff74ddff950d,28695256844572-1,None,2026-07-06 08:32:49,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-07-06 08:32:49
4823,53596,9ac66d1e-633a-590d-8a2d-77c9f6cef9dc,28695249161628-1,None,2026-07-06 08:32:50,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-07-06 08:32:50
4824,53597,290329c7-8616-5dc8-a44a-18569000a55b,28695899100572-1,None,2026-07-06 08:33:36,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-07-06 08:33:36
4825,53598,ab69fff6-2587-5511-b84b-238f1daa6b64,28695897971228-1,None,2026-07-06 08:33:42,"[{""params"": {}, ""channel"": ""zendesk-letter"", ""...",0,sent,0,egvp,2026-07-06 08:33:42

In [67]:
import json
no_auto['intents'] = no_auto['intents'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/2492881763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_auto['intents'] = no_auto['intents'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)

In [69]:
no_auto['channel'] = no_auto['intents'].apply(lambda x: x[0]['channel'] if isinstance(x, list) and len(x) > 0 and 'channel' in x[0] else None)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/4136349704.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_auto['channel'] = no_auto['intents'].apply(lambda x: x[0]['channel'] if isinstance(x, list) and len(x) > 0 and 'channel' in x[0] else None)

In [70]:
no_auto['channel'].value_counts()

channel
zendesk-letter    4693
zendesk              3
Name: count, dtype: int64

zendesk-email is only auotomated for ladung -> Why it would be: because of business logic.
Most of the not automated data is zendesk letter

In [72]:
zendesk_email_no_auto = no_auto[no_auto['channel'] == 'zendesk']
zendesk_email_no_auto

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel
66,44469,c0cb6821-217b-5af3-9b40-7e4fdc2fec76,28421403923100-1,None,2026-06-24 18:32:44,"[{'params': {'debtor_name': 'Nanette Araneta',...",0,sent,0,egvp,2026-06-24 18:32:44,zendesk
73,45328,dbd25f59-a372-5c7b-a4fa-d4dd7bcb2e51,28468000637212-1,None,2026-06-26 13:12:03,"[{'params': {'slug': '178921897074', 'judicial...",0,sent,0,egvp,2026-06-26 13:12:03,zendesk
76,45424,388417c6-a71d-51fc-b2fa-749282d1cd8e,28472281962780-1,None,2026-06-26 14:57:09,"[{'params': {'debtor_name': 'Yvonne Langosch',...",0,sent,0,egvp,2026-06-26 14:57:09,zendesk

3 data from zendesk email is not auto because 1 param is missing

## Check for zendesk letters

In [75]:
no_auto_letters = no_auto[no_auto['channel'] == 'zendesk-letter']

In [76]:
no_auto_letters

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel
98,46324,1064ad3f-edc5-5f56-b9f3-d3e3a3f6bba8,28555789622940-1,None,2026-06-30 12:53:15,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:15,zendesk-letter
99,46325,3aa5cc8c-15f8-5efd-a38d-ddd88a29726e,28555867886108-1,None,2026-06-30 12:53:27,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:27,zendesk-letter
100,46326,f7daf19f-d338-5cd6-bcc3-3756b33ec802,28555918825244-1,None,2026-06-30 12:53:28,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:28,zendesk-letter
101,46327,0275d36f-ea43-5737-ae25-524e8abea847,28556906987932-1,None,2026-06-30 12:53:38,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:38,zendesk-letter
102,46328,b919a767-a79f-5ad1-90e9-63739257ce24,28557101335836-1,None,2026-06-30 12:53:39,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:39,zendesk-letter
...,...,...,...,...,...,...,...,...,...,...,...,...
4821,53594,e60533f2-53ef-559e-ae47-5b2cca079b6e,28695225004956-1,None,2026-07-06 08:32:48,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:48,zendesk-letter
4822,53595,b6d87e6e-c62f-5429-ab45-ff74ddff950d,28695256844572-1,None,2026-07-06 08:32:49,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:49,zendesk-letter
4823,53596,9ac66d1e-633a-590d-8a2d-77c9f6cef9dc,28695249161628-1,None,2026-07-06 08:32:50,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:50,zendesk-letter
4824,53597,290329c7-8616-5dc8-a44a-18569000a55b,28695899100572-1,None,2026-07-06 08:33:36,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:33:36,zendesk-letter
4825,53598,ab69fff6-2587-5511-b84b-238f1daa6b64,28695897971228-1,None,2026-07-06 08:33:42,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:33:42,zendesk-letter

look for detection

In [77]:
find_how_detected = find_how_automated  # Reusing the same function for detection

no_auto_letters['detected'] = no_auto_letters.apply(find_how_detected, axis=1)

/var/folders/ym/hcyz4chn3cq4n_8dslg5k50h0000gn/T/ipykernel_39591/2540839624.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_auto_letters['detected'] = no_auto_letters.apply(find_how_detected, axis=1)

In [78]:
no_auto_letters['detected'].value_counts()

detected
none           4689
pfub_erlass       2
ladung_va         2
Name: count, dtype: int64

In [79]:
ladung_letter_no_auto = no_auto_letters[no_auto_letters['detected'] == 'ladung_va']
pfub_letter_no_auto = no_auto_letters[no_auto_letters['detected'] == 'pfub_erlass']

In [81]:
ladung_letter_no_auto 
# Result: slug is missing, thats why not automated

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel,detected
1331,48093,50b18d34-fa84-5258-a1aa-496e5a12c404,28576736949276-1,None,2026-07-01 06:57:44,[{'params': {'debtor_name': 'Nikola Bohdansky'...,0,sent,0,egvp,2026-07-01 06:57:44,zendesk-letter,ladung_va
1337,48099,8487151f-c776-5a52-afdd-7b2783ebf776,28576721480220-1,None,2026-07-01 06:57:49,"[{'params': {'debtor_name': 'Fatima Frade', 'j...",0,sent,0,egvp,2026-07-01 06:57:49,zendesk-letter,ladung_va

In [82]:
pfub_letter_no_auto
# Result: slug is missing, thats why not automated

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel,detected
1173,47935,4ca67f10-bbf3-56cc-8a4b-8a98669af378,28576652321564-1,None,2026-07-01 06:53:35,"[{'params': {'debtor_name': 'Softic', 'credito...",0,sent,0,egvp,2026-07-01 06:53:35,zendesk-letter,pfub_erlass
4765,53536,9ba5e0e7-757b-5b7e-8f77-d7b8a5c33054,28694525463452-1,None,2026-07-06 07:21:33,"[{'params': {'slug': '163055985135', 'debtor_n...",0,sent,0,egvp,2026-07-06 07:21:33,zendesk-letter,pfub_erlass

In [84]:
# TODO: are you sure for zendesk-letters and zendesk-emails egvp models are running? 
# Looks like only zendesk pipeline is running, resulting no egvp outputs

In [85]:
no_auto_letters

,id,ticket_uuid,attachment_id,egvp_id,created_at,intents,ready_for_automation,status,retry,target_type,updated_at,channel,detected
98,46324,1064ad3f-edc5-5f56-b9f3-d3e3a3f6bba8,28555789622940-1,None,2026-06-30 12:53:15,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:15,zendesk-letter,none
99,46325,3aa5cc8c-15f8-5efd-a38d-ddd88a29726e,28555867886108-1,None,2026-06-30 12:53:27,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:27,zendesk-letter,none
100,46326,f7daf19f-d338-5cd6-bcc3-3756b33ec802,28555918825244-1,None,2026-06-30 12:53:28,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:28,zendesk-letter,none
101,46327,0275d36f-ea43-5737-ae25-524e8abea847,28556906987932-1,None,2026-06-30 12:53:38,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:38,zendesk-letter,none
102,46328,b919a767-a79f-5ad1-90e9-63739257ce24,28557101335836-1,None,2026-06-30 12:53:39,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-06-30 12:53:39,zendesk-letter,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4821,53594,e60533f2-53ef-559e-ae47-5b2cca079b6e,28695225004956-1,None,2026-07-06 08:32:48,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:48,zendesk-letter,none
4822,53595,b6d87e6e-c62f-5429-ab45-ff74ddff950d,28695256844572-1,None,2026-07-06 08:32:49,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:49,zendesk-letter,none
4823,53596,9ac66d1e-633a-590d-8a2d-77c9f6cef9dc,28695249161628-1,None,2026-07-06 08:32:50,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:32:50,zendesk-letter,none
4824,53597,290329c7-8616-5dc8-a44a-18569000a55b,28695899100572-1,None,2026-07-06 08:33:36,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:33:36,zendesk-letter,none
4825,53598,ab69fff6-2587-5511-b84b-238f1daa6b64,28695897971228-1,None,2026-07-06 08:33:42,"[{'params': {}, 'channel': 'zendesk-letter', '...",0,sent,0,egvp,2026-07-06 08:33:42,zendesk-letter,none