In [1]:
import pandas as pd

In [2]:
current_raw = pd.read_csv('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/raw/final_raw_data.csv')

In [3]:
current_raw

,ticket_uuid,attachment_id,text,object_key,document_type,cleaned_text,data,is_pfub,is_ladung,s3_link,textract_job_id,textract_s3_link
0,937b5e2e-f3b3-56bd-9225-f67840039ee1,8e6a76c1-34ed-5fe0-9144-bbd00e1cddd8,4070071 967072\nAntrag auf Erlass eines Pfändu...,01.02.2022/1643724050_Doc_01022022_000000001_1...,attachment_and_transfer_order,4070071 967072\nantrag auf erlass eines pfändu...,NaN,False,False,NaN,aa53a00a4be3004cf77a29bad626bfd877a85217942166...,s3://pair-data-engineering-new/ocr_prepared_ou...
1,7e7ac68d-b2df-50d2-963d-200aa44b036b,417ecde8-b807-5de4-b066-f70f811c8f6a,Antrag auf Erlass eines Pfänd 070071 967072\nÜ...,01.02.2022/1643724051_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfänd 070071 967072\nü...,NaN,False,False,NaN,a526cbb704ee1ce316ef92311493578034721ce8d1ac27...,s3://pair-data-engineering-new/ocr_prepared_ou...
2,2d315b63-cb84-56ef-bb02-af6c13dff49b,acc1f4fa-6891-58d3-a3d1-d3f3e54d93ba,Antrag auf Erlass eines Pfändun\n4070071 96707...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändun\n4070071 96707...,NaN,False,False,NaN,119c66b09111a9c414741acb6a520aceac59eb2c31deeb...,s3://pair-data-engineering-new/ocr_prepared_ou...
3,dc9e9a0c-12a6-5b22-b6c0-52f1647505a2,cfc4d684-af88-506e-8fdb-39984cf93640,Antrag auf Erlass eines Pfändungs\n4 070071 96...,01.02.2022/1643724052_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändungs\n4 070071 96...,NaN,False,False,NaN,e48ca3ce0673313350c06532a2dea4fe82acf6243da3f1...,s3://pair-data-engineering-new/ocr_prepared_ou...
4,6abb8d66-912f-55bb-9b05-50dbd5c6a6f7,ccf92577-4ae3-505d-97eb-25c49e6fbc12,Antrag auf Erlass eines Pfändu\n4070071 967072...,01.02.2022/1643724053_Doc_01022022_000000001_1...,attachment_and_transfer_order,antrag auf erlass eines pfändu\n4070071 967072...,NaN,False,False,NaN,cb548acfe61af12fd9b1dd59419b673b34b7e32ff0bc1f...,s3://pair-data-engineering-new/ocr_prepared_ou...
...,...,...,...,...,...,...,...,...,...,...,...,...
5350,2bd93acd-08cd-5d66-9d0e-c72b3e1da733,0bd71681-f525-5f65-83eb-952e605409f3,"Myriam Wehmeyer\nc/o Amtsgericht Rotenburg,Am\...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"myriam wehmeyer\nc/o amtsgericht rotenburg,am\...",NaN,False,False,NaN,ea578e5a3589fc0c5b640d644d57e917f384c0458f08ef...,s3://pair-data-engineering-new/ocr_prepared_ou...
5351,079a8404-edb0-5660-8722-8d46098ae215,8e8ef642-2c7a-5bdb-810b-48344c2a235a,"Paul-Rohland-Str.2\n06712 Zeitz, Elster\nTel. ...",data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,"paul-rohland-str.2\n06712 zeitz, elster\ntel. ...",NaN,False,False,NaN,dd4d8ce69f0e90db975a425b96b6c6515f56e912df606c...,s3://pair-data-engineering-new/ocr_prepared_ou...
5352,3321bf02-b3dd-592e-b0c6-e129b3719312,d47fad4c-772a-5f89-80c0-5ac9638b9e7e,Wolfgang Lurz\nSchragenhofstraße 27\n80992 Mün...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,wolfgang lurz\nschragenhofstraße 27\n80992 mün...,NaN,False,False,NaN,ce565a09de5e250d5545b02d2a482a08806b1df497e3cd...,s3://pair-data-engineering-new/ocr_prepared_ou...
5353,f5bdf478-897e-5da6-8669-f835dfcb9a38,ec52a8de-3bf8-5660-8501-414aebade679,Obergerichtsvollzieher\n33104 Paderborn\nWagen...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\n33104 paderborn\nwagen...,NaN,False,False,NaN,3aa213ac35184d2007d9386ad4f8b0f5b502ab1cb36b7d...,s3://pair-data-engineering-new/ocr_prepared_ou...
5354,d801cd78-4ff3-57ad-beab-cf574fbf4c73,76ee1429-e30e-5faa-8875-d3ba850bb4fa,Obergerichtsvollzieher\nAmtsgericht: Wuppertal...,data/aftercourt/ladung_fp_instplan_with_bailif...,bailiff_ip,obergerichtsvollzieher\namtsgericht: wuppertal...,NaN,False,False,NaN,6a0e3e72c6c47a6197ebd35a748ed1df71fc813d1568c5...,s3://pair-data-engineering-new/ocr_prepared_ou...

In [4]:
current_raw.document_type.value_counts()

document_type
ladung_va                                 2029
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
fp_invoice                                 157
approved_attachment_and_transfer_order      60
enforcement_order                           23
bailiff_ip                                  17
contradiction                                3
vermögensverzeichnis                         3
Name: count, dtype: int64

In [5]:
data = pd.read_excel('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/notebooks/models_error_analysis/ladung/error_analysis_spreed_sheet.xlsx')

In [6]:
data.columns

Index(['Ticket uuid', 'Egvp id', 'Attachment id', 'Label',
       'Current Ladung Prob', 'Comment'],
      dtype='object')

In [7]:
data.rename(columns={'Ticket uuide': 'ticket_uuid', 'Egvp id': 'egvp_id', 'Attachment id': 'attachment_id'}, inplace=True)

In [8]:
data

,Ticket uuid,egvp_id,attachment_id,Label,Current Ladung Prob,Comment
0,NaN,NaN,50220741,Protokol Document,0.70,FP is_ladung with protocol doc
1,NaN,NaN,50223768,Protokol Document,0.93,FP is_ladung with protocol doc
2,NaN,NaN,50225565,Protokol Document,0.84,FP is_ladung with protocol doc
3,NaN,NaN,50226657,Protokol Document,0.92,FP is_ladung with protocol doc
4,NaN,NaN,50393046,Protokol Document,0.90,FP is_ladung with protocol doc
...,...,...,...,...,...,...
132,NaN,NaN,51170436,Invoice,0.85,NaN
133,NaN,NaN,52618215,ASK (prob bailiff ip),0.86,NaN
134,NaN,NaN,50758910,ASK,0.81,NaN
135,NaN,NaN,51118089,Invoice,0.82,NaN
136,NaN,NaN,50427647,Invoice,0.81,NaN

In [9]:
data['Label'] = data['Label'].apply(lambda x: x.lower() if isinstance(x, str) else x)

In [10]:
data['Label'].value_counts()

Label
invoice                  75
protokol document        12
vermögensverzeichnis     12
ask                      12
ask                       9
ask (prob fn)             6
ask (prob bailiff ip)     3
fn                        2
ask (0.17) pfub prob      2
ladung fn                 1
ask (0.24) pfub prob      1
ask (0.32 pfub prob)      1
ask (0.10) pfub prob      1
Name: count, dtype: int64

In [11]:
ask_docs = data[data['Label'].isin(['ask', 'ask?'])]

In [12]:
ask_docs

,Ticket uuid,egvp_id,attachment_id,Label,Current Ladung Prob,Comment
54,NaN,NaN,50446562,ask,0.85,/Users/melih.gorgulu/Desktop/Projects/intent_r...
56,NaN,NaN,53146808,ask,0.82,/Users/melih.gorgulu/Desktop/Projects/intent_r...
60,NaN,NaN,52254480,ask,0.84,/Users/melih.gorgulu/Desktop/Projects/intent_r...
65,NaN,NaN,53364398,ask,0.85,/Users/melih.gorgulu/Desktop/Projects/intent_r...
69,NaN,NaN,50781680,ask,0.87,/Users/melih.gorgulu/Desktop/Projects/intent_r...
70,NaN,NaN,50766261,ask,0.82,/Users/melih.gorgulu/Desktop/Projects/intent_r...
71,NaN,NaN,51646792,ask,0.84,/Users/melih.gorgulu/Desktop/Projects/intent_r...
84,NaN,NaN,51178057,ask,0.80,NaN
91,NaN,NaN,50759470,ask,0.81,/Users/melih.gorgulu/Desktop/Projects/intent_r...
97,NaN,NaN,50456233,ask,0.82,NaN
118,NaN,NaN,53414024,ask,0.89,NaN
134,NaN,NaN,50758910,ask,0.81,NaN

In [13]:
import sys
sys.path.insert(0, '/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation')
from utils.prod_utils import get_data_by_attachment_id

In [14]:
from python_utilities.db_connection import DbConnection
import boto3
analytics_db = DbConnection('ANALYTICS', 'PROD_RDS')
# Create session with specific profile
session = boto3.Session(profile_name='739275445236_DataScienceUser')
s3 = session.client('s3')

INFO [2026-03-02 15:24:58] - PYTHON_UTILITIES - secret_utilities.py - get_db_secret_config - Credentials for database were read from secret.ini file
INFO [2026-03-02 15:24:58] - Found credentials in shared credentials file: ~/.aws/credentials

In [15]:
# for idx, a_id in enumerate(ask_docs['attachment_id'].values):
#     get_data_by_attachment_id(a_id, analytics_db, s3, pdf_download=True, pdf_download_dir="/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp")

In [16]:
print(data['attachment_id'].dtype)

object

In [17]:
print(data['attachment_id'].iloc[0], type(data['attachment_id'].iloc[0]))

50220741 <class 'int'>

In [18]:
mapping = {
    50446562: "ip_bailiff",
    53146808: "ladung_va",
    52254480: "tbd",
    53364398: 'ladung_va',
    50781680: 'invoice',
    50766261: 'tbd',
    51646792: 'tbd',
    51178057: 'tbd',
    50759470: 'tbd',
    50456233: 'tbd',
    53414024: 'ladung_va',
    50758910: 'tbd',
    52593813: 'tbd',
    53364410: 'ladung_va',
    50228215: 'tbd',
    "25104443527196-1": 'ladung_va',
    50705124: 'tbd',
    50426443: 'tbd',
    52593846: 'ladung_va',
    51811572: 'tbd',
}

In [19]:
# update Label column according to mapping to the data
data['Label'] = data.apply(lambda row: mapping[row['attachment_id']] if row['attachment_id'] in mapping else row['Label'], axis=1)

In [20]:
data['Label'].value_counts()

Label
invoice                  76
tbd                      13
protokol document        12
vermögensverzeichnis     12
ask                       8
ladung_va                 6
ask (prob bailiff ip)     3
fn                        2
ladung fn                 1
ip_bailiff                1
ask (0.24) pfub prob      1
ask (0.32 pfub prob)      1
ask (0.10) pfub prob      1
Name: count, dtype: int64

In [21]:
# check the data for Label = 'ask (prob fn)'
check = data[data['Label']=="ladung fn"]
for idx, a_id in enumerate(check['attachment_id'].values):
    get_data_by_attachment_id(a_id, analytics_db, s3, pdf_download=True, pdf_download_dir="/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp")

====================================================================================================
📎 ATTACHMENT SUMMARY
====================================================================================================
Attachment ID:   50228348
File Name:       50228348_Dr_ii_41_26__an_gl____termin_ladung_vak_____802_c__einfach.pdf
====================================================================================================

│ 📄 Document S3:
│    s3://pair-data-engineering-new/ocr_source_files/2026-01-20/egvp_id_294570/50228348_Dr_ii_41_26__an_gl____termin_ladung_vak_____802_c__einfach.pdf
│
│ 📝 Textract Output:
│    s3://pair-data-engineering-new/ocr_prepared_output/ac61499287614eb198c37ba59eba3b83bb67800383b03aff16c828718cdc7518.json
│
│ 📊 Text Length:  912 characters
│
│ 📥 PDF Downloaded: /Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/assets/pdfs/tmp/50228348.pdf
│
│ 🤖 PREDICTIONS:
│    Class:      ladung
│    Prob Ladung: '0.83'
│    Prob Pfub:   '0.01'
└──────────────────────────────────────────────────────────────────────────────────────────────────

In [22]:
current_raw.document_type.value_counts()

document_type
ladung_va                                 2029
mail_attachments                          1006
monierung_mb                               545
attachment_and_transfer_order              539
approved_seizure                           408
court_inbox                                346
fp_protocol                                219
fp_invoice                                 157
approved_attachment_and_transfer_order      60
enforcement_order                           23
bailiff_ip                                  17
contradiction                                3
vermögensverzeichnis                         3
Name: count, dtype: int64

In [23]:
label_new_names = {
    'ask': 'tbd',
    'ask (prob bailiff ip)': 'bailiff_ip',
    'fn': 'ladung_va',
    'ask (0.17) pfub prob': 'tbd',
    'ladung fn': 'ladung_va',
    'ip_bailiff': 'bailiff_ip',
    "ask (0.24) pfub prob": 'tbd',
    "ask (0.32 pfub prob)": 'tbd',
    "ask (0.10) pfub prob": 'tbd',
    'fn' : 'ladung_va',
    'ladung fn': 'ladung_va',
    'invoice': 'fp_invoice',
    'protokol document': 'fp_protocol',
    'vermögensverzeichnis': 'vermögensverzeichnis',
    'ask ': 'tbd'
}

In [24]:
# apply new label names
data['Label'] = data['Label'].map(label_new_names).fillna(data['Label'])

In [25]:
data.rename({'Label':'document_type'}, inplace=True, axis=1)

In [26]:
data.document_type.value_counts()

document_type
fp_invoice              76
tbd                     24
fp_protocol             12
vermögensverzeichnis    12
ladung_va                9
bailiff_ip               4
Name: count, dtype: int64

In [28]:
data.columns

Index(['Ticket uuid', 'egvp_id', 'attachment_id', 'document_type',
       'Current Ladung Prob', 'Comment'],
      dtype='object')

In [30]:
add_new_data = data.drop(['Ticket uuid', 'egvp_id','Current Ladung Prob', 'Comment'], axis=1)

In [32]:
add_new_data

    attachment_id document_type
0        50220741   fp_protocol
1        50223768   fp_protocol
2        50225565   fp_protocol
3        50226657   fp_protocol
4        50393046   fp_protocol
..            ...           ...
132      51170436    fp_invoice
133      52618215    bailiff_ip
134      50758910           tbd
135      51118089    fp_invoice
136      50427647    fp_invoice

[137 rows x 2 columns]

In [33]:
# add text data from current_raw where possible, fetch remaining from DB
text_map = current_raw.set_index('attachment_id')['text'].to_dict()

texts = []
for a_id in add_new_data['attachment_id'].values:
    if a_id in text_map:
        texts.append(text_map[a_id])
    else:
        try:
            result = get_data_by_attachment_id(a_id, analytics_db, s3, verbose=False)
            texts.append(result['text'].iloc[0] if not result.empty and 'text' in result.columns else None)
        except Exception as e:
            print(f"Failed to fetch text for {a_id}: {e}")
            texts.append(None)

add_new_data['text'] = texts
print(f"Total rows: {len(add_new_data)}, Rows with text: {add_new_data['text'].notna().sum()}")

Total rows: 137, Rows with text: 137

In [34]:
add_new_data

,attachment_id,document_type,text
0,50220741,fp_protocol,Daniel Werle\nDie nachstehend gewählten Formul...
1,50223768,fp_protocol,Frank Kröger\nDie nachstehend gewählten Formul...
2,50225565,fp_protocol,SUSANNE DECKER\nDie nachstehend gewählten Form...
3,50226657,fp_protocol,THOMAS METHNER\nDie nachstehend gewählten Form...
4,50393046,fp_protocol,FRANK WASSERSCHLEGER\nDie nachstehend gewählte...
...,...,...,...
132,51170436,fp_invoice,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...
133,52618215,bailiff_ip,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...
134,50758910,tbd,André Rucks\nSittarder Str. 72\n52511 Geilenki...
135,51118089,fp_invoice,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...
136,50427647,fp_invoice,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...

In [50]:
add_new_data['is_pfub'] = False
add_new_data['is_ladung'] = add_new_data['document_type'].apply(lambda x: True if 'ladung' in x else False)

In [51]:
add_new_data

,attachment_id,document_type,text,is_pfub,is_ladung
0,50220741,fp_protocol,Daniel Werle\nDie nachstehend gewählten Formul...,False,False
1,50223768,fp_protocol,Frank Kröger\nDie nachstehend gewählten Formul...,False,False
2,50225565,fp_protocol,SUSANNE DECKER\nDie nachstehend gewählten Form...,False,False
3,50226657,fp_protocol,THOMAS METHNER\nDie nachstehend gewählten Form...,False,False
4,50393046,fp_protocol,FRANK WASSERSCHLEGER\nDie nachstehend gewählte...,False,False
...,...,...,...,...,...
132,51170436,fp_invoice,Gerichtsvollzieher\nSiemensstraße 20\nSteinsie...,False,False
133,52618215,bailiff_ip,Wildeshauser Str. 21\nSandra Zenker\n26197 Ahl...,False,False
134,50758910,tbd,André Rucks\nSittarder Str. 72\n52511 Geilenki...,False,False
135,51118089,fp_invoice,Sonnenscheinpfad 28\n44879 Bochum\nTel. 0234/4...,False,False
136,50427647,fp_invoice,Obergerichtsvollzieher\n34226 Fuldatal\nWürz\n...,False,False

In [52]:
add_new_data.to_csv('/Users/melih.gorgulu/Desktop/Projects/aftercourt_automation/data/new_data_add/add_new_data.csv', index=False)